### ISSUE TITLE
Segfault during normal use

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1004]
**Reported by Elephantman on 20 Oct 2010 19:40:37 UTC**
After a while (long), kvirc crashes randomly.
Here's the kde backtrace

```
Application: KVIrc (kvirc), signal: Segmentation fault
[Current thread is 1 (Thread 0xb785e710 (LWP 2899))]

Thread 2 (Thread 0xae003b70 (LWP 2900)):
#0  0x02974e16 in clock_gettime () from /lib/tls/i686/cmov/librt.so.1
#1  0x01f2c6fb in ?? () from /usr/lib/libQtCore.so.4
#2  0x01f31825 in ?? () from /usr/lib/libQtCore.so.4
#3  0x01f3186a in ?? () from /usr/lib/libQtCore.so.4
#4  0x01f2f818 in ?? () from /usr/lib/libQtCore.so.4
#5  0x01f2f8a5 in ?? () from /usr/lib/libQtCore.so.4
#6  0x0209baca in g_main_context_prepare () from /lib/libglib-2.0.so.0
#7  0x0209bee9 in ?? () from /lib/libglib-2.0.so.0
#8  0x0209c4b8 in g_main_context_iteration () from /lib/libglib-2.0.so.0
#9  0x01f2f60f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#10 0x01f02059 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#11 0x01f024aa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#12 0x01dfe5a8 in QThread::exec() () from /usr/lib/libQtCore.so.4
#13 0x01ee1c1b in ?? () from /usr/lib/libQtCore.so.4
#14 0x01e0132e in ?? () from /usr/lib/libQtCore.so.4
#15 0x0011596e in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#16 0x01887a4e in clone () from /lib/tls/i686/cmov/libc.so.6

Thread 1 (Thread 0xb785e710 (LWP 2899)):
[KCrash Handler]
#6  0x01e26c71 in ?? () from /usr/lib/libQtCore.so.4
#7  0x01e2a453 in QLocalePrivate::longLongToString(long long, int, int, int, unsigned int) const () from /usr/lib/libQtCore.so.4
#8  0x01e565dd in QString::arg(long long, int, int, QChar const&) const () from /usr/lib/libQtCore.so.4
#9  0x0814bc73 in KviUserListView::maybeTip(KviUserListToolTip*, QPoint const&) ()
#10 0xbf963a9c in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1004

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 20 Oct 2010 20:59:30**
from a first quick review it seems related to the translation of an userlist tooltip.. can you check if it happens also using the base english locale?

**Comment by DarthGandalf** [comment]
**Comment by Elephantman on 20 Oct 2010 21:10:32**
Any clue what string ?<br/>

Using english isn't easy because it's my wife's client and she'll not like me pushing her into english :p<br/>

But if there's no other way, I'll try convincing :)

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Oct 2010 23:09:42**
Looking a bit deeper is seems unrelated to the translation.. it would be really nice to get a "bt full" backtrace, if possible.

**Comment by DarthGandalf** [comment]
**Comment by Elephantman on 02 Nov 2010 23:35:45**
Lol that's gonna be fun.
I'll try talking my misses into that one :p But could take some time ;)

It seems I've got 4.0RC and 4.1 that live in parallel on her box (looks like default paths have been changed). Maybe it would be good for a start that I remove the older. Is there a nice and clean way to remove it and all it's gear without touching 4.1 ?

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 05 Nov 2010 12:25:13**
Mhh.. a mismatch between two kvirc versions could lead to a problem like this..<br/>
anyway, the best way to remove more mixed kvirc installations, supposing your prefix is /usr, is:
- quit any kvirc istance
- remove any distro package
- delete /usr/share/kvirc
- delete any /usr/lib/libkvilib.so\* or /usr/lib64/libkvilib.so*
- delete any /usr/lib/kvirc or /usr/lib64/kvirc
- delete any /usr/bin/kvirc or /usr/bin/kvirc4
- delete any local module installed in ~/.config/KVIrc/modules/
  The prefix could be /usr/local, /opt, .. check all of them.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 08 Dec 2010 17:41:22**
any evolution on this issue?

---

Resolution: none → need feedback
Status: new → closed
