### ISSUE TITLE
Crashes randomly some seconds after start

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1012]
**Reported by mren on 02 Nov 2010 18:45:46 UTC**
I auto-connect to my bouncer which opens 4 servers which several channels. Some seconds after connecting when all the buffers are played back KVIrc crashes randomly.

Revision 5125 on Kubuntu Linux, self compiled.

```
Application: KVIrc (kvirc4), signal: Aborted
[Current thread is 1 (Thread 0x7f29f4601760 (LWP 9968))]

Thread 2 (Thread 0x7f29d4e39710 (LWP 9974)):
#0  0x00007f29e9346a57 in g_main_context_prepare () from /lib/libglib-2.0.so.0
#1  0x00007f29e9346e78 in ?? () from /lib/libglib-2.0.so.0
#2  0x00007f29e934745c in g_main_context_iteration () from /lib/libglib-2.0.so.0
#3  0x00007f29ee7461e6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#4  0x00007f29ee718a02 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#5  0x00007f29ee718dec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#6  0x00007f29ee6232fd in QThread::exec() () from /usr/lib/libQtCore.so.4
#7  0x00007f29ee6f85f8 in ?? () from /usr/lib/libQtCore.so.4
#8  0x00007f29ee62627e in ?? () from /usr/lib/libQtCore.so.4
#9  0x00007f29f3ca4971 in start_thread () from /lib/libpthread.so.0
#10 0x00007f29ec20491d in clone () from /lib/libc.so.6
#11 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f29f4601760 (LWP 9968)):
[KCrash Handler]
#6  0x00007f29ec151ba5 in raise () from /lib/libc.so.6
#7  0x00007f29ec1556b0 in abort () from /lib/libc.so.6
#8  0x00007f29ee61d864 in qt_message_output(QtMsgType, char const*) () from /usr/lib/libQtCore.so.4
#9  0x00007f29ee61da42 in ?? () from /usr/lib/libQtCore.so.4
#10 0x00007f29ee61dbf5 in qFatal(char const*, ...) () from /usr/lib/libQtCore.so.4
#11 0x00007f29f37da8d1 in KviStr::KviStr (this=0x7fffbc528570, str=0x0, len=0) at /home/mr/Projekte/kvirc/trunk/src/kvilib/core/kvi_string.cpp:1073
#12 0x00000000004fadd4 in KviStatusBarUpdateIndicator::binaryDataReceived (this=0x1bcc490, buffer=...) at /home/mr/Projekte/kvirc/trunk/src/kvirc/ui/kvi_statusbarapplet.cpp:764
#13 0x00000000005ea151 in KviStatusBarUpdateIndicator::qt_metacall (this=0x1bcc490, _c=QMetaObject::InvokeMetaMethod, _id=6, _a=0x7fffbc528700) at /home/mr/Projekte/kvirc/trunk-BUILD/src/kvirc/ui/moc_kvi_statusbarapplet.cxx:428
#14 0x00007f29ee731b27 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
#15 0x00007f29f382e955 in KviHttpRequest::binaryData (this=0x26f0, _t1=<value optimized out>) at /home/mr/Projekte/kvirc/trunk-BUILD/src/kvilib/net/moc_kvi_http.cxx:167
#16 0x00007f29f380c439 in KviHttpRequest::event (this=0x1b9b9a0, e=0x35aa390) at /home/mr/Projekte/kvirc/trunk/src/kvilib/net/kvi_http.cpp:299
#17 0x00007f29efcbffdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#18 0x00007f29efcc5aed in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#19 0x00007f29f2eac156 in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#20 0x00007f29ee719cdc in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#21 0x00007f29ee71cc22 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQtCore.so.4
#22 0x00007f29ee746653 in ?? () from /usr/lib/libQtCore.so.4
#23 0x00007f29e9343342 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#24 0x00007f29e93472a8 in ?? () from /lib/libglib-2.0.so.0
#25 0x00007f29e934745c in g_main_context_iteration () from /lib/libglib-2.0.so.0
#26 0x00007f29ee746193 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#27 0x00007f29efd72a4e in ?? () from /usr/lib/libQtGui.so.4
#28 0x00007f29ee718a02 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#29 0x00007f29ee718dec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#30 0x00007f29ee71cebb in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#31 0x00000000005cdeef in main (argc=1, argv=0x7fffbc529248) at /home/mr/Projekte/kvirc/trunk/src/kvirc/kernel/kvi_main.cpp:456

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1012

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 02 Nov 2010 22:45:00**
patched in r5126

---

Resolution: none → fixed
Status: new → closed
