### ISSUE TITLE
Crash on /dcc.video

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1077]
**Reported by wodim on 23 Jan 2011 02:37:42 UTC**
My webcam's LED flickers three times, then it crashes.
I wonder if this is because I was trying to chat with myself, but I think I did that once and it didn't crash.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe00f3700 (LWP 30999)]
0x00007ffff6db3b4b in Kopete::AV::VideoDevice::getImage (this=0x15c4fd0, qimage=0x14c8dd0) at /home/neiko/kvirc/src/kvilib/ext/avdevice/videodevice.cpp:1488
1488                                            *p = qRgba(r,g,b,255);
(gdb) bt full
#0  0x00007ffff6db3b4b in Kopete::AV::VideoDevice::getImage (this=0x15c4fd0, qimage=0x14c8dd0) at /home/neiko/kvirc/src/kvilib/ext/avdevice/videodevice.cpp:1488
        c = <value optimized out>
        e = <value optimized out>
        g = 135
        d = <value optimized out>
        r = 0
        b = <value optimized out>
        p = 0x7fffe0dec010
        x = <value optimized out>
        y = 0
        cbptr = 0x157b9e1 ""
        crptr = 0x157b9e3 ""
        halfheight = <value optimized out>
        packed = true
        yptr = 0x157b9e0 ""
        bits = 0x7fffe0dec010 <Address 0x7fffe0dec010 out of bounds>
#1  0x00007fffdf4cc379 in DccVideoThread::videoStep (this=0x14c8cf0) at /home/neiko/kvirc/src/modules/dcc/DccVideoWindow.cpp:191
No locals.
#2  0x00007fffdf4cfd24 in DccVideoThread::run (this=0x14c8cf0) at /home/neiko/kvirc/src/modules/dcc/DccVideoWindow.cpp:403
No locals.
#3  0x00007ffff6da5676 in KviThread::internalThreadRun_doNotTouchThis (this=0x14c8cf0) at /home/neiko/kvirc/src/kvilib/system/KviThread.cpp:538
No locals.
#4  0x00007ffff6da5699 in internal_start_thread (arg=<value optimized out>) at /home/neiko/kvirc/src/kvilib/system/KviThread.cpp:447
No locals.
#5  0x00007ffff6ffacb0 in start_thread () from /lib/libpthread.so.0
No symbol table info available.
#6  0x00007fffef1a47ed in clone () from /lib/libc.so.6
No symbol table info available.
#7  0x0000000000000000 in ?? ()
No symbol table info available.
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1077

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 28 Mar 2011 14:53:37**
fixed in r5717 / r5718

---

Resolution: none → fixed
Status: new → closed
