### ISSUE TITLE
using ibus on kvirc crash when deleting selected, but not inputed kanji characters

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1212]
**Reported by uNmowed on 10 Sep 2011 03:34:55 UTC**
ASSERT: "i >= 0 && i < size()" in file /usr/local/include/qt4/QtCore/qstring.h, line 702
Abort trap (core dumped)

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1212

**Comment by DarthGandalf** [comment]
**Comment by uNmowed on 10 Sep 2011 03:46:14**
dump file http://madoka.pp.ua/kvirc.core

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 10 Sep 2011 16:28:19**
Unfortunately i can't get a stack trace out of the dump:

```
warning: A handler for the OS ABI "FreeBSD ELF" is not built into this configuration                                                                                                
of GDB.  Attempting to continue with the default i386 settings.
```

Could you please try to get a backtrace out of it? Just run 

```
gdb kvirc -c /path/to/kvirc.core
```

and at the gdb prompt write

```
bt full
```

Use the "spacebar" to collect all the pages and then copy/paste the result here. Thank you!

**Comment by DarthGandalf** [comment]
**Comment by uNmowed on 11 Sep 2011 01:59:37**

```
$ gdb kvirc -c /home/user/kvirc.core
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-marcel-freebsd"...(no debugging symbols found)...
Core was generated by `kvirc'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/local/lib/libkvilib.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libkvilib.so.4
Reading symbols from /lib/libthr.so.3...(no debugging symbols found)...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /lib/libz.so.5...(no debugging symbols found)...done.
Loaded symbols for /lib/libz.so.5
Reading symbols from /usr/local/lib/qt4/libQtWebKit.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtWebKit.so.4
Reading symbols from /usr/local/lib/qt4/libQtGui.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtGui.so.4
Reading symbols from /usr/local/lib/qt4/libQtDBus.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtDBus.so.4
Reading symbols from /usr/local/lib/qt4/libQtXml.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtXml.so.4
Reading symbols from /usr/local/lib/qt4/libQtSql.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtSql.so.4
Reading symbols from /usr/local/lib/qt4/libQtXmlPatterns.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtXmlPatterns.so.4
Reading symbols from /usr/local/lib/qt4/libQtNetwork.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtNetwork.so.4
Reading symbols from /usr/local/lib/qt4/libQtCore.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/libQtCore.so.4
Reading symbols from /usr/local/lib/libSM.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libSM.so.6
Reading symbols from /usr/local/lib/libICE.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libICE.so.6
Reading symbols from /usr/local/lib/libX11.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libX11.so.6
Reading symbols from /usr/local/lib/libXext.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXext.so.6
Reading symbols from /usr/local/lib/libXrender.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXrender.so.1
Reading symbols from /usr/local/kde4/lib/libphonon.so.4...(no debugging symbols found)...done.
Loaded symbols for /usr/local/kde4/lib/libphonon.so.4
Reading symbols from /usr/local/lib/libesd.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libesd.so.2
Reading symbols from /usr/local/lib/libaudiofile.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libaudiofile.so.0
Reading symbols from /usr/lib/libssl.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libssl.so.6
Reading symbols from /lib/libcrypto.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib/libcrypto.so.6
Reading symbols from /usr/local/lib/libpython2.6.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libpython2.6.so
Reading symbols from /usr/local/lib/libperl.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libperl.so
Reading symbols from /lib/libcrypt.so.5...(no debugging symbols found)...done.
Loaded symbols for /lib/libcrypt.so.5
Reading symbols from /lib/libutil.so.8...(no debugging symbols found)...done.
Loaded symbols for /lib/libutil.so.8
Reading symbols from /usr/lib/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/libstdc++.so.6
Reading symbols from /lib/libm.so.5...(no debugging symbols found)...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /lib/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /lib/libc.so.7...(no debugging symbols found)...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libfontconfig.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libfontconfig.so.1
Reading symbols from /usr/local/lib/libfreetype.so.9...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libfreetype.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libpng.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libpng.so.6
Reading symbols from /usr/local/lib/libiconv.so.3...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libiconv.so.3
Reading symbols from /usr/local/lib/libxcb.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libxcb.so.2
Reading symbols from /usr/local/lib/libXau.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXau.so.6
Reading symbols from /usr/local/lib/libXdmcp.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXdmcp.so.6
Reading symbols from /usr/local/lib/libpthread-stubs.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libpthread-stubs.so.0
Reading symbols from /usr/lib/librpcsvc.so.5...(no debugging symbols found)...done.
Loaded symbols for /usr/lib/librpcsvc.so.5
Reading symbols from /usr/local/lib/libexpat.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libexpat.so.6
Reading symbols from /usr/local/lib/libintl.so.9...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libintl.so.9
Reading symbols from /usr/local/lib/libpcre.so.0...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libpcre.so.0
Reading symbols from /usr/local/lib/libXrandr.so.2...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXrandr.so.2
Reading symbols from /usr/local/lib/libXfixes.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXfixes.so
Reading symbols from /usr/local/lib/libXcursor.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXcursor.so.1
Reading symbols from /usr/local/lib/libXinerama.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXinerama.so.1
Reading symbols from /usr/local/lib/libXi.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libXi.so
Reading symbols from /usr/local/lib/libdbus-1.so.3...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libdbus-1.so.3
Reading symbols from /usr/local/lib/kvirc/4.1/modules/libkvitrayicon.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/kvirc/4.1/modules/libkvitrayicon.so
Reading symbols from /usr/local/lib/kvirc/4.1/modules/libkvioptions.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/kvirc/4.1/modules/libkvioptions.so
Reading symbols from /usr/local/lib/qt4/plugins/inputmethods/libqimsw-multi.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/plugins/inputmethods/libqimsw-multi.so
Reading symbols from /usr/local/lib/qt4/plugins/inputmethods/libqtim-ibus.so...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/qt4/plugins/inputmethods/libqtim-ibus.so
Reading symbols from /usr/local/lib/libicui18n.so.46...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libicui18n.so.46
Reading symbols from /usr/local/lib/libicuuc.so.46...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libicuuc.so.46
Reading symbols from /usr/local/lib/libicudata.so.46...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libicudata.so.46
Reading symbols from /usr/local/lib/libibus-qt.so.1...(no debugging symbols found)...done.
Loaded symbols for /usr/local/lib/libibus-qt.so.1
Reading symbols from /libexec/ld-elf.so.1...(no debugging symbols found)...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x2bb4c66b in thr_kill () from /lib/libc.so.7
[New Thread 2d467cc0 (LWP 100469)]
[New Thread 2c001140 (LWP 100227)]
(gdb) bt full
#0  0x2bb4c66b in thr_kill () from /lib/libc.so.7
No symbol table info available.
#1  0x28497916 in pthread_kill () from /lib/libthr.so.3
No symbol table info available.
#2  0x28495393 in raise () from /lib/libthr.so.3
No symbol table info available.
#3  0x2bbef6ca in abort () from /lib/libc.so.7
No symbol table info available.
#4  0x2b13ece7 in qt_message_output () from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#5  0x2b13eebb in qt_message () from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#6  0x2b13efd9 in qFatal () from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#7  0x2b13f065 in qt_assert () from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#8  0x0812525c in KviInputEditor::drawContents ()
No symbol table info available.
#9  0x0811624c in KviInputEditor::paintEvent ()
No symbol table info available.
#10 0x29f8851d in QWidget::event () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#11 0x29f1e2fc in QApplicationPrivate::notify_helper ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#12 0x29f25063 in QApplication::notify () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#13 0x2b25257b in QCoreApplication::notifyInternal ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#14 0x29f7fdad in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#15 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#16 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#17 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#18 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#19 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#20 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#21 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#22 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#23 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#24 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#25 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#26 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#27 0x29f808e3 in QWidgetPrivate::paintSiblingsRecursive ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#28 0x29f7fabc in QWidgetPrivate::drawWidget ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#29 0x2a17ae04 in QWidgetBackingStore::sync ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#30 0x29f77092 in QWidgetPrivate::syncBackingStore ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#31 0x29f88e22 in QWidget::event () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#32 0x2a3b3b45 in QMainWindow::event () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#33 0x29f1e2fc in QApplicationPrivate::notify_helper ()
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#34 0x29f25063 in QApplication::notify () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#35 0x2b25257b in QCoreApplication::notifyInternal ()
   from /usr/local/lib/qt4/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#36 0x2b25380f in QCoreApplicationPrivate::sendPostedEvents ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#37 0x2b253a2d in QCoreApplication::sendPostedEvents ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#38 0x2b282774 in postEventSourceDispatch ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#39 0x2bd09969 in g_main_context_dispatch ()
   from /usr/local/lib/libglib-2.0.so.0
No symbol table info available.
#40 0x2bd0cee6 in g_main_context_prepare ()
   from /usr/local/lib/libglib-2.0.so.0
No symbol table info available.
#41 0x2bd0d39c in g_main_context_iteration ()
   from /usr/local/lib/libglib-2.0.so.0
No symbol table info available.
#42 0x2b282b9b in QEventDispatcherGlib::processEvents ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#43 0x29fddfe5 in QGuiEventDispatcherGlib::processEvents ()
---Type <return> to continue, or q <return> to quit---
   from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#44 0x2b251753 in QEventLoop::processEvents ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#45 0x2b2519ea in QEventLoop::exec () from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#46 0x2b253af6 in QCoreApplication::exec ()
   from /usr/local/lib/qt4/libQtCore.so.4
No symbol table info available.
#47 0x29f1d907 in QApplication::exec () from /usr/local/lib/qt4/libQtGui.so.4
No symbol table info available.
#48 0x082d3679 in main ()
No symbol table info available.
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 17 Sep 2011 11:09:08**
Thank you for the strack trace; a workaround has been added in r5967, and from my tests it doesn't crash anymore. Anyway, as far as i understand there's still something weird in kvirc's handling of characters, fell free to point them out, i'll try to get them fixed.

---

Resolution: none → fixed
Status: new → closed
