### ISSUE TITLE
Crash when I try recognice sounds with command /snd.autodetect

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1236]
**Reported by Sanskript on 04 Dec 2011 17:08:52 UTC**
Application: KVIrc (kvirc), signal: Segmentation fault
[Current thread is 1 (Thread 0xb76f3710 (LWP 4689))]

Thread 3 (Thread 0xb6c5eb70 (LWP 4692)):
#0  0x00b93416 in __kernel_vsyscall ()
#1  0x02a4e40e in poll () from /lib/i386-linux-gnu/libc.so.6
#2  0x0638d34b in g_poll () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0x0637e896 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#4  0x0637ef9b in g_main_loop_run () from /lib/i386-linux-gnu/libglib-2.0.so.0
#5  0x032a4cea in ?? () from /usr/lib/i386-linux-gnu/libgio-2.0.so.0
#6  0x063a55f4 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#7  0x00681d31 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#8  0x02a5d0ce in clone () from /lib/i386-linux-gnu/libc.so.6

Backtrace stopped: Not enough registers or memory available to unwind further

Thread 2 (Thread 0xb745fb70 (LWP 5088)):
#0  0x0637df26 in g_main_context_check () from /lib/i386-linux-gnu/libglib-2.0.so.0
#1  0x0637e8f0 in ?? () from /lib/i386-linux-gnu/libglib-2.0.so.0
#2  0x0637ec2a in g_main_context_iteration () from /lib/i386-linux-gnu/libglib-2.0.so.0
#3  0x025a4b37 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#4  0x025751dd in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#5  0x02575421 in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#6  0x0247890b in QThread::exec() () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#7  0x02555e2d in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#8  0x0247b7b3 in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
#9  0x00681d31 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#10 0x02a5d0ce in clone () from /lib/i386-linux-gnu/libc.so.6

Backtrace stopped: Not enough registers or memory available to unwind further

Thread 1 (Thread 0xb76f3710 (LWP 4689)):
[KCrash Handler]
#7  0x04bd7126 in ?? () from /usr/lib/libphonon.so.4
#8  0x00000000 in ?? ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1236

**Comment by DarthGandalf** [comment]
**Comment by Sanskript on 04 Dec 2011 17:11:24**
I love this IRC client, but can be really usefull for me try add sounds for different tasks, until now doesn't. I uploaded some sounds files .wav but can not play them.
Thanks for your great job

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 05 Dec 2011 01:11:52**
how about some more stats?

I guess you are using linux ;) Which distri? Are you using distri packages or selfcompiled? Which revision? Which Desktop do you use? What kernel do you use?

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Dec 2011 15:41:05**
Since the crash happens inside phonon, i'd eventually try to disable it at compilation time or to see if it crash with only a specific backend (xine, gstreamer, vlc, ...)

---

Resolution: none → need feedback
Status: new → closed
