### ISSUE TITLE
Crashreport on after suspension crash (for caterpillar)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1255]
**Reported by ambossarm on 03 Feb 2012 10:29:38 UTC**

```
[11:19:40] <Caterpillar> Hi, I created a crashreport http://pastebin.com/wWLZVZ1j
[11:20:36] <Caterpillar> actually I cannot open a bugreport, so I pasted everything in the pastebin
[11:21:47] <ambossarm> arch?
[11:22:28] <Caterpillar> ambossarm: i386
[11:22:29] <ambossarm> any more text for a ticket?
[11:23:11] <Caterpillar> I resumed kvirc after a computer suspension, then I clicked sometimes on connect button
```

```
    Application: kvirc (4.0.4)
    KDE Platform Version: 4.7.4 (4.7.4)
    Qt Version: 4.8.0
    Operating System: Linux 3.2.2-1.fc16.i686 i686
    Distribution: "Fedora release 16 (Verne)"

    -- Information about the crash:
    <Descrivi dettagliatamente cosa stavi facendo quando si è verificato l'errore.>

    -- Backtrace:
    Application: KVIrc (kvirc), signal: Aborted
    Using host libthread_db library "/lib/libthread_db.so.1".
    [KCrash Handler]
    #7  0x0076f416 in __kernel_vsyscall ()
    #8  0x4268998f in __GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
    #9  0x4268b2d5 in __GI_abort () at abort.c:91
    #10 0x411b9ae2 in qt_message_output (msgType=QtFatalMsg, buf=0xa541e90 "ASSERT: \"!isEmpty()\" in file /usr/include/QtCore/qlist.h, line 269") at global/qglobal.cpp:2252
    #11 0x411b9cdd in qt_message (msgType=QtFatalMsg, msg=0x41347254 "ASSERT: \"%s\" in file %s, line %d", ap=0xbf94a684 "\254\236&\be\236&\b\r\001") at global/qglobal.cpp:2298
    #12 0x411b9df9 in qFatal (msg=0x41347254 "ASSERT: \"%s\" in file %s, line %d") at global/qglobal.cpp:2481
    #13 0x411b9e86 in qt_assert (assertion=0x8269eac "!isEmpty()", file=0x8269e65 "/usr/include/QtCore/qlist.h", line=269) at global/qglobal.cpp:1999
    #14 0x0822bcdc in first (this=0xa4f32c8) at /usr/include/QtCore/qlist.h:269
    #15 takeFirst (this=0xa4f32c8) at /usr/include/QtCore/qlist.h:477
    #16 dequeue (this=0xa4f32c8) at /usr/include/QtCore/qqueue.h:60
    #17 KviRequestQueue::timerSlot (this=0xa4f32c0) at /usr/src/debug/kvirc-4.0.4/src/kvirc/kernel/kvi_ircconnectionrequestqueue.cpp:148
    #18 0x08268ae8 in KviRequestQueue::qt_metacall (this=0xa4f32c0, _c=QMetaObject::InvokeMetaMethod, _id=<optimized out>, _a=0xbf94a7d0) at /usr/src/debug/kvirc-4.0.4/src/kvirc/kernel/moc_kvi_ircconnectionrequestqueue.cxx:72
    #19 0x412e16be in metacall (argv=0xbf94a7d0, idx=4, cl=QMetaObject::InvokeMetaMethod, object=0xa4f32c0) at kernel/qmetaobject.cpp:245
    #20 QMetaObject::metacall (object=0xa4f32c0, cl=QMetaObject::InvokeMetaMethod, idx=4, argv=0xbf94a7d0) at kernel/qmetaobject.cpp:240
    #21 0x412f01ad in QMetaObject::activate (sender=0xa4f32cc, m=0x41436998, local_signal_index=0, argv=0x0) at kernel/qobject.cpp:3566
    #22 0x41344696 in QTimer::timeout (this=0xa4f32cc) at .moc/release-shared/moc_qtimer.cpp:148
    #23 0x412f9f16 in QTimer::timerEvent (this=0xa4f32cc, e=0xbf94acdc) at kernel/qtimer.cpp:280
    #24 0x412f5274 in QObject::event (this=0xa4f32cc, e=0xbf94acdc) at kernel/qobject.cpp:1157
    #25 0x4afa4134 in notify_helper (e=0xbf94acdc, receiver=0xa4f32cc, this=0x8fb8238) at kernel/qapplication.cpp:4550
    #26 QApplicationPrivate::notify_helper (this=0x8fb8238, receiver=0xa4f32cc, e=0xbf94acdc) at kernel/qapplication.cpp:4522
    #27 0x4afa95d3 in QApplication::notify (this=0xbf94acdc, receiver=0xa4f32cc, e=0xbf94acdc) at kernel/qapplication.cpp:4279
    #28 0x47e26972 in KApplication::notify (this=0x8fa89d0, receiver=0xa4f32cc, event=0xbf94acdc) at /usr/src/debug/kdelibs-4.7.4/kdeui/kernel/kapplication.cpp:311
    #29 0x412da5fe in QCoreApplication::notifyInternal (this=0x8fa89d0, receiver=0xa4f32cc, event=0xbf94acdc) at kernel/qcoreapplication.cpp:876
    #30 0x4130f3c0 in sendEvent (event=0xbf94acdc, receiver=<optimized out>) at kernel/qcoreapplication.h:231
    #31 QTimerInfoList::activateTimers (this=0x8fb730c) at kernel/qeventdispatcher_unix.cpp:611
    #32 0x4130ca89 in timerSourceDispatch (source=0x8fb72d8) at kernel/qeventdispatcher_glib.cpp:186
    #33 timerSourceDispatch (source=0x8fb72d8) at kernel/qeventdispatcher_glib.cpp:180
    #34 0x4a2ab62f in g_main_dispatch (context=0x8fb7200) at gmain.c:2441
    #35 g_main_context_dispatch (context=0x8fb7200) at gmain.c:3011
    #36 0x4a2abd70 in g_main_context_iterate (context=0x8fb7200, block=1244375056, dispatch=1, self=0x8fb8b90) at gmain.c:3089
    #37 0x4a2ac01f in g_main_context_iteration (context=0x8fb7200, may_block=1) at gmain.c:3152
    #38 0x4130d2b8 in QEventDispatcherGlib::processEvents (this=0x8f7ff28, flags=...) at kernel/qeventdispatcher_glib.cpp:424
    #39 0x4b058a9b in QGuiEventDispatcherGlib::processEvents (this=0x8f7ff28, flags=...) at kernel/qguieventdispatcher_glib.cpp:207
    #40 0x412d94ee in QEventLoop::processEvents (this=0xbf94af54, flags=...) at kernel/qeventloop.cpp:149
    #41 0x412d9799 in QEventLoop::exec (this=0xbf94af54, flags=...) at kernel/qeventloop.cpp:204
    #42 0x412de93b in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1148
    #43 0x4afa1f35 in QApplication::exec () at kernel/qapplication.cpp:3811
    #44 0x080caa93 in main (argc=2, argv=0xbf94b124) at /usr/src/debug/kvirc-4.0.4/src/kvirc/kernel/kvi_main.cpp:456

    Segnala a https://svn.kvirc.de/kvirc/
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/1255

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Jan 2015 14:50:18**
Version: 4.0.4 Insomnia → 4.2.0 Equilibrium
