### ISSUE TITLE
bold fonts cause crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#167]
**Reported by k0sm|k0 on 23 Jun 2008 02:40:37 UTC**
here is the bugtrack:

kde 3.5.9
debian testing/unstable

(no debugging symbols found)
Using host libthread_db library "/lib/i686/cmov/libthread_db.so.1".
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[Thread debugging using libthread_db enabled]
[New Thread 0xb64d26c0 (LWP 13919)](no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[KCrash handler]
#6  0xb6bf080f in ?? () from /usr/lib/libX11.so.6
#7  0x083b3b72 in ?? ()
#8  0x0000002d in ?? ()
#9  0x0000003c in ?? ()
#10 0xb6c61b24 in ?? () from /usr/lib/libX11.so.6
#11 0x083b3758 in ?? ()
#12 0x083b3a38 in ?? ()
#13 0xbfbf4228 in ?? ()
#14 0xb6befe66 in ?? () from /usr/lib/libX11.so.6
#15 0x083b3ab0 in ?? ()
#16 0x083b38f1 in ?? ()
#17 0xbfbf423c in ?? ()
#18 0xbfbf4218 in ?? ()
#19 0x083b3b38 in ?? ()
#20 0x083b36b0 in ?? ()
#21 0x086344bc in ?? ()
#22 0x08630e48 in ?? ()
#23 0x083b374c in ?? ()
#24 0x00000001 in ?? ()
#25 0x0000003c in ?? ()
#26 0xb6c61b24 in ?? () from /usr/lib/libX11.so.6
#27 0x08630f78 in ?? ()
#28 0x00000015 in ?? ()
#29 0xb64d2698 in ?? ()
#30 0xb6bf075b in ?? () from /usr/lib/libX11.so.6
#31 0x00000001 in ?? ()
#32 0x00000000 in ?? ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/167

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 23 Jun 2008 14:48:19**
It's useless.<br/>
Compile KVIrc with debug symbols!

**Comment by DarthGandalf** [comment]
**Comment by Voker57 on 23 Jun 2008 16:23:39**
Where exactly were bold fonts?

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Jul 2008 14:03:05**
useless bugreport, no information into it. tested and seems to work

---

Resolution: none → worksforme
Status: new → closed
