### ISSUE TITLE
Notifier crash in Linux while monitor is disconnected

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#1887]
All I have is `[4090358.041874] kvirc4[14717]: segfault at 28 ip 00007ff74f615d24 sp 00007ffd9ea9c0e0 error 4 in libQt5Widgets.so.5.4.2[7ff74f480000+636000]`

I _believe_ this happened when I disconnected DVI cable between my computer and monitor.
But it also _could_ be related to connectivity lost.

My internet broke, and I reattached monitor to router to debug it. When I reattached monitor back, KVIrc was already gone. The stated belief is based on timing in `dmesg`

```
KVIrc 4.9.1 'Aria'

Информация времени выполнения:
System name: Linux 4.0.5-zen+
System version: #1 ZEN SMP Thu Jun 18 22:29:11 IST 2015
Архитектура: x86_64
Qt version: 5.4.2
Qt theme: fusion

Информация о сборке:
Build date: 2016-01-03 12:15:02 UTC
Sources date: 20160102
Revision number: a90d8193157947eb1ee6b4a7a0b5a0c8801c0cb6
System name: Linux-4.0.5-zen+
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing 
Qt version: 5.4.2
```

**Comment by un1versal** [comment]
On an unrelated report @1977David told me that in his laptop when disconnecting from main power KVIrc bails, I'd be interested to know more details from him regarding that, to see if they have anything in common with this report aside from the fact that he is also running some Linux distro.

David?

**Comment by DaVukovic** [comment]
I guess my circumstances are a bit different.

I used KVIrc on a laptop. This was put into a docking station to use extenal keyboard, monitor and mouse. If I took the laptop out of the docking station, KVIrc isn't shown anymore on the laptop screen, as expected. There isn't even a minimized window or anything else. If I look for running processes (ps -u username) I can see KVIrc is still running, but I can't get it back to the screen. 

Don't know if this is really a KVIrc or maybe a Ubuntu (Kubuntu with KDE) issue. 

Killing the process and restart KVIrc works fine then.

But yes...what more details do you want to know?

**Comment by un1versal** [comment]
I see quite a few similarities even if circumstances arent exactly the same), but tbh unless your dmesg or other logs show something related idk.

Or maybe thats just me.

**Comment by DarthGandalf** [comment]
No, it's different: mine was genuine segfault, David's one was unability to access window while process is still running.

**Comment by un1versal** [comment]
Both caused by unplugging something.

**Comment by un1versal** [comment]
> [05:07:03]  `<Pragma>` #1887 is "unknown circumstances"... probably unfixable

will this ever be fixed? I mean without a real known cause how will any potential developers fix this or any similar issue?

removed from release blockers since its unlikely to be resolved like this or in any foreseeable future.

**Comment by un1versal** [comment]
@DarthGandalf retest with current master please

**Comment by DarthGandalf** [comment]
@un1versal sure.

To reproduce:
1. switch to a different window
2. disconnect monitor cable
3. highlight yourself (e.g. from a different nick)
4. notifier crashes

```
(gdb) bt full
#0  QScreen::handle (this=0x0) at kernel/qscreen.cpp:112
No locals.
#1  0x00007ffff52fa6c5 in QWindowPrivate::applyCursor (this=this@entry=0x1bf6500) at kernel/qwindow.cpp:2464
        platformCursor = <optimized out>
#2  0x00007ffff52fb861 in QWindow::setVisible (this=this@entry=0x1beb840, visible=visible@entry=true) at kernel/qwindow.cpp:514
No locals.
#3  0x00007ffff5845a96 in QWidgetPrivate::show_sys (this=this@entry=0x1bcfaf0) at kernel/qwidget.cpp:7895
        geomRect = {x1 = 1548, y1 = 890, x2 = 1917, y2 = 1049}
        window = 0x1beb840
#4  0x00007ffff584dc33 in QWidgetPrivate::show_helper (this=this@entry=0x1bcfaf0) at kernel/qwidget.cpp:7824
        isEmbedded = <optimized out>
        showEvent = {<QEvent> = {_vptr.QEvent = 0x7ffff569a210 <vtable for QShowEvent+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff5183dc0 <qt_meta_stringdata_QEvent>, data = 0x7ffff5183800 <qt_meta_data_QEvent>, static_metacall = 0x0, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d = 0x0, t = 17, posted = 0, spont = 0, m_accept = 1, reserved = 0}, <No data fields>}
#5  0x00007ffff585094d in QWidget::setVisible (this=0x1bcf9f0, visible=<optimized out>) at kernel/qwidget.cpp:8108
        initialWindowState = {i = 0}
        needUpdateGeometry = <optimized out>
        showToParentEvent = {_vptr.QEvent = 0x0, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff5183dc0 <qt_meta_stringdata_QEvent>, data = 0x7ffff5183800 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
          d = 0x6bce42f2eb6d9200, t = 61808, posted = 1, spont = 1, m_accept = 1, reserved = 139}
#6  0x00007fffc3bd7e76 in NotifierWindow::doShow (this=0x1bcf9f0, bDoAnimate=<optimized out>) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/modules/notifier/NotifierWindow.cpp:356
        tNow = <optimized out>
#7  0x00007fffc3bd5398 in notifier_module_ctrl (pcOperation=<optimized out>, pParam=0x7fffffffc640) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/modules/notifier/libkvinotifier.cpp:305
        pcOperation = <optimized out>
        pParam = 0x7fffffffc640
#8  0x0000000000696547 in KviApplication::notifierMessage (this=0xa2eb80, pWnd=pWnd@entry=0x18810f0, iIconId=iIconId@entry=48, szMsg=..., uMessageLifetime=30) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviApplication.cpp:875
        m = 0x1bc9e10
        s = {pWindow = 0x18810f0, szIcon = {static null = {<No data fields>}, d = 0x457be90}, szMessage = {static null = {<No data fields>}, d = 0x457bbb0}, uMessageLifetime = 30}
        szTitle = {static null = {<No data fields>}, d = 0x12b1760}
        szText = {static null = {<No data fields>}, d = 0x457bc00}
        __func__ = "notifierMessage"
#9  0x000000000059e9fe in KviIrcServerParser::parseLiteralPrivmsg (this=<optimized out>, msg=0x7fffffffca90) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/sparser/KviIrcServerParser_literalHandlers.cpp:1077
        szMsg = {static null = {<No data fields>}, d = 0x457bbb0}
        iFlags = <optimized out>
        szBuffer = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x457bbe0 "", m_len = 0}
        txtptr = <optimized out>
        msgtype = 26
        szMsgText = {static null = {<No data fields>}, d = 0x45bcbd0}
        szOtherHost = <optimized out>
        bSelfMessage = <optimized out>
        query = 0x18810f0
        szSourceHost = {static null = {<No data fields>}, d = 0x45cc2b0}
        szTargetHost = {static null = {<No data fields>}, d = 0x161b5e0}
        pTrailing = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x45437d0 "test", m_len = 4}
        szSourceUser = {static null = {<No data fields>}, d = 0x45cbe60}
        szTarget = {static null = {<No data fields>}, d = 0x45c9e50}
        szTargetUser = {static null = {<No data fields>}, d = 0x161b5e0}
        uSource = <optimized out>
        szSourceNick = {static null = {<No data fields>}, d = 0x214cb90}
        szMsg = {static null = {<No data fields>}, d = 0x444f740}
        szTargetNick = {static null = {<No data fields>}, d = 0x45bad10}
        console = 0xefda00
        eCapState = <optimized out>
#10 0x00000000005bd225 in KviIrcServerParser::parseMessage (this=0xc862d0, message=message@entry=0x45cc8a0 "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test", pConnection=0x12b06f0)
    at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/sparser/KviIrcServerParser.cpp:110
        i = 15
        msg = {m_ptr = 0x45cc900 "DarthGandalf :test", m_szPrefix = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x45cbb10 "testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82", m_len = 55}, m_szMessageTags = {<KviHeapObject> = {<No data fields>}, 
            m_ptr = 0x45c9720 "time=2016-08-06T14:57:24.855Z", m_len = 29}, m_szCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x45be5a0 "PRIVMSG", m_len = 7}, m_pParams = std::vector of length 2, capacity 2 = {{<KviHeapObject> = {<No data fields>}, 
              m_ptr = 0x45a7a90 "DarthGandalf", m_len = 12}, {<KviHeapObject> = {<No data fields>}, m_ptr = 0x1d8e800 "test", m_len = 4}}, m_ParsedMessageTags = {{d = 0x45ca1a0, e = 0x45ca1a0}}, m_pConsole = 0xefda00, m_pConnection = 0x12b06f0, m_iNumericCommand = -1, 
          m_iFlags = 0, m_time = {d = {d = 0x45c6340}}}
#11 0x00000000006c49f1 in KviIrcConnection::incomingMessage (this=<optimized out>, pcMessage=pcMessage@entry=0x45cc8a0 "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test")
    at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviIrcConnection.cpp:1936
No locals.
#12 0x00000000006d69fc in KviIrcLink::processData (this=0x12a7960, buffer=buffer@entry=0x7fffffffcbb0 "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test\r\n", iLen=iLen@entry=116)
    at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviIrcLink.cpp:263
        p = 0x7fffffffcc22 "\r\n"
        cBeginOfCurData = 0x7fffffffcbb0 "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test\r\n"
        iBufLen = 114
        cMessageBuffer = 0x45cc8a0 "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test"
#13 0x00000000006d99e6 in KviIrcSocket::readData (this=0x131be10) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviIrcSocket.cpp:1558
        cBuffer = "@time=2016-08-06T14:57:24.855Z :testtest!25e4e852@gateway/web/freenode/ip.37.228.232.82 PRIVMSG DarthGandalf :test\r\n\000\000\000\000\060Y\247\000\000\000\000\000\001\000\000\000\000\000\000\000&\030\354\364\377\177\000\000\217\253\a\000\000\000\000\000\264\302!\036\000\000\000\000\003\000\000\000K\000\000\000\000\222m\353\362B\316k\001", '\000' <repeats 11 times>, "\377\177\000\000\060Y\247\000\000\000\000\000"...
        iReadLength = 116
#14 0x00007ffff4ff1da7 in QMetaObject::activate (sender=sender@entry=0x15fa660, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd0f0) at kernel/qobject.cpp:3713
        receiverInSameThread = <optimized out>
        sw = {receiver = 0x131be10, previousSender = 0x0, currentSender = {sender = 0x15fa660, signal = 3, ref = 1}, switched = true}
        callFunction = 0x6fcb30 <KviIrcSocket::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>
        receiver = 0x131be10
        method_relative = 2
        c = 0x15e0dc0
        last = 0x15e0dc0
        locker = <optimized out>
        connectionLists = {connectionLists = 0x11efc00}
        list = <optimized out>
        signal_index = 3
        empty_argv = {0x0}
        currentThreadId = 0x7ffff7e05780
#15 0x00007ffff4ff24f7 in QMetaObject::activate (sender=sender@entry=0x15fa660, m=m@entry=0x7ffff51fbe80 <QSocketNotifier::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd0f0) at kernel/qobject.cpp:3578
No locals.
#16 0x00007ffff50647ae in QSocketNotifier::activated (this=this@entry=0x15fa660, _t1=14) at .moc/moc_qsocketnotifier.cpp:134
        _a = {0x0, 0x7fffffffd0ec}
#17 0x00007ffff4ffe4cb in QSocketNotifier::event (this=0x15fa660, e=<optimized out>) at kernel/qsocketnotifier.cpp:260
        d = 0x15e6fb0
#18 0x00007ffff580e2ac in QApplicationPrivate::notify_helper (this=this@entry=0xa2ec50, receiver=receiver@entry=0x15fa660, e=e@entry=0x7fffffffd360) at kernel/qapplication.cpp:3716
        consumed = <optimized out>
#19 0x00007ffff5813700 in QApplication::notify (this=0xa2eb80, receiver=0x15fa660, e=0x7fffffffd360) at kernel/qapplication.cpp:3499
        w = 0x15fa660
        extra = <optimized out>
        isProxyWidget = <optimized out>
        res = false
#20 0x00007ffff4fcac2c in QCoreApplication::notifyInternal (this=0xa2eb80, receiver=0x15fa660, event=event@entry=0x7fffffffd360) at kernel/qcoreapplication.cpp:965
        threadData = 0xa2e180
        loopLevelCounter = {threadData = 0xa2e180}
        result = false
        cbdata = {0x15fa660, 0x7fffffffd360, 0x7fffffffd30f}
        d = <optimized out>
#21 0x00007ffff5016c55 in QCoreApplication::sendEvent (event=0x7fffffffd360, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
No locals.
#22 socketNotifierSourceDispatch (source=0xa790e0) at kernel/qeventdispatcher_glib.cpp:101
        p = <optimized out>
        i = 8
        event = {_vptr.QEvent = 0x7ffff51f85f0 <vtable for QEvent+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff5183dc0 <qt_meta_stringdata_QEvent>, data = 0x7ffff5183800 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, 
              extradata = 0x0}}, d = 0x0, t = 50, posted = 0, spont = 0, m_accept = 1, reserved = 0}
#23 0x00007ffff09baf84 in g_main_dispatch (context=0x7fffe00016f0) at /mnt/3tbhome/portage-tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3154
        dispatch = 0x7ffff5016bc8 <socketNotifierSourceDispatch(GSource*, GSourceFunc, gpointer)>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0xa790e0
        current = 0xa7e360
        i = 0
#24 g_main_context_dispatch (context=context@entry=0x7fffe00016f0) at /mnt/3tbhome/portage-tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3769
No locals.
#25 0x00007ffff09bb260 in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /mnt/3tbhome/portage-tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3840
        max_priority = 2147483647
        timeout = 478
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 11
        fds = 0x1585d80
#26 0x00007ffff09bb30c in g_main_context_iteration (context=0x7fffe00016f0, may_block=1) at /mnt/3tbhome/portage-tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
        retval = <optimized out>
#27 0x00007ffff50162ef in QEventDispatcherGlib::processEvents (this=0xa75d30, flags=...) at kernel/qeventdispatcher_glib.cpp:418
        d = 0xa793e0
        canWait = <optimized out>
        savedFlags = {i = 0}
        result = <optimized out>
#28 0x00007ffff4fc9932 in QEventLoop::exec (this=this@entry=0x7fffffffd570, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
        locker = {val = 10677808}
        ref = {d = 0xd8f5c0, locker = @0x7fffffffd4f0, exceptionCaught = true}
        d = 0xd8f5c0
#29 0x00007ffff4fd0a54 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
        threadData = 0xa2e180
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff51fbb10 <vtable for QEventLoop+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff51267c0 <qt_meta_stringdata_QObject>, data = 0x7ffff5126680 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff4ffa9c8 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0xd8f5c0}, static staticQtMetaObject = {d = {superdata = 0x0, 
                stringdata = 0x7ffff516e1c0 <qt_meta_stringdata_Qt>, data = 0x7ffff516b7c0 <qt_meta_data_Qt>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {superdata = 0x7ffff51fde00 <QObject::staticMetaObject>, 
              stringdata = 0x7ffff51833c0 <qt_meta_stringdata_QEventLoop>, data = 0x7ffff5183340 <qt_meta_data_QEventLoop>, static_metacall = 0x7ffff5064150 <QEventLoop::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, 
              extradata = 0x0}}}
        returnCode = <optimized out>
#30 0x00007ffff52eb79c in QGuiApplication::exec () at kernel/qguiapplication.cpp:1527
No locals.
#31 0x00007ffff580a035 in QApplication::exec () at kernel/qapplication.cpp:2976
No locals.
#32 0x00000000004c9be8 in main (argc=1, argv=0x7fffffffd848) at /mnt/3tbhome/portage-tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviMain.cpp:488
        a = {argc = 1, argv = 0x7fffffffd848, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, bExecuteCommandAndClose = false, szExecCommand = {static null = {<No data fields>}, d = 0x7ffff5088860 <QArrayData::shared_null>}, 
          szExecRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff5088860 <QArrayData::shared_null>}}
        iRetVal = <optimized out>
        iRetCode = <optimized out>
        pAboutData = <optimized out>
        pTheApp = 0xa2eb80
        szRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff5088860 <QArrayData::shared_null>}
```

```
KVIrc 4.9.2 'Aria'

Информация времени выполнения:
System name: Linux 4.6.2-zen+
System version: #1 ZEN SMP Tue Jun 14 08:30:50 IST 2016
Архитектура: x86_64
Qt version: 5.5.1
Qt theme: breeze

Информация о сборке:
Build date: 2016-08-06 14:23:13 UTC
Sources date: 20160102
Revision number: 96a891d1aa378cfde46b9a7ecd2d3bdaff66b00f
System name: Linux-4.6.2-zen+
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Compiler name: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing 
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by ogoffart** [comment]
The backtrace indicates that this is this bug in Qt:  https://bugreports.qt.io/browse/QTBUG-59528

**Comment by IceN9ne** [comment]
Qt bug, nothing to be done.
