### ISSUE TITLE
Creating layout object with toolbar parent creates crash

### ISSUE THREAD

**Issue by Cabji** [kvirc/KVIrc#1928]
### Expected behavior

Creation of layout object with toolbar class object as its parent in KVS
### Actual behavior

Main application KVIRC crashes
### Steps to reproduce the issue
1. Use this code: paste into Script Tester

```
# toolbar-crash.kvs - this file demonstrates the gui classes in KVS

### gui stuff below here
%parentWidget = $new(widget)
%parentWidget->$setGeometry(400,400,400,200)
%toolbar = $new(toolbar, %parentWidget)

# comment/uncomment this line to toggle crash
%tbLayout = $new(layout,%toolbar)

%parentWidget->$show()
```
1. Execute code
2. KVIRC crashes
### System information

KVIrc 4.2.0 'Equilibrium'

Runtime Info:
System Name: Linux 3.16.0-4-amd64
System Version: #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17)
Architecture: x86_64

Build Info:
Build Date: 2015-12-17 17:01:37 UTC
Sources Date: 20120701
Revision Number: 420
System Name: Linux-3.16.0-4-amd64
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 

```
Debian 8 Jessie
```

**Comment by un1versal** [comment]
~~Dont be scared by the invalid label... :) it will be updated once you retest and provide feedback~~

4.2.0 is an **ancient** build and no fixes will happen there, and while its stable reporting bugs against it is useless.

Please retest with a nightly build see https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrc's-nightly-source-or-binaries

thx

**Comment by wodim** [comment]
Confirmed on trunk.

**Comment by pragmaware** [comment]
Heh.. I guess it's something Qt does not support. It's expecting to have a specialized layout class on the toolbars. The stack is entirely within Qt.

```
#0  QLayout::parentWidget (this=0x1ab3f00) at kernel/qlayout.cpp:469
#1  0x00007ffff34074fb in QToolBarLayout::movable (this=<optimized out>) at widgets/qtoolbarlayout.cpp:241
#2  0x00007ffff340640e in QToolBar::initStyleOption (this=this@entry=0x1ab3ac0, option=option@entry=0x7fffffffc630) at widgets/qtoolbar.cpp:1192
#3  0x00007ffff3406715 in QToolBar::paintEvent (this=0x1ab3ac0) at widgets/qtoolbar.cpp:983
#4  0x00007ffff328ef88 in QWidget::event (this=this@entry=0x1ab3ac0, event=event@entry=0x7fffffffca20) at kernel/qwidget.cpp:9044
#5  0x00007ffff3406aa3 in QToolBar::event (this=0x1ab3ac0, event=0x7fffffffca20) at widgets/qtoolbar.cpp:1144
#6  0x00007ffff324c05c in QApplicationPrivate::notify_helper (this=this@entry=0xa11480, receiver=receiver@entry=0x1ab3ac0, e=e@entry=0x7fffffffca20) at kernel/qapplication.cpp:3716
#7  0x00007ffff3251516 in QApplication::notify (this=0xa113e0, receiver=0x1ab3ac0, e=0x7fffffffca20) at kernel/qapplication.cpp:3499
#8  0x00007ffff295962b in QCoreApplication::notifyInternal (this=0xa113e0, receiver=receiver@entry=0x1ab3ac0, event=event@entry=0x7fffffffca20) at kernel/qcoreapplication.cpp:965
#9  0x00007ffff3287a79 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffca20, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227
#10 QWidgetPrivate::sendPaintEvent (this=this@entry=0x1ab3b00, toBePainted=...) at kernel/qwidget.cpp:5625
#11 0x00007ffff32880c1 in QWidgetPrivate::drawWidget (this=this@entry=0x1ab3b00, pdev=pdev@entry=0x156fe80, rgn=..., offset=..., flags=flags@entry=4, sharedPainter=sharedPainter@entry=0x0, 
    backingStore=0x1ab6000) at kernel/qwidget.cpp:5565
#12 0x00007ffff3288d6c in QWidgetPrivate::paintSiblingsRecursive (this=this@entry=0x1ab32c0, pdev=pdev@entry=0x156fe80, siblings=..., index=<optimized out>, rgn=..., offset=..., flags=4, sharedPainter=0x0, 
    backingStore=0x1ab6000) at kernel/qwidget.cpp:5760                                                                                                                                                         
#13 0x00007ffff3287c31 in QWidgetPrivate::drawWidget (this=0x1ab32c0, pdev=0x156fe80, rgn=..., offset=..., flags=flags@entry=5, sharedPainter=sharedPainter@entry=0x0, backingStore=0x1ab6000)                 
    at kernel/qwidget.cpp:5617                                                                                                                                                                                 
#14 0x00007ffff32598aa in QWidgetBackingStore::doSync (this=this@entry=0x1ab6000) at kernel/qwidgetbackingstore.cpp:1226                                                                                       
#15 0x00007ffff325a0a2 in QWidgetBackingStore::sync (this=0x1ab6000, exposedWidget=0x1ab3280, exposedRegion=...) at kernel/qwidgetbackingstore.cpp:954                                                         
#16 0x00007ffff32aba43 in QWidgetWindow::event (this=0x1ab2bb0, event=0x7fffffffd420) at kernel/qwidgetwindow.cpp:255                                                                                          
#17 0x00007ffff324c05c in QApplicationPrivate::notify_helper (this=this@entry=0xa11480, receiver=receiver@entry=0x1ab2bb0, e=e@entry=0x7fffffffd420) at kernel/qapplication.cpp:3716                           
#18 0x00007ffff3251516 in QApplication::notify (this=0xa113e0, receiver=0x1ab2bb0, e=0x7fffffffd420) at kernel/qapplication.cpp:3499                                                                           
#19 0x00007ffff295962b in QCoreApplication::notifyInternal (this=0xa113e0, receiver=receiver@entry=0x1ab2bb0, event=event@entry=0x7fffffffd420) at kernel/qcoreapplication.cpp:965                             
#20 0x00007ffff2c9c4ec in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd420, receiver=0x1ab2bb0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:227                            
#21 QGuiApplicationPrivate::processExposeEvent (e=0x1ab5170) at kernel/qguiapplication.cpp:2663                                                                                                                
#22 0x00007ffff2c9d25d in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0x1ab5170) at kernel/qguiapplication.cpp:1658                                                                            
#23 0x00007ffff2c80f38 in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:625                                                                                  
#24 0x00007fffe4374f10 in userEventSourceDispatch (source=<optimized out>) at eventdispatchers/qeventdispatcher_glib.cpp:70
#25 0x00007fffee317127 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fffee317380 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007fffee31742c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff29afa7f in QEventDispatcherGlib::processEvents (this=0xa5e190, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#29 0x00007ffff2956dea in QEventLoop::exec (this=this@entry=0x7fffffffd6e0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#30 0x00007ffff295ee8c in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1229
#31 0x00000000006aaea6 in main (argc=2, argv=0x7fffffffd9e8) at /src/pragma/kvirc-git/KVIrc/src/kvirc/kernel/KviMain.cpp:481
```

I'm not sure how to handle it though... disallow creation of layouts attached to toolbars?
