### ISSUE TITLE
dockwindow class: causes kvirc to crash (seem OS independant)

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2077]
### Expected behavior

to get a nice docked window
### Actual behavior

crash 

reference  
https://github.com/kvirc/KVIrc/blob/master/src/modules/objects/KvsObject_dockWindow.cpp  
https://github.com/kvirc/KVIrc/blob/master/src/modules/objects/KvsObject_dockWindow.h
### Steps to reproduce the issue
1. open script tester
2. paste https://gist.githubusercontent.com/un1versal/bf4ae903246f6b1494092866d4454860/raw
3. click execute
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-31-generic
System version: #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-07-27 09:07:27 UTC
Sources date: 20160727
Revision number: git-6816-g96bf84f-dirty
System name: Linux-4.4.0-31-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```
### stacktrace

doesnt say much sadly

```
Thread 4 (Thread 0x7fffe4eda700 (LWP 4025)):
#0  0x00007ffff78e2c5d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffeea2d4a6 in RTThreadSleep () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#2  0x00007fffeea0b493 in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#3  0x00007fffeea2f7ec in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#4  0x00007fffeea3c6fd in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#5  0x00007ffff78d96fa in start_thread (arg=0x7fffe4eda700) at pthread_create.c:333
#6  0x00007ffff2d70b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffe7132700 (LWP 4022)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007ffff2d64e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff27e8c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff27ea8d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fffe9cb9629 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ffff397984e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff78d96fa in start_thread (arg=0x7fffe7132700) at pthread_create.c:333
#6  0x00007ffff2d70b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7e258c0 (LWP 4021)):
#0  0x00007ffff2d64e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff103e39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#2  0x00007ffff103e4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff3bb0a7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff3b57dea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff3b5fe8c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00000000006ae606 in main (argc=1, argv=0x7fffffffe178) at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviMain.cpp:488
(gdb) c
Continuing.
[New Thread 0x7fffe56db700 (LWP 4038)]
[Thread 0x7fffe56db700 (LWP 4038) exited]

Thread 1 "kvirc" received signal SIGSEGV, Segmentation fault.
0x00007ffff45794f0 in QDockWidgetLayout::widgetForRole(QDockWidgetLayout::Role) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffe4eda700 (LWP 4025) exited]
[Thread 0x7fffe7132700 (LWP 4022) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by un1versal** [comment]
another stacktrace

```
Thread 1 (Thread 0x7f590ee978c0 (LWP 3669)):
#0  0x00007f5909dd2e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f59080ac39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f59080ac4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f590ac1ea7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f590abc5dea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f590abcde8c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#6  0x00000000006fa029 in main (argc=2, argv=0x7ffeb71f1ac8) at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviMain.cpp:488
(gdb) c
Continuing.

Thread 1 "kvirc" received signal SIGSEGV, Segmentation fault.
0x00007f590b5e74f0 in QDockWidgetLayout::widgetForRole(QDockWidgetLayout::Role) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) thread apply all bt

Thread 5 (Thread 0x7f58ee295700 (LWP 3677)):
#0  0x00007f590e950c5d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f5905a9b4a6 in RTThreadSleep () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#2  0x00007f5905a79493 in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#3  0x00007f5905a9d7ec in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#4  0x00007f5905aaa6fd in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#5  0x00007f590e9476fa in start_thread (arg=0x7f58ee295700) at pthread_create.c:333
#6  0x00007f5909ddeb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f58f4ab7700 (LWP 3674)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f5909dd2e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f59080ac39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f59080ac722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f58f7d5c916 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f59080d2bc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f590e9476fa in start_thread (arg=0x7f58f4ab7700) at pthread_create.c:333
#6  0x00007f5909ddeb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f58f52b8700 (LWP 3673)):
#0  0x00007f5909dd2e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f59080ac39c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#2  0x00007f59080ac4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f59080ac4e9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f59080d2bc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f590e9476fa in start_thread (arg=0x7f58f52b8700) at pthread_create.c:333
#6  0x00007f5909ddeb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f58fe1a0700 (LWP 3672)):
#0  0x00007f5909dd2e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f5909856c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f59098588d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f5900d27629 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
---Type <return> to continue, or q <return> to quit---
#4  0x00007f590a9e784e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f590e9476fa in start_thread (arg=0x7f58fe1a0700) at pthread_create.c:333
#6  0x00007f5909ddeb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f590ee978c0 (LWP 3669)):
#0  0x00007f590b5e74f0 in QDockWidgetLayout::widgetForRole(QDockWidgetLayout::Role) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007f590b5e882f in QDockWidget::paintEvent(QPaintEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007f590b4fdf88 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007f590b5eafe3 in QDockWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007f590b4bb05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007f590b4c0516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#6  0x00007f590abc862b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f590b4f6a79 in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f590b4f70c1 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f590b4f7d6c in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f590b4f6c31 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f590b4c88aa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f590b4c8a8c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f590b4e6c1f in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#14 0x00007f590b4fdd88 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f590b613d8b in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f590b4bb05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f590b4c0516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f590abc862b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f590abcaa26 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f590ac1e673 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f59080ac1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f59080ac400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f59080ac4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f590ac1ea7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#25 0x00007f590abc5dea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007f590abcde8c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00000000006fa029 in main (argc=2, argv=0x7ffeb71f1ac8) at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviMain.cpp:488
```

**Comment by un1versal** [comment]
anyone, second stacktrace is it any help?
