### ISSUE TITLE
Crash when moving dock to trash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#210]
**Reported by Voker57 on 21 Aug 2008 07:23:10 UTC**
How to reproduce: press Ctrl+Alt+6 and drag one of docking panels to trashcan, then grab it by mouse and release in the same position. Kvirc will crush either immediately or after pressing of 'close' button.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/210

**Comment by DarthGandalf** [comment]
**Comment by Voker57 on 21 Aug 2008 07:28:21**
Backtrace:

```
 [?1034hGNU gdb 6.8
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux"...
[Thread debugging using libthread_db enabled]
[New Thread 0x7fec9b4d9700 (LWP 6148)]
[New Thread 0x40f6c950 (LWP 6152)]
[New Thread 0x4176d950 (LWP 6153)]
[Thread 0x40f6c950 (LWP 6152) exited]
[Thread 0x4176d950 (LWP 6153) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fec9b4d9700 (LWP 6148)]
0x00007fec97be6897 in QTitleBar::isActive ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#0  0x00007fec97be6897 in QTitleBar::isActive ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#1  0x00007fec97b6e36d in QDockWindow::drawFrame ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#2  0x00007fec97b74597 in QFrame::paintEvent ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#3  0x000000000061f5d9 in KviCustomToolBar::paintEvent (this=0xd21bb0, 
    e=0x7fffa35227a0) at ../ui/kvi_customtoolbar.cpp:127
#4  0x00007fec97afd1c5 in QWidget::event ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#5  0x00007fec97beabee in QToolBar::event ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#6  0x00007fec97a69435 in QApplication::internalNotify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#7  0x00007fec97a6a21a in QApplication::notify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#8  0x00007fec99ad9972 in KApplication::notify ()
   from /opt/kde3/lib64/libkdecore.so.4
#9  0x00007fec979fd32d in QETWidget::translatePaintEvent ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#10 0x00007fec97a06b98 in QApplication::x11ProcessEvent ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#11 0x00007fec97a1980a in QEventLoop::processEvents ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#12 0x00007fec97a7ff69 in QEventLoop::enterLoop ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#13 0x00007fec97a1710b in QDragManager::drag ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#14 0x00000000006205f8 in KviCustomToolBar::eventFilter (this=0xd83220, 
    o=<value optimized out>, e=<value optimized out>)
    at ../ui/kvi_customtoolbar.cpp:631
#15 0x00007fec97ac7e3c in QObject::activate_filters ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#16 0x00007fec97ac7e97 in QObject::event ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#17 0x00007fec97afcf53 in QWidget::event ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#18 0x00007fec97a69435 in QApplication::internalNotify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#19 0x00007fec97a6a432 in QApplication::notify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#20 0x00007fec99ad9972 in KApplication::notify ()
   from /opt/kde3/lib64/libkdecore.so.4
#21 0x00007fec97a07d0a in QETWidget::translateMouseEvent ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#22 0x00007fec97a06a7e in QApplication::x11ProcessEvent ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#23 0x00007fec97a1980a in QEventLoop::processEvents ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#24 0x00007fec97a7ff69 in QEventLoop::enterLoop ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#25 0x00007fec97a7fdf2 in QEventLoop::exec ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#26 0x00000000005211ca in main (argc=2, 
```

**Comment by DarthGandalf** [comment]
**Comment by Voker57 on 21 Aug 2008 07:29:10**
...

`````` argv=0x7fffa3524398)
    at ../kernel/kvi_main.cpp:406```
``````

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 22 Aug 2008 12:24:29**
fixed in r2272

---

Resolution: none → fixed
Status: new → closed
