### ISSUE TITLE
crash when testing popups

### ISSUE THREAD

**Issue by un1versal** [kvirc/KVIrc#2106]
### Expected behavior

not a crash
### Actual behavior

mmm dead kittens ... and yea a KVIrc crash
### Steps to reproduce the issue
1. open popup editor
2. select windowpopup
3. click test and select Option Controller

enjoy the crash.

![capture](https://cloud.githubusercontent.com/assets/3521959/17650224/90fb5c3c-6240-11e6-984e-558a432d908e.PNG)
### System information

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 3.13.0-91-generic
System version: #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-14 11:36:26 UTC
Sources date: 20160813
Revision number: git-6928-g921bcb6
System name: Linux-3.13.0-91-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```
## Stacktrace

```
Program received signal SIGSEGV, Segmentation fault.
0x00007f4382a7e2e5 in SinglePopupEditor::findMatchingItem (this=0x25254d0, it=0x25f79d0, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:298
298     if(item->m_type != PopupTreeWidgetItem::Item)
(gdb) threads apply all bt
Undefined command: "threads".  Try "help".
(gdb) thread apply all bt

Thread 5 (Thread 0x7f43ab1e1700 (LWP 5473)):
#0  0x00007f43b62b0fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f43b5d4fb72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f43b5d5164f in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f43add5f939 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f43b6e4ef6f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f43bace5184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f43b62be37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f43aa49b700 (LWP 5476)):
#0  0x00007f43b62b0fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f43b43adfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f43b43ae30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f43a87b4336 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f43b43d2f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f43bace5184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f43b62be37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7f439d59d700 (LWP 5477)):
#0  0x00007f43b62b0fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f43b43adfe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f43b43ae0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f43b43ae129 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f43b43d2f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f43bace5184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f43b62be37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f4396cf4700 (LWP 5480)):
#0  0x00007f43bacecb9d in nanosleep () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f43b1eb4a36 in RTThreadSleep () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#2  0x00007f43b1e92a23 in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#3  0x00007f43b1eb6d7c in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#4  0x00007f43b1ec3b2d in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#5  0x00007f43bace5184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f43b62be37d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f43bb23a780 (LWP 5471)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f4382a7e2e5 in SinglePopupEditor::findMatchingItem (this=0x25254d0, it=0x25f79d0, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:298
#1  0x00007f4382a7e521 in SinglePopupEditor::findMatchingItem (this=0x25254d0, it=0x25f79d0, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:350
#2  0x00007f4382a7e5b5 in SinglePopupEditor::testModeMenuItemClicked (this=0x25254d0, it=0x25f79d0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:367
#3  0x00007f4382a87887 in SinglePopupEditor::qt_static_metacall (_o=0x25254d0, _c=QMetaObject::InvokeMetaMethod, _id=26, _a=0x7fff3eb78250)
    at /home/un1versal/Desktop/KVIrc/build/src/modules/popupeditor/moc_PopupEditorWindow.cpp:191
#4  0x00007f43b705b316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000000000071abf7 in KviKvsPopupMenu::testModeItemClicked (this=0x25c1a10, _t1=0x25f79d0) at /home/un1versal/Desktop/KVIrc/build/src/kvirc/moc_KviKvsPopupMenu.cpp:244
#6  0x000000000062392f in KviKvsPopupMenu::itemClicked (this=0x25c1a10, pAction=0x2619180) at /home/un1versal/Desktop/KVIrc/src/kvirc/kvs/KviKvsPopupMenu.cpp:920
#7  0x000000000071a9d9 in KviKvsPopupMenu::qt_static_metacall (_o=0x25c1a10, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fff3eb78480)
    at /home/un1versal/Desktop/KVIrc/build/src/kvirc/moc_KviKvsPopupMenu.cpp:178
#8  0x00007f43b705b316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f43b7ad33e2 in QMenu::triggered(QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f43b7ad6194 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f43b7ad9e61 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f43b705b316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f43b795a302 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#14 0x00007f43b795c7d8 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f43b7ad43da in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f43b7ada2a4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f43b7ade26b in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f43b79a39f1 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f43b7adec7b in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f43b79638ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f43b796918c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f43b702b4e5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f43b7967bd1 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f43b79bc506 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f43b79be9e3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f43b79638ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007f43b79686f8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007f43b702b4e5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f43b73ce9b4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007f43b73d01c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007f43b73b52c8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#32 0x00007f43add8a750 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#33 0x00007f43b43ade04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007f43b43ae048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007f43b43ae0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007f43b708237c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007f43b70293a3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f43b7030f46 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00000000006ec16e in main (argc=3, argv=0x7fff3eb79658) at /home/un1versal/Desktop/KVIrc/src/kvirc/kernel/KviMain.cpp:488
```

**Comment by un1versal** [comment]
another crash also on test but a different popup

I imagine this applies to other popups and tests just as above so I also assume cause is same.

## Duplicate

1) open popup editor 
2) select consoletextview
3) select test and click clear buffer

```
[Thread 0x7fe1de110700 (LWP 5691) exited]
[New Thread 0x7fe1de110700 (LWP 5702)]
[Thread 0x7fe1de110700 (LWP 5702) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007fe1c5d472e5 in SinglePopupEditor::findMatchingItem (this=0x26fedc0, it=0x27cc920, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:298
298     if(item->m_type != PopupTreeWidgetItem::Item)
(gdb) thread apply all bt

Thread 6 (Thread 0x7fe1ecd54700 (LWP 5685)):
#0  0x00007fe1f7e23fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe1f78c2b72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fe1f78c464f in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fe1ef8d2939 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fe1f89c1f6f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fe1fc858184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fe1f7e3137d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fe1e7fff700 (LWP 5688)):
#0  0x00007fe1f7e23fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe1f5f20fe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fe1f5f2130a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fe1e6318336 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fe1f5f45f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fe1fc858184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fe1f7e3137d in clone () from /lib/x86_64-linux-gnu/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 4 (Thread 0x7fe1df112700 (LWP 5689)):
#0  0x00007fe1f7e23fdd in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fe1f5f20fe4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fe1f5f210ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fe1f5f21129 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fe1f5f45f05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fe1fc858184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fe1f7e3137d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fe1dc8b4700 (LWP 5692)):
#0  0x00007fe1fc85fb9d in nanosleep () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fe1f3a27a36 in RTThreadSleep () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#2  0x00007fe1f3a05a23 in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#3  0x00007fe1f3a29d7c in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#4  0x00007fe1f3a36b2d in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#5  0x00007fe1fc858184 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007fe1f7e3137d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7fe1fcdad780 (LWP 5682)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007fe1c5d472e5 in SinglePopupEditor::findMatchingItem (this=0x26fedc0, it=0x27cc920, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:298
#1  0x00007fe1c5d47521 in SinglePopupEditor::findMatchingItem (this=0x26fedc0, it=0x27cc920, item=0x0)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:350
#2  0x00007fe1c5d475b5 in SinglePopupEditor::testModeMenuItemClicked (this=0x26fedc0, it=0x27cc920)
    at /home/un1versal/Desktop/KVIrc/src/modules/popupeditor/PopupEditorWindow.cpp:367
#3  0x00007fe1c5d50887 in SinglePopupEditor::qt_static_metacall (_o=0x26fedc0, _c=QMetaObject::InvokeMetaMethod, _id=26, _a=0x7ffd4aecc760)
    at /home/un1versal/Desktop/KVIrc/build/src/modules/popupeditor/moc_PopupEditorWindow.cpp:191
#4  0x00007fe1f8bce316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x000000000071abf7 in KviKvsPopupMenu::testModeItemClicked (this=0x27b9a10, _t1=0x27cc920) at /home/un1versal/Desktop/KVIrc/build/src/kvirc/moc_KviKvsPopupMenu.cpp:244
#6  0x000000000062392f in KviKvsPopupMenu::itemClicked (this=0x27b9a10, pAction=0x27e7140) at /home/un1versal/Desktop/KVIrc/src/kvirc/kvs/KviKvsPopupMenu.cpp:920
#7  0x000000000071a9d9 in KviKvsPopupMenu::qt_static_metacall (_o=0x27b9a10, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7ffd4aecc990)
    at /home/un1versal/Desktop/KVIrc/build/src/kvirc/moc_KviKvsPopupMenu.cpp:178
#8  0x00007fe1f8bce316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fe1f96463e2 in QMenu::triggered(QAction*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007fe1f9649194 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fe1f964ce61 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fe1f8bce316 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fe1f94cd302 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#14 0x00007fe1f94cf7d8 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fe1f96473da in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fe1f964d2a4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fe1f965126b in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fe1f95169f1 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fe1f9651c7b in QMenu::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fe1f94d68ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fe1f94dc18c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fe1f8b9e4e5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007fe1f94dabd1 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fe1f952f506 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fe1f95319e3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fe1f94d68ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fe1f94db6f8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007fe1f8b9e4e5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007fe1f8f419b4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007fe1f8f431c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007fe1f8f282c8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#32 0x00007fe1ef8fd750 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#33 0x00007fe1f5f20e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007fe1f5f21048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007fe1f5f210ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fe1f8bf537c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007fe1f8b9c3a3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007fe1f8ba3f46 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00000000006ec16e in main (argc=3, argv=0x7ffd4aecdb68) at /home/un1versal/Desktop/KVIrc/src/kvirc/kernel/KviMain.cpp:488
```
