### ISSUE TITLE
Crash when closing context with socket spy attached (inside context)

### ISSUE THREAD

**Issue by ReggX** [kvirc/KVIrc#2110]
### Expected behavior

When inside a window of a context with a socket spy attached, closing said context should quietly close the context and all subwindows attached to it without issue.
### Actual behavior

Closing the context will crash the application, but only if the current active window is inside the context or the context itself. Closing from outside the context will execute as expected.

[Closing the currently selected context crashes](https://i.imgur.com/buvLIpQ.png)
### Steps to reproduce the issue
1. Open KVIrc Nightly (works best without any events or startup servers, tested with the config folder moved and restored default script)
2. Create a new IRC context
3. Add a socketspy to the context
4. Make sure the context or its socketspy is selected
5. Close the context
6. Application crash
### System information

```
KVIrc 4.9.2 'Aria'

Laufzeitinformationen:
System name: Windows Release : 6.1.7601
System version: Windows 7 Professional (x64) Service Pack 1 (Build 7601)
Architektur: Intel64 Family 6 Model 60 Stepping 3
Qt version: 5.5.1
Qt theme: windowsvista

Erstellungsinfo:
Build date: 2016-08-14 21:49:18 UTC
Sources date: 20160814
Revision number: git-6933-g65f77c7
System name: Windows-6.3.9600
CPU name: AMD64
Build command: C:/Program Files (x86)/CMake/bin/cmake.exe
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compiler name: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc
Qt version: 5.5.1
Features: IRC, IPv6, Crypt, SSL, IPC, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

Unfortunately, I don't have access to Debugging tools on this machine, so I can't provide a stacktrace. If someone can reproduce it, please add a stacktrace to the issue.

**Comment by un1versal** [comment]
It must be an UNCONNECTED context to crash.
if connected works here.

Stacktrace Linux

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.4.0-34-generic
System version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Architecture: x86_64
Qt version: 5.5.1
Qt theme: fusion

Build Info:
Build date: 2016-08-15 00:07:05 UTC
Sources date: 20160814
Revision number: git-6933-g65f77c7
System name: Linux-4.4.0-34-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=/x86_64-linux-gnu
   Threads=POSIX
Compiler name: /usr/bin/c++
Compiler flags: N/A
Qt version: 5.5.1
Features: IRC, Debug, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Webkit, Perl, Python, Enchant, Qt5, KVS
```

```
Thread 1 "kvirc" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) thread apply all bt

Thread 5 (Thread 0x7fd7e4086700 (LWP 4143)):
#0  0x00007fd7ff11dc5d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd7f62684a6 in RTThreadSleep () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#2  0x00007fd7f6246493 in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#3  0x00007fd7f626a7ec in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#4  0x00007fd7f62776fd in ?? () from /var/lib/VBoxGuestAdditions/lib/libGL.so.1
#5  0x00007fd7ff1146fa in start_thread (arg=0x7fd7e4086700) at pthread_create.c:333
#6  0x00007fd7fa5abb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fd7e528e700 (LWP 4140)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007fd7fa59fe8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd7f887939c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fd7f8879722 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd7ec83e916 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fd7f889fbc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd7ff1146fa in start_thread (arg=0x7fd7e528e700) at pthread_create.c:333
#6  0x00007fd7fa5abb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fd7e5a8f700 (LWP 4139)):
#0  0x00007fd7fa59fe8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd7f887939c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#2  0x00007fd7f88794ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fd7f88794e9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fd7f889fbc5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd7ff1146fa in start_thread (arg=0x7fd7e5a8f700) at pthread_create.c:333
#6  0x00007fd7fa5abb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fd7ee96d700 (LWP 4138)):
#0  0x00007fd7fa59fe8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd7fa023c62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fd7fa0258d7 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fd7f14f4629 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
---Type <return> to continue, or q <return> to quit---
#4  0x00007fd7fb1b484e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fd7ff1146fa in start_thread (arg=0x7fd7ee96d700) at pthread_create.c:333
#6  0x00007fd7fa5abb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7fd7ff66f8c0 (LWP 4136)):
#0  0x0000000000000000 in ?? ()
#1  0x00000000005295cd in KviMainWindow::windowActivated (this=0x24172b0, wnd=0x29f8de0, bForce=false)
    at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviMainWindow.cpp:787
#2  0x00000000005bb686 in KviWindowStack::currentWindowChanged (this=0x242f9b0, iIdx=12) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviWindowStack.cpp:78
#3  0x000000000074c08e in KviWindowStack::qt_static_metacall (_o=0x242f9b0, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7ffcb247e220)
    at /home/un1versal/Desktop/kvirc/build/src/kvirc/moc_KviWindowStack.cpp:80
---Type <return> to continue, or q <return> to quit---
#4  0x00007fd7fb3c3fca in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fd7fc02716e in QStackedWidget::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fd7fc0272f3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fd7fb3c3fca in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fd7fc020941 in QStackedLayout::currentChanged(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007fd7fbcad040 in QStackedLayout::setCurrentIndex(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007fd7fbcadc50 in QStackedLayout::takeAt(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fd7fbca65c7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fd7fbc8802e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007fd7fbc8d516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fd7fb39562b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#15 0x00007fd7fb3cb737 in QObjectPrivate::setParent_helper(QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fd7fb3cbdd4 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fd7fbcc6748 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00000000005aecc3 in KviWindow::~KviWindow (this=0x2a502a0, __in_chrg=<optimised out>) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviWindow.cpp:144
#19 0x00007fd7d48df3b0 in SocketSpyWindow::~SocketSpyWindow (this=0x2a502a0, __in_chrg=<optimised out>)
    at /home/un1versal/Desktop/kvirc/src/modules/socketspy/SocketSpyWindow.cpp:49
#20 0x00007fd7d48df408 in SocketSpyWindow::~SocketSpyWindow (this=0x2a502a0, __in_chrg=<optimised out>)
    at /home/un1versal/Desktop/kvirc/src/modules/socketspy/SocketSpyWindow.cpp:52
#21 0x00000000006fc76b in KviIrcContext::~KviIrcContext (this=0x2a21240, __in_chrg=<optimised out>)
    at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviIrcContext.cpp:100
#22 0x00000000006fc8e0 in KviIrcContext::~KviIrcContext (this=0x2a21240, __in_chrg=<optimised out>)
---Type <return> to continue, or q <return> to quit---
    at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviIrcContext.cpp:116
#23 0x0000000000513906 in KviConsoleWindow::~KviConsoleWindow (this=0x29f9340, __in_chrg=<optimised out>)
    at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviConsoleWindow.cpp:185
#24 0x00000000005139c8 in KviConsoleWindow::~KviConsoleWindow (this=0x29f9340, __in_chrg=<optimised out>)
    at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviConsoleWindow.cpp:189
#25 0x00000000005bb737 in KviWindowStack::destroyWindow (this=0x242f9b0, pWnd=0x29f9340) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviWindowStack.cpp:97
#26 0x0000000000528934 in KviMainWindow::closeWindow (this=0x24172b0, wnd=0x29f9340) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviMainWindow.cpp:516
#27 0x000000000052931d in KviMainWindow::childWindowCloseRequest (this=0x24172b0, wnd=0x29f9340) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviMainWindow.cpp:706
#28 0x00000000005b223c in KviWindow::closeEvent (this=0x29f9340, pEvent=0x7ffcb247ed80) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviWindow.cpp:870
#29 0x000000000051685a in KviConsoleWindow::closeEvent (this=0x29f9340, e=0x7ffcb247ed80) at /home/un1versal/Desktop/kvirc/src/kvirc/ui/KviConsoleWindow.cpp:555
#30 0x00007fd7fbccaf88 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#31 0x00007fd7fbc8805c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007fd7fbc8d516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007fd7fb39562b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fd7fbcc627d in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007fd7fbcc9c22 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007fd7fb3c4ea1 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007fd7fbccacdb in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007fd7fbc8805c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fd7fbc8d516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007fd7fb39562b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fd7fb397a26 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#42 0x00007fd7fb3eb673 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00007fd7f88791a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007fd7f8879400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007fd7f88794ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007fd7fb3eba7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007fd7fb392dea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007fd7fb39ae8c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x0000000000711543 in main (argc=2, argv=0x7ffcb247f638) at /home/un1versal/Desktop/kvirc/src/kvirc/kernel/KviMain.cpp:488
```

**Comment by IceN9ne** [comment]
Segfault (undefined behavior?) introduced (made apparent?) in 4bf5e90.  I gave up trying to figure out why deleting one way versus the other introduces the error.  Maybe @staticfox will know since it's his commit.
