### ISSUE TITLE
KVIrc crashes when trying to re-register an existing nick in the reguser database

### ISSUE THREAD

**Issue by SteJay** [kvirc/KVIrc#2226]
There seems to be a bug when we attempt to register a user who is already registered; this is happening where the netmask of the user differs from the one previously registered.

### Expected behavior

Netmask gets added to user record rather than a new record being created

### Actual behavior

kVIrc crashes completely

[//]:# (Besides the text description, include any screenshots that help us visualize the issue you're facing)

### Steps to reproduce the issue

As an example here is a popup I have that is causing kVIrc to crash - Note that it is the `reguser.add -g=Default $0 $mask($0,25)` instruction that is causing kVIrc to crash, and only when a user with the same nickname already exists in the regisitered users but with a different netmask:

```
defpopup()
{
	prologue
	{
		%:regName = $reguser.match($mask($0))
		if(%:regName)
		{
			%:allowQueries = $reguser.property(%:regName,allow_queries);
		}
	}
	
	item(Allow Queries,137) (%:regName==""||"%:allowQueries"=="false")
	{
		if("%:regName"=="") {
			// This next line will crash kVIrc if the nick already exists in the reguser database
			reguser.add -g=Default $0 $mask($0,25)
		}
		reguser.setproperty $0 allow_queries true
	}
}
```

1. A user is added with a given netmask, for example Nick!~user1@their.provider.domain.com
2. User is added to database, for example as Nick!~user1@*.domain.com
3. User later connects using a different name, for example Nick!~user2@their.provider.domain.com
4. User no longer matches the stored netmask, so they show up as unregistered
5. Attempting to register again as Nick!~user2@their.provider.domain.com crashes kVIrc

### System information

```
KVIrc 4.2.0 'Equilibrium'

Runtime Info:
System Name: Linux 4.4.1-1-default
System Version: #1 SMP PREEMPT Mon Feb 15 11:03:27 UTC 2016 (6398c2d)
Architecture: x86_64

Build Info:
Build Date: 2015-10-25 14:37:29 UTC
Sources Date: 20120701
Revision Number: 6190
System Name: Linux-4.1.10-1-default
CPU Name: x86_64
Build Command: /usr/bin/cmake
Build Flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   LIB_SUFFIX=64
   Threads=POSIX
Compiler Name: /usr/bin/c++
Compiler Flags: -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g 
```
Using KDE on OpenSuse

### Backtrace:
```
Application: KVIrc (kvirc), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fc5276487c0 (LWP 2828))]

Thread 2 (Thread 0x7fc50fdf1700 (LWP 2917)):
#0  0x00007fc51dfb8249 in  () at /usr/lib64/libglib-2.0.so.0
#1  0x00007fc51dfba44b in g_main_context_prepare () at /usr/lib64/libglib-2.0.so.0
#2  0x00007fc51dfbad80 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007fc51dfbaf7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007fc522ff9f9e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#5  0x00007fc522fcbd0f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#6  0x00007fc522fcc005 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#7  0x00007fc522ec949f in QThread::exec() () at /usr/lib64/libQtCore.so.4
#8  0x00007fc522fad613 in  () at /usr/lib64/libQtCore.so.4
#9  0x00007fc522ecbb7f in  () at /usr/lib64/libQtCore.so.4
#10 0x00007fc526b290a4 in start_thread () at /lib64/libpthread.so.0
#11 0x00007fc5212b102d in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7fc5276487c0 (LWP 2828)):
[KCrash Handler]
#6  0x00007fc522f14295 in QString::operator=(QString const&) () at /usr/lib64/libQtCore.so.4
#7  0x00007fc50d3b71af in  () at /usr/lib64/kvirc/4.2/modules/libkvireguser.so
#8  0x00000000005cebf6 in KviKvsTreeNodeModuleSimpleCommand::execute(KviKvsRunTimeContext*) ()
#9  0x00000000005cd343 in KviKvsTreeNodeInstructionBlock::execute(KviKvsRunTimeContext*) ()
#10 0x00000000005da3ee in KviKvsTreeNodeSpecialCommandIf::execute(KviKvsRunTimeContext*) ()
#11 0x00000000005cd343 in KviKvsTreeNodeInstructionBlock::execute(KviKvsRunTimeContext*) ()
#12 0x00000000005973fd in KviKvsScript::executeInternal(KviKvsRunTimeContext*) ()
#13 0x0000000000597530 in KviKvsScript::execute(KviWindow*, KviKvsVariantList*, KviKvsVariant*, int, KviKvsExtendedRunTimeData*) ()
#14 0x0000000000590348 in KviKvsPopupMenu::itemClicked(QAction*) ()
#15 0x0000000000637434 in  ()
#16 0x00007fc522fe10ba in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib64/libQtCore.so.4
#17 0x00007fc523ef9062 in QMenu::triggered(QAction*) () at /usr/lib64/libQtGui.so.4
#18 0x00007fc523efa3d0 in  () at /usr/lib64/libQtGui.so.4
#19 0x00007fc522fe10ba in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib64/libQtCore.so.4
#20 0x00007fc523ace5b2 in QAction::triggered(bool) () at /usr/lib64/libQtGui.so.4
#21 0x00007fc523acff63 in QAction::activate(QAction::ActionEvent) () at /usr/lib64/libQtGui.so.4
#22 0x00007fc523ef92d9 in  () at /usr/lib64/libQtGui.so.4
#23 0x00007fc523efd829 in  () at /usr/lib64/libQtGui.so.4
#24 0x00007fc523b23bba in QWidget::event(QEvent*) () at /usr/lib64/libQtGui.so.4
#25 0x00007fc523f0167b in QMenu::event(QEvent*) () at /usr/lib64/libQtGui.so.4
#26 0x00007fc523ad46fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQtGui.so.4
#27 0x00007fc523adad7a in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQtGui.so.4
#28 0x00007fc521ff1e9a in KApplication::notify(QObject*, QEvent*) () at /usr/lib64/libkdeui.so.5
#29 0x00007fc522fcd14d in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQtCore.so.4
#30 0x00007fc523ada573 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib64/libQtGui.so.4
#31 0x00007fc523b4bf7c in  () at /usr/lib64/libQtGui.so.4
#32 0x00007fc523b4a6bc in QApplication::x11ProcessEvent(_XEvent*) () at /usr/lib64/libQtGui.so.4
#33 0x00007fc523b71552 in  () at /usr/lib64/libQtGui.so.4
#34 0x00007fc51dfbac84 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#35 0x00007fc51dfbaed8 in  () at /usr/lib64/libglib-2.0.so.0
#36 0x00007fc51dfbaf7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#37 0x00007fc522ff9f7e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#38 0x00007fc523b71606 in  () at /usr/lib64/libQtGui.so.4
#39 0x00007fc522fcbd0f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#40 0x00007fc522fcc005 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#41 0x00007fc522fd1459 in QCoreApplication::exec() () at /usr/lib64/libQtCore.so.4
#42 0x00000000004aac5c in  ()
#43 0x00007fc5211edb25 in __libc_start_main () at /lib64/libc.so.6
#44 0x00000000004b8b5c in _start ()
```

**Comment by IceN9ne** [comment]
This sounds exactly like what I fixed in d4d29a8 for #2205 about 3 months ago.

KVIrc 4.2.0 is no longer maintained.  We recommend using nightlies.

https://github.com/kvirc/KVIrc/wiki/Downloading-KVIrcs-nightly-source-or-binaries
