### ISSUE TITLE
Crash on exit after failing to play a sound with Phonon

### ISSUE THREAD

**Issue by wodim** [kvirc/KVIrc#2286]
I can't play sounds with Phonon on Linux. I assume it is because I have no backend plugins installed, according to these messages.

	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: Phonon::createPath: Cannot connect  Phonon::MediaObject ( no objectName ) to  Phonon::AudioOutput ( no objectName ).
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
	WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded

If I quit KVIrc normally after trying (and failing) to play a sound with Phonon, I get this crash:

```
#0  0x00007fffc1ad97f0 in  ()
#1  0x00007ffff555517f in qt_call_post_routines() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff622ca56 in QApplication::~QApplication() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff7b943be in KviTalApplication::~KviTalApplication() (this=0x555555bf8320, __in_chrg=<optimized out>) at /home/wodim/KVIrc/src/kvilib/tal/KviTalApplication.h:53
#4  0x000055555581fade in KviApplication::~KviApplication() (this=0x555555bf8320, __in_chrg=<optimized out>) at /home/wodim/KVIrc/src/kvirc/kernel/KviApplication.cpp:505
#5  0x000055555581fb02 in KviApplication::~KviApplication() (this=0x555555bf8320, __in_chrg=<optimized out>) at /home/wodim/KVIrc/src/kvirc/kernel/KviApplication.cpp:618
#6  0x000055555587afce in main(int, char**) (argc=1, argv=0x7fffffffdf78) at /home/wodim/KVIrc/src/kvirc/kernel/KviMain.cpp:491
        a = 
            {argc = 1, argv = 0x7fffffffdf78, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, bExecuteCommandAndClose = false, szExecCommand = {static null = {<No data fields>}, d = 0x7ffff56009c0 <QArrayData::shared_null>}, szExecRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff56009c0 <QArrayData::shared_null>}}
        iRetCode = 0
        pTheApp = 0x555555bf8320
        szRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff56009c0 <QArrayData::shared_null>}
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        iRetVal = 0
```

This doesn't happen with any other sound system.

```
KVIrc 4.9.2 'Aria'

Runtime Info:
System name: Linux 4.10.0-32-generic
System version: #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017
Architecture: x86_64
Qt version: 5.7.1
Qt theme: 

Build Info:
Build date: 2017-08-29 13:57:13 UTC
Sources date: 20170829
Revision number: git-7170-ge4ef82fcf-dirty
System name: Linux-4.10.0-32-generic
CPU name: x86_64
Build command: /usr/bin/cmake
Build flags: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr/local
   LIB_SUFFIX=
   Threads=POSIX
Compiler name: /usr/lib/ccache/c++
Compiler flags: N/A
Qt version: 5.7.1
Features: IRC, Debug, IPv6, Crypt, SSL, IfAddr, IPC, OSS, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
```

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
