### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#2387]
I don't understand when it happens, but it's several times a day. Started recently, but I don't know when exactly.

```
Thread 1 "kvirc" received signal SIGSEGV, Segmentation fault.
0x00007fffef63ccb8 in g_main_context_prepare (context=context@entry=0x7fffe00016f0, priority=priority@entry=0x7fffffffd3d0) at /mnt/portagetmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3529
3529    /mnt/portagetmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c: Нет такого файла или каталога.
(gdb) bt full
#0  0x00007fffef63ccb8 in g_main_context_prepare (context=context@entry=0x7fffe00016f0, priority=priority@entry=0x7fffffffd3d0) at /mnt/portagetmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3529
        result = <optimized out>
        prepare = <optimized out>
        source_timeout = -1
        i = <optimized out>
        n_ready = 1
        current_priority = 0
        source = 0x55555c0e8380
        iter = {context = 0x7fffe00016f0, may_modify = 1, current_list = 0x7fffe00027a0, source = 0x55555c0e8380}
#1  0x00007fffef63d6eb in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /mnt/portagetmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3952
        max_priority = 1438417888
        timeout = 21845
        some_ready = <optimized out>
        nfds = <optimized out>
        allocated_nfds = 10
        fds = <optimized out>
#2  0x00007fffef63d8cc in g_main_context_iteration (context=0x7fffe00016f0, may_block=may_block@entry=1) at /mnt/portagetmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:4033
        retval = <optimized out>
#3  0x00007ffff423532f in QEventDispatcherGlib::processEvents (this=0x555555bc83e0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
        d = 0x555555bccef0
        canWait = true
        savedFlags = {i = 0}
        result = <optimized out>
#4  0x00007ffff41e57ea in QEventLoop::exec (this=this@entry=0x7fffffffd510, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
        d = 0x55555648eb10
        locker = {val = 93824998612336}
        ref = {d = 0x55555648eb10, locker = @0x7fffffffd498, exceptionCaught = true}
#5  0x00007ffff41edb1c in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1289
        threadData = 0x555555b68d80
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff462b4e8 <vtable for QEventLoop+16>, static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff433bc40 <qt_meta_stringdata_QObject>, data = 0x7ffff433bb20 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff42167d0 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x55555648eb10}, static staticQtMetaObject = {d = {superdata = 0x0, 
                stringdata = 0x7ffff433e8e0 <qt_meta_stringdata_Qt>, data = 0x7ffff433bd60 <qt_meta_data_Qt>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {superdata = 0x7ffff4623ba0 <QObject::staticMetaObject>, 
              stringdata = 0x7ffff4336840 <qt_meta_stringdata_QEventLoop>, data = 0x7ffff43367e0 <qt_meta_data_QEventLoop>, static_metacall = 0x7ffff41e5540 <QEventLoop::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, 
              extradata = 0x0}}}
        returnCode = <optimized out>
#6  0x0000555555656ac2 in main (argc=<optimized out>, argv=0x7fffffffd7a8) at /mnt/portagetmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/KviMain.cpp:488
        a = {argc = 1, argv = 0x7fffffffd7a8, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, bExecuteCommandAndClose = false, szExecCommand = {static null = {<No data fields>}, d = 0x7ffff427e380 <QArrayData::shared_null>}, 
          szExecRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff427e380 <QArrayData::shared_null>}}
        iRetCode = 0
        pAboutData = <optimized out>
        pTheApp = 0x555555b69ac0
        szRemoteCommand = {static null = {<No data fields>}, d = 0x7ffff427e380 <QArrayData::shared_null>}
        iRetVal = <optimized out>
```

```
Информация времени выполнения:
Система: Linux 4.14.8-gentoo-r1
Версия системы: #3 SMP Fri Dec 29 08:46:57 GMT 2017
Архитектура: x86_64
Версия Qt: 5.9.4
Qt theme: breeze

Информация о сборке:
Дата сборки: 2018-05-26 09:08:27 UTC
Дата исходных текстов программы: 20160102
Номер ревизии: 5c80922489a68a6ab0786de1cc972291deabe1e0
Система: Linux-4.14.8-gentoo-r1
Процессор: x86_64
Команда сборки: /usr/bin/cmake
Флаги сборки: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=/usr
   VERBOSE
   LIB_SUFFIX=64
   Threads=POSIX
Компилятор: /usr/bin/x86_64-pc-linux-gnu-g++
Флаги компилятора: -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing
Версия Qt: 5.9.4
Features: IRC, IPv6, Crypt, SSL, IfAddr, IPC, KDE, Transparency, Phonon, DCCVoice, Perl, Python, Enchant, Qt5, KVS
OpenSSL version: OpenSSL 1.0.2o 27 Mar 2018
OpenSSL compiler flags: compiler: x86_64-pc-linux-gnu-gcc -I. -I.. -I../include -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -O2 -pipe -march=bdver2 -ggdb3 -fno-strict-aliasing -Wa,--noexecstack
OpenSSL built on: built on: reproducible build, date unspecified
```

**Comment by DarthGandalf** [comment]
Doesn't seem to happen now ><

**Comment by DarthGandalf** [comment]
`kvirc[2801]: segfault at 7faa6c72dd00 ip 00007faaa0790e4c sp 00007ffedfcd08d0 error 4 in libglib-2.0.so.0.5200.3[7faaa0748000+10d000]` :(

It didn't happen for a while though.

**Comment by ctrlaltca** [comment]
We are about to release a new version, please try https://github.com/kvirc/KVIrc/releases/tag/5.2.0-beta1-fix and report if this issue is still present. Thank you
