### ISSUE TITLE
KVIrc 4 crash at server settings -> advanced

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#261]
**Reported by Fiber on 17 Oct 2008 09:31:15 UTC**
Okay, new install, setup done, kvirc up & running, serverlist have focus.
Clear list, add a network, server, when i click to advanced it crashes:

running from gdb:

```
fiber@lucifer:~$ gdb kvirc4
GNU gdb 6.8
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-slackware-linux"...
(gdb) run
Starting program: /usr/local/bin/kvirc4
[Thread debugging using libthread_db enabled]
[New Thread 0xb65bd6d0 (LWP 20104)]
Object::connect: No such signal KviTalTreeWidget::selectionChanged()

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb65bd6d0 (LWP 20104)]
0x0812c3e0 in QListData::size (this=0xc)
    at /usr/lib/qt4/include/QtCore/qlist.h:89
89          inline int size() const { return d->end - d->begin; }


(gdb) backtrace
#0  0x0812c3e0 in QListData::size (this=0xc)
    at /usr/lib/qt4/include/QtCore/qlist.h:89
#1  0xb333977d in QList<QString>::at (this=0xc, i=1)
    at /usr/lib/qt4/include/QtCore/qlist.h:393
#2  0xb3335306 in KviScriptEditorWidget::asyncCompleterCreation (
    this=0x9ec82e8)
    at /home/fiber/compile/kvirc/src/modules/editor/scripteditor.cpp:138
#3  0xb333a0c2 in KviScriptEditorWidget::qt_metacall (this=0x9ec82e8,
    _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0xbfff3588)
    at /home/fiber/compile/kvirc/release/src/modules/editor/moc_scripteditor.cxx                                                                           :84
#4  0xb6c2871d in QMetaObject::activate () from /usr/lib/qt4/lib/libQtCore.so.4
#5  0xb6c28b25 in QMetaObject::activate () from /usr/lib/qt4/lib/libQtCore.so.4
#6  0xb6c60f17 in QTimer::timeout () from /usr/lib/qt4/lib/libQtCore.so.4
#7  0xb6c30ccf in QTimer::timerEvent () from /usr/lib/qt4/lib/libQtCore.so.4
#8  0xb6c25568 in QObject::event () from /usr/lib/qt4/lib/libQtCore.so.4
#9  0xb7080a5a in QApplicationPrivate::notify_helper ()
   from /usr/lib/qt4/lib/libQtGui.so.4
#10 0xb7087b82 in QApplication::notify () from /usr/lib/qt4/lib/libQtGui.so.4
#11 0xb6c17383 in QCoreApplication::notifyInternal ()
   from /usr/lib/qt4/lib/libQtCore.so.4
#12 0xb6c4082b in ?? () from /usr/lib/qt4/lib/libQtCore.so.4
#13 0x083e3c10 in ?? ()
---Type <return> to continue, or q <return> to quit---
#14 0x09ec70d8 in ?? ()
#15 0xbfff3978 in ?? ()
#16 0x09ebb768 in ?? ()
#17 0xb6af210c in ?? () from /usr/lib/libgthread-2.0.so.0
#18 0x09ec70d8 in ?? ()
#19 0x00000002 in ?? ()
#20 0x00000000 in ?? ()
(gdb)
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/261

**Comment by DarthGandalf** [comment]
**Modified by Voker57 on 17 Oct 2008 09:36:26**
Description:

``` diff
--- 
+++ 
@@ -3,7 +3,7 @@


 running from gdb:
-
+{{{
 fiber@lucifer:~$ gdb kvirc4
 GNU gdb 6.8
 Copyright (C) 2008 Free Software Foundation, Inc.
@@ -57,4 +57,4 @@
 #19 0x00000002 in ?? ()
 #20 0x00000000 in ?? ()
 (gdb)
-
+}}}

```

**Comment by DarthGandalf** [comment]
**Comment by Fiber on 17 Oct 2008 09:58:23**
SVN 2748

```
(gdb) run
Starting program: /usr/local/bin/kvirc4
[Thread debugging using libthread_db enabled]
[New Thread 0xb655a6d0 (LWP 29512)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb655a6d0 (LWP 29512)]
0x0812c3b0 in QListData::size (this=0xc) at /usr/lib/qt4/include/QtCore/qlist.h:89
89          inline int size() const { return d->end - d->begin; }
(gdb) backtrace
#0  0x0812c3b0 in QListData::size (this=0xc) at /usr/lib/qt4/include/QtCore/qlist.h:89
#1  0xb31e175d in QList<QString>::at (this=0xc, i=1) at /usr/lib/qt4/include/QtCore/qlist.h:393
#2  0xb31dd2e6 in KviScriptEditorWidget::asyncCompleterCreation (this=0x872bfb8) at /home/fiber/compile/kvirc/src/modules/editor/scripteditor.cpp:138
#3  0xb31e20a2 in KviScriptEditorWidget::qt_metacall (this=0x872bfb8, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0xbfc311c8)
    at /home/fiber/compile/kvirc/release/src/modules/editor/moc_scripteditor.cxx:84
#4  0xb6bc571d in QMetaObject::activate () from /usr/lib/qt4/lib/libQtCore.so.4
#5  0xb6bc5b25 in QMetaObject::activate () from /usr/lib/qt4/lib/libQtCore.so.4
#6  0xb6bfdf17 in QTimer::timeout () from /usr/lib/qt4/lib/libQtCore.so.4
#7  0xb6bcdccf in QTimer::timerEvent () from /usr/lib/qt4/lib/libQtCore.so.4
#8  0xb6bc2568 in QObject::event () from /usr/lib/qt4/lib/libQtCore.so.4
#9  0xb701da5a in QApplicationPrivate::notify_helper () from /usr/lib/qt4/lib/libQtGui.so.4
#10 0xb7024b82 in QApplication::notify () from /usr/lib/qt4/lib/libQtGui.so.4
#11 0xb6bb4383 in QCoreApplication::notifyInternal () from /usr/lib/qt4/lib/libQtCore.so.4
#12 0xb6bdd82b in ?? () from /usr/lib/qt4/lib/libQtCore.so.4
#13 0x083e3c10 in ?? ()
#14 0x08709428 in ?? ()
#15 0xbfc315b8 in ?? ()
#16 0x08766578 in ?? ()
#17 0xb664210c in ?? () from /usr/lib/libgthread-2.0.so.0
#18 0x08709428 in ?? ()
#19 0x00000002 in ?? ()
#20 0x00000000 in ?? ()
```

**Comment by DarthGandalf** [comment]
**Modified by Noldor73 on 17 Oct 2008 11:03:58**
Resolution: none → fixed
Status: new → closed
