### ISSUE TITLE
Crash while try to connect to server

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#30]
**Reported by radoen on 16 Sep 2007 16:05:34 UTC**
the application crash SO Kubuntu feisty kernel 2.6.22-radoen  Kvirc version 3.2.4 . Next the report 
---------------------------START REPORT-------------------------------------------------
(no debugging symbols found)
Using host libthread_db library "/lib/tls/i686/cmov/libthread_db.so.1".
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[Thread debugging using libthread_db enabled]
[New Thread -1240794912 (LWP 7837)](no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
0xffffe410 in ?? ()
#0  0xffffe410 in ?? ()
#1  0xbf814148 in ?? ()
#2  0xb621dff4 in ?? () from /lib/tls/i686/cmov/libc.so.6
#3  0xbf814134 in ?? ()
#4  0xb6170e66 in nanosleep () from /lib/tls/i686/cmov/libc.so.6
#5  0xb6170c8f in sleep () from /lib/tls/i686/cmov/libc.so.6
#6  0xb76e6549 in KCrash::startDrKonqi () from /usr/lib/libkdecore.so.4
#7  0xb76fc98e in KCrash::defaultCrashHandler () from /usr/lib/libkdecore.so.4
#8  0xffffe420 in ?? ()
#9  0x0000000b in ?? ()
#10 0x00000033 in ?? ()
#11 0xc0100000 in ?? ()
#12 0x0000007b in ?? ()
#13 0xbf81007b in ?? ()
#14 0x00000048 in ?? ()
#15 0x086ffdb8 in ?? ()
#16 0xbf816710 in ?? ()
#17 0xbf8166c8 in ?? ()
#18 0xb621dff4 in ?? () from /lib/tls/i686/cmov/libc.so.6
#19 0x00000049 in ?? ()
#20 0xb621f120 in ?? () from /lib/tls/i686/cmov/libc.so.6
#21 0x00200008 in ?? ()
#22 0x0000000e in ?? ()
#23 0x00000004 in ?? ()
#24 0xb6149e8c in ?? () from /lib/tls/i686/cmov/libc.so.6
#25 0x00000073 in ?? ()
#26 0x00010287 in ?? ()
#27 0xbf8166c8 in ?? ()
#28 0x0000007b in ?? ()
#29 0xbf81644c in ?? ()
#30 0x00000000 in ?? ()

---------------------------------END REPORT---------------------------------------------

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/30

**Comment by DarthGandalf** [comment]
**Comment by mren on 01 Mar 2008 14:43:58**
Please test w/ latest sources. If it happens again reopen this bug w/ some more info please (which revision of kvirc, on which action/event it crashes...)

---

Component: none → Core
Priority: Major → Crash
Resolution: none → fixed
Status: new → closed
