### ISSUE TITLE
Disconnect a server ends in a deadlock

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#302]
**Reported by anonymous on 20 Nov 2008 09:34:55 UTC**
The message kvirc prings in the console is:

QMdiArea::removeSubWindow: window is not inside workspace

Backtrace:

```
Program received signal SIGINT, Interrupt.
0x00007ffff58cda19 in QApplication::compressEvent(QEvent*, QObject*, QPostEventList*) () from /usr/lib64/libQtGui.so.4
(gdb) bt
#0  0x00007ffff58cda19 in QApplication::compressEvent(QEvent*, QObject*, QPostEventList*) () from /usr/lib64/libQtGui.so.4
#1  0x00007ffff2937dc7 in QCoreApplication::postEvent(QObject*, QEvent*, int) () from /usr/lib64/libQtCore.so.4
#2  0x00007ffff594dfea in QWidgetPrivate::dirtyWidget_sys(QRegion const&, bool) () from /usr/lib64/libQtGui.so.4
#3  0x00007ffff5a74aaa in ?? () from /usr/lib64/libQtGui.so.4
#4  0x00007ffff5a74cee in ?? () from /usr/lib64/libQtGui.so.4
#5  0x00007ffff5c54653 in ?? () from /usr/lib64/libQtGui.so.4
#6  0x00007ffff5c56077 in QMdiSubWindow::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/libQtGui.so.4
#7  0x000000000065baa5 in KviMdiChild::qt_metacall (this=0x1243, _c=77, _id=11253184, _a=0x7fffe4d6e010)
    at /usr/src/debug/kvirc-3.9.89svn2899/build/src/kvirc/ui/moc_kvi_mdichild.cxx:78
#8  0x00007ffff294c444 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQtCore.so.4
#9  0x00007ffff58cce0b in QApplication::focusChanged(QWidget*, QWidget*) () from /usr/lib64/libQtGui.so.4
#10 0x00007ffff58d3809 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
#11 0x00007ffff5920983 in QWidget::setFocus(Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
#12 0x000000000050c21d in KviMdiManager::focusTopChild (this=0xaf4280) at /usr/include/QtGui/qwidget.h:403
#13 0x000000000050c380 in KviMdiManager::destroyChild (this=0xaf4280, lpC=0x1581310, bFocusTopChild=true)
    at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/ui/kvi_mdimanager.cpp:180
#14 0x00000000004e4114 in KviFrame::closeWindow (this=0xabb5c0, wnd=0x1560f20) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/ui/kvi_frame.cpp:621
#15 0x00000000004c7b35 in KviChannel::closeEvent (this=0x1560f20, e=0x7fffffffc9a0) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/ui/kvi_channel.cpp:1535
#16 0x00007ffff591f1d7 in QWidget::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#17 0x00007ffff58cd1bd in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#18 0x00007ffff58d4f8a in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#19 0x00007ffff12c6b6b in KApplication::notify(QObject*, QEvent*) () from /usr/lib64/libkdeui.so.5
#20 0x00007ffff2938081 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/libQtCore.so.4
#21 0x00007ffff592205b in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib64/libQtGui.so.4
#22 0x0000000000624265 in KviIrcConnection::closeAllChannels (this=0xd25ec0) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_ircconnection.cpp:437
#23 0x000000000062ec42 in KviIrcContext::destroyConnection (this=0xce0940) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_irccontext.cpp:326
#24 0x000000000062ed18 in KviIrcContext::setState (this=0xce0940, eState=KviIrcContext::Idle)
    at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_irccontext.cpp:350
#25 0x00000000006301a8 in KviIrcContext::connectionTerminated (this=0xce0940) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_irccontext.cpp:775
#26 0x0000000000631ea9 in KviIrcLink::socketStateChange (this=0x13f3b40) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_irclink.cpp:361
#27 0x0000000000633abe in KviIrcSocket::readData (this=0x1405380) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_ircsocket.cpp:1460
#28 0x000000000066150e in KviIrcSocket::qt_metacall (this=0x1405380, _c=QMetaObject::InvokeMetaMethod, _id=<value optimized out>, _a=0x7fffffffd290)
    at /usr/src/debug/kvirc-3.9.89svn2899/build/src/kvirc/kernel/moc_kvi_ircsocket.cxx:76
#29 0x00007ffff294c444 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQtCore.so.4
#30 0x00007ffff298307e in QSocketNotifier::activated(int) () from /usr/lib64/libQtCore.so.4
#31 0x00007ffff2951f93 in QSocketNotifier::event(QEvent*) () from /usr/lib64/libQtCore.so.4
#32 0x00007ffff58cd1bd in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#33 0x00007ffff58d4f8a in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
#34 0x00007ffff12c6b6b in KApplication::notify(QObject*, QEvent*) () from /usr/lib64/libkdeui.so.5
#35 0x00007ffff2938081 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/libQtCore.so.4
#36 0x00007ffff2960759 in ?? () from /usr/lib64/libQtCore.so.4
#37 0x00007ffff23610db in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#38 0x00007ffff23648ad in ?? () from /usr/lib64/libglib-2.0.so.0
#39 0x00007ffff2364a6b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#40 0x00007ffff29604df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#41 0x00007ffff595d96f in ?? () from /usr/lib64/libQtGui.so.4
#42 0x00007ffff2936992 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#43 0x00007ffff2936b1d in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#44 0x00007ffff2938fed in QCoreApplication::exec() () from /usr/lib64/libQtCore.so.4
#45 0x000000000063a3de in main (argc=1, argv=0x7fffffffdd88) at /usr/src/debug/kvirc-3.9.89svn2899/src/kvirc/kernel/kvi_main.cpp:395
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/302

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 20 Nov 2008 13:12:43**
fixed in r2901 , thank you for posting your backtrace :)

---

Resolution: none → fixed
Status: new → closed
