### ISSUE TITLE
kvirc crashes on exit with the following backtrace

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#305]
**Reported by anonymous on 21 Nov 2008 16:41:45 UTC**
svn revision: 2905

```
Application: KVIrc (), signal SIGSEGV
[Thread debugging using libthread_db enabled]
[New Thread 0x7f66da1af950 (LWP 8934)]
[KCrash handler]
#5  0x00007f66e87090a1 in ?? () from /usr/lib64/libQtGui.so.4
#6  0x00007f66e87093ff in QMdiArea::subWindowList(QMdiArea::WindowOrder) const
    () from /usr/lib64/libQtGui.so.4
#7  0x000000000050bec1 in KviMdiManager::setTopChild (this=0xb58670, 
    lpC=0x1be91b0, bSetFocus=false)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_mdimanager.cpp:148
#8  0x000000000053b9d8 in KviWindow::activateSelf (this=0x1bca400)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_window.cpp:948
#9  0x000000000053ba5f in KviWindow::eventFilter (this=0x1bca400, 
    o=0x63002d00200070, e=0x1)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_window.cpp:1019
#10 0x00007f66e53ff348 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib64/libQtCore.so.4
#11 0x00007f66e839518c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib64/libQtGui.so.4
#12 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#13 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libkdeui.so.5
#14 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib64/libQtCore.so.4
#15 0x00007f66e839b8c4 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
#16 0x00007f66e83e8993 in QWidget::setFocus(Qt::FocusReason) ()
   from /usr/lib64/libQtGui.so.4
#17 0x000000000053bbb4 in KviWindow::focusInEvent (this=0x1bca400)
    at /usr/include/QtGui/qwidget.h:403
#18 0x00007f66e83e7491 in QWidget::event(QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#19 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib64/libQtGui.so.4
#20 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#21 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libkdeui.so.5
#22 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib64/libQtCore.so.4
#23 0x00007f66e839b8c4 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
#24 0x00007f66e83e8993 in QWidget::setFocus(Qt::FocusReason) ()
   from /usr/lib64/libQtGui.so.4
#25 0x00007f66e839be8c in QApplication::setActiveWindow(QWidget*) ()
   from /usr/lib64/libQtGui.so.4
#26 0x00007f66e83ffef5 in QApplication::x11ProcessEvent(_XEvent*) ()
   from /usr/lib64/libQtGui.so.4
#27 0x00007f66e84261d4 in ?? () from /usr/lib64/libQtGui.so.4
#28 0x00007f66e4e290db in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
#29 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
#30 0x00007f66e4e2ca6b in g_main_context_iteration ()
   from /usr/lib64/libglib-2.0.so.0
#31 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#32 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
#33 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#34 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0x1872a80)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
#35 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xbbd400)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
#36 0x000000000062ec58 in KviIrcContext::setState (this=0xbbd400, 
    eState=KviIrcContext::Idle)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
#37 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xbbd400)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
#38 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xc3b8f0)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
#39 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
    this=0xbbd400, bForce=true, szQuitMsg=@0x7ffff2ac2380, 
    bSimulateUnexpectedDisconnect=<value optimized out>)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
#40 0x00000000004d32d0 in ~KviConsole (this=0xbbcf50)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
#41 0x00007f66e540f115 in QObject::event(QEvent*) ()
   from /usr/lib64/libQtCore.so.4
#42 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#43 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib64/libQtGui.so.4
#44 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#45 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libkdeui.so.5
#46 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib64/libQtCore.so.4
#47 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
#48 0x00007f66e5428853 in ?? () from /usr/lib64/libQtCore.so.4
#49 0x00007f66e4e290db in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
#50 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
#51 0x00007f66e4e2ca6b in g_main_context_iteration ()
   from /usr/lib64/libglib-2.0.so.0
#52 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#53 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
#54 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#55 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0xbc7590)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
#56 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xc06f40)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
#57 0x000000000062ec58 in KviIrcContext::setState (this=0xc06f40, 
    eState=KviIrcContext::Idle)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
#58 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xc06f40)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
#59 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xba9700)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
#60 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
    this=0xc06f40, bForce=true, szQuitMsg=@0x7ffff2ac31e0, 
    bSimulateUnexpectedDisconnect=<value optimized out>)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
#61 0x00000000004d32d0 in ~KviConsole (this=0xc4c290)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
#62 0x00007f66e540f115 in QObject::event(QEvent*) ()
   from /usr/lib64/libQtCore.so.4
#63 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#64 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib64/libQtGui.so.4
#65 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#66 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libkdeui.so.5
#67 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib64/libQtCore.so.4
#68 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
#69 0x00007f66e5428853 in ?? () from /usr/lib64/libQtCore.so.4
#70 0x00007f66e4e290db in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
#71 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
#72 0x00007f66e4e2ca6b in g_main_context_iteration ()
   from /usr/lib64/libglib-2.0.so.0
#73 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#74 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
#75 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
#76 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0xb9c2f0)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
#77 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xc8d650)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
#78 0x000000000062ec58 in KviIrcContext::setState (this=0xc8d650, 
    eState=KviIrcContext::Idle)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
#79 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xc8d650)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
#80 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xc6d1b0)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
#81 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
    this=0xc8d650, bForce=true, szQuitMsg=@0x7ffff2ac4040, 
    bSimulateUnexpectedDisconnect=<value optimized out>)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
#82 0x00000000004d32d0 in ~KviConsole (this=0xc8d530)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
#83 0x00007f66e540f115 in QObject::event(QEvent*) ()
   from /usr/lib64/libQtCore.so.4
#84 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#85 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib64/libQtGui.so.4
#86 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libQtGui.so.4
#87 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
   from /usr/lib64/libkdeui.so.5
#88 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib64/libQtCore.so.4
#89 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
#90 0x00007f66e5401019 in QCoreApplication::exec() ()
   from /usr/lib64/libQtCore.so.4
#91 0x000000000063a31e in main (argc=2, argv=0x7ffff2ac4bc8)
    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_main.cpp:395
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/305

**Comment by DarthGandalf** [comment]
**Modified by thexception on 22 Nov 2008 17:09:06**
Owner: pragmaware → thexception
Description:

``` diff
--- 
+++ 
@@ -1,176 +1,4 @@
 svn revision: 2905
-
-}}}
-Application: KVIrc (), signal SIGSEGV
-[Thread debugging using libthread_db enabled]
-[New Thread 0x7f66da1af950 (LWP 8934)]
-[KCrash handler]
-#5  0x00007f66e87090a1 in ?? () from /usr/lib64/libQtGui.so.4
-#6  0x00007f66e87093ff in QMdiArea::subWindowList(QMdiArea::WindowOrder) const
-    () from /usr/lib64/libQtGui.so.4
-#7  0x000000000050bec1 in KviMdiManager::setTopChild (this=0xb58670, 
-    lpC=0x1be91b0, bSetFocus=false)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_mdimanager.cpp:148
-#8  0x000000000053b9d8 in KviWindow::activateSelf (this=0x1bca400)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_window.cpp:948
-#9  0x000000000053ba5f in KviWindow::eventFilter (this=0x1bca400, 
-    o=0x63002d00200070, e=0x1)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_window.cpp:1019
-#10 0x00007f66e53ff348 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib64/libQtCore.so.4
-#11 0x00007f66e839518c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
-    () from /usr/lib64/libQtGui.so.4
-#12 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#13 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libkdeui.so.5
-#14 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
-    () from /usr/lib64/libQtCore.so.4
-#15 0x00007f66e839b8c4 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
-#16 0x00007f66e83e8993 in QWidget::setFocus(Qt::FocusReason) ()
-   from /usr/lib64/libQtGui.so.4
-#17 0x000000000053bbb4 in KviWindow::focusInEvent (this=0x1bca400)
-    at /usr/include/QtGui/qwidget.h:403
-#18 0x00007f66e83e7491 in QWidget::event(QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#19 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
-    () from /usr/lib64/libQtGui.so.4
-#20 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#21 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libkdeui.so.5
-#22 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
-    () from /usr/lib64/libQtCore.so.4
-#23 0x00007f66e839b8c4 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib64/libQtGui.so.4
-#24 0x00007f66e83e8993 in QWidget::setFocus(Qt::FocusReason) ()
-   from /usr/lib64/libQtGui.so.4
-#25 0x00007f66e839be8c in QApplication::setActiveWindow(QWidget*) ()
-   from /usr/lib64/libQtGui.so.4
-#26 0x00007f66e83ffef5 in QApplication::x11ProcessEvent(_XEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#27 0x00007f66e84261d4 in ?? () from /usr/lib64/libQtGui.so.4
-#28 0x00007f66e4e290db in g_main_context_dispatch ()
-   from /usr/lib64/libglib-2.0.so.0
-#29 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
-#30 0x00007f66e4e2ca6b in g_main_context_iteration ()
-   from /usr/lib64/libglib-2.0.so.0
-#31 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#32 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
-#33 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#34 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0x1872a80)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
-#35 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xbbd400)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
-#36 0x000000000062ec58 in KviIrcContext::setState (this=0xbbd400, 
-    eState=KviIrcContext::Idle)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
-#37 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xbbd400)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
-#38 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xc3b8f0)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
-#39 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
-    this=0xbbd400, bForce=true, szQuitMsg=@0x7ffff2ac2380, 
-    bSimulateUnexpectedDisconnect=<value optimized out>)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
-#40 0x00000000004d32d0 in ~KviConsole (this=0xbbcf50)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
-#41 0x00007f66e540f115 in QObject::event(QEvent*) ()
-   from /usr/lib64/libQtCore.so.4
-#42 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#43 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
-    () from /usr/lib64/libQtGui.so.4
-#44 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#45 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libkdeui.so.5
-#46 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
-    () from /usr/lib64/libQtCore.so.4
-#47 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
-#48 0x00007f66e5428853 in ?? () from /usr/lib64/libQtCore.so.4
-#49 0x00007f66e4e290db in g_main_context_dispatch ()
-   from /usr/lib64/libglib-2.0.so.0
-#50 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
-#51 0x00007f66e4e2ca6b in g_main_context_iteration ()
-   from /usr/lib64/libglib-2.0.so.0
-#52 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#53 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
-#54 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#55 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0xbc7590)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
-#56 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xc06f40)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
-#57 0x000000000062ec58 in KviIrcContext::setState (this=0xc06f40, 
-    eState=KviIrcContext::Idle)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
-#58 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xc06f40)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
-#59 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xba9700)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
-#60 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
-    this=0xc06f40, bForce=true, szQuitMsg=@0x7ffff2ac31e0, 
-    bSimulateUnexpectedDisconnect=<value optimized out>)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
-#61 0x00000000004d32d0 in ~KviConsole (this=0xc4c290)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
-#62 0x00007f66e540f115 in QObject::event(QEvent*) ()
-   from /usr/lib64/libQtCore.so.4
-#63 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#64 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
-    () from /usr/lib64/libQtGui.so.4
-#65 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#66 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libkdeui.so.5
-#67 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
-    () from /usr/lib64/libQtCore.so.4
-#68 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
-#69 0x00007f66e5428853 in ?? () from /usr/lib64/libQtCore.so.4
-#70 0x00007f66e4e290db in g_main_context_dispatch ()
-   from /usr/lib64/libglib-2.0.so.0
-#71 0x00007f66e4e2c8ad in ?? () from /usr/lib64/libglib-2.0.so.0
-#72 0x00007f66e4e2ca6b in g_main_context_iteration ()
-   from /usr/lib64/libglib-2.0.so.0
-#73 0x00007f66e54284df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#74 0x00007f66e842597f in ?? () from /usr/lib64/libQtGui.so.4
-#75 0x00007f66e5401159 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQtCore.so.4
-#76 0x00000000006241a4 in KviIrcConnection::closeAllChannels (this=0xb9c2f0)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_ircconnection.cpp:439
-#77 0x000000000062eb82 in KviIrcContext::destroyConnection (this=0xc8d650)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:326
-#78 0x000000000062ec58 in KviIrcContext::setState (this=0xc8d650, 
-    eState=KviIrcContext::Idle)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:350
-#79 0x00000000006300e8 in KviIrcContext::connectionTerminated (this=0xc8d650)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:775
-#80 0x0000000000631de9 in KviIrcLink::socketStateChange (this=0xc6d1b0)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irclink.cpp:361
-#81 0x000000000062fef5 in KviIrcContext::terminateConnectionRequest (
-    this=0xc8d650, bForce=true, szQuitMsg=@0x7ffff2ac4040, 
-    bSimulateUnexpectedDisconnect=<value optimized out>)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_irccontext.cpp:887
-#82 0x00000000004d32d0 in ~KviConsole (this=0xc8d530)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/ui/kvi_console.cpp:187
-#83 0x00007f66e540f115 in QObject::event(QEvent*) ()
-   from /usr/lib64/libQtCore.so.4
-#84 0x00007f66e83e6e36 in QWidget::event(QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#85 0x00007f66e83951bd in QApplicationPrivate::notify_helper(QObject*, QEvent*)
-    () from /usr/lib64/libQtGui.so.4
-#86 0x00007f66e839cf8a in QApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libQtGui.so.4
-#87 0x00007f66e3d8eb6b in KApplication::notify(QObject*, QEvent*) ()
-   from /usr/lib64/libkdeui.so.5
-#88 0x00007f66e5400081 in QCoreApplication::notifyInternal(QObject*, QEvent*)
-    () from /usr/lib64/libQtCore.so.4
-#89 0x00007f66e5400d2a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQtCore.so.4
-#90 0x00007f66e5401019 in QCoreApplication::exec() ()
-   from /usr/lib64/libQtCore.so.4
-#91 0x000000000063a31e in main (argc=2, argv=0x7ffff2ac4bc8)
-    at /usr/src/debug/kvirc-3.9.89svn2905/src/kvirc/kernel/kvi_main.cpp:395
-}}}
-
-or

 {{{
 Application: KVIrc (), signal SIGSEGV

```

**Comment by DarthGandalf** [comment]
**Modified by thexception on 22 Nov 2008 17:16:16**
Status: new → assigned

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 07 Jan 2009 01:34:44**
Priority: Normal → Crash

**Comment by DarthGandalf** [comment]
**Modified by thexception on 08 Jan 2009 23:52:45**
Resolution: none → fixed
Status: assigned → closed

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 18 Jan 2009 15:19:31**
the patch for this issue has been reworked in r3006, since the original patch (r2984) caused some side effect
