### ISSUE TITLE
Crash at exit

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#306]
**Reported by wrar on 22 Nov 2008 17:37:29 UTC**
I start kvirc, it connects to one network and joins a channel, then I close it. It crashes. r2905

```
KviFrame::consoleCount (this=0x0) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_frame.cpp:782
782             for(KviWindow * wnd = m_pWinList->first();wnd;wnd = m_pWinList->next())
(gdb) bt
#0  KviFrame::consoleCount (this=0x0) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_frame.cpp:782
#1  0x0812aa15 in ~KviConsole (this=0x9da4330) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_console.cpp:191
#2  0x42d85e7d in qDeleteInEventHandler () from /usr/lib/libQtCore.so.4
#3  0x42d88e19 in QObject::event () from /usr/lib/libQtCore.so.4
#4  0x433ba6a1 in QWidget::event () from /usr/lib/libQtGui.so.4
#5  0x43382aac in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#6  0x43383a07 in QApplication::notify () from /usr/lib/libQtGui.so.4
#7  0x430c4d4a in KApplication::notify () from /usr/lib/libkdeui.so.5
#8  0x42d7caf0 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#9  0x42d7ce89 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
#10 0x42d7cff6 in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
#11 0x42d7d0e0 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#12 0x43382952 in QApplication::exec () from /usr/lib/libQtGui.so.4
#13 0x08246c27 in main (argc=163386048, argv=0xbfb0c444) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/kernel/kvi_main.cpp:395
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/306

**Comment by DarthGandalf** [comment]
**Modified by thexception on 22 Nov 2008 17:39:35**
Owner: pragmaware → thexception

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 22 Nov 2008 17:44:49**

``````
(gdb) fr 1
#1  0x0812aa15 in ~KviConsole (this=0x9da4330) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_console.cpp:191
191             if(g_pFrame->consoleCount() <= 1)
(gdb) p g_pFrame
$1 = (class KviFrame *) 0x0
```}
``````

**Comment by DarthGandalf** [comment]
**Modified by thexception on 22 Nov 2008 19:45:21**
Status: new → assigned

**Comment by DarthGandalf** [comment]
**Modified by thexception on 22 Nov 2008 20:26:35**
Resolution: none → fixed
Status: assigned → closed
