### ISSUE TITLE
resizing console hang causes 100% cpu hang

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#308]
**Reported by blub on 28 Nov 2008 23:27:30 UTC**
when resizing a console window from the bottom up the bottom rendering is faulty when the height gets small. when i slowly resized the window to understand the behaviour, kvirc hung unusable, didn't crash though.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/308

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 28 Nov 2008 23:35:57**
reproducable here,

backtrace during hang

```
!#0  0x00007f2f67bf5499 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#1  0x00007f2f67bf58b6 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#2  0x00007f2f67bf5a7e in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#3  0x00007f2f67bf4af7 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#4  0x00007f2f67bf5162 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#5  0x00007f2f67bc7f28 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#6  0x00007f2f67bcf6bf in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#7  0x00007f2f67bd5073 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#8  0x00007f2f67b5f466 in ?? () from /usr/lib64/qt4/libQtGui.so.4                                                  
!#9  0x00007f2f67b65c02 in QPainter::drawRoundedRect () from /usr/lib64/qt4/libQtGui.so.4                           
!#10 0x00007f2f5f09a8f8 in ?? () from /usr/lib64/kde4/plugins/styles/oxygen.so                                      
!#11 0x00007f2f5f09dab7 in ?? () from /usr/lib64/kde4/plugins/styles/oxygen.so                                      
!#12 0x00007f2f6434026e in KStyle::drawControl () from /usr/lib64/libkdeui.so.5                                     
!#13 0x00007f2f5f096291 in ?? () from /usr/lib64/kde4/plugins/styles/oxygen.so                                      
!#14 0x00007f2f67cdd4b4 in QCommonStyle::drawComplexControl () from /usr/lib64/qt4/libQtGui.so.4
!#15 0x00007f2f6433e046 in KStyle::drawComplexControl () from /usr/lib64/libkdeui.so.5
!#16 0x00007f2f5f092eca in ?? () from /usr/lib64/kde4/plugins/styles/oxygen.so
!#17 0x00007f2f67e1290a in QScrollBar::paintEvent () from /usr/lib64/qt4/libQtGui.so.4
!#18 0x00007f2f67ac24db in QWidget::event () from /usr/lib64/qt4/libQtGui.so.4
!#19 0x00007f2f67d7b209 in QAbstractSlider::event () from /usr/lib64/qt4/libQtGui.so.4
!#20 0x00007f2f67e11ffd in QScrollBar::event () from /usr/lib64/qt4/libQtGui.so.4
!#21 0x00007f2f67a762be in QApplicationPrivate::notify_helper () from /usr/lib64/qt4/libQtGui.so.4
!#22 0x00007f2f67a7adde in QApplication::notify () from /usr/lib64/qt4/libQtGui.so.4
!#23 0x00007f2f6432afeb in KApplication::notify () from /usr/lib64/libkdeui.so.5
!#24 0x00007f2f651072c8 in QCoreApplication::notifyInternal () from /usr/lib64/qt4/libQtCore.so.4
!#25 0x00007f2f67acb8ac in ?? () from /usr/lib64/qt4/libQtGui.so.4
!#26 0x00007f2f67ac1413 in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#27 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#28 0x00007f2f67ac19b2 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#29 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#30 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#31 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#32 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#33 0x00007f2f67ac19b2 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#34 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#35 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#36 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#37 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#38 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#39 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#40 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#41 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#42 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#43 0x00007f2f67ac1a71 in QWidgetPrivate::paintSiblingsRecursive () from /usr/lib64/qt4/libQtGui.so.4
!#44 0x00007f2f67ac0ffd in QWidgetPrivate::drawWidget () from /usr/lib64/qt4/libQtGui.so.4
!#45 0x00007f2f67c0e46d in ?? () from /usr/lib64/qt4/libQtGui.so.4
!#46 0x00007f2f67c0eb12 in ?? () from /usr/lib64/qt4/libQtGui.so.4
!#47 0x00007f2f67ac2301 in QWidget::event () from /usr/lib64/qt4/libQtGui.so.4
---Type <return> to continue, or q <return> to quit---
!#48 0x00007f2f67dd93eb in QMainWindow::event () from /usr/lib64/qt4/libQtGui.so.4
!#49 0x00007f2f643f1fab in KMainWindow::event () from /usr/lib64/libkdeui.so.5
!#50 0x00007f2f67a762be in QApplicationPrivate::notify_helper () from /usr/lib64/qt4/libQtGui.so.4
!#51 0x00007f2f67a7adde in QApplication::notify () from /usr/lib64/qt4/libQtGui.so.4
!#52 0x00007f2f6432afeb in KApplication::notify () from /usr/lib64/libkdeui.so.5
!#53 0x00007f2f651072c8 in QCoreApplication::notifyInternal () from /usr/lib64/qt4/libQtCore.so.4
!#54 0x00007f2f6510812d in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib64/qt4/libQtCore.so.4
!#55 0x00007f2f651315a3 in QEventDispatcherUNIX::processEvents () from /usr/lib64/qt4/libQtCore.so.4
!#56 0x00007f2f67afafb3 in ?? () from /usr/lib64/qt4/libQtGui.so.4
!#57 0x00007f2f65106645 in QEventLoop::processEvents () from /usr/lib64/qt4/libQtCore.so.4
!#58 0x00007f2f651067a8 in QEventLoop::exec () from /usr/lib64/qt4/libQtCore.so.4
!#59 0x00007f2f651084ce in QCoreApplication::exec () from /usr/lib64/qt4/libQtCore.so.4
!#60 0x000000000062af6b in main ()
```

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 29 Nov 2008 13:57:30**
Your stack trace starts at 9<br/>
Recompile using -DDEBUG=1 at CMake stage and try to reproduce the crash

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 02 Dec 2008 11:44:41**
ok, seems a oxygen bug, as it works with plastque (doesn't hang), drawing is still not correct but thats another bug.

**Comment by DarthGandalf** [comment]
**Comment by maruel on 18 Dec 2008 14:51:15**
Yep this bug is a real pain. On Windows XP, it happens most of the time when switching between a RDP connection (16 bits display) and a local connection (32 bits display). It hangs for several minutes.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 21 Jan 2009 20:46:34**
closing since it seems to be unrelated to kvirc.

---

Resolution: none → worksforme
Status: new → closed
