### ISSUE TITLE
Crash on slow paste module

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#312]
**Reported by HelLViS69 on 05 Dec 2008 03:42:33 UTC**
KVIrc hangs with spaste module

``` html
<pre>
[Thread debugging using libthread_db enabled]
[New Thread 0xb57516f0 (LWP 7775)]
[New Thread 0xb5165b90 (LWP 9040)]
[KCrash handler]
#5  0x0823f914 in KviConsole::isNotConnected ()
#6  0xb559eadc in spaste_kvs_cmd_clipboard ()
   from /usr/share/kvirc/3.4/modules/libkvispaste.so
#7  0x081e3657 in KviKvsTreeNodeModuleSimpleCommand::execute ()
#8  0x081cfdd1 in KviKvsScript::execute ()
#9  0x081d0b5d in KviKvsScript::run ()
#10 0x0826074b in KviInputEditor::pasteSlow ()
#11 0x08267cb6 in KviInputEditor::qt_invoke ()
#12 0xb6ff5a7d in QObject::activate_signal ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#13 0xb7301fae in QSignal::signal () from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#14 0xb70113d7 in QSignal::activate ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#15 0xb70f7c2a in QPopupMenu::mouseReleaseEvent ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#16 0xb702c5c4 in QWidget::event () from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#17 0xb6f9815a in QApplication::internalNotify ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#18 0xb6f98e7a in QApplication::notify ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#19 0xb7689672 in KApplication::notify () from /usr/lib/libkdecore.so.4
#20 0xb6f3a8c8 in QETWidget::translateMouseEvent ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#21 0xb6f38c23 in QApplication::x11ProcessEvent ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#22 0xb6f4925d in QEventLoop::processEvents ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#23 0xb6fae720 in QEventLoop::enterLoop ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#24 0xb6fae5b6 in QEventLoop::exec () from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#25 0xb6f97bbf in QApplication::exec ()
   from /usr/lib/qt-3.3.8b/lib/libqt-mt.so.3
#26 0x0813ea40 in main ()
</pre>
```

I know this trace is quite useless..
I'll try to investigate with debug symbols

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/312

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 05 Dec 2008 17:34:27**
Priority: Normal → Crash
Version: none → 3.4.2 Shiny

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 06 Dec 2008 22:44:54**
fixed in r2940

---

Resolution: none → fixed
Status: new → closed
