### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#316]
**Reported by wrar on 12 Dec 2008 07:05:54 UTC**
kvirc starts, connects to one network and joins one channel. Then I close it and it crashes.

```
#0  0x08137e77 in KviPointerList<KviWindow>::next (this=0x92a8880)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/../kvilib/core/kvi_pointerlist.h:735
#1  0x08137ed5 in KviPointerList<KviWindow>::findRef (this=0x92a8880, d=0x96b0a40)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/../kvilib/core/kvi_pointerlist.h:809
#2  0x08138719 in KviPointerList<KviWindow>::removeRef (this=0x92a8880, d=0x96b0a40)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/../kvilib/core/kvi_pointerlist.h:1067
#3  0x08135fa5 in KviFrame::closeWindow (this=0x91f4dd0, wnd=0x96b0a40) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_frame.cpp:586
#4  0x0823f91b in KviIrcContext::closeAllDeadChannels (this=0x92f95e0)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/kernel/kvi_irccontext.cpp:163
#5  0x0823fa26 in ~KviIrcContext (this=0x92f95e0) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/kernel/kvi_irccontext.cpp:120
#6  0x0812b0d7 in ~KviConsole (this=0x92c5380) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_console.cpp:193
#7  0x41653e7d in qDeleteInEventHandler () from /usr/lib/libQtCore.so.4
#8  0x41656e19 in QObject::event () from /usr/lib/libQtCore.so.4
#9  0x433ba6a1 in QWidget::event () from /usr/lib/libQtGui.so.4
#10 0x43382aac in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#11 0x43383a07 in QApplication::notify () from /usr/lib/libQtGui.so.4
#12 0x42f49d4a in KApplication::notify () from /usr/lib/libkdeui.so.5
#13 0x4164aaf0 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#14 0x4164ae89 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
#15 0x4164aff6 in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
#16 0x4164b0e0 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#17 0x43382952 in QApplication::exec () from /usr/lib/libQtGui.so.4
#18 0x08248807 in main (argc=152004376, argv=0xbfbd4514) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/kernel/kvi_main.cpp:417
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/316

**Comment by DarthGandalf** [comment]
**Comment by wrar on 14 Dec 2008 14:50:34**

```
0x08137e77 in KviPointerList<KviWindow>::next (this=0x9c2cb28)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/../kvilib/core/kvi_pointerlist.h:735
735                     if(m_pAux)return (T *)(m_pAux->m_pData);
(gdb) p m_pAux
warning: RTTI symbol not found for class 'QToolButton'
$1 = (KviPointerListNode *) 0x1b855
(gdb) p *m_pAux
warning: RTTI symbol not found for class 'QToolButton'
Cannot access memory at address 0x1b855
```

**Comment by DarthGandalf** [comment]
**Modified by thexception on 17 Dec 2008 00:13:14**
Owner: pragmaware → thexception

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Jan 2009 22:28:19**
merged with #337

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Jan 2009 22:34:18**
it's not 337, it's #334 , sorry

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 07 Jan 2009 15:47:13**
sghould have been fixed in r2979 (needs testing). Reopen if the problem re-appears

---

Resolution: none → fixed
Status: new → closed
