### ISSUE TITLE
KVIrc crashes when I close it

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#334]
**Reported by wodim on 02 Jan 2009 00:34:36 UTC**
Here is a backtrace:

```

GNU gdb 6.8-debian
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i486-linux-gnu"...
(gdb) handle SIG33 pass nostop noprint
Signal        Stop  Print   Pass to program Description
SIG33         No    No  Yes     Real-time event 33
(gdb) set pagination 0
(gdb) run kvirc4
Starting program: /usr/local/bin/kvirc4 kvirc4
[Thread debugging using libthread_db enabled]
[New Thread 0xb51886c0 (LWP 7810)]
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QPainter::begin: Cannot paint on a null pixmap
QPainter::setRenderHint: Painter must be active to set rendering hints
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
[New Thread 0xb0ee4b90 (LWP 7813)]
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
[New Thread 0xb06c4b90 (LWP 7814)]
[New Thread 0xafec3b90 (LWP 7815)]
[New Thread 0xaf6c2b90 (LWP 7816)]
[New Thread 0xaeec1b90 (LWP 7817)]
[New Thread 0xae6c0b90 (LWP 7818)]
[New Thread 0xadebfb90 (LWP 7819)]
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
QObject: Do not delete object, 'unnamed', during its event handler!
Loggin' in...
Object::connect: No such signal KviIrcView::fileDropped(const char*)
Object::connect:  (sender name:   'irc_view')
Object::connect:  (receiver name: 'NiCK')
[Thread 0xb0ee4b90 (LWP 7813) exited]
[Thread 0xadebfb90 (LWP 7819) exited]
[Thread 0xb06c4b90 (LWP 7814) exited]
[Thread 0xaeec1b90 (LWP 7817) exited]
[Thread 0xae6c0b90 (LWP 7818) exited]
[Thread 0xaf6c2b90 (LWP 7816) exited]
[Thread 0xafec3b90 (LWP 7815) exited]
[New Thread 0xafec3b90 (LWP 7820)]
Inserting phonon
[Thread 0xafec3b90 (LWP 7820) exited]
kvirc(7810) Phonon::KdePlatformPlugin::createBackend: using backend:  "Xine"
[New Thread 0xafec3b90 (LWP 7821)]
[New Thread 0xaf6c2b90 (LWP 7822)]
[New Thread 0xae6c0b90 (LWP 7823)]
[New Thread 0xaeec1b90 (LWP 7824)]
[Thread 0xaeec1b90 (LWP 7824) exited]
[Thread 0xae6c0b90 (LWP 7823) exited]
[New Thread 0xae6c0b90 (LWP 7825)]
[New Thread 0xaeec1b90 (LWP 7826)]
[New Thread 0xadab4b90 (LWP 7827)]
[New Thread 0xacecab90 (LWP 7828)]
[New Thread 0xac6c9b90 (LWP 7829)]
[New Thread 0xabec8b90 (LWP 7830)]
[New Thread 0xab6c7b90 (LWP 7831)]
[Thread 0xab6c7b90 (LWP 7831) exited]
QObject: Do not delete object, 'unnamed', during its event handler!
Object::connect: No such signal KviIrcView::fileDropped(const char*)
Object::connect:  (sender name:   'irc_view')
Object::connect:  (receiver name: 'NiCK')
[New Thread 0xab6c7b90 (LWP 7832)]
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'unnamed', during its event handler!
QObject: Do not delete object, 'kvirc_frame', during its event handler!
[New Thread 0xaa792b90 (LWP 7833)]
[Thread 0xaa792b90 (LWP 7833) exited]
[New Thread 0xaa792b90 (LWP 7834)]
[Thread 0xaa792b90 (LWP 7834) exited]
[New Thread 0xaa792b90 (LWP 7835)]
[Thread 0xaa792b90 (LWP 7835) exited]
[New Thread 0xaa792b90 (LWP 7836)]
[Thread 0xaa792b90 (LWP 7836) exited]
[New Thread 0xaa792b90 (LWP 7837)]
[Thread 0xaa792b90 (LWP 7837) exited]
[New Thread 0xaa792b90 (LWP 7838)]
[Thread 0xaa792b90 (LWP 7838) exited]
[New Thread 0xaa792b90 (LWP 7839)]
[Thread 0xaa792b90 (LWP 7839) exited]
[New Thread 0xaa792b90 (LWP 7840)]
[New Thread 0xa9f8db90 (LWP 7841)]
[Thread 0xa9f8db90 (LWP 7841) exited]
[New Thread 0xa9f8db90 (LWP 7842)]
[Thread 0xaa792b90 (LWP 7840) exited]
[Thread 0xa9f8db90 (LWP 7842) exited]
[Thread 0xab6c7b90 (LWP 7832) exited]
[New Thread 0xab6c7b90 (LWP 7843)]
[Thread 0xab6c7b90 (LWP 7843) exited]
[New Thread 0xab6c7b90 (LWP 7847)]
[Thread 0xab6c7b90 (LWP 7847) exited]
[New Thread 0xab6c7b90 (LWP 7848)]
[Thread 0xab6c7b90 (LWP 7848) exited]
[New Thread 0xab6c7b90 (LWP 7849)]
[Thread 0xab6c7b90 (LWP 7849) exited]
[New Thread 0xab6c7b90 (LWP 7850)]
[Thread 0xab6c7b90 (LWP 7850) exited]
[New Thread 0xab6c7b90 (LWP 7851)]
[Thread 0xab6c7b90 (LWP 7851) exited]
[New Thread 0xab6c7b90 (LWP 7852)]
[Thread 0xab6c7b90 (LWP 7852) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb51886c0 (LWP 7810)]
0x08150357 in KviPointerList<KviWindow>::next (this=0x88bc9f8) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:735
735         if(m_pAux)return (T *)(m_pAux->m_pData);
(gdb) backtrace full
#0  0x08150357 in KviPointerList<KviWindow>::next (this=0x88bc9f8) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:735
No locals.
#1  0x081503b5 in KviPointerList<KviWindow>::findRef (this=0x88bc9f8, d=0x9a72718) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:809
    t = (class KviWindow *) 0xe9000000
    ret = 1
#2  0x08150bf9 in KviPointerList<KviWindow>::removeRef (this=0x88bc9f8, d=0x9a72718) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:1067
No locals.
#3  0x0814e475 in KviFrame::closeWindow (this=0x85e80b8, wnd=0x9a72718) at /home/egn/kvirc/src/kvirc/ui/kvi_frame.cpp:586
No locals.
#4  0x0825858b in KviIrcContext::closeAllDeadChannels (this=0x88968b8) at /home/egn/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:163
    c = <value optimized out>
#5  0x08258696 in ~KviIrcContext (this=0x88968b8) at /home/egn/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:120
No locals.
#6  0x08143567 in ~KviConsole (this=0x8896608) at /home/egn/kvirc/src/kvirc/ui/kvi_console.cpp:193
No locals.
#7  0xb662cf6c in qDeleteInEventHandler () from /usr/lib/libQtCore.so.4
No symbol table info available.
#8  0xb662e923 in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#9  0xb6b7fe64 in QWidget::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#10 0xb6b2879c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
#11 0xb6b306ea in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#12 0xb607ca0d in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#13 0xb661f0e1 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0xb661fd65 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0xb661ff5d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0xb662005b in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0xb6b28617 in QApplication::exec () from /usr/lib/libQtGui.so.4
No symbol table info available.
#18 0x08261357 in main (argc=138294288, argv=0xbfd9cb84) at /home/egn/kvirc/src/kvirc/kernel/kvi_main.cpp:417
    a = {argc = 2, argv = 0xbfd9cb84, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x838edb0 "server -u kvirc4", m_len = 16}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x838e9f8 "", m_len = 0}}
    retCode = <value optimized out>
    theApp = (class KviApp *) 0x8391e88
    szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x83e3410 "server -u kvirc4", m_len = 16}
    retVal = <value optimized out>
(gdb) info registers
eax            0xe9000000   -385875968
ecx            0x29 41
edx            0x88bc9f8    143378936
ebx            0x1  1
esp            0xbfd9c3a8   0xbfd9c3a8
ebp            0xbfd9c3a8   0xbfd9c3a8
esi            0x9a72718    161949464
edi            0x88bc9f8    143378936
eip            0x8150357    0x8150357 <KviPointerList<KviWindow>::next()+23>
eflags         0x210286 [ PF SF IF RF ID ]
cs             0x73 115
ss             0x7b 123
ds             0x7b 123
es             0x7b 123
fs             0x0  0
gs             0x33 51
(gdb) thread apply all backtrace

Thread 19 (Thread 0xabec8b90 (LWP 7830)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb7e03025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0b2033c in ?? () from /usr/lib/libxine.so.1
#3  0x099a2824 in ?? ()
#4  0x099a280c in ?? ()
#5  0x00000000 in ?? ()

Thread 18 (Thread 0xac6c9b90 (LWP 7829)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb7e03025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0b0ef00 in ?? () from /usr/lib/libxine.so.1
#3  0x09979784 in ?? ()
#4  0x0997976c in ?? ()
#5  0x00001e95 in ?? ()
#6  0x00000000 in ?? ()

Thread 17 (Thread 0xacecab90 (LWP 7828)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb7e03025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0b0ef00 in ?? () from /usr/lib/libxine.so.1
#3  0x0843153c in ?? ()
#4  0x08431524 in ?? ()
#5  0x00001e94 in ?? ()
#6  0x00000000 in ?? ()

Thread 16 (Thread 0xadab4b90 (LWP 7827)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb59199f1 in select () from /lib/i686/cmov/libc.so.6
#2  0xb0b36bd8 in xine_usec_sleep () from /usr/lib/libxine.so.1
#3  0x00000000 in ?? ()

Thread 15 (Thread 0xaeec1b90 (LWP 7826)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb7e03025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0b1d2a3 in ?? () from /usr/lib/libxine.so.1
#3  0x084386e0 in ?? ()
#4  0x084386c8 in ?? ()
#5  0x00000000 in ?? ()

Thread 14 (Thread 0xae6c0b90 (LWP 7825)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb5916da7 in poll () from /lib/i686/cmov/libc.so.6
#2  0xb076fed3 in ?? () from /usr/lib/xine/plugins/1.23/xineplug_ao_out_alsa.so
#3  0xae6c02f8 in ?? ()
#4  0x00000001 in ?? ()
#5  0x0000014d in ?? ()
#6  0xae6c0380 in ?? ()
#7  0xb7e12000 in ?? ()
#8  0xb7dfb2b2 in ?? () from /lib/i686/cmov/libpthread.so.0
#9  0x0000000d in ?? ()
#10 0xb0772eb0 in ?? () from /usr/lib/xine/plugins/1.23/xineplug_ao_out_alsa.so
#11 0xb0772070 in ?? () from /usr/lib/xine/plugins/1.23/xineplug_ao_out_alsa.so
#12 0xae6c03a0 in ?? ()
#13 0xae6c039c in ?? ()
#14 0xae6c02f8 in ?? ()
#15 0x08467d78 in ?? ()
#16 0xae6c02f0 in ?? ()
#17 0x00000000 in ?? ()

Thread 11 (Thread 0xaf6c2b90 (LWP 7822)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb5916da7 in poll () from /lib/i686/cmov/libc.so.6
#2  0xb55d6872 in ?? () from /usr/lib/libglib-2.0.so.0
#3  0x08420ce8 in ?? ()
#4  0x00000001 in ?? ()
#5  0x0000002d in ?? ()
#6  0x08420ce8 in ?? ()
#7  0x00000001 in ?? ()
#8  0xb564e9c8 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0xb564e5f8 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0xb564e620 in ?? () from /usr/lib/libglib-2.0.so.0
#11 0xaf6c2224 in ?? ()
#12 0xb564e5f8 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0xb564e620 in ?? () from /usr/lib/libglib-2.0.so.0
#14 0x08488d0c in ?? ()
#15 0x00000001 in ?? ()
#16 0x08488d08 in ?? ()
#17 0x08420ce8 in ?? ()
#18 0xb5916d30 in ?? () from /lib/i686/cmov/libc.so.6
#19 0xb7e023f0 in ?? () from /lib/i686/cmov/libpthread.so.0
#20 0xb7e00980 in ?? () from /lib/i686/cmov/libpthread.so.0
#21 0x08488d0c in ?? ()
#22 0xb6634935 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#23 0xb55d6ba1 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#24 0xb66495e8 in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#25 0xb661d7aa in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#26 0xb661d96a in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#27 0xb652c289 in QThread::exec () from /usr/lib/libQtCore.so.4
#28 0xb0b59022 in ?? () from /usr/lib/kde4/plugins/phonon_backend/phonon_xine.so
#29 0x08481428 in ?? ()
#30 0x08481428 in ?? ()
#31 0xb0b975d4 in ?? () from /usr/lib/kde4/plugins/phonon_backend/phonon_xine.so
#32 0xb64f5dbe in ?? () from /usr/lib/libQtCore.so.4
#33 0x000000ba in ?? ()
#34 0xb64d9000 in ?? ()
#35 0x0022abc0 in ?? ()
#36 0x00000005 in ?? ()
#37 0xb7dfb128 in ?? () from /lib/i686/cmov/libpthread.so.0
#38 0xb6702798 in ?? () from /usr/lib/libQtCore.so.4
#39 0x0846d130 in ?? ()
#40 0x08481428 in ?? ()
#41 0xaf6c23b8 in ?? ()
#42 0xb7f972e0 in ?? () from /lib/ld-linux.so.2
#43 0xb652f52e in ?? () from /usr/lib/libQtCore.so.4
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0xafec3b90 (LWP 7821)):
#0  0xb7f83424 in __kernel_vsyscall ()
#1  0xb7e03352 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0b0b3ff in ?? () from /usr/lib/libxine.so.1

Thread 1 (Thread 0xb51886c0 (LWP 7810)):
#0  0x08150357 in KviPointerList<KviWindow>::next (this=0x88bc9f8) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:735
#1  0x081503b5 in KviPointerList<KviWindow>::findRef (this=0x88bc9f8, d=0x9a72718) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:809
#2  0x08150bf9 in KviPointerList<KviWindow>::removeRef (this=0x88bc9f8, d=0x9a72718) at /home/egn/kvirc/src/kvirc/../kvilib/core/kvi_pointerlist.h:1067
#3  0x0814e475 in KviFrame::closeWindow (this=0x85e80b8, wnd=0x9a72718) at /home/egn/kvirc/src/kvirc/ui/kvi_frame.cpp:586
#4  0x0825858b in KviIrcContext::closeAllDeadChannels (this=0x88968b8) at /home/egn/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:163
#5  0x08258696 in ~KviIrcContext (this=0x88968b8) at /home/egn/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:120
#6  0x08143567 in ~KviConsole (this=0x8896608) at /home/egn/kvirc/src/kvirc/ui/kvi_console.cpp:193
#7  0xb662cf6c in qDeleteInEventHandler () from /usr/lib/libQtCore.so.4
#8  0xb662e923 in QObject::event () from /usr/lib/libQtCore.so.4
#9  0xb6b7fe64 in QWidget::event () from /usr/lib/libQtGui.so.4
#10 0xb6b2879c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#11 0xb6b306ea in QApplication::notify () from /usr/lib/libQtGui.so.4
#12 0xb607ca0d in KApplication::notify () from /usr/lib/libkdeui.so.5
#13 0xb661f0e1 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#14 0xb661fd65 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
#15 0xb661ff5d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
#16 0xb662005b in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#17 0xb6b28617 in QApplication::exec () from /usr/lib/libQtGui.so.4
#18 0x08261357 in main (argc=138294288, argv=0xbfd9cb84) at /home/egn/kvirc/src/kvirc/kernel/kvi_main.cpp:417
(gdb) quit
The program is running.  Exit anyway? (y or n)

```

Happy New Year.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/334

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Jan 2009 22:28:00**
merged with #316

---

Resolution: none → duplicate
Status: new → closed
