### ISSUE TITLE
KVIrc crashes when I open "Edit Settings..." window

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#337]
**Reported by wodim on 04 Jan 2009 20:13:39 UTC**
Backtrace:

```

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb511b6c0 (LWP 9083)]
0x0813268d in QString (this=0xb7d471c, other=@0xc) at /usr/include/qt4/QtCore/qstring.h:670
670 inline QString::QString(const QString &other) : d(other.d)
(gdb) backtrace full
#0  0x0813268d in QString (this=0xb7d471c, other=@0xc) at /usr/include/qt4/QtCore/qstring.h:670
No locals.
#1  0xb7ba0ce1 in KviAnimatedPixmap (this=0xb7d4710, source=0x0) at /home/egn/kvirc/src/kvilib/ext/kvi_animatedpixmap.cpp:46
No locals.
#2  0x082781ad in KviTextIcon (this=0xb7d46f8, pIcon=0x9b84468) at /home/egn/kvirc/src/kvirc/kernel/kvi_texticonmanager.cpp:90
No locals.
#3  0xa9ef690d in KviTextIconsOptionsWidget (this=0xb7c9bf0, parent=0xb6f79e8) at /home/egn/kvirc/src/modules/options/optw_texticons.cpp:106
No locals.
#4  0xa9eaccf4 in classKviTextIconsOptionsWidget_createInstanceProc (parent=0xb6f79e8) at /home/egn/kvirc/src/modules/options/instances.cpp:410
No locals.
#5  0xa9ea26a3 in KviOptionsInstanceManager::getInstance (this=0xb6bac90, e=0xb6d84e8, par=0xb6f79e8) at /home/egn/kvirc/src/modules/options/instances.cpp:3584
No locals.
#6  0xa9e9e1a0 in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0xb7c66e8, l=0xb6d7598, szGroup=@0xbfc2ef98, bNotContainedOnly=false) at /home/egn/kvirc/src/modules/options/dialog.cpp:515
    it = (KviOptionsTreeWidgetItem *) 0xb7c8ec0
    e = (KviOptionsWidgetInstanceEntry *) 0xb6d84e8
    tmp = {_vptr.KviPointerList = 0xa9f15300, m_bAutoDelete = false, m_pHead = 0xb7c9aa0, m_pTail = 0xb7c9a10, m_pAux = 0xb7c9aa0, m_uCount = 9}
#7  0xa9e9e1fa in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0xb7ba118, l=0xb6d65a0, szGroup=@0xbfc2ef98, bNotContainedOnly=true) at /home/egn/kvirc/src/modules/options/dialog.cpp:530
    it = (KviOptionsTreeWidgetItem *) 0xb7c66e8
    e = (KviOptionsWidgetInstanceEntry *) 0xb6d7498
    tmp = {_vptr.KviPointerList = 0xa9f15300, m_bAutoDelete = false, m_pHead = 0xb7c65f8, m_pTail = 0xb7bbc48, m_pAux = 0xb7c65f8, m_uCount = 7}
#8  0xa9e9e1fa in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0x0, l=0xb6ba630, szGroup=@0xbfc2ef98, bNotContainedOnly=false) at /home/egn/kvirc/src/modules/options/dialog.cpp:530
    it = (KviOptionsTreeWidgetItem *) 0xb7ba118
    e = (KviOptionsWidgetInstanceEntry *) 0xb6d6508
    tmp = {_vptr.KviPointerList = 0xa9f15300, m_bAutoDelete = false, m_pHead = 0xb700d70, m_pTail = 0xb700c18, m_pAux = 0xb700c98, m_uCount = 18}
#9  0xa9e9f2f1 in KviOptionsDialog (this=0xb6ee698, par=0x9c2f0a8, szGroup=@0xbfc2ef98) at /home/egn/kvirc/src/modules/options/dialog.cpp:256
No locals.
#10 0xa9e9a99e in options_kvs_cmd_dialog (c=0xbfc2efd8) at /home/egn/kvirc/src/modules/options/libkvioptions.cpp:122
    szGroup = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 39154}, alloc = 0, size = 0, data = 0x82c0f62, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 201}, alloc = 0, size = 0, data = 0xb669716e, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xb11e4c0, static codecForCStrings = 0x99f16e8}
    parameter_format_list = {{szName = 0xa9f02d99 "options_group", uType = 0 '\0', uFlags = 1 '\001', pContainer = 0xbfc2ef98}, {szName = 0x0, uType = 0 '\0', uFlags = 0 '\0', pContainer = 0x0}}
    d = <value optimized out>
#11 0x0821d683 in KviKvsTreeNodeModuleSimpleCommand::execute (this=0xb276fc8, c=0xbfc2f068) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_treenode_modulesimplecommand.cpp:92
    m = <value optimized out>
    proc = (KviKvsModuleSimpleCommandExecRoutine *) 0xb6ee258
    l = {m_pList = 0xb11e4a0}
    swl = {m_pShortSwitchDict = 0x0, m_pLongSwitchDict = 0x0}
    call = {<KviKvsModuleRunTimeCall> = {<KviKvsRunTimeCall> = {_vptr.KviKvsRunTimeCall = 0x82905d0, m_pContext = 0xbfc2f068, m_pParams = 0xbfc2eff4}, m_pModule = 0xb6b6410}, m_pSwitchList = 0xbfc2efec}
#12 0x0820daa7 in KviKvsScript::executeInternal (this=0x9e92c98, pContext=0xbfc2f068) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:291
    iRunStatus = <value optimized out>
#13 0x0820dbfb in KviKvsScript::execute (this=0x9e92c98, pWnd=0xb165be0, pParams=0x9aeef48, pRetVal=0xb669450, iRunFlags=<value optimized out>, pExtData=0x0) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:342
    bDeleteParams = false
    bDeleteRetVal = true
    ctx = {m_pScript = 0x9e92c98, m_pLocalVariables = 0xb6b8a98, m_pParameterList = 0x9aeef48, m_pReturnValue = 0xb669450, m_pWindow = 0xb165be0, m_uRunTimeFlags = 0, m_pExtendedData = 0x0, m_bError = false, m_pDefaultReportLocation = 0xb276fc8}
    iRunStatus = <value optimized out>
#14 0x081cb08a in KviKvsAction::activate (this=0x9e92b68) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_action.cpp:65
No locals.
#15 0x08282638 in KviAction::qt_metacall (this=0x9e92b68, _c=QMetaObject::InvokeMetaMethod, _id=7, _a=0xbfc2f1dc) at /home/egn/kvirc/release/src/kvirc/kernel/moc_kvi_action.cxx:86
No locals.
#16 0xb65c6be0 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0xb65c6fe0 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
No symbol table info available.
#18 0xb70a5b71 in QAbstractButton::clicked () from /usr/lib/libQtGui.so.4
No symbol table info available.
#19 0xb6df8ea9 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#20 0xb6dfaaa4 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#21 0xb6dfad36 in QAbstractButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4
No symbol table info available.
#22 0xb6ed779c in QToolButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4
No symbol table info available.
#23 0xb6b137c2 in QWidget::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#24 0xb6df8d4e in QAbstractButton::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#25 0xb6ed7264 in QToolButton::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#26 0xb6abb79c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
#27 0xb6ac3fd1 in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#28 0xb600fa0d in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#29 0xb65b20e1 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#30 0xb6ac325e in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
No symbol table info available.
#31 0xb6b2ce2d in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#32 0xb6b2bc11 in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
No symbol table info available.
#33 0xb6b5563a in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#34 0xb5566348 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#35 0xb55699e3 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#36 0x099f6698 in ?? ()
No symbol table info available.
#37 0x00000000 in ?? ()
No symbol table info available.
(gdb) info registers
eax            0xb7d471c    192759580
ecx            0xb7bef520   -1212222176
edx            0xc  12
ebx            0xb7d471c    192759580
esp            0xbfc2ebf0   0xbfc2ebf0
ebp            0xbfc2ec08   0xbfc2ec08
esi            0x0  0
edi            0xb7d4710    192759568
eip            0x813268d    0x813268d <QString+13>
eflags         0x210286 [ PF SF IF RF ID ]
cs             0x73 115
ss             0x7b 123
ds             0x7b 123
es             0x7b 123
fs             0x0  0
gs             0x33 51
(gdb) thread apply all backtrace

Thread 16 (Thread 0xabed2b90 (LWP 9100)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb7d96025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb036433c in ?? () from /usr/lib/libxine.so.1
#3  0x0afad26c in ?? ()
#4  0x0afad254 in ?? ()
#5  0x00000000 in ?? ()

Thread 15 (Thread 0xac6d3b90 (LWP 9099)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb7d96025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0352f00 in ?? () from /usr/lib/libxine.so.1
#3  0x0af84b8c in ?? ()
#4  0x0af84b74 in ?? ()
#5  0x0000238b in ?? ()
#6  0x00000000 in ?? ()

Thread 14 (Thread 0xad0a1b90 (LWP 9098)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb7d96025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb0352f00 in ?? () from /usr/lib/libxine.so.1
#3  0x09ac6e2c in ?? ()
#4  0x09ac6e14 in ?? ()
#5  0x0000238a in ?? ()
#6  0x00000000 in ?? ()

Thread 13 (Thread 0xadcaeb90 (LWP 9097)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb58ac9f1 in select () from /lib/i686/cmov/libc.so.6
#2  0xb037abd8 in xine_usec_sleep () from /usr/lib/libxine.so.1
#3  0x00000000 in ?? ()

Thread 12 (Thread 0xaee84b90 (LWP 9096)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb7d96025 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb03612a3 in ?? () from /usr/lib/libxine.so.1
#3  0x09a9a398 in ?? ()
#4  0x09a9a380 in ?? ()
#5  0x00000000 in ?? ()

Thread 11 (Thread 0xaf685b90 (LWP 9095)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb58a9da7 in poll () from /lib/i686/cmov/libc.so.6
#2  0xaffb0ed3 in ?? () from /usr/lib/xine/plugins/1.23/xineplug_ao_out_alsa.so
#3  0xaf6852f8 in ?? ()
#4  0x00000001 in ?? ()
#5  0x0000014d in ?? ()
#6  0xaf6852f0 in ?? ()
#7  0xaf6852d8 in ?? ()
#8  0xb7d9a733 in sigaction () from /lib/i686/cmov/libpthread.so.0
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 8 (Thread 0xafe86b90 (LWP 9092)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb58a9da7 in poll () from /lib/i686/cmov/libc.so.6
#2  0xb5569872 in ?? () from /usr/lib/libglib-2.0.so.0
#3  0x09acc3f0 in ?? ()
#4  0x00000001 in ?? ()
#5  0x0000002d in ?? ()
#6  0x09acc3f0 in ?? ()
#7  0x00000001 in ?? ()
#8  0xb55e19c8 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0xb55e15f8 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0xb55e1620 in ?? () from /usr/lib/libglib-2.0.so.0
#11 0xafe86224 in ?? ()
#12 0xb55e15f8 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0xb55e1620 in ?? () from /usr/lib/libglib-2.0.so.0
#14 0x09a9ca0c in ?? ()
#15 0x00000001 in ?? ()
#16 0x09a9ca08 in ?? ()
#17 0x09acc3f0 in ?? ()
#18 0xb58a9d30 in ?? () from /lib/i686/cmov/libc.so.6
#19 0xb7d953f0 in ?? () from /lib/i686/cmov/libpthread.so.0
#20 0xb7d93980 in ?? () from /lib/i686/cmov/libpthread.so.0
#21 0x09a9ca0c in ?? ()
#22 0xb65c7935 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#23 0xb5569ba1 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#24 0xb65dc5e8 in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#25 0xb65b07aa in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#26 0xb65b096a in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#27 0xb64bf289 in QThread::exec () from /usr/lib/libQtCore.so.4
#28 0xb039d022 in ?? () from /usr/lib/kde4/plugins/phonon_backend/phonon_xine.so
#29 0x09aeb7b8 in ?? ()
#30 0x09aeb7b8 in ?? ()
#31 0xb03db5d4 in ?? () from /usr/lib/kde4/plugins/phonon_backend/phonon_xine.so
#32 0xb6488dbe in ?? () from /usr/lib/libQtCore.so.4
#33 0x000000ba in ?? ()
#34 0xb646c000 in ?? ()
#35 0x0022abc0 in ?? ()
#36 0x00000005 in ?? ()
#37 0xb7d8e128 in ?? () from /lib/i686/cmov/libpthread.so.0
#38 0xb6695798 in ?? () from /usr/lib/libQtCore.so.4
#39 0x09ad11f0 in ?? ()
#40 0x09aeb7b8 in ?? ()
#41 0xafe863b8 in ?? ()
#42 0xb7f2a2e0 in ?? () from /lib/ld-linux.so.2
#43 0xb64c252e in ?? () from /usr/lib/libQtCore.so.4
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0xb0ec1b90 (LWP 9091)):
#0  0xb7f16424 in __kernel_vsyscall ()
#1  0xb7d96352 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/i686/cmov/libpthread.so.0
#2  0xb034f3ff in ?? () from /usr/lib/libxine.so.1

Thread 1 (Thread 0xb511b6c0 (LWP 9083)):
#0  0x0813268d in QString (this=0xb7d471c, other=@0xc) at /usr/include/qt4/QtCore/qstring.h:670
#1  0xb7ba0ce1 in KviAnimatedPixmap (this=0xb7d4710, source=0x0) at /home/egn/kvirc/src/kvilib/ext/kvi_animatedpixmap.cpp:46
#2  0x082781ad in KviTextIcon (this=0xb7d46f8, pIcon=0x9b84468) at /home/egn/kvirc/src/kvirc/kernel/kvi_texticonmanager.cpp:90
#3  0xa9ef690d in KviTextIconsOptionsWidget (this=0xb7c9bf0, parent=0xb6f79e8) at /home/egn/kvirc/src/modules/options/optw_texticons.cpp:106
#4  0xa9eaccf4 in classKviTextIconsOptionsWidget_createInstanceProc (parent=0xb6f79e8) at /home/egn/kvirc/src/modules/options/instances.cpp:410
#5  0xa9ea26a3 in KviOptionsInstanceManager::getInstance (this=0xb6bac90, e=0xb6d84e8, par=0xb6f79e8) at /home/egn/kvirc/src/modules/options/instances.cpp:3584
#6  0xa9e9e1a0 in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0xb7c66e8, l=0xb6d7598, szGroup=@0xbfc2ef98, bNotContainedOnly=false) at /home/egn/kvirc/src/modules/options/dialog.cpp:515
#7  0xa9e9e1fa in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0xb7ba118, l=0xb6d65a0, szGroup=@0xbfc2ef98, bNotContainedOnly=true) at /home/egn/kvirc/src/modules/options/dialog.cpp:530
#8  0xa9e9e1fa in KviOptionsDialog::fillTreeWidget (this=0xb6ee698, p=0x0, l=0xb6ba630, szGroup=@0xbfc2ef98, bNotContainedOnly=false) at /home/egn/kvirc/src/modules/options/dialog.cpp:530
#9  0xa9e9f2f1 in KviOptionsDialog (this=0xb6ee698, par=0x9c2f0a8, szGroup=@0xbfc2ef98) at /home/egn/kvirc/src/modules/options/dialog.cpp:256
#10 0xa9e9a99e in options_kvs_cmd_dialog (c=0xbfc2efd8) at /home/egn/kvirc/src/modules/options/libkvioptions.cpp:122
#11 0x0821d683 in KviKvsTreeNodeModuleSimpleCommand::execute (this=0xb276fc8, c=0xbfc2f068) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_treenode_modulesimplecommand.cpp:92
#12 0x0820daa7 in KviKvsScript::executeInternal (this=0x9e92c98, pContext=0xbfc2f068) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:291
#13 0x0820dbfb in KviKvsScript::execute (this=0x9e92c98, pWnd=0xb165be0, pParams=0x9aeef48, pRetVal=0xb669450, iRunFlags=<value optimized out>, pExtData=0x0) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:342
#14 0x081cb08a in KviKvsAction::activate (this=0x9e92b68) at /home/egn/kvirc/src/kvirc/kvs/kvi_kvs_action.cpp:65
#15 0x08282638 in KviAction::qt_metacall (this=0x9e92b68, _c=QMetaObject::InvokeMetaMethod, _id=7, _a=0xbfc2f1dc) at /home/egn/kvirc/release/src/kvirc/kernel/moc_kvi_action.cxx:86
#16 0xb65c6be0 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#17 0xb65c6fe0 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#18 0xb70a5b71 in QAbstractButton::clicked () from /usr/lib/libQtGui.so.4
#19 0xb6df8ea9 in ?? () from /usr/lib/libQtGui.so.4
#20 0xb6dfaaa4 in ?? () from /usr/lib/libQtGui.so.4
#21 0xb6dfad36 in QAbstractButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4
#22 0xb6ed779c in QToolButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4
#23 0xb6b137c2 in QWidget::event () from /usr/lib/libQtGui.so.4
#24 0xb6df8d4e in QAbstractButton::event () from /usr/lib/libQtGui.so.4
#25 0xb6ed7264 in QToolButton::event () from /usr/lib/libQtGui.so.4
#26 0xb6abb79c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#27 0xb6ac3fd1 in QApplication::notify () from /usr/lib/libQtGui.so.4
#28 0xb600fa0d in KApplication::notify () from /usr/lib/libkdeui.so.5
#29 0xb65b20e1 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#30 0xb6ac325e in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
#31 0xb6b2ce2d in ?? () from /usr/lib/libQtGui.so.4
#32 0xb6b2bc11 in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#33 0xb6b5563a in ?? () from /usr/lib/libQtGui.so.4
#34 0xb5566348 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#35 0xb55699e3 in ?? () from /usr/lib/libglib-2.0.so.0
#36 0x099f6698 in ?? ()
#37 0x00000000 in ?? ()

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/337

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 04 Jan 2009 22:19:54**
fixed in r2974

---

Resolution: none → fixed
Status: new → closed
