### ISSUE TITLE
kvirc crahes on exit

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#339]
**Reported by bugs on 07 Jan 2009 01:27:11 UTC**
Thread 1 (Thread 0xb544f700 (LWP 7437)):
[KCrash Handler]
#6  0x0810d65b in KviFrame::closeWindow ()
#7  0x0825b067 in KviIrcContext::closeAllDeadChannels ()
#8  0x0825b374 in KviIrcContext::~KviIrcContext ()
#9  0x080fdc8f in KviConsole::~KviConsole ()
#10 0xb662ccbc in qDeleteInEventHandler () from /usr/lib/qt4/libQtCore.so.4
#11 0xb662ead3 in QObject::event () from /usr/lib/qt4/libQtCore.so.4
#12 0xb6ce0972 in QWidget::event () from /usr/lib/qt4/libQtGui.so.4
#13 0xb6c88aef in QApplicationPrivate::notify_helper () from /usr/lib/qt4/libQtGui.so.4
#14 0xb6c8d58c in QApplication::notify () from /usr/lib/qt4/libQtGui.so.4
#15 0xb6028daa in KApplication::notify () from /usr/kde/svn/lib/libkdeui.so.5
#16 0xb661e327 in QCoreApplication::notifyInternal () from /usr/lib/qt4/libQtCore.so.4
#17 0xb661f37d in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/qt4/libQtCore.so.4
#18 0xb661f61d in QCoreApplication::sendPostedEvents () from /usr/lib/qt4/libQtCore.so.4
#19 0xb661f707 in QCoreApplication::exec () from /usr/lib/qt4/libQtCore.so.4
#20 0xb6c88317 in QApplication::exec () from /usr/lib/qt4/libQtGui.so.4
#21 0x08266a2b in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/339

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 07 Jan 2009 01:30:18**
Recompile using -DDEBUG=1 at CMake stage since this stack trace is quite useless

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 07 Jan 2009 01:32:16**
Duplicate of #316

---

Resolution: none → duplicate
Status: new → closed
