### ISSUE TITLE
KVIrc crashes sometimes when I close a server window

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#349]
**Reported by wodim on 24 Jan 2009 01:15:00 UTC**
That's it, sometimes when you close a server window with open channels, KVIrc crashes.

```

#0  0x000001c1 in ?? ()                             
No symbol table info available.                     
#1  0x0814a568 in QObject::inherits (this=0xa9bdf18, classname=0x82893a8 "KviWindow") at /usr/include/qt4/QtCore/qobject.h:241
No locals.                                                                                                                    
#2  0x08177ac1 in KviMdiChild::updateCaption (this=0xa9b6418) at /home/egn/kvirc/src/kvirc/ui/kvi_mdichild.cpp:295            
No locals.                                                                                                                    
#3  0x0827d4db in KviMdiChild::qt_metacall (this=0xa9b6418, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0xa930e18) at /home/egn/kvirc/release/src/kvirc/ui/moc_kvi_mdichild.cxx:88                                                                                                              
No locals.                                                                                                                                      
#4  0xb65d0d7b in QMetaCallEvent::placeMetaCall () from /usr/lib/libQtCore.so.4                                                                 
No symbol table info available.                                                                                                                 
#5  0xb65d28f1 in QObject::event () from /usr/lib/libQtCore.so.4                                                                                
No symbol table info available.                                                                                                                 
#6  0xb6b23e64 in QWidget::event () from /usr/lib/libQtGui.so.4                                                                                 
No symbol table info available.                                                                                                                 
#7  0xb6e94d1a in QMdiSubWindow::event () from /usr/lib/libQtGui.so.4                                                                           
No symbol table info available.                                                                                                                 
#8  0xb6acc79c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4                                                             
No symbol table info available.                                                                                                                 
#9  0xb6ad46ea in QApplication::notify () from /usr/lib/libQtGui.so.4                                                                           
No symbol table info available.                                                                                                                 
#10 0xb601d77d in KApplication::notify () from /usr/lib/libkdeui.so.5                                                                           
No symbol table info available.                                                                                                                 
#11 0xb65c30e1 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4                                                              
No symbol table info available.                                                                                                                 
#12 0xb65c3d65 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4                                                     
No symbol table info available.                                                                                                                 
#13 0xb65c3f5d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4                                                            
No symbol table info available.                                                                                                                 
#14 0xb65ed99f in ?? () from /usr/lib/libQtCore.so.4                                                                                            
No symbol table info available.                                                                                                                 
#15 0xb5574348 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0                                                                     
No symbol table info available.                                                                                                                 
#16 0xb55779e3 in ?? () from /usr/lib/libglib-2.0.so.0                                                                                          
No symbol table info available.                                                                                                                 
#17 0x0932d6d0 in ?? ()                                                                                                                         
No symbol table info available.                                                                                                                 
#18 0x00000000 in ?? ()                                                                                                                         
No symbol table info available.           

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/349

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 24 Jan 2009 11:19:10**
merged with 347, the problems seems identical

---

Resolution: none → duplicate
Status: new → closed
