### ISSUE TITLE
Crash while closing channels/servers windows

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#372]
**Reported by wodim on 22 Feb 2009 19:55:17 UTC**

```
#0  0xb7005f63 in QWidget::ensurePolished () from /usr/lib/libQtGui.so.4
No symbol table info available.
#1  0xb700612e in QWidget::showMaximized () from /usr/lib/libQtGui.so.4
No symbol table info available.
#2  0x081777bf in KviMdiChild::maximize (this=0xbd02bf8) at /home/egns/kvirc4/src/kvirc/ui/kvi_mdichild.cpp:235
No locals.
#3  0x0827bacc in KviFrame::qt_metacall (this=0x98f77f8, _c=QMetaObject::InvokeMetaMethod, _id=22, _a=0xb2085d0) at /home/egns/kvirc4/release/src/kvirc/ui/moc_kvi_frame.cxx:129
No locals.
#4  0xb6a1069b in QMetaCallEvent::placeMetaCall () from /usr/lib/libQtCore.so.4
No symbol table info available.
#5  0xb6a12241 in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#6  0xb70126d6 in QWidget::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#7  0xb73150f7 in QMainWindow::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#8  0xb657d997 in KMainWindow::event () from /usr/lib/libkdeui.so.5
No symbol table info available.
#9  0xb6fc0aec in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
#10 0xb6fc6fba in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#11 0xb6494c9d in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#12 0xb6a03f31 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#13 0xb6a04889 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0xb6a04a1d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0xb6a2a94f in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0x00000000 in ?? ()
No symbol table info available.
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/372

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 23 Feb 2009 17:24:59**
it should have been fixed in r3096 , please test

---

Resolution: none → fixed
Status: new → closed
