### ISSUE TITLE
crash on exit

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#375]
**Reported by dessa on 24 Feb 2009 02:36:41 UTC**
r3095, qt 4.5 rc1 (it used to happen on 4.4.2 too, just got a valid backtrace by now)

``````
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7febf3042750 (LWP 3651)]     
0x00007febf230a868 in QTreeModel::index (this=0x228b640, item=0x219ed80, column=0) at itemviews/qtreewidget.cpp:235
235     itemviews/qtreewidget.cpp: No such file or directory.                                                      
        in itemviews/qtreewidget.cpp                                                                               
(gdb) bt full                                                                                                      
#0  0x00007febf230a868 in QTreeModel::index (this=0x228b640, item=0x219ed80, column=0)                             
    at itemviews/qtreewidget.cpp:235                                                                               
        par = (const QTreeWidgetItem *) 0x210daf0                                                                  
        row = <value optimized out>                                                                                
        guess = <value optimized out>                                                                              
#1  0x00007febf230aa98 in QTreeModel::parent (this=0x228b640, child=<value optimized out>)                         
    at itemviews/qtreewidget.cpp:293                                                                               
        itm = (QTreeWidgetItem *) 0x210daf0                                                                        
#2  0x00007febf22d9289 in QTreeView::indexRowSizeHint (this=0x2123b20, index=@0x477e2e0)                           
    at ../../include/QtCore/../../src/corelib/kernel/qabstractitemmodel.h:364                                      
        start = <value optimized out>                                                                              
        end = <value optimized out>                                                                                
        count = 1                                                                                                  
        parent = {r = 36222528, c = 0, p = 0x7febf1454eb3, m = 0x2296d80}                                          
        height = <value optimized out>                                                                             
        option = {<QStyleOptionViewItemV3> = {<QStyleOptionViewItemV2> = {<QStyleOptionViewItem> = {<QStyleOption> = {version = -83343344, type = 32767, state = {i = -247011198}, direction = 32747, rect = {x1 = 41, y1 = 0,          
            x2 = -83343456, y2 = 32767}, fontMetrics = {d = 0x7ffffb084790}, palette = {static staticMetaObject = { 
              d = {superdata = 0x0, stringdata = 0x7febf23f8a00 "QPalette", data = 0x7febf23f8b40,                  
                extradata = 0x0}}, d = 0x7ffffb0847c0, current_group = 0, resolve_mask = 4}}, displayAlignment = {  
          i = 35025968}, decorationAlignment = {i = 0}, textElideMode = 6, decorationPosition = 6,                  
        decorationSize = {wd = 35080608, ht = 0}, font = {static staticMetaObject = {d = {superdata = 0x0,          
              stringdata = 0x7febf23f98e0 "QFont", data = 0x7febf23f99a0, extradata = 0x0}}, d = 0x1e5c770,         
          resolve_mask = 4211624528}, showDecorationSelected = false}, features = {i = 0}}, locale = {              
      static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7febf14f4840 "QLocale",                       
          data = 0x7febf14f5800, extradata = 0x0}}, {v = 0x2fc5f20, p = {index = 24352, numberOptions = 764```,     
    widget = 0x21749a0}, index = {r = 6, c = 1, p = 0x2fc5bd0, m = 0x7ffffb0848c0}, checkState = 31836104, icon = { 
    d = 0x2fc5bd0}, text = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 27054},       
      alloc = 0, size = 0, data = 0x8cabfa, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,             
      capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 236}, alloc = 0,           
      size = 0, data = 0x7febf172f81a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0,    
      reserved = 0, array = {0}}, d = 0x0, static codecForCStrings = 0x1e77940}, viewItemPosition = 35080608,       
  backgroundBrush = {d = 0x21749a0}}                                                                                
#3  0x00007febf22d98c2 in QTreeViewPrivate::itemHeight (this=0x231d6e0, item=2) at itemviews/qtreeview.cpp:3162     
        height = 0                                                                                                  
---Type <return> to continue, or q <return> to quit---                                                              
#4  0x00007febf22ddd95 in QTreeView::verticalOffset (this=0x2123b20) at itemviews/qtreeview.cpp:2014                
        i = 2                                                                                                       
        offset = 54                                                                                                 
        d = (const QTreeViewPrivate * const) 0x231d6e0                                                              
#5  0x00007febf22aa940 in QAbstractItemView::setCurrentIndex (this=0x2123b20, index=@0x7ffffb084a50)                
    at ../../include/QtGui/private/../../../src/gui/itemviews/qabstractitemview_p.h:221                             
        command = {i = 35}                                                                                          
        d = (QAbstractItemViewPrivate * const) 0x231d6e0                                                            
#6  0x00007febf22ab81d in QAbstractItemView::rowsAboutToBeRemoved (this=0x2123b20, parent=@0x7ffffb084e30,          
    start=8, end=8) at itemviews/qabstractitemview.cpp:2976                                                         
        row = -231679940                                                                                            
        next = {r = 9, c = 0, p = 0x32398f0, m = 0x228b640}                                                         
        d = (QAbstractItemViewPrivate * const) 0x231d6e0                                                            
        current = {r = 8, c = 0, p = 0x2fc5a80, m = 0x228b640}                                                      
#7  0x00007febf22ac427 in QAbstractItemView::qt_metacall (this=0x2123b20, _c=QMetaObject::InvokeMetaMethod,         
    _id=<value optimized out>, _a=0x7ffffb084d80) at .moc/release-shared/moc_qabstractitemview.cpp:228              
No locals.                                                                                                          
#8  0x00007febf22e3ad1 in QTreeView::qt_metacall (this=0x7ffffb084820, _c=36222528, _id=34659056, _a=0x0)           
    at .moc/release-shared/moc_qtreeview.cpp:124                                                                    
No locals.                                                                                                          
#9  0x00007febf23117e9 in QTreeWidget::qt_metacall (this=0x7ffffb084820, _c=36222528, _id=34659056, _a=0x0)         
    at .moc/release-shared/moc_qtreewidget.cpp:123                                                                  
No locals.                                                                                                          
#10 0x000000000061d522 in KviTreeWindowListTreeWidget::qt_metacall (this=0x7ffffb084820, _c=36222528,               
    _id=34659056, _a=0x0)                                                                                           
    at /home/portage/net-irc/kvirc-9999/work/kvirc_build/src/kvirc/ui/moc_kvi_windowlist_tree.cxx:123               
No locals.                                                                                                          
#11 0x00007febf146e7e0 in QMetaObject::activate (sender=0x228b640, from_signal_index=<value optimized out>,         
    to_signal_index=10, argv=0x0) at kernel/qobject.cpp:3052                                                        
        method = 49                                                                                                 
        currentSender = {sender = 0x228b640, signal = 10, ref = 1}                                                  
        previousSender = (QObjectPrivate::Sender *) 0x0                                                             
        count = 4                                                                                                   
        signal = 10                                                                                                 
        empty_argv = {0x0}                                                                                          
---Type <return> to continue, or q <return> to quit---                                                              
        locker = {{mtx = 0x1e5c7c8, val = 31836104}}                                                                
        currentThreadData = (QThreadData *) 0x1e5c770                                                               
        connectionLists = (QObjectConnectionListVector *) 0x215b990                                                 
#12 0x00007febf149c446 in QAbstractItemModel::rowsAboutToBeRemoved (this=0x7ffffb084820,                            
    _t1=<value optimized out>, _t2=8, _t3=8) at .moc/release-shared/moc_qabstractitemmodel.cpp:166                  
        _a = {0x0, 0x7ffffb084e30, 0x7ffffb084d7c, 0x7ffffb084d78}                                                  
#13 0x00007febf1457761 in QAbstractItemModel::beginRemoveRows (this=0x228b640, parent=@0x7ffffb084e30, first=8,     
    last=8) at kernel/qabstractitemmodel.cpp:2108                                                                   
        d = (QAbstractItemModelPrivate * const) 0x21b07f0                                                           
#14 0x00007febf230d9ec in QTreeModel::beginRemoveItems (this=0x228b640, parent=0x2296d80, row=8, count=1)           
    at itemviews/qtreewidget.cpp:805                                                                                
No locals.                                                                                                          
#15 0x00007febf230e0b9 in ~QTreeWidgetItem (this=0x2fc5a80) at itemviews/qtreewidget.cpp:1479                       
        i = 34659056                                                                                                
        model = (class QTreeModel *) 0x228b640                                                                      
        wasSkipSort = false                                                                                         
#16 0x000000000056c984 in ~KviTreeWindowListItem (this=0x2fc5a80)                                                   
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_windowlist_tree.cpp:86                     
No locals.                                                                                                          
#17 0x000000000056aac7 in KviTreeWindowList::removeItem (this=<value optimized out>, it=0x228b640)                  
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_windowlist_tree.cpp:450                    
No locals.                                                                                                          
#18 0x000000000056833e in ~KviWindow (this=0x7ffffb084820)                                                          
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_window.cpp:142                             
No locals.                                                                                                          
#19 0x000000000050e4aa in ~KviChannel (this=0x2fa48a0)                                                              
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_channel.cpp:231                            
No locals.                                                                                                          
#20 0x000000000054203c in ~KviMdiChild (this=0x2fc6130)                                                             
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_mdichild.cpp:109                           
No locals.                                                                                                          
#21 0x0000000000543731 in KviMdiManager::destroyChild (this=0x212cf80, lpC=0x2fc6130, bFocusTopChild=true)          
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_mdimanager.cpp:182                         
No locals.                                                                                                          
#22 0x000000000051f119 in KviFrame::closeWindow (this=0x21897f0, wnd=0x2fa48a0)                                     
---Type <return> to continue, or q <return> to quit---                                                              
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_frame.cpp:527                              
No locals.                                                                                                          
#23 0x00000000005fcc5e in KviIrcContext::closeAllDeadChannels (this=0x227d6e0)                                      
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/kvi_irccontext.cpp:163                     
        c = (class KviChannel *) 0x210daf0                                                                          
#24 0x00000000005fcd3b in ~KviIrcContext (this=0x227d6e0)                                                           
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/kvi_irccontext.cpp:120                     
No locals.                                                                                                          
#25 0x00000000005163fe in ~KviConsole (this=0x22878c0)                                                              
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_console.cpp:193                            
No locals.                                                                                                          
#26 0x000000000054203c in ~KviMdiChild (this=0x2266780)                                                             
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_mdichild.cpp:109                           
No locals.                                                                                                          
#27 0x0000000000543731 in KviMdiManager::destroyChild (this=0x212cf80, lpC=0x2266780, bFocusTopChild=true)          
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_mdimanager.cpp:182                         
No locals.                                                                                                          
#28 0x000000000051f119 in KviFrame::closeWindow (this=0x21897f0, wnd=0x22878c0)                                     
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_frame.cpp:527                              
No locals.                                                                                                          
#29 0x000000000051fc20 in ~KviFrame (this=0x21897f0)                                                                
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_frame.cpp:214                              
No locals.                                                                                                          
#30 0x00007febf146bbb5 in QObject::event (this=0x21897f0, e=0x228b640) at kernel/qobject.cpp:1087                   
No locals.                                                                                                          
#31 0x00007febf1ea1677 in QWidget::event (this=0x21897f0, event=0x3a0ac90) at kernel/qwidget.cpp:7908               
No locals.                                                                                                          
#32 0x00007febf21c74e1 in QMainWindow::event (this=0x21897f0, event=0x3a0ac90) at widgets/qmainwindow.cpp:1391      
        d = (QMainWindowPrivate * const) 0x21fa8c0                                                                  
#33 0x00007febf1e5d61d in QApplicationPrivate::notify_helper (this=0x1e8cb80, receiver=0x21897f0, e=0x3a0ac90)      
    at kernel/qapplication.cpp:4051                                                                                 
        consumed = <value optimized out>                                                                            
#34 0x00007febf1e651ea in QApplication::notify (this=0x1e8c6e0, receiver=0x21897f0, e=0x3a0ac90)                    
    at kernel/qapplication.cpp:4016                                                                                 
        res = <value optimized out>
---Type <return> to continue, or q <return> to quit---
#35 0x00007febf0b0f434 in KApplication::notify () from /usr/kde/4.2/lib64/libkdeui.so.5
No symbol table info available.
#36 0x00007febf145e67e in QCoreApplication::notifyInternal (this=0x1e8c6e0, receiver=0x21897f0, event=0x3a0ac90)
    at kernel/qcoreapplication.cpp:590
        result = false
        cbdata = {0x21897f0, 0x3a0ac90, 0x7ffffb0858ef}
        threadData = (QThreadData *) 0x1e5c770
        returnValue = <value optimized out>
#37 0x00007febf145ee78 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=52, data=0x1e5c770)
    at kernel/qcoreapplication.h:208
        e = (class QEvent *) 0x3a0ac90
        r = (class QObject *) 0x0
        locker = {{mtx = 0x1e5c7b0, val = 31836080}}
        startOffset = 1
        i = (int &) @0x7ffffb08596c: 1
#38 0x00007febf145f11a in QCoreApplication::exec () at kernel/qcoreapplication.cpp:879
        threadData = <value optimized out>
        eventLoop = {<QObject> = {_vptr.QObject = 0x7febf172dff0, static staticMetaObject = {d = {superdata = 0x0,
        stringdata = 0x7febf14e5fe0 "QObject", data = 0x7febf14e6080, extradata = 0x7febf1727320}},
    d_ptr = 0x28ef9a0, static staticQtMetaObject = {d = {superdata = 0x0, stringdata = 0x7febf14ef880 "Qt",
        data = 0x7febf14f2760, extradata = 0x0```, static staticMetaObject = {d = {superdata = 0x8ca7e0,
      stringdata = 0x7febf14f7580 "QEventLoop", data = 0x7febf14f75a0, extradata = 0x0```
        returnCode = 0
#39 0x00000000006043b5 in main (argc=1, argv=0x7ffffb085c58)
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/kvi_main.cpp:417
        a = {argc = 1, argv = 0x7ffffb085c58, configFile = 0x0, createFile = false, bForceNewSession = false,
  bShowPopup = false, bShowSplashScreen = true, bExecuteCommandAndClose = false,
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x1e76600 "", m_len = 0},
  szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x1e76620 "", m_len = 0}}
        retCode = <value optimized out>
        theApp = (class KviApp *) 0x1e8c6e0
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x1feaf90 "", m_len = 0}
        retVal = <value optimized out>
``````

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/375

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Feb 2009 11:55:21**
we were missing some sanity checking in the involved code, they have been added in r3098 so the issue should be fixed

---

Resolution: none → fixed
Status: new → closed
