### ISSUE TITLE
Crash when opening banlist in a disconnected context

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#389]
**Reported by Andrey on 02 Mar 2009 06:07:43 UTC**
Join a channel, disconnect, open the banlist for that channel.

```
#0  0x08123536 in KviIrcConnection::userInfo (this=0x0) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/kernel/kvi_ircconnection.h:240
#1  0x0815ddfb in KviMaskEditor (this=0x9b114d8, par=0x9b203e8, button=0x9b23788, maskList=0x9b14e90, flag=98 'b')
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_maskeditor.cpp:135
#2  0x081208f8 in KviChannel::toggleEditor (this=0x9337048, ppEd=0x93370d8, ppBtn=0x93370c8, l=0x9b14e90, cFlag=98 'b',
    pcEdName=0x826d0f3 "ban_editor") at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_channel.cpp:520
#3  0x08120a7f in KviChannel::toggleBanEditor (this=0x9337048) at /home/wrar/tmp/BUILD/kvirc4-4.0.0/src/kvirc/ui/kvi_channel.cpp:460
#4  0x08262f03 in KviChannel::qt_metacall (this=0x9337048, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0xbf826b5c)
    at /home/wrar/tmp/BUILD/kvirc4-4.0.0/BUILD-athlon-alt-linux/src/kvirc/ui/moc_kvi_channel.cxx:87
#5  0x42306667 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#6  0x423067ec in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#7  0x42f6e783 in QAbstractButton::clicked () from /usr/lib/libQtGui.so.4
#8  0x42dc439e in QMdiArea::eventFilter () from /usr/lib/libQtGui.so.4
#9  0x09b23788 in ?? ()
#10 0x00000001 in ?? ()
#11 0x42eb4d5f in QAccessible::updateAccessibility () from /usr/lib/libQtGui.so.4
#12 0x42dc4f5f in QMdiArea::eventFilter () from /usr/lib/libQtGui.so.4
#13 0x09b30dc0 in ?? ()
#14 0x00000000 in ?? ()
```

3.x is also affected.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/389

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 02 Mar 2009 08:51:55**
fix'd in r3115

---

Resolution: none → fixed
Status: new → closed
