### ISSUE TITLE
Crash with no apparent reason

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#392]
**Reported by wodim on 05 Mar 2009 17:05:41 UTC**
Anyway, looking at the backtrace it seems to be related to a channel CTCP PING that I received.

```
Thread 1 (Thread 0xb56a8700 (LWP 4924)):
[KCrash Handler]
#6  QString::isEmpty (this=0xbf9b0858) at /usr/include/QtCore/qstring.h:649
#7  0x081a2ef3 in KviWindow::output (this=0xaf5cfc8, msg_type=29, szFmt=@0xed00b38) at /home/egns/kvirc/src/kvirc/ui/kvi_window.cpp:1311
#8  0x081adda8 in KviServerParser::echoCtcpRequest (this=0xa3d34a0, msg=0xbf9b0ac0) at /home/egns/kvirc/src/kvirc/sparser/kvi_sp_ctcp.cpp:1041
#9  0x081ae8c0 in KviServerParser::parseCtcpRequestPing (this=0xa3d34a0, msg=0xbf9b0ac0) at /home/egns/kvirc/src/kvirc/sparser/kvi_sp_ctcp.cpp:1058
#10 0x081af47e in KviServerParser::parseCtcpRequest (this=0xa3d34a0, msg=0xbf9b0ac0) at /home/egns/kvirc/src/kvirc/sparser/kvi_sp_ctcp.cpp:864
#11 0x081b8c10 in KviServerParser::parseLiteralPrivmsg (this=0xa3d34a0, msg=0xbf9b0ba4) at /home/egns/kvirc/src/kvirc/sparser/kvi_sp_literal.cpp:774
#12 0x081c609d in KviServerParser::parseMessage (this=0xa3d34a0, message=0xed02540 ":bot|shellium!i=balasyum@support.team.at.shellium.org PRIVMSG #shellium :\001PING\001", pConnection=0xb0c49c0)
    at /home/egns/kvirc/src/kvirc/sparser/kvi_sparser.cpp:105
#13 0x0824c6e6 in KviIrcConnection::incomingMessage (this=0xb0c49c0, pcMessage=0xed02540 ":bot|shellium!i=balasyum@support.team.at.shellium.org PRIVMSG #shellium :\001PING\001")
    at /home/egns/kvirc/src/kvirc/kernel/kvi_ircconnection.cpp:1483
#14 0x0825a01d in KviIrcLink::processData (this=0xb9684b0, buffer=0xbf9b0cba "\r\n", iLen=81) at /home/egns/kvirc/src/kvirc/kernel/kvi_irclink.cpp:271
#15 0x0825bec9 in KviIrcSocket::readData (this=0xaff1c78) at /home/egns/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1483
#16 0x08284c4c in KviIrcSocket::qt_metacall (this=0xaff1c78, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0xbf9b116c) at /home/egns/kvirc/release/src/kvirc/kernel/moc_kvi_ircsocket.cxx:76
#17 0xb69b777b in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#18 0xb69b7cd2 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#19 0xb69edcf3 in QSocketNotifier::activated () from /usr/lib/libQtCore.so.4
#20 0xb69be0d7 in QSocketNotifier::event () from /usr/lib/libQtCore.so.4
#21 0xb6f61aec in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#22 0xb6f67eee in QApplication::notify () from /usr/lib/libQtGui.so.4
#23 0xb637bcfd in KApplication::notify () from /usr/lib/libkdeui.so.5
#24 0xb69a5f31 in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#25 0xb69cc837 in ?? () from /usr/lib/libQtCore.so.4
#26 0x0a15e500 in ?? ()
#27 0x0b1094d0 in ?? ()
#28 0xbf9b1510 in ?? ()
#29 0x00000000 in ?? ()
```

I think this bt is useless but anyway I posted it...

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/392

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 06 Mar 2009 10:24:45**
Were you using a localized kvirc? that routine seems to work fine in here, but it is using some QString pointers that gets directly caught from the translations texts (as an optimization).
So maybe a broken translation may be the cause of the crash..

---

Owner: pragmaware → ctrlaltca

**Comment by DarthGandalf** [comment]
**Comment by wodim on 06 Mar 2009 17:30:01**
Sorry, my bad :(
It was a broken "CTCP query from..." translated string.

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 06 Mar 2009 22:09:22**
Resolution: none → worksforme
Status: new → closed
