### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#4]
**Reported by anonymous on 11 Jul 2007 11:12:56 UTC**
Under Gentoo, compiling from source, Kvirc 3.2.5, KDE 3.5.7
After compiling and installation, I can't keep running Kvirc. That's only first messages (hello and basic settings), i've clicked 'Finish' button, and here's the crash:

```
(no debugging symbols found)
Using host libthread_db library "/lib/libthread_db.so.1".
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[Thread debugging using libthread_db enabled]
[New Thread -1239484096 (LWP 2639)]
0xffffe410 in __kernel_vsyscall ()
#0  0xffffe410 in __kernel_vsyscall ()
#1  0xb627a9e0 in nanosleep () from /lib/libc.so.6
#2  0xb627a82b in sleep () from /lib/libc.so.6
#3  0xb77f3d27 in KCrash::startDrKonqi ()
   from /usr/kde/3.5/lib/libkdecore.so.4
#4  0x00000001 in ?? ()
#5  0xbfced278 in ?? ()
#6  0x08330b48 in ?? ()
#7  0x0000007d in ?? ()
#8  0xbfcec1b0 in ?? ()
#9  0xbfcee1ba in ?? ()
#10 0xbfcec1b0 in ?? ()
#11 0x00000000 in ?? ()
```

... from KDE Crash Handler
for addition i can tell, that's no my first Kvirc crash. Some time ago I've installed it and I took this same crash (it was another machine, but it was Gentoo too).

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/4

**Comment by DarthGandalf** [comment]
**Comment by Lunate on 30 Jul 2007 03:23:04**
I have the same problem (but I'm using Gnome). When I click finish in the welcome/configuration screen, the program crashes with a Segmentation Fault message. 

Linux laptop 2.6.22.1 #12 Sat Jul 28 16:50:52 CEST 2007 i686 AMD Turion(tm) 64 X2 Mobile Technology TL-56 AuthenticAMD GNU/Linux

gcc version 4.1.2 (Gentoo 4.1.2 p1.0.1)

KVIrc 3.2.5 'Anomalies'
Sources date: 20060910

**Comment by DarthGandalf** [comment]
**Modified by anonymous on 12 Nov 2007 18:56:07**
Component: component1 → core

**Comment by DarthGandalf** [comment]
**Comment by mren on 27 Feb 2008 22:28:08**
If this problem still exists w/ latest sources please reopen.

---

Priority: Major → Crash
Resolution: none → worksforme
Status: new → closed
