### ISSUE TITLE
I/O traffic graph causes freeze

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#409]
**Reported by anonymous on 25 Mar 2009 23:48:29 UTC**
hi,

kvirc becomes nonreactive when displaying the graph, 100% cpu.

second try crashed when the graph was working but closing caused this:

```
Anwendung: KVIrc (p), Signal SIGSEGV
Using host libthread_db library "/lib/libthread_db.so.1".
0x00007f889f9df7e1 in nanosleep () from /lib64/libc.so.6
[Current thread is 0 (LWP 16714)]

Thread 2 (Thread 0x4160a950 (LWP 16741)):
#0  0x00007f889fa05146 in poll () from /lib64/libc.so.6
#1  0x00007f889dc6f448 in ?? () from /lib/libresolv.so.2
#2  0x00007f889dc6e5f9 in __libc_res_nquery () from /lib/libresolv.so.2
#3  0x00007f889dc6e817 in ?? () from /lib/libresolv.so.2
#4  0x00007f889dc6ea9a in __libc_res_nsearch () from /lib/libresolv.so.2
#5  0x00007f88976bf46f in _nss_dns_gethostbyname3_r () from /lib64/libnss_dns.so.2
#6  0x00007f88976bf6e4 in _nss_dns_gethostbyname2_r () from /lib64/libnss_dns.so.2
#7  0x00007f889fa2104b in gethostbyname2_r () from /lib64/libc.so.6
#8  0x00007f889f9f9720 in ?? () from /lib64/libc.so.6
#9  0x00007f889f9fa4b0 in getaddrinfo () from /lib64/libc.so.6
#10 0x00007f88a543e92c in KviDnsThread::run () from /usr/lib64/libkvilib4.so.4
#11 0x00007f88a54483c6 in KviThread::internalThreadRun_doNotTouchThis () from /usr/lib64/libkvilib4.so.4
#12 0x00007f88a54483e9 in ?? () from /usr/lib64/libkvilib4.so.4
#13 0x00007f88a64b7047 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f889fa0d28d in clone () from /lib64/libc.so.6
#15 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f88a6ab7720 (LWP 16714)):
[KCrash Handler]
#5  0x00007f88a4a4679c in QTextEngine::itemize () from /usr/lib64/qt4/libQtGui.so.4
#6  0x00007f88a4a4a76c in QTextEngine::width () from /usr/lib64/qt4/libQtGui.so.4
#7  0x00007f88a4a4aaa4 in QTextEngine::elidedText () from /usr/lib64/qt4/libQtGui.so.4
#8  0x00007f88a4a274c9 in QFontMetrics::elidedText () from /usr/lib64/qt4/libQtGui.so.4
#9  0x00007f88a4bfb06d in ?? () from /usr/lib64/qt4/libQtGui.so.4
#10 0x00007f88a4c01a11 in QMdiSubWindow::mouseReleaseEvent () from /usr/lib64/qt4/libQtGui.so.4
#11 0x00007f88a4891dd0 in QWidget::event () from /usr/lib64/qt4/libQtGui.so.4
#12 0x00007f88a4c023db in QMdiSubWindow::event () from /usr/lib64/qt4/libQtGui.so.4
#13 0x00007f88a4849c5e in QApplicationPrivate::notify_helper () from /usr/lib64/qt4/libQtGui.so.4
#14 0x00007f88a4851606 in QApplication::notify () from /usr/lib64/qt4/libQtGui.so.4
#15 0x00007f88a0c1b2db in KApplication::notify () from /usr/kde/live/lib64/libkdeui.so.5
#16 0x00007f88a1f486b3 in QCoreApplication::notifyInternal () from /usr/lib64/qt4/libQtCore.so.4
#17 0x00007f88a484ee3a in QApplicationPrivate::sendMouseEvent () from /usr/lib64/qt4/libQtGui.so.4
#18 0x00007f88a48a76ea in ?? () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007f88a48a6200 in QApplication::x11ProcessEvent () from /usr/lib64/qt4/libQtGui.so.4
#20 0x00007f88a48c9a73 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007f88a19794d2 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#22 0x00007f88a197c7b5 in ?? () from /usr/lib64/libglib-2.0.so.0
#23 0x00007f88a197ccbb in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#24 0x00007f88a1f6d38e in QEventDispatcherGlib::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#25 0x00007f88a48c988f in ?? () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007f88a1f47aa5 in QEventLoop::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#27 0x00007f88a1f47c26 in QEventLoop::exec () from /usr/lib64/qt4/libQtCore.so.4
#28 0x00007f88a1f49a69 in QCoreApplication::exec () from /usr/lib64/qt4/libQtCore.so.4
#29 0x00000000006164c9 in main ()
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/409

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 26 Mar 2009 08:32:25**
The crash backtrace seems related to a bug patched in r3159.

---

Resolution: none → worksforme
Status: new → closed
