### ISSUE TITLE
crash after disconnecting

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#421]
**Reported by mren on 14 Apr 2009 18:35:30 UTC**
I disconnected a server in one context but an other context to the same server got (also?) disconnected. After pressing the connect button for that wrong disconencted contex KVIrc (r3174) crashed, here the backtrace:

```
Anwendung: KVIrc (/home/mr), Signal SIGSEGV
0x00007f8553798aa1 in nanosleep () from /lib64/libc.so.6
[Current thread is 0 (LWP 10755)]

Thread 2 (Thread 0x427c7950 (LWP 14600)):
#0  0x00007f85537bfa62 in select () from /lib64/libc.so.6
#1  0x00007f8555e5463e in ?? () from /usr/lib64/qt4/libQtCore.so.4
#2  0x00007f8555da6f80 in ?? () from /usr/lib64/qt4/libQtCore.so.4
#3  0x00007f855ae57097 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f85537c5ccd in clone () from /lib64/libc.so.6
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f855b564760 (LWP 10755)):
[KCrash Handler]
#5  0x00000000004fec0a in QBasicAtomicInt::ref ()
#6  0x00000000004ff4a6 in QString::QString ()
#7  0x000000000050b269 in QList<QString>::node_copy ()
#8  0x000000000050b491 in QList<QString>::detach_helper ()
#9  0x000000000050b6cd in QList<QString>::operator= ()
#10 0x000000000051ca23 in QStringList::operator= ()
#11 0x00007f8559db9934 in KviServerReconnectInfo::KviServerReconnectInfo () from /usr/lib64/libkvilib4.so.4
#12 0x00007f8559dba4f8 in KviServer::KviServer () from /usr/lib64/libkvilib4.so.4
#13 0x000000000065b308 in KviIrcConnectionTarget::KviIrcConnectionTarget ()
#14 0x000000000065f9b7 in KviIrcContext::connectToCurrentServer ()
#15 0x000000000065fd3a in KviIrcContext::connectButtonClicked ()
#16 0x0000000000649ce5 in KviIrcContext::connectOrDisconnect ()
#17 0x0000000000646956 in KviConnectAction::activate ()
#18 0x000000000068e6a7 in KviAction::qt_metacall ()
#19 0x000000000068f2b9 in KviConnectAction::qt_metacall ()
#20 0x00007f8555e7d95d in QMetaObject::activate () from /usr/lib64/qt4/libQtCore.so.4
#21 0x00007f8558be47e7 in QAbstractButton::clicked () from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007f85589be86b in ?? () from /usr/lib64/qt4/libQtGui.so.4
#23 0x00007f85589bff35 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#24 0x00007f85589c013d in QAbstractButton::mouseReleaseEvent () from /usr/lib64/qt4/libQtGui.so.4
#25 0x00007f8558a6c4ca in QToolButton::mouseReleaseEvent () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007f8558743b3e in QWidget::event () from /usr/lib64/qt4/libQtGui.so.4
#27 0x00007f85589bf47f in QAbstractButton::event () from /usr/lib64/qt4/libQtGui.so.4
#28 0x00007f8558a6c0b9 in QToolButton::event () from /usr/lib64/qt4/libQtGui.so.4
#29 0x00007f85586ff40e in QApplicationPrivate::notify_helper () from /usr/lib64/qt4/libQtGui.so.4
#30 0x00007f8558705dd6 in QApplication::notify () from /usr/lib64/qt4/libQtGui.so.4
#31 0x00007f8554bb3f0b in KApplication::notify () from /usr/lib64/libkdeui.so.5
#32 0x00007f8555e6de54 in QCoreApplication::notifyInternal () from /usr/lib64/qt4/libQtCore.so.4
#33 0x00007f85587079aa in QApplicationPrivate::sendMouseEvent () from /usr/lib64/qt4/libQtGui.so.4
#34 0x00007f855875718a in ?? () from /usr/lib64/qt4/libQtGui.so.4
#35 0x00007f8558755c35 in QApplication::x11ProcessEvent () from /usr/lib64/qt4/libQtGui.so.4
#36 0x00007f8558777ae3 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#37 0x00007f855589ffd1 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#38 0x00007f85558a36ad in ?? () from /usr/lib64/libglib-2.0.so.0
#39 0x00007f85558a386b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#40 0x00007f8555e91afe in QEventDispatcherGlib::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#41 0x00007f85587778ff in ?? () from /usr/lib64/qt4/libQtGui.so.4
#42 0x00007f8555e6d205 in QEventLoop::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#43 0x00007f8555e6d386 in QEventLoop::exec () from /usr/lib64/qt4/libQtCore.so.4
#44 0x00007f8555e6f47e in QCoreApplication::exec () from /usr/lib64/qt4/libQtCore.so.4
#45 0x000000000066b117 in main ()
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/421

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 24 May 2009 12:22:26**
merged with #450

---

Resolution: none → duplicate
Status: new → closed
