### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#436]
**Reported by acky_max on 05 May 2009 14:31:25 UTC**
Applicazione: KVIrc (kvirc), segnale SIGSEGV
[Current thread is 1 (Thread 0xb8010770 (LWP 13439))]

Thread 1 (Thread 0xb8010770 (LWP 13439)):
[KCrash Handler]
#6  0x08119e68 in KviIrcView::getLinkUnderMouse ()
#7  0x08120799 in KviIrcView::mouseMoveEvent ()
#8  0x02eff7ad in QWidget::event () from /usr/lib/libQtGui.so.4
#9  0x02ea8cec in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#10 0x02eb1941 in QApplication::notify () from /usr/lib/libQtGui.so.4
#11 0x03b7217d in KApplication::notify () from /usr/lib/libkdeui.so.5
#12 0x0283d75b in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#13 0x02eb09ae in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
#14 0x02f2055e in ?? () from /usr/lib/libQtGui.so.4
#15 0x02f1ebdd in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#16 0x02f48f6a in ?? () from /usr/lib/libQtGui.so.4
#17 0x002c7258 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#18 0x002ca903 in ?? () from /lib/libglib-2.0.so.0
#19 0x002caac1 in g_main_context_iteration () from /lib/libglib-2.0.so.0
#20 0x02869188 in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#21 0x02f48665 in ?? () from /usr/lib/libQtGui.so.4
#22 0x0283bd8a in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#23 0x0283c1ca in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#24 0x0283e679 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#25 0x02ea8b67 in QApplication::exec () from /usr/lib/libQtGui.so.4
#26 0x0825ccb3 in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/436

**Comment by DarthGandalf** [comment]
**Comment by mren on 05 May 2009 18:56:19**
Please state what you have done right before the crash and which version you're using and on which os you are.

Changed priority to crash.

---

Priority: Normal → Crash

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 05 May 2009 19:33:10**
.. and a backtrace with debug symbols enabled would be nice :)

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 11 May 2009 15:11:59**
in the meanwhile, closing down this ticket for pointlessness

---

Resolution: none → invalid
Status: new → closed
