### ISSUE TITLE
Crash/Freeze without Internet

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#440]
**Reported by ambossarm on 07 May 2009 22:57:37 UTC**
If I have no Internet Connection and KVIrc runs it goes black ("dead").

If I run it without gdb I have to kill it after that. If I run it within gdb attached after KVIrc started and I enter "quit" in gdb the KVIrc window comes back to live.

On the "Server Status Window" I see only a single try to reconnect if the window goes black, so it happens "fast"

I disconnected my Internet Connection at 0:20 and the first (and only) reconnect try was at 0:41

Backtrace:

```
Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fed7b015750 (LWP 17055)]
0x00007fed7a6bce5b in write () from /lib/libpthread.so.0
(gdb) backtrace full
#0  0x00007fed7a6bce5b in write () from /lib/libpthread.so.0
No symbol table info available.
#1  0x00007fed7405cf47 in sock_write (b=0x37d4740, 
    in=0x37dfdb0 "\025\003\001", inl=37) at bss_sock.c:155
    ret = <value optimized out>
#2  0x00007fed7405af8e in BIO_write (b=0x37d4740, in=0x37dfdb0, inl=37)
    at bio_lib.c:247
    i = <value optimized out>
    cb = (long int (*)(BIO *, int, const char *, int, long int, 
    long int)) 0
#3  0x00007fed74349324 in ssl3_write_pending (s=0x37d4ba0, 
    type=<value optimized out>, buf=<value optimized out>, 
    len=<value optimized out>) at s3_pkt.c:741
    i = -32
#4  0x00007fed74349803 in ssl3_dispatch_alert (s=0x15) at s3_pkt.c:1283
    i = <value optimized out>
    cb = <value optimized out>
#5  0x00007fed74346c1a in ssl3_shutdown (s=0x15) at s3_lib.c:2418
No locals.
#6  0x00007fed7990bd91 in KviSSL::shutdown ()
   from /usr/local/lib/libkvilib4.so.4
No locals.
#7  0x00007fed7990bdcd in KviSSL::~KviSSL ()
   from /usr/local/lib/libkvilib4.so.4
No locals.
#8  0x0000000000654e2e in KviSSLMaster::freeSSL ()
No locals.
#9  0x00000000006342ba in KviIrcSocket::reset ()
No locals.
#10 0x0000000000634dac in KviIrcSocket::readData ()
No locals.
#11 0x00000000006629be in KviIrcSocket::qt_metacall ()
No locals.
#12 0x00007fed765721f2 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
No symbol table info available.
#13 0x00007fed765a944e in QSocketNotifier::activated ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0x00007fed76576e53 in QSocketNotifier::event ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0x00007fed7796683d in QApplicationPrivate::notify_helper ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#16 0x00007fed7796ea2a in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#17 0x00007fed7510f26b in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#18 0x00007fed7655c75c in QCoreApplication::notifyInternal ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#19 0x00007fed765860e9 in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#20 0x00007fed7248520a in IA__g_main_context_dispatch (context=0x1bb0920)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:1814
No locals.
#21 0x00007fed724888e0 in g_main_context_iterate (context=0x1bb0920, block=1, 
    dispatch=1, self=<value optimized out>)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2448
    max_priority = 2147483647
    timeout = 98
    some_ready = 1
    nfds = 15
    allocated_nfds = <value optimized out>
    fds = (GPollFD *) 0x3cd4b60
    __PRETTY_FUNCTION__ = "g_main_context_iterate"
#22 0x00007fed72488a7c in IA__g_main_context_iteration (context=0x1bb0920, 
    may_block=1) at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2511
    retval = <value optimized out>
#23 0x00007fed76585e6f in QEventDispatcherGlib::processEvents ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#24 0x00007fed779fec9f in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#25 0x00007fed7655b002 in QEventLoop::processEvents ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#26 0x00007fed7655b3cd in QEventLoop::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#27 0x00007fed7655d694 in QCoreApplication::exec ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#28 0x000000000063b8b1 in main ()
No locals.
(gdb) info registers
rax            0xffffffffffffffe0   -32
rbx            0x25 37
rcx            0xffffffffffffffff   -1
rdx            0x25 37
rsi            0x37dfdb0    58588592
rdi            0x15 21
rbp            0x37d4740    0x37d4740
rsp            0x7fff8305c870   0x7fff8305c870
r8             0x615a   24922
r9             0x8c031963   2349013347
r10            0x5325c2ad   1394983597
r11            0x202    514
r12            0x37dfdb0    58588592
r13            0x37dfdb0    58588592
r14            0x0  0
r15            0x7fff8305ced0   140735391583952
rip            0x7fed7a6bce5b   0x7fed7a6bce5b <write+75>
eflags         0x202    [ IF ]
cs             0x33 51
ss             0x2b 43
ds             0x0  0
es             0x0  0
fs             0x0  0
gs             0x0  0
fctrl          0x37f    895
fstat          0x20 32
ftag           0xffff   65535
fiseg          0x7fed   32749
fioff          0x7505139e   1963266974
foseg          0x7fff   32767
fooff          0x8305bdb8   -2096775752
fop            0x30f    783
mxcsr          0x1fa0   [ PE IM DM ZM OM UM PM ]
(gdb) thread apply all backtrace

Thread 2 (Thread 0x7fed5cec0950 (LWP 17070)):
#0  0x00007fed73d09742 in select () from /lib/libc.so.6
#1  0x00007fed7653af06 in ?? () from /usr/lib/libQtCore.so.4
#2  0x00007fed76473952 in ?? () from /usr/lib/libQtCore.so.4
#3  0x00007fed7a6b63ba in start_thread () from /lib/libpthread.so.0
#4  0x00007fed73d10fcd in clone () from /lib/libc.so.6
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fed7b015750 (LWP 17055)):
#0  0x00007fed7a6bce5b in write () from /lib/libpthread.so.0
#1  0x00007fed7405cf47 in sock_write (b=0x37d4740, 
    in=0x37dfdb0 "\025\003\001", inl=37) at bss_sock.c:155
#2  0x00007fed7405af8e in BIO_write (b=0x37d4740, in=0x37dfdb0, inl=37)
    at bio_lib.c:247
#3  0x00007fed74349324 in ssl3_write_pending (s=0x37d4ba0, 
    type=<value optimized out>, buf=<value optimized out>, 
    len=<value optimized out>) at s3_pkt.c:741
#4  0x00007fed74349803 in ssl3_dispatch_alert (s=0x15) at s3_pkt.c:1283
#5  0x00007fed74346c1a in ssl3_shutdown (s=0x15) at s3_lib.c:2418
#6  0x00007fed7990bd91 in KviSSL::shutdown ()
   from /usr/local/lib/libkvilib4.so.4
#7  0x00007fed7990bdcd in KviSSL::~KviSSL ()
   from /usr/local/lib/libkvilib4.so.4
#8  0x0000000000654e2e in KviSSLMaster::freeSSL ()
#9  0x00000000006342ba in KviIrcSocket::reset ()
#10 0x0000000000634dac in KviIrcSocket::readData ()
#11 0x00000000006629be in KviIrcSocket::qt_metacall ()
#12 0x00007fed765721f2 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#13 0x00007fed765a944e in QSocketNotifier::activated ()
   from /usr/lib/libQtCore.so.4
#14 0x00007fed76576e53 in QSocketNotifier::event ()
   from /usr/lib/libQtCore.so.4
#15 0x00007fed7796683d in QApplicationPrivate::notify_helper ()
   from /usr/lib/libQtGui.so.4
#16 0x00007fed7796ea2a in QApplication::notify () from /usr/lib/libQtGui.so.4
#17 0x00007fed7510f26b in KApplication::notify () from /usr/lib/libkdeui.so.5
#18 0x00007fed7655c75c in QCoreApplication::notifyInternal ()
   from /usr/lib/libQtCore.so.4
#19 0x00007fed765860e9 in ?? () from /usr/lib/libQtCore.so.4
#20 0x00007fed7248520a in IA__g_main_context_dispatch (context=0x1bb0920)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:1814
#21 0x00007fed724888e0 in g_main_context_iterate (context=0x1bb0920, block=1, 
    dispatch=1, self=<value optimized out>)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2448
#22 0x00007fed72488a7c in IA__g_main_context_iteration (context=0x1bb0920, 
    may_block=1) at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2511
#23 0x00007fed76585e6f in QEventDispatcherGlib::processEvents ()
   from /usr/lib/libQtCore.so.4
#24 0x00007fed779fec9f in ?? () from /usr/lib/libQtGui.so.4
#25 0x00007fed7655b002 in QEventLoop::processEvents ()
   from /usr/lib/libQtCore.so.4
#26 0x00007fed7655b3cd in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#27 0x00007fed7655d694 in QCoreApplication::exec ()
   from /usr/lib/libQtCore.so.4
#28 0x000000000063b8b1 in main ()
(gdb) quit
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/440

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 09 May 2009 08:47:49**
fixed in r3203: ignore SIGPIPE on SSL_shutdown. please test

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 09 May 2009 12:05:52**
tested, works

thank you
