### ISSUE TITLE
crash on /part (in active channel window, without params)

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#443]
**Reported by harry_ on 09 May 2009 22:15:20 UTC**
if in the active #channel window, if I /part without specifying the channel KVirc crashes with:

Application: KVIrc (), signal SIGSEGV
0x00007f5b67e8dc31 in nanosleep () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f5b6af2a700 (LWP 5800))]

Thread 2 (Thread 0x7f5b5b84c950 (LWP 5942)):
#0  0x00007f5b67ec2f62 in select () from /lib64/libc.so.6
#1  0x00007f5b6915aa86 in ?? () from /usr/lib64/libQtCore.so.4
#2  0x00007f5b69093392 in ?? () from /usr/lib64/libQtCore.so.4
#3  0x00007f5b6a871263 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f5b67eca78d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f5b6af2a700 (LWP 5800)):
[KCrash Handler]
#5  0x0000000000000201 in ?? ()
#6  0x00000000004fb4b8 in KviMdiChild::updateCaption ()
#7  0x000000000064bf30 in KviMdiChild::qt_metacall ()
#8  0x00007f5b6918c428 in QObject::event () from /usr/lib64/libQtCore.so.4
#9  0x00007f5b69c4bddd in QWidget::event () from /usr/lib64/libQtGui.so.4
#10 0x00007f5b6a01f29b in QMdiSubWindow::event () from /usr/lib64/libQtGui.so.4
#11 0x00007f5b69bfb49d in QApplicationPrivate::notify_helper () from /usr/lib64/libQtGui.so.4
#12 0x00007f5b69c0368a in QApplication::notify () from /usr/lib64/libQtGui.so.4
#13 0x00007f5b687f30db in KApplication::notify () from /usr/lib64/libkdeui.so.5
#14 0x00007f5b6917c35c in QCoreApplication::notifyInternal () from /usr/lib64/libQtCore.so.4
#15 0x00007f5b6917cfca in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib64/libQtCore.so.4
#16 0x00007f5b691a5d63 in ?? () from /usr/lib64/libQtCore.so.4
#17 0x00007f5b658e8e91 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#18 0x00007f5b658ec540 in ?? () from /usr/lib64/libglib-2.0.so.0
#19 0x00007f5b658ec6dc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#20 0x00007f5b691a59ef in QEventDispatcherGlib::processEvents () from /usr/lib64/libQtCore.so.4
#21 0x00007f5b69c9264f in ?? () from /usr/lib64/libQtGui.so.4
#22 0x00007f5b6917ac02 in QEventLoop::processEvents () from /usr/lib64/libQtCore.so.4
#23 0x00007f5b6917afcd in QEventLoop::exec () from /usr/lib64/libQtCore.so.4
#24 0x00007f5b6917d294 in QCoreApplication::exec () from /usr/lib64/libQtCore.so.4
#25 0x000000000062a844 in main ()

If you need more information, just advise as to what commands I need to run and I will be happy to help.

Harry_

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/443

**Comment by DarthGandalf** [comment]
**Modified by harry_ on 09 May 2009 22:16:02**
Version: none → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by mren on 09 May 2009 23:29:11**

```
[00:17:12] <+KviSynd> SVN: Ticket #443 (crash on /part (in active channel window, without params)) created by anonymous - https://svn.kvirc.de/kvirc/ticket/443
[00:18:31] <_harry__> hrrm... i didn't send that anonymously
[00:18:35] <_harry__> or so I thought
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 10 May 2009 08:48:51**
fixed in r3210

---

Resolution: none → fixed
Status: new → closed
