### ISSUE TITLE
Crash when reconnecting

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#450]
**Reported by wodim on 20 May 2009 10:47:42 UTC**
I got a (global) connectivity problem so I double-clicked "Connect" toolbar button to force disconnect. When I fixed that problem I clicked that button again, but KVIrc crashed with this backtrace:

```

Aplicación: KVIrc (kvirc), señal SIGSEGV

Thread 1 (Thread 0xb48c2930 (LWP 4583)):
[KCrash Handler]                        
#6  0xb5d9cfc2 in QString::operator= () from /usr/lib/libQtCore.so.4
#7  0xb7cb51de in KviServerReconnectInfo (this=0xa804038, info=@0xa092360) at /home/egns/kvirc/src/kvilib/irc/kvi_ircserver.cpp:343
#8  0xb7cb5cc7 in KviServer (this=0xa9ac1b8, serv=@0x85f52e0) at /home/egns/kvirc/src/kvilib/irc/kvi_ircserver.cpp:71              
#9  0x0825a56b in KviIrcConnectionTarget (this=0xa4effb8, pNetwork=0x85486c8, pServer=0x85f52e0, pProxy=0x0, szBindAddress=@0xbfe4bd98)
    at /home/egns/kvirc/src/kvirc/kernel/kvi_ircconnectiontarget.cpp:38                                                                
#10 0x0825e2c6 in KviIrcContext::connectToCurrentServer (this=0x8fa3bc0) at /home/egns/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:546   
#11 0x0825e567 in KviIrcContext::connectButtonClicked (this=0x8fa3bc0) at /home/egns/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:389     
#12 0x082889cb in KviAction::qt_metacall (this=0x8f35158, _c=QMetaObject::InvokeMetaMethod, _id=11, _a=0xbfe4bf48) at /home/egns/kvirc/release/src/kvirc/kernel/moc_kvi_action.cxx:87                                                                                                             
#13 0xb5e5e831 in QMetaObject::activate () from /usr/lib/libQtCore.so.4                                                                          
#14 0xb5e5ec98 in QMetaObject::activate () from /usr/lib/libQtCore.so.4                                                                          
#15 0xb6b8a611 in QAbstractButton::clicked () from /usr/lib/libQtGui.so.4                                                                        
#16 0xb68b2d69 in ?? () from /usr/lib/libQtGui.so.4                                                                                              
#17 0xb68b4a04 in ?? () from /usr/lib/libQtGui.so.4                                                                                              
#18 0xb68b4c91 in QAbstractButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4                                                              
#19 0xb699bd6c in QToolButton::mouseReleaseEvent () from /usr/lib/libQtGui.so.4                                                                  
#20 0xb6526807 in QWidget::event () from /usr/lib/libQtGui.so.4                                                                                  
#21 0xb68b2bfe in QAbstractButton::event () from /usr/lib/libQtGui.so.4
#22 0xb699e78a in QToolButton::event () from /usr/lib/libQtGui.so.4
#23 0xb64d16ac in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#24 0xb64d96b8 in QApplication::notify () from /usr/lib/libQtGui.so.4
#25 0xb5724bba in KApplication::notify () from /usr/lib/libkdeui.so.5
#26 0xb5e4874b in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#27 0xb64d87b3 in QApplicationPrivate::sendMouseEvent () from /usr/lib/libQtGui.so.4
#28 0xb6546fd4 in ?? () from /usr/lib/libQtGui.so.4
#29 0xb654647c in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#30 0xb6570e92 in ?? () from /usr/lib/libQtGui.so.4
#31 0xb5c89718 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0xb5c8cc7b in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
#33 0xb5c8cdf8 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0xb5e73a1c in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#35 0xb65705c5 in ?? () from /usr/lib/libQtGui.so.4
#36 0xb5e46cd9 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#37 0xb5e47122 in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#38 0xb5e4949f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#39 0xb64d1527 in QApplication::exec () from /usr/lib/libQtGui.so.4
#40 0x08267917 in main (argc=1, argv=0xbfe4e034) at /home/egns/kvirc/src/kvirc/kernel/kvi_main.cpp:471

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/450

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 24 May 2009 12:22:47**
merged with #421

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 03 Jul 2009 14:54:08**
It '''should''' be fixed in r3302

---

Resolution: none → fixed
Status: new → closed
