### ISSUE TITLE
crash when using the search function and then pressing escape

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#460]
**Reported by dessa on 01 Jun 2009 16:51:58 UTC**

```
Application: KVIrc (p), signal: Segmentation fault
[KCrash Handler]
#5  0x0000000300000002 in ?? ()
#6  0x00000000005517d1 in QTreeWidgetItem::checkState (this=0x4543070, column=0) at /usr/include/qt4/QtGui/qtreewidget.h:163
#7  0x0000000000551817 in KviIrcMessageCheckListItem::isOn (this=0x4543070) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.h:73
#8  0x000000000055185f in KviIrcViewToolWidget::messageEnabled (this=0x43c3220, msg_type=20) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.h:108
#9  0x0000000000549f7b in KviIrcView::paintEvent (this=0x3778b70, p=0x7fffd05cd8c0) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview.cpp:1109
#10 0x00007f4dc00f92b6 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#11 0x0000000000557179 in KviIrcView::event (this=0x3778b70, e=0x7fffd05cd8c0) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:1116
#12 0x00007f4dc00b3afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#13 0x00007f4dc00ba044 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#14 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#15 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#16 0x00007f4dc00faaab in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#17 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#18 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#20 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#23 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#24 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#25 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#27 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#28 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#29 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#30 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#31 0x00007f4dc00fb1f3 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib64/qt4/libQtGui.so.4
#32 0x00007f4dc00fa6f4 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#33 0x00007f4dc0269757 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#34 0x00007f4dc00ee634 in QWidgetPrivate::syncBackingStore() () from /usr/lib64/qt4/libQtGui.so.4
#35 0x00007f4dc00f918d in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#36 0x00007f4dc0421321 in QMainWindow::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#37 0x00007f4dc00b3afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#38 0x00007f4dc00ba044 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#39 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#40 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#41 0x00007f4dc0267397 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#42 0x00007f4dc0269cab in ?? () from /usr/lib64/qt4/libQtGui.so.4
#43 0x00007f4dc00f0178 in QWidget::repaint(QRect const&) () from /usr/lib64/qt4/libQtGui.so.4
#44 0x00000000005554d7 in KviIrcView::mouseMoveEvent (this=0x3778b70, e=0x7fffd05d0450) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:754
#45 0x00007f4dc00f9333 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#46 0x0000000000557179 in KviIrcView::event (this=0x3778b70, e=0x7fffd05d0450) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:1116
#47 0x00007f4dc00b3afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#48 0x00007f4dc00ba79c in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#49 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#50 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#51 0x00007f4dc00b9a62 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&) () from /usr/lib64/qt4/libQtGui.so.4
#52 0x00007f4dc00b9f50 in QApplicationPrivate::sendSyntheticEnterLeave(QWidget*) () from /usr/lib64/qt4/libQtGui.so.4
#53 0x00007f4dc00f060a in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#54 0x00007f4dc044ed21 in QPushButton::~QPushButton() () from /usr/lib64/qt4/libQtGui.so.4
#55 0x00007f4dbf4b6042 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#56 0x00007f4dc00f0cd7 in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#57 0x00007f4dbf4b6042 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#58 0x00007f4dc00f03fb in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#59 0x00007f4dc045e9e1 in QStackedWidget::~QStackedWidget() () from /usr/lib64/qt4/libQtGui.so.4
#60 0x00007f4dbf4b6042 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#61 0x00007f4dc00f03fb in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#62 0x00007f4dc046c9dd in QTabWidget::~QTabWidget() () from /usr/lib64/qt4/libQtGui.so.4
#63 0x00007f4dbf4b6042 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#64 0x00007f4dc00f03fb in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#65 0x000000000055e3a9 in KviIrcViewToolWidget::~KviIrcViewToolWidget (this=0x43c3220, __in_chrg=<value optimized out>, __in_chrg=<value optimized out>)
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.cpp:201
#66 0x000000000054faa4 in KviIrcView::toggleToolWidget (this=0x3778b70) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview.cpp:2051
#67 0x000000000055e49e in KviIrcViewToolWidget::closeEvent (this=0x43c3220) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.cpp:228
#68 0x00007f4dc00f8efe in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#69 0x00007f4dc040b8ec in QFrame::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#70 0x00007f4dc00b3afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#71 0x00007f4dc00ba044 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#72 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#73 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#74 0x00007f4dc00f7bfa in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib64/qt4/libQtGui.so.4
#75 0x00007f4dc00f8333 in QWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtGui.so.4
#76 0x00007f4dc06035df in QFrame::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtGui.so.4
#77 0x00000000006b9a69 in KviIrcViewToolWidget::qt_metacall (this=0x43c3220, _c=QMetaObject::InvokeMetaMethod, _id=22, _a=0x7fffd05d11a0)
    at /home/portage/net-irc/kvirc-9999/work/kvirc-9999_build/src/kvirc/ui/moc_kvi_ircviewtools.cxx:69
#78 0x00007f4dbf4ba007 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
#79 0x00007f4dc00ddfe5 in QShortcut::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#80 0x00007f4dc00b3afc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#81 0x00007f4dc00ba044 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#82 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#83 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#84 0x00007f4dc00dea7c in ?? () from /usr/lib64/qt4/libQtGui.so.4
#85 0x00007f4dc00e04ba in ?? () from /usr/lib64/qt4/libQtGui.so.4
#86 0x00007f4dc00bb099 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#87 0x00007f4dbeb36b5c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#88 0x00007f4dbf4aa28e in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#89 0x00007f4dc012a4eb in ?? () from /usr/lib64/qt4/libQtGui.so.4
#90 0x00007f4dc012d052 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#91 0x00007f4dc010b18e in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#92 0x00007f4dc012dce9 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#93 0x00007f4dbb916b1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#94 0x00007f4dbb919ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#95 0x00007f4dbb919e78 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#96 0x00007f4dbf4cb743 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#97 0x00007f4dc012d682 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#98 0x00007f4dbf4a8fc4 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#99 0x00007f4dbf4a914b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#100 0x00007f4dbf4aab5b in QCoreApplication::exec() () from /usr/lib64/qt4/libQtCore.so.4
#101 0x0000000000698ce4 in main (argc=2, argv=0x7fffd05d3ef8) at /home/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/kvi_main.cpp:471
```

Qt 4.5.1 SVN rev 3226 

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/460

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 28 Jun 2009 21:00:43**
should have been fixed in r3293

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by dessa on 22 Jul 2009 19:12:30**

```
Application: KVIrc (P), signal: Segmentation fault
[KCrash Handler]
#5  0x0000000100000002 in ?? ()
#6  0x000000000052f90f in QTreeWidgetItem::checkState (this=0x319a200, column=0) at /usr/include/qt4/QtGui/qtreewidget.h:163
#7  0x000000000052f955 in KviIrcMessageCheckListItem::isOn (this=0x319a200) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.h:73
#8  0x000000000052f99d in KviIrcViewToolWidget::messageEnabled (this=0x420d2b0, msg_type=25) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.h:108
#9  0x0000000000528187 in KviIrcView::paintEvent (this=0x28591c0, p=0x7fff2317a850) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview.cpp:1107
#10 0x00007fae236e55de in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#11 0x000000000053525d in KviIrcView::event (this=0x28591c0, e=0x7fff2317a850) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:1116
#12 0x00007fae2369fe9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#13 0x00007fae236a60e4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#14 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#15 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#16 0x00007fae236e6dd3 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib64/qt4/libQtGui.so.4
#17 0x00007fae2382947a in ?? () from /usr/lib64/qt4/libQtGui.so.4
#18 0x00007fae236da9e4 in QWidgetPrivate::syncBackingStore() () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007fae236e54b5 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#20 0x00007fae239e17d1 in QMainWindow::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007fae2369fe9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007fae236a60e4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#23 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#24 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#25 0x00007fae23827077 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007fae23829a2b in ?? () from /usr/lib64/qt4/libQtGui.so.4
#27 0x00007fae236dc4a6 in QWidget::repaint(QRect const&) () from /usr/lib64/qt4/libQtGui.so.4
#28 0x0000000000533670 in KviIrcView::mouseMoveEvent (this=0x28591c0, e=0x7fff2317bbc0) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:764
#29 0x00007fae236e565b in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#30 0x000000000053525d in KviIrcView::event (this=0x28591c0, e=0x7fff2317bbc0) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview_events.cpp:1116
#31 0x00007fae2369fe9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#32 0x00007fae236a683c in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#33 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#34 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#35 0x00007fae236a5b02 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&) () from /usr/lib64/qt4/libQtGui.so.4
#36 0x00007fae236a5ff0 in QApplicationPrivate::sendSyntheticEnterLeave(QWidget*) () from /usr/lib64/qt4/libQtGui.so.4
#37 0x00007fae236dc95a in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#38 0x00007fae22a751c2 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#39 0x00007fae236dcbb1 in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#40 0x00007fae23a1ee91 in QStackedWidget::~QStackedWidget() () from /usr/lib64/qt4/libQtGui.so.4
#41 0x00007fae22a751c2 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#42 0x00007fae236dcbb1 in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#43 0x00007fae23a2d0dd in QTabWidget::~QTabWidget() () from /usr/lib64/qt4/libQtGui.so.4
#44 0x00007fae22a751c2 in QObjectPrivate::deleteChildren() () from /usr/lib64/qt4/libQtCore.so.4
#45 0x00007fae236dcbb1 in QWidget::~QWidget() () from /usr/lib64/qt4/libQtGui.so.4
#46 0x000000000053c621 in KviIrcViewToolWidget::~KviIrcViewToolWidget (this=0x420d2b0, __in_chrg=<value optimized out>, __in_chrg=<value optimized out>)
    at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.cpp:200
#47 0x000000000052dc20 in KviIrcView::toggleToolWidget (this=0x28591c0) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircview.cpp:2047
#48 0x000000000053c716 in KviIrcViewToolWidget::closeEvent (this=0x420d2b0) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/ui/kvi_ircviewtools.cpp:227
#49 0x00007fae236e5226 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#50 0x00007fae239cbd9c in QFrame::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#51 0x00007fae2369fe9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#52 0x00007fae236a60e4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#53 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#54 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#55 0x00007fae236e3f22 in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib64/qt4/libQtGui.so.4
#56 0x00007fae236e465b in QWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtGui.so.4
#57 0x00007fae23bc554f in QFrame::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtGui.so.4
#58 0x0000000000696395 in KviIrcViewToolWidget::qt_metacall (this=0x420d2b0, _c=QMetaObject::InvokeMetaMethod, _id=22, _a=0x7fff2317c840)
    at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999_build/src/kvirc/ui/moc_kvi_ircviewtools.cxx:69
#59 0x00007fae22a7918f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
#60 0x00007fae236ca385 in QShortcut::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#61 0x00007fae2369fe9c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#62 0x00007fae236a60e4 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#63 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#64 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#65 0x00007fae236cae1c in ?? () from /usr/lib64/qt4/libQtGui.so.4
#66 0x00007fae236cc86a in ?? () from /usr/lib64/qt4/libQtGui.so.4
#67 0x00007fae236a7139 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#68 0x00007fae220f512c in KApplication::notify(QObject*, QEvent*) () from /usr/kde/4.3/lib64/libkdeui.so.5
#69 0x00007fae22a695be in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#70 0x00007fae2371699b in ?? () from /usr/lib64/qt4/libQtGui.so.4
#71 0x00007fae23719502 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#72 0x00007fae236f755d in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#73 0x00007fae2371a199 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#74 0x00007fae1f263aed in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#75 0x00007fae1f266d6d in ?? () from /usr/lib/libglib-2.0.so.0
#76 0x00007fae1f266ed8 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#77 0x00007fae22a8a853 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#78 0x00007fae23719b32 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#79 0x00007fae22a682c4 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#80 0x00007fae22a68452 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#81 0x00007fae22a69f03 in QCoreApplication::exec() () from /usr/lib64/qt4/libQtCore.so.4
#82 0x0000000000675a60 in main (argc=2, argv=0x7fff2317f598) at /var/tmp/portage/net-irc/kvirc-9999/work/kvirc-9999/src/kvirc/kernel/kvi_main.cpp:471
```

r3363

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 23 Jul 2009 13:11:42**
possible fix in r3371, please test

---

Resolution: none → fixed
Status: reopened → closed
