### ISSUE TITLE
Crash with new notifier

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#490]
**Reported by wodim on 09 Jul 2009 12:37:44 UTC**

```

Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#6  0x0040006b in ?? ()
#7  0xa897c5f1 in KviNotifierWindow::paintEvent (this=0xbc20e30, e=0xbfdaf384) at /home/egns/Programas/kvirc/src/modules/notifier/notifierwindow.cpp:606
#8  0xb67b0db4 in QWidget::event () from /usr/lib/libQtGui.so.4
#9  0xb675c674 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#10 0xb6763caa in QApplication::notify () from /usr/lib/libQtGui.so.4
#11 0xb59bca7a in KApplication::notify () from /usr/lib/libkdeui.so.5
#12 0xb60b2edb in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#13 0xb67b8db5 in QWidgetPrivate::drawWidget () from /usr/lib/libQtGui.so.4
#14 0xb6940f33 in ?? () from /usr/lib/libQtGui.so.4
#15 0xb694137a in ?? () from /usr/lib/libQtGui.so.4
#16 0xb67aa1d5 in QWidgetPrivate::syncBackingStore () from /usr/lib/libQtGui.so.4
#17 0xb67c1f20 in ?? () from /usr/lib/libQtGui.so.4
#18 0xb67d01da in QApplication::x11ProcessEvent () from /usr/lib/libQtGui.so.4
#19 0xb67fad42 in ?? () from /usr/lib/libQtGui.so.4
#20 0xb5ef6d98 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#21 0xb5efa3e0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
#22 0xb5efa513 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0xb60dd57c in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#24 0xb67fa475 in ?? () from /usr/lib/libQtGui.so.4
#25 0xb60b1489 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#26 0xb60b18da in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#27 0xb60b3d4f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#28 0xb675c4f7 in QApplication::exec () from /usr/lib/libQtGui.so.4
#29 0x08266487 in main (argc=1, argv=0xbfdb11f4) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471

```

Dunno how to reproduce. It happened to me when the notifier appeared.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/490

**Comment by DarthGandalf** [comment]
**Comment by wodim on 09 Jul 2009 16:10:54**
Oops, wrong priority.

---

Priority: Normal → Crash

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 09 Jul 2009 16:30:15**
Can you please report a backtrace of kvirc compiled with debug symbols? it's quite hard to track the bug down with this report :(

**Comment by DarthGandalf** [comment]
**Comment by wodim on 10 Jul 2009 13:27:28**
I thought I had debug symbols activated... I'm recompiling now and I will post another backtrace if possible. ;)

**Comment by DarthGandalf** [comment]
**Comment by wodim on 10 Jul 2009 15:10:07**
Ok, new backtrace. I had two tabs opened in the notifier. I clicked the unselected one, and... it crashed.

```
#0  0xa88862f3 in KviNotifierWindow::paintEvent (this=0xa0f3d78, e=0xbfdc68f4)
    at /home/egns/Programas/kvirc/src/modules/notifier/notifierwindow.cpp:584 
        p = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0xb5970b40 "QPainter", data = 0xb5970be0, 
      extradata = 0x0}}, d_ptr = 0xa210110}                                                                          
        title = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 25318}, alloc = 0, size = 0, 
    data = 0x831be42, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, 
  static shared_empty = {ref = {_q_value = 155}, alloc = 0, size = 0, data = 0xb6e2d64e, clean = 0, simpletext = 0,         
    righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xa2abcd0,                               
  static codecForCStrings = 0x88e1578}                                                                                      
#1  0xb52e9db4 in QWidget::event () from /usr/lib/libQtGui.so.4                                                             
No symbol table info available.                                                                                             
#2  0xb5295674 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4                                         
No symbol table info available.                                                                                             
#3  0xb529ccaa in QApplication::notify () from /usr/lib/libQtGui.so.4                                                       
No symbol table info available.                                                                                             
#4  0xb64f9a7a in KApplication::notify () from /usr/lib/libkdeui.so.5                                                       
No symbol table info available.                                                                                             
#5  0xb6d3cedb in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4                                          
No symbol table info available.                                                                                             
#6  0xb52f1db5 in QWidgetPrivate::drawWidget () from /usr/lib/libQtGui.so.4                                                 
No symbol table info available.                                                                                             
#7  0xb5479f33 in ?? () from /usr/lib/libQtGui.so.4                                                                         
No symbol table info available.                                                                                             
#8  0xb52e3296 in QWidgetPrivate::syncBackingStore () from /usr/lib/libQtGui.so.4                                           
No symbol table info available.                                                                                              
#9  0xb52ea1f5 in QWidget::event () from /usr/lib/libQtGui.so.4                                                                 
No symbol table info available.                                                                                                 
#10 0xb5295674 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
#11 0xb529ccaa in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#12 0xb64f9a7a in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#13 0xb6d3cedb in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0xb6d3dac2 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0xb6d3dc8d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0xb6d6794f in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0xb6b80d98 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#18 0xb6b843e0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#19 0xb6b84513 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#20 0xb6d6757c in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#21 0xb5333475 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#22 0xb6d3b489 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#23 0xb6d3b8da in QEventLoop::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#24 0xb6d3dd4f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#25 0xb52954f7 in QApplication::exec () from /usr/lib/libQtGui.so.4
No symbol table info available.
#26 0x082664a7 in main (argc=1, argv=0xbfdc7554) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471
        a = {argc = 1, argv = 0xbfdc7554, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false,
  bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>},
    m_ptr = 0x88e0a90 "", m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x88e0aa0 "",
    m_len = 0}}
        theApp = <value optimized out>
        dpy = (Display *) 0x890c450
        visual = <value optimized out>
        retVal = <value optimized out>
        retCode = <value optimized out>
        colormap = <value optimized out>
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x8978190 "", m_len = 0}
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 10 Jul 2009 15:41:45**
should have been fixed in r3330, please test

---

Resolution: none → fixed
Status: new → closed
