### ISSUE TITLE
Crash while closing a query window

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#493]
**Reported by wodim on 11 Jul 2009 17:52:56 UTC**
Someone opened me a query. I closed it and KVIrc crashed.

```

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb4a6a710 (LWP 11158)]        
0xb67d4176 in QWidget::window () from /usr/lib/libQtGui.so.4
(gdb) bt full
#0  0xb67d4176 in QWidget::window () from /usr/lib/libQtGui.so.4
No symbol table info available.                                 
#1  0xb67dc0c5 in QWidget::isActiveWindow () from /usr/lib/libQtGui.so.4
No symbol table info available.                                         
#2  0x081a783f in KviWindow::hasAttention (this=0xaab6568) at /home/egns/Programas/kvirc/src/kvirc/ui/kvi_window.cpp:192
        w = <value optimized out>                                                                                       
#3  0xa81918c3 in KviNotifierWindow::shouldHideIfMainWindowGotAttention (this=0xaaf3550)                                
    at /home/egns/Programas/kvirc/src/modules/notifier/notifierwindow.cpp:319                                           
No locals.                                                                                                              
#4  0xa8191928 in KviNotifierWindow::blink (this=0xaaf3550)                                                             
    at /home/egns/Programas/kvirc/src/modules/notifier/notifierwindow.cpp:524                                           
No locals.                                                                                                              
#5  0xa8196d03 in KviNotifierWindow::qt_metacall (this=0xaaf3550, _c=QMetaObject::InvokeMetaMethod, _id=29, _a=0xbfe5820c)
    at /home/egns/Programas/kvirc/build/src/modules/notifier/moc_notifierwindow.cxx:91                                    
No locals.                                                                                                                
#6  0xb60f98bc in QMetaObject::activate () from /usr/lib/libQtCore.so.4                                                   
No symbol table info available.                                                                                           
#7  0xb60fa4f2 in QMetaObject::activate () from /usr/lib/libQtCore.so.4                                                   
No symbol table info available.                                                                                           
#8  0xb6133957 in QTimer::timeout () from /usr/lib/libQtCore.so.4                                                         
No symbol table info available.                                                                                           
#9  0xb60fef6e in QTimer::timerEvent () from /usr/lib/libQtCore.so.4                                                      
No symbol table info available.                                                                                           
#10 0xb60f3a6f in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#11 0xb678d674 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/493

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Jul 2009 14:28:56**
fixed in r3333

---

Resolution: none → fixed
Status: new → closed
