### ISSUE TITLE
Crash while auto-reconnecting

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#494]
**Reported by wodim on 13 Jul 2009 22:54:54 UTC**
I got disconnected from a server. When KVIrc tried to auto-reconnect, it crashed. Backtrace from KCrash:

```

Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#6  QBasicAtomicInt::deref (this=0x2) at /usr/include/QtCore/qatomic_i386.h:132
#7  0x08132744 in ~QString (this=0xaa7b4e8) at /usr/include/QtCore/qstring.h:866
#8  0xb7e38d00 in ~KviServerReconnectInfo (this=0xaa7b4e0) at /home/egns/Programas/kvirc/src/kvilib/irc/kvi_ircserver.cpp:343
#9  0xb7e39d4c in ~KviServer (this=0xbf8f075c) at /home/egns/Programas/kvirc/src/kvilib/irc/kvi_ircserver.cpp:129
#10 0x0825c31d in KviIrcContext::connectionTerminated (this=0x9c01b40) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:804
#11 0x0825e214 in KviIrcLink::socketStateChange (this=0xabb2290) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_irclink.cpp:361
#12 0x08261e48 in KviIrcSocket::reset (this=0xaa9c900) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:172
#13 0x08260957 in KviIrcSocket::readData (this=0xaa9c900) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1460
#14 0x082893ac in KviIrcSocket::qt_metacall (this=0xaa9c900, _c=QMetaObject::InvokeMetaMethod, _id=6, _a=0xbf8f0de8) at /home/egns/Programas/kvirc/build/src/kvirc/kernel/moc_kvi_ircsocket.cxx:77
#15 0xb5fd98bc in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#16 0xb5fda4f2 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#17 0xb60137f3 in QSocketNotifier::activated () from /usr/lib/libQtCore.so.4
#18 0xb5fde247 in QSocketNotifier::event () from /usr/lib/libQtCore.so.4
#19 0xb666d674 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#20 0xb6674d5c in QApplication::notify () from /usr/lib/libQtGui.so.4
#21 0xb58cbf0a in KApplication::notify () from /usr/lib/libkdeui.so.5
#22 0xb5fc3edb in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#23 0xb5fee81a in ?? () from /usr/lib/libQtCore.so.4
#24 0xb5e07d98 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#25 0xb5e0b3e0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
#26 0xb5e0b513 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#27 0xb5fee57c in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#28 0xb670b475 in ?? () from /usr/lib/libQtGui.so.4
#29 0xb5fc2489 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#30 0xb5fc28da in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#31 0xb5fc4d4f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#32 0xb666d4f7 in QApplication::exec () from /usr/lib/libQtGui.so.4
#33 0x082664d7 in main (argc=1, argv=0xbf8f1654) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/494

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 14 Jul 2009 10:08:51**
should have been fixed in r3337, please test

---

Resolution: none → fixed
Status: new → closed
