### ISSUE TITLE
unexpected Kvirc crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#53]
**Reported by cgreco on 28 Nov 2007 20:02:36 UTC**
I'm running KVirc 3.2.4 'Anomalies' 20060808 from package '3.2.4-5ubuntu1.1' on Kubuntu Feisty. Sometimes (two times since installation) when KVirc is minimized to the systray and there isn't any user interaction, it unexpectedly crashes. Following is report from last crash.

```
(no debugging symbols found)
Using host libthread_db library "/lib/libthread_db.so.1".
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[Thread debugging using libthread_db enabled]
[New Thread -1241565504 (LWP 6855)]
[KCrash handler]
#5  0xb608e2cf in ?? () from /lib/libc.so.6
#6  0xb6156140 in ?? () from /lib/libc.so.6
#7  0x0862fa48 in ?? ()
#8  0xbfaedf08 in ?? ()
#9  0xb608cde9 in free () from /lib/libc.so.6
#10 0xb608ee28 in realloc () from /lib/libc.so.6
#11 0xb7e7a33d in KviQString::vsprintf () from /usr/lib/libkvilib.so.3
#12 0x0827aced in KviWindow::output ()
#13 0x081d8366 in KviServerParser::parseLiteralPing ()
#14 0x081d2329 in KviServerParser::parseMessage ()
#15 0x08131568 in KviIrcConnection::incomingMessage ()
#16 0x0813c8fd in KviIrcLink::processData ()
#17 0x0813f1c4 in KviIrcSocket::readData ()
#18 0x0829268f in KviIrcSocket::qt_invoke ()
#19 0xb6fb888b in QObject::activate_signal () from /usr/lib/libqt-mt.so.3
#20 0xb6fb91a2 in QObject::activate_signal () from /usr/lib/libqt-mt.so.3
#21 0xb7345547 in QSocketNotifier::activated () from /usr/lib/libqt-mt.so.3
#22 0xb6fdb44a in QSocketNotifier::event () from /usr/lib/libqt-mt.so.3
#23 0xb6f4fa60 in QApplication::internalNotify () from /usr/lib/libqt-mt.so.3
#24 0xb6f5188f in QApplication::notify () from /usr/lib/libqt-mt.so.3
#25 0xb771ecc2 in KApplication::notify () from /usr/lib/libkdecore.so.4
#26 0xb6ee21e9 in QApplication::sendEvent () from /usr/lib/libqt-mt.so.3
#27 0xb6f41e59 in QEventLoop::activateSocketNotifiers ()
   from /usr/lib/libqt-mt.so.3
#28 0xb6ef6d07 in QEventLoop::processEvents () from /usr/lib/libqt-mt.so.3
#29 0xb6f6a136 in QEventLoop::enterLoop () from /usr/lib/libqt-mt.so.3
#30 0xb6f69f46 in QEventLoop::exec () from /usr/lib/libqt-mt.so.3
#31 0xb6f51609 in QApplication::exec () from /usr/lib/libqt-mt.so.3
#32 0x08140e51 in main ()

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/53

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 28 Nov 2007 20:27:03**
Update to 3.2.6

---

Resolution: none → wontfix
Status: new → closed
