### ISSUE TITLE
Crashed when closing a server window

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#532]
**Reported by wodim on 18 Aug 2009 22:19:51 UTC**
I got this crash with KCrash so it may be useless. :-\

```
Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#6  0x0813bdb7 in KviIrcContext::isConnected (this=0xa223440) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_irccontext.h:118
#7  0x0823b062 in KviApp::heartbeat (this=0xa223440, tNow=1250633935) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_app.cpp:1847
#8  0xb5ffbb3f in QObject::event () from /usr/lib/libQtCore.so.4
#9  0xb5feb8db in QCoreApplication::event () from /usr/lib/libQtCore.so.4
#10 0xb66990e6 in QApplication::event () from /usr/lib/libQtGui.so.4
#11 0xb6693694 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#12 0xb669ad7c in QApplication::notify () from /usr/lib/libQtGui.so.4
#13 0xb58f2fca in KApplication::notify () from /usr/lib/libkdeui.so.5
#14 0xb5febfab in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#15 0xb601977e in ?? () from /usr/lib/libQtCore.so.4
#16 0xb6016760 in ?? () from /usr/lib/libQtCore.so.4
#17 0xb5e2fd98 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#18 0xb5e333e0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
#19 0xb5e33513 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#20 0xb60166ac in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#21 0xb6731325 in ?? () from /usr/lib/libQtGui.so.4
#22 0xb5fea559 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#23 0xb5fea9aa in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#24 0xb5fece1f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#25 0xb6693517 in QApplication::exec () from /usr/lib/libQtGui.so.4
#26 0x08264ff7 in main (argc=1, argv=0xbf9615f4) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/532

**Comment by DarthGandalf** [comment]
**Modified by anonymous on 18 Aug 2009 22:20:01**
Priority: Normal → Crash

**Comment by DarthGandalf** [comment]
**Comment by aeriana on 19 Aug 2009 11:05:23**
I can't reproduce this on r3416 so far, I've tried both a connected context and a disconnected context, although egns reported that it was a dead context with many channels. However, I do lack the third mouse button to close contexts with so I just did right click - close.

**Comment by DarthGandalf** [comment]
**Comment by wodim on 19 Aug 2009 23:15:43**
Another backtrace, this from gdb. It looks like the another one, and it has one thing in common: I had a DCC window in the irc context when I closed it.

```
(gdb) bt full
#0  0x0813bdb7 in KviIrcContext::isConnected (this=0x9ee1440)
    at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_irccontext.h:118
No locals.
#1  0x0823b062 in KviApp::heartbeat (this=0x9ee1440, tNow=1250723306)
    at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_app.cpp:1847
        pTm = (const tm *) 0xb510a20
#2  0xb6015b3f in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#3  0xb60058db in QCoreApplication::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#4  0xb66b30e6 in QApplication::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#5  0xb66ad694 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
#6  0xb66b4d7c in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#7  0xb590cfea in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#8  0xb6005fab in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#9  0xb603377e in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#10 0xb6030760 in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#11 0xb5e49d98 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0                                                     
No symbol table info available.
#12 0xb5e4d3e0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#13 0xb5e4d513 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#14 0xb60306ac in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0xb674b325 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#16 0xb6004559 in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0xb60049aa in QEventLoop::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#18 0xb6006e1f in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#19 0xb66ad517 in QApplication::exec () from /usr/lib/libQtGui.so.4 
No symbol table info available.
#20 0x08264ff7 in main (argc=1, argv=0xbf8a9694) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471
        a = {argc = 1, argv = 0xbf8a9694, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false,
  bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>},
    m_ptr = 0x9eab8c8 "", m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x9eab8d8 "", 
    m_len = 0}}
        theApp = <value optimized out>
        dpy = (Display *) 0x9ed75a8
        visual = <value optimized out>
        retVal = <value optimized out>
        retCode = <value optimized out>
        fooArgv = {0x82b5f8a "kvirc", 0x0}
        colormap = <value optimized out>
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x9f6a768 "", m_len = 0}
```

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Sep 2009 13:58:35**
Version: none → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 03 Sep 2009 16:57:35**
I have crashes after closing any window on RC1. I'm using updated from 3.4.3 version.

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 13 Sep 2009 23:23:20**
I am here on the MS-windows RC1 from ctrlaltca and it just crashed after I closed a channel with the Right-Click GUI.

First everything turned white and CPU worked hard, after 30s the MS-windows crash message

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 26 Sep 2009 14:10:22**
I get this too. Win32, upgraded from 3.4.2, get crash on closing query window / server context window with right click -> close.

Unhandled exception at 0x004f71ea in kvirc.exe: 0xC0000005: Access violation reading location 0x0000003e.

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 26 Sep 2009 14:28:56**
(forgot to mention version: rc1 r3472)

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 18 Oct 2009 08:12:20**
r3514 
crash on windows, when closing a window.

Reproducable. Everytime I type "/part" in a channel or rightclick close, it crashes.

The window becomes sort of "fullscreen" and crashes.

(r3555 is not downloadable from gizmokid)

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 03 Nov 2009 15:43:35**
Version: 4.0 Insomnia → 4.0rc1 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 15 Nov 2009 14:58:06**
this was probably the same bug of #352, a problem related to "closing a console window"

---

Resolution: none → duplicate
Status: new → closed
