### ISSUE TITLE
Crash while closing KVIrc

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#534]
**Reported by wodim on 19 Aug 2009 23:47:12 UTC**

```
(gdb) bt full       
#0  0x081a7477 in KviIrcConnection::textCodec (this=0x9050a80)   
    at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_ircconnection.h:611
No locals. 
#1  0x081a5e09 in KviWindow::saveProperties (this=0x9050a80, cfg=0x84fa1f8)        
    at /home/egns/Programas/kvirc/src/kvirc/ui/kvi_window.cpp:566
        szCodec = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 12070}, alloc = 0, size = 0,       
    data = 0x831a2e2, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}},     
  static shared_empty = {ref = {_q_value = 84}, alloc = 0, size = 0, data = 0xb60ae64e, clean = 0, simpletext = 0,     
    righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xb60ae63c,       
  static codecForCStrings = 0x8482ef0}
        c = <value optimized out>     
        szKey = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 12070}, alloc = 0, size = 0,
    data = 0x831a2e2, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}},     
  static shared_empty = {ref = {_q_value = 84}, alloc = 0, size = 0, data = 0xb60ae64e, clean = 0, simpletext = 0,     
    righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xbfba1578,       
  static codecForCStrings = 0x8482ef0}
#2  0x0814cef1 in KviFrame::saveWindowProperties (this=0x85b75d0, wnd=0x9050a80, szSection=@0xbfba1578)       
    at /home/egns/Programas/kvirc/src/kvirc/ui/kvi_frame.cpp:467 
No locals. 
#3  0x0814d04e in KviFrame::closeWindow (this=0x85b75d0, wnd=0x9050a80)   
---Type <return> to continue, or q <return> to quit---  
    at /home/egns/Programas/kvirc/src/kvirc/ui/kvi_frame.cpp:490 
        group = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 12070}, alloc = 0, size = 0,
    data = 0x831a2e2, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}},     
  static shared_empty = {ref = {_q_value = 84}, alloc = 0, size = 0, data = 0xb60ae64e, clean = 0, simpletext = 0,     
    righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x85acca8,
  static codecForCStrings = 0x8482ef0}
#4  0x0814df77 in ~KviFrame (this=0x85b75d0) at /home/egns/Programas/kvirc/src/kvirc/ui/kvi_frame.cpp:220
No locals.
#5  0xb5fcc8a5 in qDeleteInEventHandler () from /usr/lib/libQtCore.so.4
No symbol table info available.
#6  0xb5fcddab in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#7  0xb66b97d6 in QWidget::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#8  0xb6a7de77 in QMainWindow::event () from /usr/lib/libQtGui.so.4
No symbol table info available.
#9  0xb59a9f54 in KMainWindow::event () from /usr/lib/libkdeui.so.5
No symbol table info available.
#10 0xb6665694 in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#11 0xb666ccca in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#12 0xb58c4fea in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#13 0xb5fbdfab in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0xb5fbeb92 in QCoreApplicationPrivate::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0xb5fbed5d in QCoreApplication::sendPostedEvents () from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0xb5fbee69 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0xb6665517 in QApplication::exec () from /usr/lib/libQtGui.so.4
No symbol table info available.
#18 0x08264ff7 in main (argc=4, argv=0xbfba1e64) at /home/egns/Programas/kvirc/src/kvirc/kernel/kvi_main.cpp:471
        a = {argc = 4, argv = 0xbfba1e64, configFile = 0xbfba2883 ".kvircx.rc", createFile = false, bForceNewSession = true,
  bShowPopup = false, bShowSplashScreen = true, bExecuteCommandAndClose = false,
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x84828c8 "", m_len = 0},
  szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x84828d8 "", m_len = 0}}
        theApp = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        dpy = (Display *) 0x84ae5b8
        visual = <value optimized out>
        retVal = <value optimized out>
        retCode = <value optimized out>
        fooArgv = {0x82b5f8a "kvirc", 0x0}
        colormap = <value optimized out>
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x85417a0 "", m_len = 0}
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/534

**Comment by DarthGandalf** [comment]
**Comment by wodim on 20 Aug 2009 12:02:31**
Using r3413.
When it happened, KVIrc window was no longer visible.

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 02 Sep 2009 13:58:16**
Version: none → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Modified by ctrlaltca on 03 Nov 2009 15:43:39**
Version: 4.0 Insomnia → 4.0rc1 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 15 Nov 2009 14:54:43**
The fault is that the dcc window while closing asks for some values of its mother console window.
If the console window has already been deleted.. it just fails and crashes :(

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 15 Nov 2009 16:52:53**
btw the fix was reworked in r3612
