### ISSUE TITLE
KVIrc crash on editing servers

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#54]
**Reported by mren on 30 Nov 2007 00:23:37 UTC**
I edited a server in server preferences. As I clicked ok KVIrc crashed. Here's the backlog (at least the parts w/ debug symbols):

Using host libthread_db library "/lib/libthread_db.so.1".<br/>
[...]<br/>
[KCrash handler]<br/>
#6  0xb7ef2373 in KviIrcServer::~KviIrcServer () from /usr/lib/libkvilib.so.3<br/>
#7  0xb7ef685f in QPtrList<KviIrcServer>::deleteItem () from /usr/lib/libkvilib.so.3<br/>
#8  0xb71c8ead in QGList::clear () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#9  0xb7ef6a30 in QPtrList<KviIrcServer>::~QPtrList () from /usr/lib/libkvilib.so.3<br/>
#10 0xb7ef29f2 in KviIrcServerDataBaseRecord::~KviIrcServerDataBaseRecord () from /usr/lib/libkvilib.so.3<br/>
#11 0xb7ef68cf in QDict<KviIrcServerDataBaseRecord>::deleteItem () from /usr/lib/libkvilib.so.3<br/>
#12 0xb71c72e7 in QGDict::clear () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#13 0xb7ef688d in QDict<KviIrcServerDataBaseRecord>::clear () from /usr/lib/libkvilib.so.3<br/>
#14 0xb7ef2937 in KviIrcServerDataBase::clear () from /usr/lib/libkvilib.so.3<br/>
#15 0xb31559bf in KviServerOptionsWidget::commit () from /usr/share/kvirc/3.2/modules/libkvioptions.so<br/>
#16 0xb30f16cf in KviOptionsWidgetContainer::okClicked () from /usr/share/kvirc/3.2/modules/libkvioptions.so<br/>
#17 0xb30f174a in KviOptionsWidgetContainer::qt_invoke () from /usr/share/kvirc/3.2/modules/libkvioptions.so<br/>
#18 0xb6f166b9 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#19 0xb6f1730d in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#20 0xb725123c in QButton::clicked () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#21 0xb6fa8e9d in QButton::mouseReleaseEvent () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#22 0xb6f4f5ba in QWidget::event () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#23 0xb6eb7747 in QApplication::internalNotify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#24 0xb6eb8499 in QApplication::notify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#25 0xb765791e in KApplication::notify () from /usr/kde/3.5/lib/libkdecore.so.4<br/>
#26 0xb6e57fd2 in QETWidget::translateMouseEvent () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#27 0xb6e5789f in QApplication::x11ProcessEvent () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#28 0xb6e6783a in QEventLoop::processEvents () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#29 0xb6ecde30 in QEventLoop::enterLoop () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#30 0xb6ecdcb6 in QEventLoop::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#31 0xb6eb71df in QApplication::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#32 0x081317d7 in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/54

**Comment by DarthGandalf** [comment]
**Comment by mren on 26 Feb 2008 02:05:06**
Seems to be fixed now.

---

Resolution: none → worksforme
Status: new → closed
Summary: KVIrc crash → KVIrc crash on editing servers
