### ISSUE TITLE
crash on disconnecting a network

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#553]
**Reported by mren on 03 Sep 2009 20:51:01 UTC**
r3472, just wanted to disconnect from a network

don't know if the backtrace shows anything useful but here it goes:

```
Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#5  0x00000000004fd118 in QBasicAtomicInt::ref ()
#6  0x00000000005096b4 in QList<QString>::operator= ()
#7  0x000000000051952b in QStringList::operator= ()
#8  0x00007fa6f2e548f8 in KviServerReconnectInfo::KviServerReconnectInfo () from /usr/lib64/libkvilib4.so.4
#9  0x00007fa6f2e55690 in KviServer::KviServer () from /usr/lib64/libkvilib4.so.4
#10 0x000000000065913c in KviIrcConnectionTarget::KviIrcConnectionTarget ()
#11 0x000000000065d7d0 in KviIrcContext::connectToCurrentServer ()
#12 0x000000000065db54 in KviIrcContext::connectButtonClicked ()
#13 0x0000000000647aa5 in KviIrcContext::connectOrDisconnect ()
#14 0x00000000006446a8 in KviConnectAction::activate ()
#15 0x000000000068c4d7 in KviAction::qt_metacall ()
#16 0x000000000068d11d in KviConnectAction::qt_metacall ()
#17 0x00007fa6ee375720 in QMetaObject::activate () from /usr/lib64/qt4/libQtCore.so.4
#18 0x00007fa6f16ca137 in QAbstractButton::clicked () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007fa6f14634d0 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#20 0x00007fa6f1464362 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007fa6f1464565 in QAbstractButton::mouseReleaseEvent () from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007fa6f1521f4a in QToolButton::mouseReleaseEvent () from /usr/lib64/qt4/libQtGui.so.4
#23 0x00007fa6f11510c8 in QWidget::event () from /usr/lib64/qt4/libQtGui.so.4
#24 0x00007fa6f1103dbd in QApplicationPrivate::notify_helper () from /usr/lib64/qt4/libQtGui.so.4
#25 0x00007fa6f110cb61 in QApplication::notify () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007fa6ece3b72a in KApplication::notify () from /usr/lib64/libkdeui.so.5
#27 0x00007fa6ee36346b in QCoreApplication::notifyInternal () from /usr/lib64/qt4/libQtCore.so.4
#28 0x00007fa6f110be71 in QApplicationPrivate::sendMouseEvent () from /usr/lib64/qt4/libQtGui.so.4
#29 0x00007fa6f1166bec in ?? () from /usr/lib64/qt4/libQtGui.so.4
#30 0x00007fa6f1165705 in QApplication::x11ProcessEvent () from /usr/lib64/qt4/libQtGui.so.4
#31 0x00007fa6f118a00c in ?? () from /usr/lib64/qt4/libQtGui.so.4
#32 0x00007fa6edd84fd1 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#33 0x00007fa6edd886ad in ?? () from /usr/lib64/libglib-2.0.so.0
#34 0x00007fa6edd8886b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#35 0x00007fa6ee388aef in QEventDispatcherGlib::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#36 0x00007fa6f11898a8 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#37 0x00007fa6ee361df2 in QEventLoop::processEvents () from /usr/lib64/qt4/libQtCore.so.4
#38 0x00007fa6ee361f95 in QEventLoop::exec () from /usr/lib64/qt4/libQtCore.so.4
#39 0x00007fa6ee36401c in QCoreApplication::exec () from /usr/lib64/qt4/libQtCore.so.4
#40 0x0000000000668f8d in main ()
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/553

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Dec 2009 17:15:37**
closing since no confirmation in over 3 months

---

Resolution: none → worksforme
Status: new → closed
