### ISSUE TITLE
crach

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#556]
**Reported by valenstijn on 05 Sep 2009 22:37:00 UTC**
Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#6  0xb7df6cb3 in KviQString::vsprintf () from /usr/lib/libkvilib4.so.4
#7  0x08173c05 in KviWindow::output ()
#8  0x08198cea in KviServerParser::parseNumeric004 ()
#9  0x0819b033 in KviServerParser::parseMessage ()
#10 0x08254fe3 in KviIrcConnection::incomingMessage ()
#11 0x08263ef5 in KviIrcLink::processData ()
#12 0x08265710 in KviIrcSocket::readData ()
#13 0x08295b74 in KviIrcSocket::qt_metacall ()
#14 0xb61711b8 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#15 0xb6171e42 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#16 0xb61ad513 in QSocketNotifier::activated () from /usr/lib/libQtCore.so.4
#17 0xb6176877 in QSocketNotifier::event () from /usr/lib/libQtCore.so.4
#18 0xb66a8d3c in QApplicationPrivate::notify_helper () from /usr/lib/libQtGui.so.4
#19 0xb66b103e in QApplication::notify () from /usr/lib/libQtGui.so.4
#20 0xb5bc085d in KApplication::notify () from /usr/lib/libkdeui.so.5
#21 0xb615bbcb in QCoreApplication::notifyInternal () from /usr/lib/libQtCore.so.4
#22 0xb618758a in ?? () from /usr/lib/libQtCore.so.4
#23 0xb505fb88 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#24 0xb50630eb in ?? () from /usr/lib/libglib-2.0.so.0
#25 0xb5063268 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#26 0xb61872f8 in QEventDispatcherGlib::processEvents () from /usr/lib/libQtCore.so.4
#27 0xb674aa75 in ?? () from /usr/lib/libQtGui.so.4
#28 0xb615a1fa in QEventLoop::processEvents () from /usr/lib/libQtCore.so.4
#29 0xb615a642 in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#30 0xb615cae9 in QCoreApplication::exec () from /usr/lib/libQtCore.so.4
#31 0xb66a8bb7 in QApplication::exec () from /usr/lib/libQtGui.so.4
#32 0x0826c3cb in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/556

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 06 Sep 2009 16:53:28**
Unfortunately this backtrace doesn't give us any info about what really happened. I've two questions for you: 1) what server were you connecting to? 2) what language are you using in kvirc?

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 07 Sep 2009 13:56:55**
Priority: Normal → Crash

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 18 Sep 2009 16:13:15**
can you explain how to reproduce the crash?

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 22 Sep 2009 21:03:17**
closing as invalid

---

Resolution: none → invalid
Status: new → closed
