### ISSUE TITLE
Crash on connection to a server.

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#592]
**Reported by anonymous on 05 Oct 2009 18:31:59 UTC**
The crash happens at:

m_pConsole->output(KVI_OUT_VERBOSE,__tr2qs("Using server specific password (%s)

commenting out that line, makes the crash go away and i'm able to connect again. Full bt:
#6  0x0813a2d9 in QString::isEmpty (this=0xbfa95348) at /opt/qt/4.6/include/QtCore/qstring.h:690
#7  0x081a11f3 in KviWindow::output (this=0xa4bbf30, msg_type=128, szFmt=...) at /mnt/data/kvirc/src/kvirc/ui/kvi_window.cpp:1296
#8  0x0824e2b8 in KviIrcConnection::loginToIrcServer (this=0xa524fb0) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircconnection.cpp:1126
#9  0x0825726a in KviIrcLink::socketStateChange (this=0xa689b58) at /mnt/data/kvirc/src/kvirc/kernel/kvi_irclink.cpp:349
#10 0x0825872b in KviIrcSocket::linkUp (this=0xa4dd778) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1379
#11 0x0825ad89 in KviIrcSocket::writeNotifierFired (this=0xa4dd778) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:452
#12 0x082825d4 in KviIrcSocket::qt_metacall (this=0xa4dd778, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0xbfa955ec) at /mnt/data/kvirc/build/src/kvirc/kernel/moc_kvi_ircsocket.cxx:76
#13 0xb65a7753 in QMetaObject::activate (sender=0xa68a498, from_signal_index=4, to_signal_index=4, argv=0xbfa955ec) at /kde/source/qt-copy/src/corelib/kernel/qobject.cpp:3109
#14 0xb65a7d02 in QMetaObject::activate (sender=0xa68a498, m=0xb663fd30, local_signal_index=0, argv=0xbfa955ec) at /kde/source/qt-copy/src/corelib/kernel/qobject.cpp:3186
#15 0xb65de993 in QSocketNotifier::activated (this=0xa68a498, _t1=13) at .moc/release-shared/moc_qsocketnotifier.cpp:83
#16 0xb65ad947 in QSocketNotifier::event (this=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/corelib/kernel/qsocketnotifier.cpp:316
#17 0xb6a6d724 in QApplicationPrivate::notify_helper (this=0xa1f6a38, receiver=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:4056
#18 0xb6a75f2e in QApplication::notify (this=0xa1f69a8, receiver=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:3603
#19 0xb5fdfdcb in KApplication::notify (this=0xa1f69a8, receiver=0xa68a498, event=0xbfa95990) at /kde/source/kdelibs/kdeui/kernel/kapplication.cpp:302
#20 0xb65953cb in QCoreApplication::notifyInternal (this=0xa1f69a8, receiver=0xa68a498, event=0xbfa95990) at /kde/source/qt-copy/src/corelib/kernel/qcoreapplication.cpp:606
#21 0xb65bc977 in QCoreApplication::sendEvent (source=0xa1fd590) at ../../include/QtCore/../../../../source/qt-copy/src/corelib/kernel/qcoreapplication.h:213
#22 socketNotifierSourceDispatch (source=0xa1fd590) at /kde/source/qt-copy/src/corelib/kernel/qeventdispatcher_glib.cpp:110
#23 0xb54d2368 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#24 0xb54d58c3 in ?? () from /usr/lib/libglib-2.0.so.0
#25 0xb54d5a48 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#26 0xb65bc6e8 in QEventDispatcherGlib::processEvents (this=0xa1f6408, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventdispatcher_glib.cpp:327
#27 0xb6afd095 in QGuiEventDispatcherGlib::processEvents (this=0xa1f6408, flags=...) at /kde/source/qt-copy/src/gui/kernel/qguieventdispatcher_glib.cpp:202
#28 0xb6593b8a in QEventLoop::processEvents (this=0xbfa95b80, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventloop.cpp:149
#29 0xb6593d52 in QEventLoop::exec (this=0xbfa95b80, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventloop.cpp:197
#30 0xb6595f41 in QCoreApplication::exec () at /kde/source/qt-copy/src/corelib/kernel/qcoreapplication.cpp:888
#31 0xb6a6d5a7 in QApplication::exec () at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:3525
#32 0x0825f3e8 in main (argc=) at /mnt/data/kvirc/src/kvirc/kernel/kvi_main.cpp:471

using kvirc trunk svn

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/592

**Comment by DarthGandalf** [comment]
**Comment by toma on 05 Oct 2009 18:36:18**
trac messed up my post.

This is the crashing line:

```
m_pConsole->output(KVI_OUT_VERBOSE,__tr2qs("Using server specific password (%s)"),szHidden.ptr());
```

bt:

```
Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#6  0x0813a2d9 in QString::isEmpty (this=0xbfa95348) at /opt/qt/4.6/include/QtCore/qstring.h:690
#7  0x081a11f3 in KviWindow::output (this=0xa4bbf30, msg_type=128, szFmt=...) at /mnt/data/kvirc/src/kvirc/ui/kvi_window.cpp:1296
#8  0x0824e2b8 in KviIrcConnection::loginToIrcServer (this=0xa524fb0) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircconnection.cpp:1126
#9  0x0825726a in KviIrcLink::socketStateChange (this=0xa689b58) at /mnt/data/kvirc/src/kvirc/kernel/kvi_irclink.cpp:349
#10 0x0825872b in KviIrcSocket::linkUp (this=0xa4dd778) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1379
#11 0x0825ad89 in KviIrcSocket::writeNotifierFired (this=0xa4dd778) at /mnt/data/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:452
#12 0x082825d4 in KviIrcSocket::qt_metacall (this=0xa4dd778, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0xbfa955ec) at /mnt/data/kvirc/build/src/kvirc/kernel/moc_kvi_ircsocket.cxx:76
#13 0xb65a7753 in QMetaObject::activate (sender=0xa68a498, from_signal_index=4, to_signal_index=4, argv=0xbfa955ec) at /kde/source/qt-copy/src/corelib/kernel/qobject.cpp:3109
#14 0xb65a7d02 in QMetaObject::activate (sender=0xa68a498, m=0xb663fd30, local_signal_index=0, argv=0xbfa955ec) at /kde/source/qt-copy/src/corelib/kernel/qobject.cpp:3186
#15 0xb65de993 in QSocketNotifier::activated (this=0xa68a498, _t1=13) at .moc/release-shared/moc_qsocketnotifier.cpp:83
#16 0xb65ad947 in QSocketNotifier::event (this=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/corelib/kernel/qsocketnotifier.cpp:316
#17 0xb6a6d724 in QApplicationPrivate::notify_helper (this=0xa1f6a38, receiver=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:4056
#18 0xb6a75f2e in QApplication::notify (this=0xa1f69a8, receiver=0xa68a498, e=0xbfa95990) at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:3603
#19 0xb5fdfdcb in KApplication::notify (this=0xa1f69a8, receiver=0xa68a498, event=0xbfa95990) at /kde/source/kdelibs/kdeui/kernel/kapplication.cpp:302
#20 0xb65953cb in QCoreApplication::notifyInternal (this=0xa1f69a8, receiver=0xa68a498, event=0xbfa95990) at /kde/source/qt-copy/src/corelib/kernel/qcoreapplication.cpp:606
#21 0xb65bc977 in QCoreApplication::sendEvent (source=0xa1fd590) at ../../include/QtCore/../../../../source/qt-copy/src/corelib/kernel/qcoreapplication.h:213
#22 socketNotifierSourceDispatch (source=0xa1fd590) at /kde/source/qt-copy/src/corelib/kernel/qeventdispatcher_glib.cpp:110
#23 0xb54d2368 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#24 0xb54d58c3 in ?? () from /usr/lib/libglib-2.0.so.0
#25 0xb54d5a48 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#26 0xb65bc6e8 in QEventDispatcherGlib::processEvents (this=0xa1f6408, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventdispatcher_glib.cpp:327
#27 0xb6afd095 in QGuiEventDispatcherGlib::processEvents (this=0xa1f6408, flags=...) at /kde/source/qt-copy/src/gui/kernel/qguieventdispatcher_glib.cpp:202
#28 0xb6593b8a in QEventLoop::processEvents (this=0xbfa95b80, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventloop.cpp:149
#29 0xb6593d52 in QEventLoop::exec (this=0xbfa95b80, flags=...) at /kde/source/qt-copy/src/corelib/kernel/qeventloop.cpp:197
#30 0xb6595f41 in QCoreApplication::exec () at /kde/source/qt-copy/src/corelib/kernel/qcoreapplication.cpp:888
#31 0xb6a6d5a7 in QApplication::exec () at /kde/source/qt-copy/src/gui/kernel/qapplication.cpp:3525
#32 0x0825f3e8 in main (argc=) at /mnt/data/kvirc/src/kvirc/kernel/kvi_main.cpp:471
```

**Comment by DarthGandalf** [comment]
**Modified by toma on 05 Oct 2009 18:46:37**

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 06 Oct 2009 08:12:33**
should be fixed on r3540 (at least valgrind now says it's okay)

---

Resolution: none → fixed
Status: new → closed
