### ISSUE TITLE
crash upon pasting logs

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#594]
**Reported by Deathvalley122 on 14 Oct 2009 00:47:09 UTC**
This backtrace appears to be of no use.
This is probably because your packages are built in a way which prevents creation of proper backtraces, or the stack frame was seriously corrupted in the crash.

[Thread debugging using libthread_db enabled]
[New Thread 0xb5c49700 (LWP 25013)]
0xb7fdc430 in __kernel_vsyscall ()
[Current thread is 0 (process 25013)]

Thread 1 (Thread 0xb5c49700 (LWP 25013)):
#0  0xb7fdc430 in __kernel_vsyscall ()
#1  0xb7f0d03b in waitpid () from /lib/tls/i686/cmov/libpthread.so.0
#2  0xb6e3d18f in ?? () from /usr/lib/libkdeui.so.5
#3  0xb6e3e0e3 in KCrash::defaultCrashHandler () from /usr/lib/libkdeui.so.5
#4  <signal handler called>
#5  0x08150160 in KviQuery::ownMessage ()
#6  0xbf9f6ac4 in ?? ()
#7  0xb699c170 in ?? () from /lib/tls/i686/cmov/libc.so.6

Backtrace stopped: previous frame inner to this frame (corrupt stack?)
#0  0xb7fdc430 in __kernel_vsyscall ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/594

**Comment by DarthGandalf** [comment]
**Comment by aeriana on 14 Oct 2009 01:07:58**
I can't reproduce it on r3555, reporter should get a debug build.

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 14 Oct 2009 01:09:50**
debug is installed but idk what seems to be the problem with the crashes

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 14 Oct 2009 22:06:37**
I have a crash if I paste 2 times slowly, no clue i

```
GNU gdb 6.8-debian
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu"...
(gdb) run
Starting program: /usr/local/bin/kvirc 
[Thread debugging using libthread_db enabled]
[New Thread 0x7fbeedc2f750 (LWP 17430)]
[New Thread 0x7fbecfdb8950 (LWP 17476)]
[Thread 0x7fbecfdb8950 (LWP 17476) exited]
[New Thread 0x7fbecfdb8950 (LWP 17477)]
[Thread 0x7fbecfdb8950 (LWP 17477) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fbeedc2f750 (LWP 17430)]
0x000000000050f523 in QString::isEmpty (this=0x38a38c0)
    at /usr/include/qt4/QtCore/qstring.h:690
690 inline bool QString::isEmpty() const
(gdb) bt full
#0  0x000000000050f523 in QString::isEmpty (this=0x38a38c0)
    at /usr/include/qt4/QtCore/qstring.h:690
No locals.
#1  0x00007fbeced9e21e in SPasteController::pasteClipboard (this=0x389e6a0)
    at /home/ambossarm/svn/kvirc/src/modules/spaste/controller.cpp:127
    line = {static null = {<No data fields>}, static shared_null = {ref = {
      _q_value = 15578}, alloc = 0, size = 0, data = 0x8e897a, clean = 0, 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, 
    reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 114}, 
    alloc = 0, size = 0, data = 0x7fbee9b4c83a, clean = 0, simpletext = 0, 
    righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, 
  d = 0x8e8960, static codecForCStrings = 0x1851050}
#2  0x00007fbeced9f262 in SPasteController::qt_metacall (this=0x389e6a0, 
    _c=QMetaObject::InvokeMetaMethod, _id=0, _a=<value optimized out>)
    at /home/ambossarm/svn/kvirc/make/src/modules/spaste/moc_controller.cxx:69
No locals.
#3  0x00007fbee986e962 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
No symbol table info available.
#4  0x00007fbee9868c43 in QObject::event () from /usr/lib/libQtCore.so.4
No symbol table info available.
#5  0x00007fbeeaea6b9d in QApplicationPrivate::notify_helper ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#6  0x00007fbeeaeaedea in QApplication::notify () from /usr/lib/libQtGui.so.4
No symbol table info available.
#7  0x00007fbee841984b in KApplication::notify () from /usr/lib/libkdeui.so.5
No symbol table info available.
#8  0x00007fbee9858e8c in QCoreApplication::notifyInternal ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#9  0x00007fbee9885f46 in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#10 0x00007fbee988265d in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#11 0x00007fbee578d20a in IA__g_main_context_dispatch (context=0x18729f0)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:1814
No locals.
#12 0x00007fbee57908e0 in g_main_context_iterate (context=0x18729f0, block=1, 
    dispatch=1, self=<value optimized out>)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2448
    max_priority = 0
    timeout = 0
    some_ready = 1
    nfds = 11
    allocated_nfds = <value optimized out>
    fds = (GPollFD *) 0x2872160
---Type <return> to continue, or q <return> to quit---
    __PRETTY_FUNCTION__ = "g_main_context_iterate"
#13 0x00007fbee5790a7c in IA__g_main_context_iteration (context=0x18729f0, 
    may_block=1) at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2511
    retval = <value optimized out>
#14 0x00007fbee98825bf in QEventDispatcherGlib::processEvents ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0x00007fbeeaf3f70f in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#16 0x00007fbee9857732 in QEventLoop::processEvents ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#17 0x00007fbee9857afd in QEventLoop::exec () from /usr/lib/libQtCore.so.4
No symbol table info available.
#18 0x00007fbee9859dc4 in QCoreApplication::exec ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#19 0x0000000000626ddb in main (argc=1, argv=0x7fffd9ec5ef8)
    at /home/ambossarm/svn/kvirc/src/kvirc/kernel/kvi_main.cpp:471
    a = {argc = 1, argv = 0x7fffd9ec5ef8, configFile = 0x0, 
  createFile = false, bForceNewSession = false, bShowPopup = false, 
  bShowSplashScreen = true, bExecuteCommandAndClose = false, 
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x184f8d0 "", 
---Type <return> to continue, or q <return> to quit---
    m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, 
    m_ptr = 0x184f8f0 "", m_len = 0}}
    retCode = <value optimized out>
    theApp = <value optimized out>
    fooArgv = {0x67d3cb "kvirc", 0x0}
    dpy = <value optimized out>
    colormap = 54525953
    visual = (<anonymous struct> *) 0x184f9d0
    szRemoteCommand = {<KviHeapObject> = {<No data fields>}, 
  m_ptr = 0x1b9d1b0 "", m_len = 0}
    retVal = <value optimized out>
(gdb) info registers
rax            0x4093d40000000000   4653295936468942848
rbx            0x7fffd9ec51c0   140736849531328
rcx            0x0  0
rdx            0x21 33
rsi            0x7fbee706f528   140457896506664
rdi            0x38a38c0    59390144
rbp            0x389e6a0    0x389e6a0
rsp            0x7fffd9ec5198   0x7fffd9ec5198
r8             0x3892f60    59322208
r9             0x7fffd9ec5980   140736849533312
r10            0x1  1
r11            0x1  1
r12            0x389e6d8    59369176
r13            0x7fffd9ec51b0   140736849531312
r14            0x0  0
r15            0x0  0
rip            0x50f523 0x50f523 <QString::isEmpty() const+3>
eflags         0x10202  [ IF RF ]
cs             0x33 51
ss             0x2b 43
ds             0x0  0
es             0x0  0
fs             0x0  0
---Type <return> to continue, or q <return> to quit---
gs             0x0  0
fctrl          0x37f    895
fstat          0x20 32
ftag           0xffff   65535
fiseg          0x7fbe   32702
fioff          0xe835b72e   -399132882
foseg          0x7fff   32767
fooff          0xd9ec15b8   -638839368
fop            0x4c 76
mxcsr          0x9fe0   [ PE DAZ IM DM ZM OM UM PM FZ ]
(gdb) x/16i $pc
0x50f523 <_ZNK7QString7isEmptyEv+3>:    mov    0x8(%rax),%eax
0x50f526 <_ZNK7QString7isEmptyEv+6>:    test   %eax,%eax
0x50f528 <_ZNK7QString7isEmptyEv+8>:    sete   %al
0x50f52b <_ZNK7QString7isEmptyEv+11>:   retq   
0x50f52c:   nop    
0x50f52d:   nop    
0x50f52e:   nop    
0x50f52f:   nop    
0x50f530 <_ZNK7QString9constDataEv>:    mov    (%rdi),%rax
0x50f533 <_ZNK7QString9constDataEv+3>:  mov    0x10(%rax),%rax
0x50f537 <_ZNK7QString9constDataEv+7>:  retq   
0x50f538:   nop    
0x50f539:   nop    
0x50f53a:   nop    
0x50f53b:   nop    
0x50f53c:   nop    
(gdb) thread apply all backtrace

Thread 1 (Thread 0x7fbeedc2f750 (LWP 17430)):
#0  0x000000000050f523 in QString::isEmpty (this=0x38a38c0)
    at /usr/include/qt4/QtCore/qstring.h:690
#1  0x00007fbeced9e21e in SPasteController::pasteClipboard (this=0x389e6a0)
    at /home/ambossarm/svn/kvirc/src/modules/spaste/controller.cpp:127
#2  0x00007fbeced9f262 in SPasteController::qt_metacall (this=0x389e6a0, 
    _c=QMetaObject::InvokeMetaMethod, _id=0, _a=<value optimized out>)
    at /home/ambossarm/svn/kvirc/make/src/modules/spaste/moc_controller.cxx:69
#3  0x00007fbee986e962 in QMetaObject::activate () from /usr/lib/libQtCore.so.4
#4  0x00007fbee9868c43 in QObject::event () from /usr/lib/libQtCore.so.4
#5  0x00007fbeeaea6b9d in QApplicationPrivate::notify_helper ()
   from /usr/lib/libQtGui.so.4
#6  0x00007fbeeaeaedea in QApplication::notify () from /usr/lib/libQtGui.so.4
#7  0x00007fbee841984b in KApplication::notify () from /usr/lib/libkdeui.so.5
#8  0x00007fbee9858e8c in QCoreApplication::notifyInternal ()
   from /usr/lib/libQtCore.so.4
#9  0x00007fbee9885f46 in ?? () from /usr/lib/libQtCore.so.4
#10 0x00007fbee988265d in ?? () from /usr/lib/libQtCore.so.4
#11 0x00007fbee578d20a in IA__g_main_context_dispatch (context=0x18729f0)
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:1814
#12 0x00007fbee57908e0 in g_main_context_iterate (context=0x18729f0, block=1, 
    dispatch=1, self=<value optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2448
#13 0x00007fbee5790a7c in IA__g_main_context_iteration (context=0x18729f0, 
    may_block=1) at /build/buildd/glib2.0-2.20.1/glib/gmain.c:2511
#14 0x00007fbee98825bf in QEventDispatcherGlib::processEvents ()
   from /usr/lib/libQtCore.so.4
#15 0x00007fbeeaf3f70f in ?? () from /usr/lib/libQtGui.so.4
#16 0x00007fbee9857732 in QEventLoop::processEvents ()
   from /usr/lib/libQtCore.so.4
#17 0x00007fbee9857afd in QEventLoop::exec () from /usr/lib/libQtCore.so.4
#18 0x00007fbee9859dc4 in QCoreApplication::exec ()
   from /usr/lib/libQtCore.so.4
#19 0x0000000000626ddb in main (argc=1, argv=0x7fffd9ec5ef8)
    at /home/ambossarm/svn/kvirc/src/kvirc/kernel/kvi_main.cpp:471

```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 24 Oct 2009 21:50:05**
fixed in r3569

---

Resolution: none → fixed
Status: new → closed
