### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#631]
**Reported by anonymous on 28 Nov 2009 20:12:29 UTC**
==== How to Reproduce ====

While doing a GET operation on `/ticket/630`, Trac issued an internal error.

''(please provide additional details here)''

Request parameters:

```
{'id': u'630'}
```

==== System Information ====

|| '''Trac''' || `0.11.1` ||
|| '''Python''' || `2.5.2 (r252:60911, Jan  4 2009, 18:00:02)` <br/> `[GCC 4.3.2]` ||
|| '''setuptools''' || `0.6c8` ||
|| '''SQLite''' || `3.5.9` ||
|| '''pysqlite''' || `2.4.1` ||
|| '''Genshi''' || `0.5.1` ||
|| '''mod_python''' || `3.3.1` ||
|| '''Subversion''' || `1.5.1 (r32289)` ||

==== Python Traceback ====

```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/trac/web/main.py", line 423, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.5/site-packages/trac/web/main.py", line 222, in dispatch
    req.session.save()
  File "/usr/lib/python2.5/site-packages/trac/web/session.py", line 130, in save
    db.commit()
OperationalError: database is locked

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/631

**Comment by DarthGandalf** [comment]
**Comment by mren on 28 Nov 2009 20:16:10**
WFM, try reloading the page

---

Resolution: none → invalid
Status: new → closed
