### ISSUE TITLE
Crash on nick change

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#659]
**Reported by HelLViS69 on 20 Dec 2009 04:50:37 UTC**
Sometimes, changing nick, KVIrc hangs with a segmentation fault due to animated avatar.<br/>
I investigated a bit but didn't understand with which logic it happens. I've experienced this crash at random only when I connect through a bnc.

This is the stack:

```
(gdb) bt full                                                                             
#0  0x00007ffd059ced7a in QObject::disconnect () from /usr/lib64/libQtCore.so.4           
No symbol table info available.                                                           
#1  0x0000000000558593 in KviUserListView::nickChange (this=0x1e126e0,                    
    szOldNick=@0x3ff4c98, szNewNick=@0x7fff9b8dd690)                                      
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_userlistview.cpp:1306                                                                                        
        szUser = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x4244dd0,                              
  static codecForCStrings = 0x1904320}                                                    
        pAv = (KviAvatar *) 0x403a730                                                     
        szHost = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x42d7ef0,                              
  static codecForCStrings = 0x1904320}                                                    
        joint = 1261284352                                                                
        bSelect = false                                                                   
        gender = <value optimized out>                                                    
        bBot = <value optimized out>                                                      
        pEntry = (KviUserListEntry *) 0x4009910                                           
#2  0x00000000005fe51e in KviIrcConnection::nickChange (this=0x3ff8290,                   
    szNewNick=@0x7fff9b8dd690)                                                            
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnection.c---Type <return> to continue, or q <return> to quit---                                    
pp:1239                                                                                   
No locals.                                                                                
#3  0x000000000056ceae in KviServerParser::parseLiteralNick (this=<value optimized out>,  
    msg=0x7fff9b8dd720)                                                                   
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sp_literal.cpp:1454                                                                                     
        szNick = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x41d9fd0,                              
  static codecForCStrings = 0x1904320}                                                    
        szUser = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x42dd360,                              
  static codecForCStrings = 0x1904320}                                                    
        szHost = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x42d7890,                              
  static codecForCStrings = 0x1904320}                                                    
        console = (class KviConsole *) 0x1e030b0                                          
        szNewNick = {static null = {<No data fields>}, static shared_null = {ref = {      
---Type <return> to continue, or q <return> to quit---                                    
      _q_value = 15057}, alloc = 0, size = 0, data = 0x8d613a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 103}, alloc = 0, size = 0,     
    data = 0x7ffd05cafc9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x42df6f0,                              
  static codecForCStrings = 0x1904320}                                                    
        bIsMe = <value optimized out>                                                     
        q = <value optimized out>                                                         
        old = <value optimized out>                                                       
#4  0x000000000057bfaf in KviServerParser::parseMessage (this=0x1b476e0,                  
    message=<value optimized out>, pConnection=0x3ff8290)                                 
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sparser.cpp:105                                                                                         
        i = <value optimized out>                                                         
        msg = {m_ptr = 0x42d8da6 ":HelL`TeSt",                                            
  m_szPrefix = {<KviHeapObject> = {<No data fields>},                                     
    m_ptr = 0x42df370 "HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net", m_len = 47},     
  m_szCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x42605b0 "NICK",          
    m_len = 4}, m_pParams = 0x42d7850, m_pConsole = 0x1e030b0,                            
  m_pConnection = 0x3ff8290, m_iNumericCommand = -1, m_iFlags = 0}                        
#5  0x000000000060b150 in KviIrcLink::processData (this=0x3ffc530,                        
    buffer=<value optimized out>, iLen=<value optimized out>)                             
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_irclink.cpp:272
        p = <value optimized out>                                                         
        cBeginOfCurData = 0x7fff9b8dd860 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`TeSt\r\n"                                                                     
        cMessageBuffer = 0x42d8d70 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`TeSt"                                                                               
---Type <return> to continue, or q <return> to quit---                                    
#6  0x000000000060cfa3 in KviIrcSocket::readData (this=0x3ff74e0)                         
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1484                                                                                       
        cBuffer = ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`TeSt\r\n\000\233ÿ\177\000\000`Ú\215\233ÿ\177\000\000ðÚ\215\233ÿ\177\000\000\200Ú\215\233ÿ\177\000\000@\000\000\000\000\000\000\000\000\234-\004\000\000\000\000\002\000\000\000\000\000\000\0000A¶\001\000\000\000\000ÐÛ\215\233ÿ\177\000\000\200Û\215\233ÿ\177\000\000\020Ü\215\233ÿ\177\000\000\021«\000\000ý\177\000\0000Ù\215\233ÿ\177\000\000\000\000\000\000\000\000\000\000¶\000\000\0006\000\000\000ÿ\003\000\000·\002\000\000 \000\000\000\000\000\000\000"...      
        iReadLength = 66                                                                  
#7  0x000000000063090e in KviIrcSocket::qt_metacall (this=0x3ff74e0,                      
    _c=QMetaObject::InvokeMetaMethod, _id=<value optimized out>, _a=0x7fff9b8ddda0)       
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/debug/src/kvirc/kernel/moc_kvi_ircsocket.cxx:77                                                                               
No locals.                                                                                
#8  0x00007ffd059cf232 in QMetaObject::activate () from /usr/lib64/libQtCore.so.4         
No symbol table info available.                                                           
#9  0x00007ffd05a0668e in QSocketNotifier::activated () from /usr/lib64/libQtCore.so.4    
No symbol table info available.                                                           
#10 0x00007ffd059d3e03 in QSocketNotifier::event () from /usr/lib64/libQtCore.so.4        
No symbol table info available.                                                           
#11 0x00007ffd07fd3b2d in QApplicationPrivate::notify_helper ()                           
   from /usr/lib64/libQtGui.so.4                                                          
No symbol table info available.                                                           
#12 0x00007ffd07fdbd9a in QApplication::notify () from /usr/lib64/libQtGui.so.4           
No symbol table info available.                                                           
#13 0x00007ffd042748db in KApplication::notify () from /usr/lib64/libkdeui.so.5           
No symbol table info available.                                                           
#14 0x00007ffd059b9b0c in QCoreApplication::notifyInternal ()                             
---Type <return> to continue, or q <return> to quit---                                    
   from /usr/lib64/libQtCore.so.4                                                         
No symbol table info available.                                                           
#15 0x00007ffd059e3199 in ?? () from /usr/lib64/libQtCore.so.4                            
No symbol table info available.                                                           
#16 0x00007ffd053bc28b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0     
No symbol table info available.                                                           
#17 0x00007ffd053bfa4d in ?? () from /usr/lib64/libglib-2.0.so.0                          
No symbol table info available.                                                           
#18 0x00007ffd053bfc0b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0    
No symbol table info available.
#19 0x00007ffd059e2e4c in QEventDispatcherGlib::processEvents ()
   from /usr/lib64/libQtCore.so.4
No symbol table info available.
#20 0x00007ffd0806b40f in ?? () from /usr/lib64/libQtGui.so.4
No symbol table info available.
#21 0x00007ffd059b83a2 in QEventLoop::processEvents () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#22 0x00007ffd059b8774 in QEventLoop::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#23 0x00007ffd059baa44 in QCoreApplication::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#24 0x0000000000612224 in main (argc=1, argv=0x7fff9b8de8d8)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_main.cpp:486
        a = {argc = 1, argv = 0x7fff9b8de8d8, configFile = 0x0, createFile = false,
  bForceNewSession = false, bShowPopup = false, bShowSplashScreen = true,
  bExecuteCommandAndClose = false,
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x1903110 "",
    m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>},
    m_ptr = 0x1903130 "", m_len = 0}}
---Type <return> to continue, or q <return> to quit---
        iRetCode = <value optimized out>
        pTheApp = <value optimized out>
        pDisplay = (Display *) 0x193d7a0
        colormap = 44040193
        pVisual = (<anonymous struct> *) 0x1948d10
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x19aae10 "",
  m_len = 0}
        iRetVal = <value optimized out>
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/659

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 20 Dec 2009 14:09:32**
fixed in r3717,  please test

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by anonymous on 22 Dec 2009 02:52:45**
The bug still exists, the stack is the same... I'm a bit confused atm..

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 23 Dec 2009 17:46:20**
Fixed on r3738

---

Resolution: none → fixed
Status: reopened → closed

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 23 Dec 2009 17:52:32**
Closed wrong ticket :(

---

Resolution: fixed → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 01 Jan 2010 17:23:45**
is it fixed with r3778?

---

Resolution: none → fixed
Status: reopened → closed
