### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#67]
**Reported by ossi on 20 Jan 2008 09:27:36 UTC**
svn trunk as of today.

Using host libthread_db library "/lib/libthread_db.so.1".
[Thread debugging using libthread_db enabled]
[New Thread 0xa5ec46c0 (LWP 31226)]
[KCrash handler]
#5  KviKvsParser::parseSpecialCommandDefpopupLabelPopup (this=0xaf8424b0)

```
at /home/ossi/src/kde/3.5/kvirc/src/kvilib/include/kvi_pointerlist.h:650
```
#6  0x081952c2 in KviKvsParser::parseSpecialCommandDefpopup (this=0xaf8424b0)

```
at ../kvs/kvi_kvs_parser_specialcommands.cpp:1949
```
#7  0x08190d33 in KviKvsParser::parseCommand (this=0xaf8424b0)

```
at ../kvs/kvi_kvs_parser_command.cpp:190
```
#8  0x0818e29b in KviKvsParser::parseInstructionList (this=0xaf8424b0)

```
at ../kvs/kvi_kvs_parser.cpp:2364
```
#9  0x081a117e in KviKvsScript::parse (this=0xaf8425b0,

```
pOutput=<value optimized out>, iRunFlags=<value optimized out>)
at ../kvs/kvi_kvs_script.cpp:279
```
#10 0x081a1265 in KviKvsScript::run (this=0xaf8425b0, pWnd=0x83cdd40,

```
pParams=0xaf8425d0, pRetVal=0x0, iRunFlags=1, pExtData=0xaf842564)
at ../kvs/kvi_kvs_script.cpp:195
```
#11 0x0817979f in KviKvsCoreSimpleCommands::parse (__pContext=0xaf842698,

```
__pParams=0xaf842618, __pSwitches=0xaf842610)
at ../kvs/kvi_kvs_coresimplecommands_mr.cpp:656
```
#12 0x081a8483 in KviKvsTreeNodeCoreSimpleCommand::execute (this=0x83def18,

```
c=0xaf842698) at ../kvs/kvi_kvs_treenode_coresimplecommand.cpp:69
```
#13 0x081acfcd in KviKvsTreeNodeInstructionBlock::execute (this=0x84bb988,

```
c=0xaf842698) at ../kvs/kvi_kvs_treenode_instructionblock.cpp:84
```
#14 0x081a0db2 in KviKvsScript::executeInternal (this=0xaf842770,

```
pContext=0xaf842698) at ../kvs/kvi_kvs_script.cpp:298
```
#15 0x081a0ead in KviKvsScript::execute (this=0xaf842770, pWnd=0x83cdd40,

```
pParams=0xaf842790, pRetVal=0x84d0648, iRunFlags=<value optimized out>, 
pExtData=0xaf842724) at ../kvs/kvi_kvs_script.cpp:346
```
#16 0x0817979f in KviKvsCoreSimpleCommands::parse (__pContext=0xaf842838,

```
__pParams=0xaf8427d8, __pSwitches=0xaf8427d0)
at ../kvs/kvi_kvs_coresimplecommands_mr.cpp:656
```
#17 0x081a8483 in KviKvsTreeNodeCoreSimpleCommand::execute (this=0x83395f8,

```
c=0xaf842838) at ../kvs/kvi_kvs_treenode_coresimplecommand.cpp:69
```
#18 0x081a0db2 in KviKvsScript::executeInternal (this=0xaf8428a0,

```
pContext=0xaf842838) at ../kvs/kvi_kvs_script.cpp:298
```
#19 0x081a0ead in KviKvsScript::execute (this=0xaf8428a0, pWnd=0x83cdd40,

```
pParams=0x8322720, pRetVal=0x84b8928, iRunFlags=<value optimized out>, 
pExtData=0x0) at ../kvs/kvi_kvs_script.cpp:346
```
#20 0x081a15a4 in KviKvsScript::run (szCode=@0xaf8428cc, pWindow=0x83cdd40,

```
pParams=0x0, pRetVal=0x0) at ../kvs/kvi_kvs_script.cpp:157
```
#21 0x0812bc56 in KviApp::loadDefaultScript (this=0x83010d0)

```
at ../kernel/kvi_app.cpp:732
```
#22 0x0812bd19 in KviApp::restoreDefaultScript (this=0x83010d0)

```
at ../kernel/kvi_app.cpp:841
```
#23 0x0812ed7d in KviApp::setup (this=0x83010d0) at ../kernel/kvi_app.cpp:512
#24 0x08151d1e in main (argc=2, argv=0xaf842a64) at ../kernel/kvi_main.cpp:403

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/67

**Comment by DarthGandalf** [comment]
**Comment by mren on 25 Feb 2008 13:55:24**
Should be fixed now (r1148)

---

Resolution: none → fixed
Status: new → closed
