### ISSUE TITLE
Random Crash when use "options"

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#687]
**Reported by Falko on 11 Jan 2010 07:22:46 UTC**
Application: KVIrc (kvirc4), signal: Segmentation fault
[KCrash Handler]
#5  0x00007fb54b2ae10e in ?? () from /usr/lib64/kvirc/4.0/modules/libkvioptions.so
#6  0x00000000005bb514 in KviKvsTreeNodeModuleSimpleCommand::execute(KviKvsRunTimeContext*) ()
#7  0x00000000005a8d74 in KviKvsScript::executeInternal(KviKvsRunTimeContext*) ()
#8  0x00000000005a8e50 in KviKvsScript::execute(KviWindow_, KviKvsVariantList_, KviKvsVariant_, int, KviKvsExtendedRunTimeData_) ()
#9  0x0000000000639aa4 in KviAction::qt_metacall(QMetaObject::Call, int, void**) ()
#10 0x00007fb5610bf43e in QMetaObject::activate(QObject_, int, int, void_*) () from /usr/lib64/qt4/libQtCore.so.4
#11 0x00007fb5610c348e in QSignalMapper::mapped(int) () from /usr/lib64/qt4/libQtCore.so.4
#12 0x00007fb5610c3530 in QSignalMapper::map(QObject*) () from /usr/lib64/qt4/libQtCore.so.4
#13 0x00007fb5610c4700 in QSignalMapper::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
#14 0x00007fb5610bf43e in QMetaObject::activate(QObject_, int, int, void_*) () from /usr/lib64/qt4/libQtCore.so.4
#15 0x00007fb561ede807 in QAction::triggered(bool) () from /usr/lib64/qt4/libQtGui.so.4
#16 0x00007fb561edfa60 in QAction::activate(QAction::ActionEvent) () from /usr/lib64/qt4/libQtGui.so.4
#17 0x00007fb56225eeb4 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#18 0x00007fb562264abb in ?? () from /usr/lib64/qt4/libQtGui.so.4
#19 0x00007fb561f2fdd8 in QWidget::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#20 0x00007fb562266053 in QMenu::event(QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#21 0x00007fb561ee3aad in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib64/qt4/libQtGui.so.4
#22 0x00007fb561eeb983 in QApplication::notify(QObject_, QEvent_) () from /usr/lib64/qt4/libQtGui.so.4
#23 0x00007fb56493886b in KApplication::notify(QObject_, QEvent_) () from /usr/lib64/libkdeui.so.5
#24 0x00007fb5610ad953 in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib64/qt4/libQtCore.so.4
#25 0x00007fb561eece08 in QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget**, QPointer<QWidget>&) () from /usr/lib64/qt4/libQtGui.so.4
#26 0x00007fb561f45413 in ?? () from /usr/lib64/qt4/libQtGui.so.4
#27 0x00007fb561f43de6 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#28 0x00007fb561f6804c in ?? () from /usr/lib64/qt4/libQtGui.so.4
#29 0x00007fb55bdf7e61 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#30 0x00007fb55bdfb3f8 in ?? () from /usr/lib/libglib-2.0.so.0
#31 0x00007fb55bdfb5ac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#32 0x00007fb5610d1d1f in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/qt4/libQtCore.so.4
#33 0x00007fb561f6791f in ?? () from /usr/lib64/qt4/libQtGui.so.4
#34 0x00007fb5610ac382 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/qt4/libQtCore.so.4
#35 0x00007fb5610ac51c in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/qt4/libQtCore.so.4
#36 0x00007fb5610ae4b4 in QCoreApplication::exec() () from /usr/lib64/qt4/libQtCore.so.4
#37 0x0000000000615f41 in ?? ()
#38 0x00007fb55e82aa26 in __libc_start_main () from /lib64/libc.so.6
#39 0x000000000049c6f9 in _start ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/687

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 13 Jan 2010 22:34:58**
should have been fixed with r3836, please test

---

Resolution: none → fixed
Status: new → closed
