### ISSUE TITLE
kvirc crashes randomly changing nick

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#689]
**Reported by HelLViS69 on 12 Jan 2010 01:10:33 UTC**

```
Application: KVIrc (kvirc), signal: Segmentation fault
[KCrash Handler]
#5  0x00007f7e32b8680d in QMetaObject::indexOfSignal () from /usr/lib64/libQtCore.so.4
#6  0x00007f7e32b95db8 in QObject::disconnect () from /usr/lib64/libQtCore.so.4
#7  0x00000000004fbba7 in KviUserListView::nickChange (this=0x1bf3430, szOldNick=@0x3f6c538, szNewNick=@0x7fff3659b100)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_userlistview.cpp:1305
#8  0x000000000059f80d in KviIrcConnection::nickChange (this=0x3f69470, szNewNick=@0x7fff3659b100) at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnection.cpp:1239
#9  0x0000000000510106 in KviServerParser::parseLiteralNick (this=<value optimized out>, msg=0x7fff3659b190)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sp_literal.cpp:1454
#10 0x000000000051ef70 in KviServerParser::parseMessage (this=0x1b2fbf0, message=<value optimized out>, pConnection=0x3f69470)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sparser.cpp:105
#11 0x00000000005ac03f in KviIrcLink::processData (this=0x3f71da0, buffer=<value optimized out>, iLen=<value optimized out>)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_irclink.cpp:272
#12 0x00000000005adebc in KviIrcSocket::readData (this=0x3f38280) at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1484
#13 0x00000000005d1bae in KviIrcSocket::qt_metacall (this=0x3f38280, _c=QMetaObject::InvokeMetaMethod, _id=<value optimized out>, _a=0x7fff3659b820)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/debug/src/kvirc/moc_kvi_ircsocket.cxx:77
#14 0x00007f7e32b96232 in QMetaObject::activate () from /usr/lib64/libQtCore.so.4
#15 0x00007f7e32bcd68e in QSocketNotifier::activated () from /usr/lib64/libQtCore.so.4
#16 0x00007f7e32b9ae03 in QSocketNotifier::event () from /usr/lib64/libQtCore.so.4
#17 0x00007f7e33a5ab2d in QApplicationPrivate::notify_helper () from /usr/lib64/libQtGui.so.4
#18 0x00007f7e33a62d9a in QApplication::notify () from /usr/lib64/libQtGui.so.4
#19 0x00007f7e3679b8db in KApplication::notify () from /usr/lib64/libkdeui.so.5
#20 0x00007f7e32b80b0c in QCoreApplication::notifyInternal () from /usr/lib64/libQtCore.so.4
#21 0x00007f7e32baa199 in ?? () from /usr/lib64/libQtCore.so.4
#22 0x00007f7e2d33b28b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#23 0x00007f7e2d33ea4d in ?? () from /usr/lib64/libglib-2.0.so.0
#24 0x00007f7e2d33ec0b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#25 0x00007f7e32ba9e4c in QEventDispatcherGlib::processEvents () from /usr/lib64/libQtCore.so.4
#26 0x00007f7e33af240f in ?? () from /usr/lib64/libQtGui.so.4
#27 0x00007f7e32b7f3a2 in QEventLoop::processEvents () from /usr/lib64/libQtCore.so.4
#28 0x00007f7e32b7f774 in QEventLoop::exec () from /usr/lib64/libQtCore.so.4
#29 0x00007f7e32b81a44 in QCoreApplication::exec () from /usr/lib64/libQtCore.so.4
#30 0x00000000005b3124 in main (argc=2, argv=0x7fff3659c388) at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_main.cpp:488
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/689

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 12 Jan 2010 13:41:25**
Another crash.<br/>
Just entered a channel and went away (changing nick)

```
(gdb) bt full                                                                             
#0  0x0000000000000002 in ?? ()                                                           
No symbol table info available.                                                           
#1  0x00000000005e2630 in ?? ()                                                           
No symbol table info available.                                                           
#2  0x00000000028dd060 in ?? ()                                                           
No symbol table info available.                                                           
#3  0x00000000005e26a0 in ?? ()                                                           
No symbol table info available.                                                           
#4  0x0000000004ad96c0 in ?? ()                                                           
No symbol table info available.                                                           
#5  0x00007fff29fee460 in ?? ()                                                           
No symbol table info available.                                                           
#6  0x00000000fffffffd in ?? ()                                                           
No symbol table info available.                                                           
#7  0x0000000004b82ca9 in ?? ()                                                           
No symbol table info available.                                                           
#8  0x0000000004b2ce39 in ?? ()                                                           
No symbol table info available.                                                           
#9  0x0000000004ad96c0 in ?? ()                                                           
No symbol table info available.                                                           
#10 0x00000000005e26a0 in ?? ()                                                           
No symbol table info available.                                                           
#11 0x00000000028dd060 in ?? ()                                                           
No symbol table info available.                                                           
#12 0x00000000005e2630 in ?? ()                                                           
No symbol table info available.                                                           
#13 0x0000000004b2ce20 in ?? ()                                                           
No symbol table info available.                                                           
#14 0x0000000000000008 in ?? ()                                                           
---Type <return> to continue, or q <return> to quit---                                    
No symbol table info available.                                                           
#15 0x00007fca84714adc in ?? () from /usr/lib64/libQtCore.so.4                            
No symbol table info available.                                                           
#16 0x00007fca84714e4d in ?? () from /usr/lib64/libQtCore.so.4                            
No symbol table info available.                                                           
#17 0x00007fca88bfa3da in QTextCodec::toUnicode (this=0x7fff29fee3a0,                     
    in=0x4ad96c0 " là\004", length=78827040, state=0x5e2630)                              
    at /usr/lib64/qt/include/QtCore/qtextcodec.h:116                                      
No locals.                                                                                
#18 0x00007fca88bfa4b3 in KviSmartTextCodec::convertToUnicode (this=0x4ac5ac8,            
    chars=0x4b4c7951 <Address 0x4b4c7951 out of bounds>, len=704570704,                   
    state=<value optimized out>)                                                          
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvilib/system/kvi_locale.cpp:302
No locals.                                                                                
#19 0x00000000028c3f40 in ?? ()                                                           
No symbol table info available.                                                           
#20 0x00007fff29fee5e0 in ?? ()                                                           
No symbol table info available.                                                           
#21 0x000000000059f74d in KviIrcConnection::nickChange (this=0x4ac63a0,                   
    szNewNick=@0x7fff29fee550)                                                            
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnection.cpp:1239                                                                                   
No locals.                                                                                
#22 0x0000000000510046 in KviServerParser::parseLiteralNick (this=<value optimized out>,  
    msg=0x7fff29fee5e0)                                                                   
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sp_literal.cpp:1454                                                                                     
        szNick = {static null = {<No data fields>}, static shared_null = {ref = {         
---Type <return> to continue, or q <return> to quit---                                    
      _q_value = 15955}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 109}, alloc = 0, size = 0,     
    data = 0x7fca849d7c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x4dcc920,                              
  static codecForCStrings = 0x23c0520}                                                    
        szUser = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15955}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 109}, alloc = 0, size = 0,     
    data = 0x7fca849d7c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x4e5aeb0,                              
  static codecForCStrings = 0x23c0520}                                                    
        console = (class KviConsole *) 0x4fbae7                                           
        q = <value optimized out>                                                         
        old = <value optimized out>                                                       
        szHost = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15955}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 109}, alloc = 0, size = 0,     
    data = 0x7fca849d7c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x4b395e0,                              
  static codecForCStrings = 0x23c0520}                                                    
        szNewNick = {static null = {<No data fields>}, static shared_null = {ref = {      
      _q_value = 15955}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 109}, alloc = 0, size = 0,     
    data = 0x7fca849d7c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x4d2a360,                              
---Type <return> to continue, or q <return> to quit---                                    
  static codecForCStrings = 0x23c0520}                                                    
        bIsMe = <value optimized out>                                                     
#23 0x000000000051eeb0 in KviServerParser::parseMessage (this=0x263acd0,                  
    message=<value optimized out>, pConnection=0x4ac63a0)                                 
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sparser.cpp:105                                                                                         
        i = <value optimized out>                                                         
        msg = {m_ptr = 0x4d9d146 ":HelL`Out",                                             
  m_szPrefix = {<KviHeapObject> = {<No data fields>},                                     
    m_ptr = 0x4a255e0 "HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net", m_len = 47},     
  m_szCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x4de31f0 "NICK",          
    m_len = 4}, m_pParams = 0x4c3d350, m_pConsole = 0x28c3f40,                            
  m_pConnection = 0x4ac63a0, m_iNumericCommand = -1, m_iFlags = 0}                        
#24 0x00000000005abf7f in KviIrcLink::processData (this=0x4ab9330,                        
    buffer=<value optimized out>, iLen=<value optimized out>)                             
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_irclink.cpp:272
        p = <value optimized out>                                                         
        cBeginOfCurData = 0x7fff29fee730 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out\r\n"                                                                      
        cMessageBuffer = 0x4d9d110 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out"                                                                                
#25 0x00000000005addfc in KviIrcSocket::readData (this=0x293c900)                         
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1484                                                                                       
        cBuffer = ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out\r\n\000þ)ÿ\177\000\0000éþ)ÿ\177\000\000Àéþ)ÿ\177\000\000Péþ)ÿ\177\000\000Ðñ\210\002\000\000\000\0000Ñ´\004\000\000\000\000\002\000\000\000\000\000\000\000\200!k\002\000\000\000\000 êþ)ÿ\177\000\000Pêþ)ÿ\177\000\000àêþ)ÿ\177\000\000\000\230\000\000\000\000\000\000\000èþ)ÿ\177\0---Type <return> to continue, or q <return> to quit---                                    
00\000\f\035ª\205Ê\177\000\000\000\000\000\000\000\000\000\000¬\000\000\000z\002\000\000 \000\000\000\000\000\000\000"...                                                           
        iReadLength = 65                                                                  
#26 0x00000000005d1aee in KviIrcSocket::qt_metacall (this=0x293c900,                      
    _c=QMetaObject::InvokeMetaMethod, _id=<value optimized out>, _a=0x7fff29feec70)       
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/debug/src/kvirc/moc_kvi_ircsocket.cxx:77                                                                                      
No locals.                                                                                
#27 0x00007fca846f7232 in QMetaObject::activate () from /usr/lib64/libQtCore.so.4         
No symbol table info available.                                                           
#28 0x00007fca8472e68e in QSocketNotifier::activated () from /usr/lib64/libQtCore.so.4    
No symbol table info available.                                                           
#29 0x00007fca846fbe03 in QSocketNotifier::event () from /usr/lib64/libQtCore.so.4        
No symbol table info available.                                                           
#30 0x00007fca855bbb2d in QApplicationPrivate::notify_helper ()                           
   from /usr/lib64/libQtGui.so.4                                                          
No symbol table info available.                                                           
#31 0x00007fca855c3d9a in QApplication::notify () from /usr/lib64/libQtGui.so.4           
No symbol table info available.                                                           
#32 0x00007fca882fc8db in KApplication::notify () from /usr/lib64/libkdeui.so.5           
No symbol table info available.                                                           
#33 0x00007fca846e1b0c in QCoreApplication::notifyInternal ()                             
   from /usr/lib64/libQtCore.so.4                                                         
No symbol table info available.                                                           
#34 0x00007fca8470b199 in ?? () from /usr/lib64/libQtCore.so.4                            
No symbol table info available.                                                           
#35 0x00007fca7ee9c28b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0     
No symbol table info available.                                                           
#36 0x00007fca7ee9fa4d in ?? () from /usr/lib64/libglib-2.0.so.0                          
---Type <return> to continue, or q <return> to quit---                                    
No symbol table info available.                                                           
#37 0x00007fca7ee9fc0b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0    
No symbol table info available.
#38 0x00007fca8470ae4c in QEventDispatcherGlib::processEvents ()
   from /usr/lib64/libQtCore.so.4
No symbol table info available.
#39 0x00007fca8565340f in ?? () from /usr/lib64/libQtGui.so.4
No symbol table info available.
#40 0x00007fca846e03a2 in QEventLoop::processEvents () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#41 0x00007fca846e0774 in QEventLoop::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#42 0x00007fca846e2a44 in QCoreApplication::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#43 0x00000000005b3064 in main (argc=1, argv=0x7fff29fef7d8)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_main.cpp:488
        a = {argc = 1, argv = 0x7fff29fef7d8, configFile = 0x0, createFile = false,
  bForceNewSession = false, bShowPopup = false, bShowSplashScreen = true,
  bExecuteCommandAndClose = false,
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x23bf2b0 "",
    m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>},
    m_ptr = 0x23bf2d0 "", m_len = 0}}
        pDisplay = <value optimized out>
        iRetVal = <value optimized out>
        iRetCode = <value optimized out>
        pTheApp = <value optimized out>
        colormap = 4194305
        pVisual = (<anonymous struct> *) 0x24051a0
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x241b970 "",
---Type <return> to continue, or q <return> to quit---
  m_len = 0}
```

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 12 Jan 2010 13:48:09**
Same operations, same crash

```
(gdb) bt full                                                              
#0  0x00007f843f5a1d7a in QObject::disconnect () from /usr/lib64/libQtCore.so.4
No symbol table info available.                                                
#1  0x00000000004fbae7 in KviUserListView::nickChange (this=0x132a070,         
    szOldNick=@0x35060d8, szNewNick=@0x7fffaeef4fb0)                           
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/ui/kvi_userlistview.cpp:1305                                                                                        
        szUser = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 105}, alloc = 0, size = 0,     
    data = 0x7f843f882c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x37d4a60,                              
  static codecForCStrings = 0xe0d520}                                                     
        pAv = <value optimized out>                                                       
        szHost = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = {ref = {_q_value = 105}, alloc = 0, size = 0,     
    data = 0x7f843f882c9a, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0,    
    capacity = 0, reserved = 0, array = {0}}, d = 0x37d4e10,                              
  static codecForCStrings = 0xe0d520}                                                     
        joint = 1263303625                                                                
        bSelect = false                                                                   
        gender = <value optimized out>                                                    
        bBot = <value optimized out>                                                      
        pEntry = (KviUserListEntry *) 0x10dbdc0                                           
#2  0x000000000059f74d in KviIrcConnection::nickChange (this=0x3503990,                   
    szNewNick=@0x7fffaeef4fb0)                                                            
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircconnection.c---Type <return> to continue, or q <return> to quit---                                    
pp:1239                                                                                   
No locals.                                                                                
#3  0x0000000000510046 in KviServerParser::parseLiteralNick (this=<value optimized out>,  
    msg=0x7fffaeef5040)                                                                   
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sp_literal.cpp:1454                                                                                     
        szNick = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = <error reading variable>                          
        szUser = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = <error reading variable>                          
        console = (class KviConsole *) 0x1310fd0                                          
        q = <value optimized out>                                                         
        old = <value optimized out>                                                       
        szHost = {static null = {<No data fields>}, static shared_null = {ref = {         
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = <error reading variable>                          
        szNewNick = {static null = {<No data fields>}, static shared_null = {ref = {      
      _q_value = 15580}, alloc = 0, size = 0, data = 0x87a03a, clean = 0,                 
    simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0,          
    array = {0}}, static shared_empty = <error reading variable>                          
        bIsMe = <value optimized out>                                                     
#4  0x000000000051eeb0 in KviServerParser::parseMessage (this=0x10781a0,                  
    message=<value optimized out>, pConnection=0x3503990)                                 
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/sparser/kvi_sparser.cpp:10---Type <return> to continue, or q <return> to quit---                                    
5                                                                                         
        i = <value optimized out>                                                         
        msg = {m_ptr = 0x1043376 ":HelL`Out",                                             
  m_szPrefix = {<KviHeapObject> = {<No data fields>},                                     
    m_ptr = 0x34cbf70 "HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net", m_len = 47},     
  m_szCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x35199d0 "NICK",          
    m_len = 4}, m_pParams = 0x36591a0, m_pConsole = 0x1310fd0,                            
  m_pConnection = 0x3503990, m_iNumericCommand = -1, m_iFlags = 0}                        
#5  0x00000000005abf7f in KviIrcLink::processData (this=0x3506b40,                        
    buffer=<value optimized out>, iLen=<value optimized out>)                             
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_irclink.cpp:272
        p = <value optimized out>                                                         
        cBeginOfCurData = 0x7fffaeef5190 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out\r\n"                                                                      
        cMessageBuffer = 0x1043340 ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out"                                                                                
#6  0x00000000005addfc in KviIrcSocket::readData (this=0x351a220)                         
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_ircsocket.cpp:1484                                                                                       
        cBuffer = ":HelLViS69!~BlackStar@cl-429.trn-01.it.sixxs.net NICK :HelL`Out\r\n\000ï®ÿ\177\000\000\220Sï®ÿ\177\000\000 Tï®ÿ\177\000\000°Sï®ÿ\177\000\000 ç.\001\000\000\000\000p\016j\003\000\000\000\000\002\000\000\000\000\000\000\000Ð§\006\001\000\000\000\000\000Uï®ÿ\177\000\000°Tï®ÿ\177\000\000@Uï®ÿ\177\000\000À8\000\000\000\000\000\000`Rï®ÿ\177\000\000\fÍ\224@\204\177\000\000\000\000\000\000\000\000\000\000¬\000\000\000z\002\000\000 \000\000\000\000\000\000\000"...                                                              
        iReadLength = 65                                                                  
#7  0x00000000005d1aee in KviIrcSocket::qt_metacall (this=0x351a220,                      
    _c=QMetaObject::InvokeMetaMethod, _id=<value optimized out>, _a=0x7fffaeef56d0)       
---Type <return> to continue, or q <return> to quit---                                    
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/debug/src/kvirc/moc_kvi_ircsocket.cxx:77                                                                                      
No locals.                                                                                
#8  0x00007f843f5a2232 in QMetaObject::activate () from /usr/lib64/libQtCore.so.4         
No symbol table info available.                                                           
#9  0x00007f843f5d968e in QSocketNotifier::activated () from /usr/lib64/libQtCore.so.4    
No symbol table info available.                                                           
#10 0x00007f843f5a6e03 in QSocketNotifier::event () from /usr/lib64/libQtCore.so.4        
No symbol table info available.                                                           
#11 0x00007f8440466b2d in QApplicationPrivate::notify_helper ()                           
   from /usr/lib64/libQtGui.so.4                                                          
No symbol table info available.                                                           
#12 0x00007f844046ed9a in QApplication::notify () from /usr/lib64/libQtGui.so.4           
No symbol table info available.                                                           
#13 0x00007f84431a78db in KApplication::notify () from /usr/lib64/libkdeui.so.5           
No symbol table info available.                                                           
#14 0x00007f843f58cb0c in QCoreApplication::notifyInternal ()                             
   from /usr/lib64/libQtCore.so.4                                                         
No symbol table info available.                                                           
#15 0x00007f843f5b6199 in ?? () from /usr/lib64/libQtCore.so.4                            
No symbol table info available.                                                           
#16 0x00007f8439d4728b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0     
No symbol table info available.                                                           
#17 0x00007f8439d4aa4d in ?? () from /usr/lib64/libglib-2.0.so.0                          
No symbol table info available.                                                           
#18 0x00007f8439d4ac0b in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0    
No symbol table info available.
#19 0x00007f843f5b5e4c in QEventDispatcherGlib::processEvents ()
   from /usr/lib64/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#20 0x00007f84404fe40f in ?? () from /usr/lib64/libQtGui.so.4
No symbol table info available.
#21 0x00007f843f58b3a2 in QEventLoop::processEvents () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#22 0x00007f843f58b774 in QEventLoop::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#23 0x00007f843f58da44 in QCoreApplication::exec () from /usr/lib64/libQtCore.so.4
No symbol table info available.
#24 0x00000000005b3064 in main (argc=1, argv=0x7fffaeef6238)
    at /home/hellvis69/Progetti/KVIrc/svn/trunk/kvirc/src/kvirc/kernel/kvi_main.cpp:488
        a = {argc = 1, argv = 0x7fffaeef6238, configFile = 0x0, createFile = false,
  bForceNewSession = false, bShowPopup = false, bShowSplashScreen = true,
  bExecuteCommandAndClose = false,
  szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0xe0c2b0 "",
    m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>},
    m_ptr = 0xe0c2d0 "", m_len = 0}}
        pDisplay = <value optimized out>
        iRetVal = <value optimized out>
        iRetCode = <value optimized out>
        pTheApp = <value optimized out>
        colormap = 4194305
        pVisual = (<anonymous struct> *) 0xe521a0
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0xe68970 "",
  m_len = 0}
```

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 12 Jan 2010 14:19:26**
Ok.. followed the memory<br/>
In attach the stack

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 20 Feb 2010 19:21:24**
temporary fix applied in r3997

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 18 May 2010 01:32:07**
closing, since it doesn't seem to happen anymore

---

Resolution: none → wontfix
Status: new → closed
