### ISSUE TITLE
Crash when using Undo at the inputbar

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#693]
**Reported by wodim on 19 Jan 2010 16:36:43 UTC**
Finally I got a way to trigger it:<br/>

1- Type three words... "bla bla bla".<br/>

2- Select the last one, by pressing Ctrl + Shift + Left arrow.<br/>

3- Cut (Ctrl + X).<br/>

4- Undo (Ctrl + Z) '''_crash_'''<br/>

And here's the backtrace:

```
ASSERT: "i >= 0 && i < size()" in file /usr/include/QtCore/qstring.h, line 688

Program received signal SIGABRT, Aborted.
0xb7fe1424 in __kernel_vsyscall ()       
(gdb) bt full                            
#0  0xb7fe1424 in __kernel_vsyscall ()   
No symbol table info available.          
#1  0xb4ca3571 in raise () from /lib/libc.so.6
No symbol table info available.               
#2  0xb4ca4d72 in abort () from /lib/libc.so.6
No symbol table info available.               
#3  0xb5257fd4 in qt_message_output(QtMsgType, char const*) () from /usr/lib/libQtCore.so.4
No symbol table info available.                                                            
#4  0xb525818a in ?? () from /usr/lib/libQtCore.so.4                                       
No symbol table info available.                                                            
#5  0xb5258299 in qFatal(char const*, ...) () from /usr/lib/libQtCore.so.4                 
No symbol table info available.                                                            
#6  0xb5258325 in qt_assert(char const*, char const*, int) () from /usr/lib/libQtCore.so.4 
No symbol table info available.                                                            
#7  0x080f52d4 in QString::at (this=0x89f7c74, i=2) at /usr/include/QtCore/qstring.h:688   
No locals.                                                                                 
#8  0x080f7da6 in KviInputEditor::xPositionFromCharIndex (this=0x89f7c60, fm=0x8d7a0a8, iChIdx=3, bContentsCoords=true)
    at /homer/neikon/kvirc/src/kvirc/ui/kvi_input_editor.cpp:2074                                                      
        c = {ucs = 115}                                                                                                
        iCurXPos = 11                                                                                                  
        iCurChar = 2                                                                                                   
#9  0x080fdd85 in KviInputEditor::drawContents (this=0x89f7c60, p=0xbfffca8c)                                          
    at /homer/neikon/kvirc/src/kvirc/ui/kvi_input_editor.cpp:285                                                       
        iXLeft = 2                                                                                                     
        iWidgetHeight = 23                                                                                             
        iCurXPos = <value optimized out>                                                                               
        iWidgetWidth = <value optimized out>                                                                           
        fm = 0x8d7a0a8                                                                                                 
        iBottom = 21                                                                                                   
        iTextBaseline = 19                                                                                             
        rect = {x1 = 0, y1 = 0, x2 = 858, y2 = 22}                                                                     
        iMaxXPos = 855                                                                                                 
        iCharIdx = 0                                                                                                   
#10 0x080fe2a8 in KviInputEditor::paintEvent (this=0x89f7c60) at /homer/neikon/kvirc/src/kvirc/ui/kvi_input_editor.cpp:216
        p = {static staticMetaObject = {d = {superdata = 0x0, stringdata = 0xb61d37c0 "QPainter", data = 0xb61d3860,      
---Type <return> to continue, or q <return> to quit---                                                                    
              extradata = 0x0}}, d_ptr = {d = 0x8ceae38}}                                                                 
#11 0xb5ab5575 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4                                                  
No symbol table info available.                                                                                           
#12 0xb5ea5ee3 in QFrame::event(QEvent*) () from /usr/lib/libQtGui.so.4                                                   
No symbol table info available.                                                                                           
#13 0xb5a58c1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4                    
No symbol table info available.                                                                                           
#14 0xb5a5f8e7 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4                                  
No symbol table info available.                                                                                           
#15 0xb794a60a in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5                                  
No symbol table info available.                                                                                           
#16 0xb5360c6b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4                     
No symbol table info available.                                                                                           
#17 0xb5abe6f6 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#18 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#19 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#20 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#21 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#22 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#23 0xb5abf328 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#24 0xb5abf328 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint cons---Type <return> to continue, or q <return> to quit---                                                                          
t&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#25 0xb5abf328 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#26 0xb5abf328 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#27 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#28 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#29 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#30 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#31 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#32 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#33 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
#34 0xb5abf4ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#35 0xb5abe445 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/libQtGui.so.4                                                                                                 
No symbol table info available.                                                                                                 
---Type <return> to continue, or q <return> to quit---                                                                          
#36 0xb5c8c2f8 in ?? () from /usr/lib/libQtGui.so.4                                                                             
No symbol table info available.                                                                                                 
#37 0xb5aaeac3 in QWidgetPrivate::syncBackingStore() () from /usr/lib/libQtGui.so.4                                             
No symbol table info available.                                                                                                 
#38 0xb5ab5eac in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4                                                        
No symbol table info available.                                                                                                 
#39 0xb5ec41d7 in QMainWindow::event(QEvent*) () from /usr/lib/libQtGui.so.4                                                    
No symbol table info available.                                                                                                 
#40 0xb7a3a484 in KMainWindow::event(QEvent*) () from /usr/lib/libkdeui.so.5                                                    
No symbol table info available.                                                                                                 
#41 0xb5a58c1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4                          
No symbol table info available.                                                                                                 
#42 0xb5a5f8e7 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4                                        
No symbol table info available.                                                                                                 
#43 0xb794a60a in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5                                        
No symbol table info available.                                                                                                 
#44 0xb5360c6b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4                           
No symbol table info available.                                                                                                 
#45 0xb5363643 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQtCore.so.4        
No symbol table info available.                                                                                                 
#46 0xb53637ad in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#47 0xb538cbef in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#48 0xb517b378 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#49 0xb517ebf0 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#50 0xb517ed23 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#51 0xb538c6e5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#52 0xb5b137b5 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#53 0xb535f2a9 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#54 0xb535f6fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#55 0xb536386f in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#56 0xb5a58cb7 in QApplication::exec() () from /usr/lib/libQtGui.so.4
No symbol table info available.
#57 0x08204890 in main (argc=1, argv=0xbffff774) at /homer/neikon/kvirc/src/kvirc/kernel/kvi_main.cpp:488
        a = {argc = 1, argv = 0xbffff774, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false,
          bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>},
            m_ptr = 0x828d708 "", m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>},
            m_ptr = 0x828d718 "", m_len = 0}}
        pVisual = <value optimized out>
        pDisplay = 0x82b9638
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x837f608 "", m_len = 0}
        iRetCode = <value optimized out>
        pTheApp = <value optimized out>
        colormap = <value optimized out>
        iRetVal = <value optimized out>
```

r3850

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/693

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 19 Jan 2010 17:00:47**
fixed in r3852

---

Resolution: none → fixed
Status: new → closed
