### ISSUE TITLE
Kvirc crash after ~30 sec past a valid connection

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#720]
**Reported by Falko on 13 Feb 2010 14:25:54 UTC**

```
Application: KVIrc (kvirc4), signal: Segmentation fault
#0  0xb770c424 in __kernel_vsyscall ()
#1  0x415acdb6 in nanosleep () from /lib/libc.so.6
#2  0x415acbce in sleep () from /lib/libc.so.6
#3  0x4f7a3866 in ?? () from /usr/lib/libkdeui.so.5
#4  0x00000000 in ?? ()
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/720

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 16 Feb 2010 13:45:39**
The backtrace is useless, and there's no way to understand how to reproduce. Please try to:
- run kvirc with a clean configuration, and see if it still crashes
- run kvirc with your configuration, but disabling any autoconnect/join, and see if it still crashes
- restrict the crash to a single network/channel/kvs script of your current configuration
- use a kvirc package with debug symbols, and generate a useful backtrace.

---

Resolution: none → need feedback
Status: new → closed
