### ISSUE TITLE
Segfault when opening kvirc configuration

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#726]
**Reported by webmaster on 19 Feb 2010 23:07:20 UTC**
When I want to open the kvirc configuration inside the menu or any alias editor I get a segfault:

Application: KVIrc (kvirc), signal: Segmentation fault
[Current thread is 1 (Thread 0x7f1d8bc6f7f0 (LWP 2790))]

Thread 2 (Thread 0x7f1d7bc4f910 (LWP 3044)):
#0  0x00007f1d887f73e2 in select () from /lib64/libc.so.6
#1  0x00007f1d89471903 in ?? () from /usr/lib64/libQtCore.so.4
#2  0x00007f1d893a0775 in ?? () from /usr/lib64/libQtCore.so.4
#3  0x00007f1d8a65a65d in start_thread () from /lib64/libpthread.so.0
#4  0x00007f1d887fde1d in clone () from /lib64/libc.so.6
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f1d8bc6f7f0 (LWP 2790)):
[KCrash Handler]
#5  0x00007f1d8b85515f in KviPointerHashTable<char const*, KviTranslationEntry>::find(char const\* const&) () from /usr/lib64/libkvilib.so.4
#6  0x00007f1d8b8538c8 in KviMessageCatalogue::translateToQString(char const*) () from /usr/lib64/libkvilib.so.4
#7  0x00007f1d8b853a13 in KviLocale::translateToQString(char const_, char const_) () from /usr/lib64/libkvilib.so.4
#8  0x00007f1d79d1facc in KviOptionsInstanceManager::KviOptionsInstanceManager() () from /usr/lib64/kvirc/4.0/modules/libkvioptions.so
#9  0x00007f1d79d1886e in options_module_init(KviModule*) () from /usr/lib64/kvirc/4.0/modules/libkvioptions.so
#10 0x000000000052e81c in KviModuleManager::loadModule(QString const&) ()
#11 0x000000000052ea35 in KviModuleManager::getModule(QString const&) ()
#12 0x000000000057e0ae in KviKvsTreeNodeModuleSimpleCommand::execute(KviKvsRunTimeContext*) ()
#13 0x000000000056fac5 in KviKvsScript::executeInternal(KviKvsRunTimeContext*) ()
#14 0x000000000056fc32 in KviKvsScript::execute(KviWindow_, KviKvsVariantList_, KviKvsVariant_, int, KviKvsExtendedRunTimeData_) ()
#15 0x00000000005706a2 in KviKvsScript::run(QString const&, KviWindow_, KviKvsVariantList_, KviKvsVariant*) ()
#16 0x00000000005ddf21 in KviAction::qt_metacall(QMetaObject::Call, int, void**) ()
#17 0x00007f1d894a778f in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib64/libQtCore.so.4
#18 0x00007f1d894aca7e in QSignalMapper::mapped(int) () from /usr/lib64/libQtCore.so.4
#19 0x00007f1d894adc92 in QSignalMapper::map(QObject*) () from /usr/lib64/libQtCore.so.4
#20 0x00007f1d894adf10 in QSignalMapper::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib64/libQtCore.so.4
#21 0x00007f1d894a778f in QMetaObject::activate(QObject_, QMetaObject const_, int, void**) () from /usr/lib64/libQtCore.so.4
#22 0x00007f1d89961d12 in QAction::triggered(bool) () from /usr/lib64/libQtGui.so.4
#23 0x00007f1d89963d8b in QAction::activate(QAction::ActionEvent) () from /usr/lib64/libQtGui.so.4
#24 0x00007f1d89da04dd in ?? () from /usr/lib64/libQtGui.so.4
#25 0x00007f1d89da604a in ?? () from /usr/lib64/libQtGui.so.4
#26 0x00007f1d899be172 in QWidget::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#27 0x00007f1d89da820b in QMenu::event(QEvent*) () from /usr/lib64/libQtGui.so.4
#28 0x00007f1d89967e1c in QApplicationPrivate::notify_helper(QObject_, QEvent_) () from /usr/lib64/libQtGui.so.4
#29 0x00007f1d8996ebdb in QApplication::notify(QObject_, QEvent_) () from /usr/lib64/libQtGui.so.4
#30 0x00007f1d8aee7446 in KApplication::notify(QObject_, QEvent_) () from /usr/lib64/libkdeui.so.5
#31 0x00007f1d8949498c in QCoreApplication::notifyInternal(QObject_, QEvent_) () from /usr/lib64/libQtCore.so.4
#32 0x00007f1d8996ddb6 in QApplicationPrivate::sendMouseEvent(QWidget_, QMouseEvent_, QWidget_, QWidget_, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQtGui.so.4
#33 0x00007f1d899edba5 in ?? () from /usr/lib64/libQtGui.so.4
#34 0x00007f1d899ec47a in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib64/libQtGui.so.4
#35 0x00007f1d89a16932 in ?? () from /usr/lib64/libQtGui.so.4
#36 0x00007f1d856c6dee in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#37 0x00007f1d856ca7b8 in ?? () from /usr/lib64/libglib-2.0.so.0
#38 0x00007f1d856ca8e0 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#39 0x00007f1d894bdeb3 in QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/libQtCore.so.4
#40 0x00007f1d89a1651e in ?? () from /usr/lib64/libQtGui.so.4
#41 0x00007f1d894932a2 in QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/libQtCore.so.4
#42 0x00007f1d8949367c in QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) () from /usr/lib64/libQtCore.so.4
#43 0x00007f1d894973cb in QCoreApplication::exec() () from /usr/lib64/libQtCore.so.4
#44 0x00000000005c0b9f in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/726

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 19 Feb 2010 23:11:15**
what rev do you use?
/echo $version should tell you everything

**Comment by DarthGandalf** [comment]
**Comment by HelLViS69 on 20 Feb 2010 02:42:32**
fixed in r3987

---

Resolution: none → fixed
Status: new → closed
