### ISSUE TITLE
kvirc crash using svn release 1110

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#73]
**Reported by mmodem on 01 Feb 2008 04:09:47 UTC**
kvirc crash using svn release 1110, the output:

[KCrash handler]
#5  0x000000000051906e in KviIsOnNotifyListManager::handleUserhost ()
#6  0x00000000005ea10a in KviServerParser::parseNumericUserhost ()
#7  0x00000000005cd534 in KviServerParser::parseMessage ()
#8  0x00000000005064a9 in KviIrcLink::processData ()
#9  0x0000000000509644 in KviIrcSocket::readData ()
#10 0x000000000068720a in KviIrcSocket::qt_invoke ()
#11 0x00002af4763f24c2 in QObject::activate_signal ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#12 0x00002af4763f2e97 in QObject::activate_signal ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#13 0x00002af47674aa8c in QSocketNotifier::activated ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#14 0x00002af4764133b8 in QSocketNotifier::event ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#15 0x00002af47638b52a in QApplication::internalNotify ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#16 0x00002af47638d2d4 in QApplication::notify ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#17 0x00002af473c25ede in KApplication::notify ()

   from /usr/lib64/libkdecore.so.4
#18 0x00002af4727bfc50 in QApplication::sendEvent ()

   from /usr/lib64/libkparts.so.2
#19 0x00002af47637dc0f in QEventLoop::activateSocketNotifiers ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#20 0x00002af47633175a in QEventLoop::processEvents ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#21 0x00002af4763a4a0b in QEventLoop::enterLoop ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#22 0x00002af4763a46f7 in QEventLoop::exec ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#23 0x00002af47638d00c in QApplication::exec ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#24 0x000000000050db3a in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/73

**Comment by DarthGandalf** [comment]
**Comment by mren on 01 Feb 2008 11:43:06**
Duplicate of #72

---

Resolution: none → duplicate
Status: new → closed
