### ISSUE TITLE
Export all button raw make kvirc Crash

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#730]
**Reported by anonymous on 22 Feb 2010 18:12:12 UTC**
Every time I click on Export all, under Modify Raw Events, kvirc crashes.

Version: 4.0.0 Insomnia rc2, revision 3959 

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/730

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Feb 2010 15:17:59**
Can't reproduce here, any chance to get a backtrace?

**Comment by DarthGandalf** [comment]
**Comment by Weegee on 28 Feb 2010 10:16:37**
Using r4000:

```
Program received signal SIGSEGV, Segmentation fault.
0xb3956e40 in QTreeWidgetItem::parent (this=0x0)
    at /usr/include/qt4/QtGui/qtreewidget.h:183
183     inline QTreeWidgetItem *parent() const { return par; }
Current language:  auto
The current source language is "auto; currently c++".
(gdb) bt full
#0  0xb3956e40 in QTreeWidgetItem::parent (this=0x0)
    at /usr/include/qt4/QtGui/qtreewidget.h:183
No locals.
#1  0xb3955325 in KviRawEditor::getExportEventBuffer (this=0x9311508, 
    buffer=..., it=0x0)
    at /home/weegee/Downloads/Backen/kvirc/src/modules/raweditor/raweditor.cpp:379
        szBuf = {static null = {<No data fields>}, static shared_null = {
            ref = {_q_value = 32669}, alloc = 0, size = 0, data = 0x8355552, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
            ref = {_q_value = 100}, alloc = 0, size = 0, data = 0xb632746e, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, d = 0xb3956e6c, 
          static codecForCStrings = 0x8376cd0}
#2  0xb39558cf in KviRawEditor::exportAllEvents (this=0x9311508)
    at /home/weegee/Downloads/Backen/kvirc/src/modules/raweditor/raweditor.cpp:448
        tmp = {static null = {<No data fields>}, static shared_null = {ref = {
              _q_value = 32669}, alloc = 0, size = 0, data = 0x8355552, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
            ref = {_q_value = 100}, alloc = 0, size = 0, data = 0xb632746e, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, d = 0x8355540, 
          static codecForCStrings = 0x8376cd0}
        j = 0
        item = 0x0
        i = 1
        it = 0x9350e28
        out = {static null = {<No data fields>}, static shared_null = {ref = {
              _q_value = 32669}, alloc = 0, size = 0, data = 0x8355552, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
            ref = {_q_value = 100}, alloc = 0, size = 0, data = 0xb632746e, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, d = 0x9372998, 
          static codecForCStrings = 0x8376cd0}
        szName = {static null = {<No data fields>}, static shared_null = {
            ref = {_q_value = 32669}, alloc = 0, size = 0, data = 0x8355552, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
            ref = {_q_value = 100}, alloc = 0, size = 0, data = 0xb632746e, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, d = 0xb394ec70, 
          static codecForCStrings = 0x8376cd0}
        szFile = {static null = {<No data fields>}, static shared_null = {
            ref = {_q_value = 32669}, alloc = 0, size = 0, data = 0x8355552, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, static shared_empty = {
            ref = {_q_value = 100}, alloc = 0, size = 0, data = 0xb632746e, 
            clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, 
            capacity = 0, reserved = 0, array = {0}}, d = 0x0, 
          static codecForCStrings = 0x8376cd0}
#3  0xb3957e1d in KviRawEditor::qt_metacall (this=0x9311508, 
    _c=QMetaObject::InvokeMetaMethod, _id=6, _a=0xbfffd998)
    at /home/weegee/Downloads/Backen/kvirc/kvirc/src/modules/raweditor/moc_raweditor.cxx:85
No locals.
#4  0xb624b263 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#5  0xb624b6d8 in QMetaObject::activate(QObject*, QMetaObject const*, int, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#6  0xb6e1ecc1 in QAbstractButton::clicked(bool) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#7  0xb6b47549 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#8  0xb6b491a4 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#9  0xb6b49431 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#10 0xb67e7012 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#11 0xb6b473ee in QAbstractButton::event(QEvent*) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#12 0xb6bf166d in QPushButton::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#13 0xb6791f54 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#14 0xb679a033 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#15 0xb62356cb in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0xb6798f6e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#17 0xb68077c0 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#18 0xb6806c4b in QApplication::x11ProcessEvent(_XEvent*) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#19 0xb6833502 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#20 0xb5a66e88 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
No symbol table info available.
#21 0xb5a6a730 in ?? () from /lib/libglib-2.0.so.0
No symbol table info available.
#22 0xb5a6a863 in g_main_context_iteration () from /lib/libglib-2.0.so.0
No symbol table info available.
#23 0xb626002c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#24 0xb6832be5 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#25 0xb6233c79 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#26 0xb62340ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQtCore.so.4
No symbol table info available.
#27 0xb623653f in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#28 0xb6791dd7 in QApplication::exec() () from /usr/lib/libQtGui.so.4
No symbol table info available.
#29 0x08266202 in ?? ()
No symbol table info available.
#30 0xb5cd1b56 in __libc_start_main () from /lib/tls/i686/cmov/libc.so.6
No symbol table info available.
#31 0x080d1401 in _start ()
No symbol table info available.
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 28 Feb 2010 18:34:00**
fixed in r4067, thank you!

---

Resolution: none → fixed
Status: new → closed
