### ISSUE TITLE
Crash when adding a new raw handler

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#752]
**Reported by wodim on 25 Mar 2010 14:20:13 UTC**
I typed 433 in the new raw dialog, then clicked OK, and it crashed.

```
Program received signal SIGSEGV, Segmentation fault.
0xb529d64a in QString::toUtf8() const () from /usr/lib/libQtCore.so.4                                                           
(gdb) bt full                                                                                                                   
#0  0xb529d64a in QString::toUtf8() const () from /usr/lib/libQtCore.so.4                                                       
No symbol table info available.                                                                                                 
#1  0xb10b4265 in KviRawEditor::currentItemChanged (this=0x8c5aa28, it=0x8d12a50)
    at /home/neiko/kvirc/src/modules/raweditor/raweditor.cpp:382                                                                
        tmp = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 18920}, alloc = 0, size = 0,           
            data = 0x82729c2, clean = 0, simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = { 
              0}}, static shared_empty = {ref = {_q_value = 91}, alloc = 0, size = 0, data = 0xb54695ee, clean = 0,             
            simpletext = 0, righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x82729b0,           
          static codecForCStrings = 0x82913b0}                                                                                  
#2  0xb10b72d8 in KviRawEditor::qt_metacall (this=0x8c5aa28, _c=QMetaObject::InvokeMetaMethod, _id=27, _a=0xbfffdf14)
    at /home/neiko/kvirc/build/src/modules/raweditor/moc_raweditor.cxx:85
No locals.
#3  0xb535b06a in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#4  0xb536965f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#5  0xb60690c9 in QTreeWidget::currentItemChanged(QTreeWidgetItem*, QTreeWidgetItem*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#6  0xb606b845 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#7  0xb60758f2 in QTreeWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#8  0xb535b06a in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#9  0xb536965f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#10 0xb60443e9 in QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&) () from /usr/lib/libQtGui.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#11 0xb6044582 in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) ()
   from /usr/lib/libQtGui.so.4
No symbol table info available.
#12 0xb5feb7ac in QAbstractItemView::setCurrentIndex(QModelIndex const&) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#13 0xb6071c94 in QTreeWidget::setCurrentItem(QTreeWidgetItem*, int) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#14 0xb6071cdc in QTreeWidget::setCurrentItem(QTreeWidgetItem*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#15 0xb10b5d45 in KviRawEditor::addRaw (this=0x8c5aa28) at /home/neiko/kvirc/src/modules/raweditor/raweditor.cpp:253
        bOk = true
        iIdx = 433
#16 0xb10b733b in KviRawEditor::qt_metacall (this=0x8c5aa28, _c=QMetaObject::InvokeMetaMethod, _id=32, _a=0xbfffe378)
    at /home/neiko/kvirc/build/src/modules/raweditor/moc_raweditor.cxx:90
No locals.
#17 0xb535b06a in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#18 0xb536965f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#19 0xb536ecb3 in QSignalMapper::mapped(int) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#20 0xb536fefd in QSignalMapper::map(QObject*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#21 0xb53700de in QSignalMapper::map() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#22 0xb53701ab in QSignalMapper::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#23 0xb535b06a in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#24 0xb536965f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#25 0xb5a4d659 in QAction::triggered(bool) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#26 0xb5a4f84c in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#27 0xb5ee8f1c in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#28 0xb5eef3eb in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#29 0xb5ef03f7 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#30 0xb5ab19a8 in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#31 0xb5ef19ec in QMenu::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#32 0xb5a53e4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#33 0xb5a5b63f in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#34 0xb79200ca in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
No symbol table info available.
#35 0xb5355e6b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#36 0xb5a5a367 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#37 0xb5ae4caa in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#38 0xb5ae3d43 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#39 0xb5b10a62 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#40 0xb516f398 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#41 0xb5172c10 in g_main_context_iterate () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#42 0xb5172d43 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#43 0xb53817b5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#44 0xb5b105c5 in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#45 0xb53544a9 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#46 0xb53548fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#47 0xb5358a6f in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#48 0xb5a53ee7 in QApplication::exec() () from /usr/lib/libQtGui.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#49 0x0820862b in main (argc=1, argv=0xbffff6e4) at /home/neiko/kvirc/src/kvirc/kernel/kvi_main.cpp:436
        a = {argc = 1, argv = 0xbffff6e4, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, 
          bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>}, 
            m_ptr = 0x82909f8 "", m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, 
            m_ptr = 0x8290a08 "", m_len = 0}}
        iRetVal = <value optimized out>
        iRetCode = <value optimized out>
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x83535c0 "", m_len = 0}

```

r4213

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/752

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Mar 2010 16:36:52**
hopefully fixed in r4217

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by wodim on 25 Mar 2010 19:36:27**
It works now. Thanks!
