### ISSUE TITLE
KVIrc Crashes on any Real number

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#801]
**Reported by explosivecranberry on 30 May 2010 07:43:25 UTC**
Whenever a real number is used as a variable in KVIrc, it crashes.
(This is Version 4.0)
For example: /echo $(3.3) will crash the client. As will anything involving $real(number)

This renders KVIrc useless for any sort of computation at all.

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/801

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 30 May 2010 13:30:43**
Thank you for your report, but unfortunately we can't reproduce the problem you described.
Please have a look at https://svn.kvirc.de/kvirc/wiki about how to report a bug. It would be helpful for us to understand what version of kvirc you are running on (version 4.0 hasn't been released yet, so i assume you're using a pre-release revision) and where idd you get it from (compiled from sources, some distro package, etc..)

---

Component: Core → KVS Engine
Priority: Normal → Crash
Resolution: none → worksforme
Status: new → closed
Version: 4.0 Insomnia → 4.0rc3 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 03 Jun 2010 08:20:12**
reproduced successfully on windows, it seems it's a windows-only bug involving real numbers

---

Resolution: worksforme → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 03 Jun 2010 14:47:45**
here's a backtrace

```
(gdb)
KviKvsCoreSimpleCommands::echo (__pContext=0x22c9a0, __pParams=0x22c938,
    __pSwitches=0x22c930)
    at C:\kvirc\kvirc\src\kvirc\kvs\kvi_kvs_coresimplecommands_af.cpp:1070
1070                    KVSCSC_pParams->allAsString(szAll);
(gdb)
KviKvsVariantList::allAsString (this=0x22c938, szBuffer=@0x22c8e4)
    at C:\kvirc\kvirc\src\kvirc\kvs\kvi_kvs_variantlist.cpp:175
175             szBuffer = QString();
(gdb) n
176             bool bFirst = true;
(gdb)
177             for(KviKvsVariant * v = first();v;v = next())
(gdb) n
179                     if(bFirst)bFirst = false;
(gdb)
181                     v->appendAsString(szBuffer);
(gdb) p v
$3 = (KviKvsVariant *) 0xe62b758
(gdb) p *v
$4 = {<KviHeapObject> = {<No data fields>}, m_pData = 0xeed5510}
(gdb) p *v->m_pData
$5 = {m_uRefs = 1, m_eType = KviKvsVariantData::Real, m_u = {
    iInteger = -4995072472808209696, pReal = 0xeef42e0, pString = 0xeef42e0,
    pArray = 0xeef42e0, pHash = 0xeef42e0, bBoolean = 224,
    hObject = 0xeef42e0}}
(gdb) p *v->m_pData->m_u->pReal
$6 = 1
(gdb) s
KviKvsVariant::appendAsString (this=0xe62b758, szBuffer=@0x22c8e4)
    at C:\kvirc\kvirc\src\kvirc\kvs\kvi_kvs_variant.cpp:607
607             if(!m_pData)return;
(gdb)
608             switch(m_pData->m_eType)
(gdb)
614                     case KviKvsVariantData::Real: KviQString::appendNumber(s
zBuffer,*(m_pData->m_u.pReal)); break;
(gdb) s
KviQString::appendNumber (szSrc=@0x22c8e4, dReal=1)
    at C:\kvirc\kvirc\src\kvilib\core\kvi_qstring.cpp:646
646                     ::sprintf(cBuffer,"%f",dReal);
(gdb) s
sprintf (__stream=0x22c65c "­°\227|    ╠°\227|L╝\225|",
    __format=0x6f5445e3 "%f")
    at c:/qt/2010.02/mingw/bin/../lib/gcc/mingw32/4.4.0/../../../../include/stdi
o.h:265
265       __builtin_va_list __local_argv; __builtin_va_start( __local_argv, __fo
rmat );
(gdb) s
266       __retval = __mingw_vsprintf( __stream, __format, __local_argv );
(gdb)

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt full
#0  0x00000000 in ?? ()
No symbol table info available.
#1  0x6f5168b2 in dtoa_unlock ()
   from C:\kvirc\kvirc\build_debug\release\libkvilib.dll
        qt_meta_data_KviTalTableWidget = {4, 0 <repeats 14 times>}
        RGB_MASK = 16777215
        qt_meta_stringdata_KviTalTableWidget = "KviTalTableWidget\000"
        KviTalTableWidget::staticMetaObject = {d = {superdata = 0x60af28c,
    stringdata = 0x6f54b9dc "KviTalTableWidget", data = 0x6f54b9a0,
    extradata = 0x0}}
```

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 03 Jun 2010 15:07:54**
added a workaround in r4418

---

Resolution: none → fixed
Status: reopened → closed
