### ISSUE TITLE
Kvirc for OSX crash when drag&drop button on toolbar

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#803]
**Reported by Pix on 31 May 2010 17:37:27 UTC**
Kvirc Version:   4.0.0 (4405)<br/>

Code Type:       i386<br/>

OS Version:      Mac OS X 10.6.3 (10D578)<br/>

QT Version:      qt-mac-cocoa-opensource-4.6.2<br/>

kvirc crash when when drag & drop a button on a toolbar, trying to customize it.

```
GNU gdb 6.3.50-20050815 (Apple version gdb-1461.2) (Fri Mar  5 04:39:39 UTC 2010)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-apple-darwin"...
warning: Unable to read symbols for "QtWebKit.framework/Versions/4/QtWebKit" (file not found).

warning: Unable to read symbols from "QtWebKit" (not yet mapped into memory).

warning: Unable to read symbols for "QtGui.framework/Versions/4/QtGui" (file not found).

warning: Unable to read symbols from "QtGui" (not yet mapped into memory).

warning: Unable to read symbols for "QtDBus.framework/Versions/4/QtDBus" (file not found).

warning: Unable to read symbols from "QtDBus" (not yet mapped into memory).

warning: Unable to read symbols for "QtXml.framework/Versions/4/QtXml" (file not found).

warning: Unable to read symbols from "QtXml" (not yet mapped into memory).

warning: Unable to read symbols for "QtSql.framework/Versions/4/QtSql" (file not found).

warning: Unable to read symbols from "QtSql" (not yet mapped into memory).

warning: Unable to read symbols for "QtXmlPatterns.framework/Versions/4/QtXmlPatterns" (file not found).

warning: Unable to read symbols from "QtXmlPatterns" (not yet mapped into memory).

warning: Unable to read symbols for "QtNetwork.framework/Versions/4/QtNetwork" (file not found).

warning: Unable to read symbols from "QtNetwork" (not yet mapped into memory).

warning: Unable to read symbols for "QtCore.framework/Versions/4/QtCore" (file not found).

warning: Unable to read symbols from "QtCore" (not yet mapped into memory).

warning: Unable to read symbols for "phonon.framework/Versions/4/phonon" (file not found).

warning: Unable to read symbols from "phonon" (not yet mapped into memory).
Reading symbols for shared libraries ....... done

(gdb) r -f
Starting program: /Users/Gigiopix/Desktop/KVIrc.app/Contents/MacOS/kvirc -f
Reading symbols for shared libraries .+++.......warning: Could not find object file "/Developer/SDKs/MacOSX10.4u.sdk/usr/lib/gcc/i686-apple-darwin10/4.0.1/libgcc.a(_eprintf.o)" - no debug information available for "/var/tmp/gcc_40/gcc_40-5493~93/src/gcc/libgcc2.c".

..+++............................................................................................. done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries .. done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries .. done
Reading symbols for shared libraries warning: Could not find object file "/Developer/SDKs/MacOSX10.4u.sdk/usr/lib/gcc/i686-apple-darwin10/4.0.1/libgcc.a(_eprintf.o)" - no debug information available for "/var/tmp/gcc_40/gcc_40-5493~93/src/gcc/libgcc2.c".

. done
Reading symbols for shared libraries .. done
Reading symbols for shared libraries . done
2010-05-31 19:04:33.371 kvirc[34687:80f] Can't open input server /Library/InputManagers/GrowlSafari
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Reading symbols for shared libraries . done
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Qt: internal: -108: Error ATSUMeasureTextImage text/qfontengine_mac.mm: 1138
Reading symbols for shared libraries warning: Could not find object file "/Users/mike/Projects/simbl/build/SIMBL.build/Deployment/SIMBL.build/Objects-normal/i386/NSAlert_SIMBL.o" - no debug information available for "/Users/mike/Projects/simbl/src/NSAlert_SIMBL.m".

warning: Could not find object file "/Users/mike/Projects/simbl/build/SIMBL.build/Deployment/SIMBL.build/Objects-normal/i386/SIMBL-4A64B91627DFD16A.o" - no debug information available for "/Users/mike/Projects/simbl/src/SIMBL.m".

warning: Could not find object file "/Users/mike/Projects/simbl/build/SIMBL.build/Deployment/SIMBL.build/Objects-normal/i386/SIMBLPlugin.o" - no debug information available for "/Users/mike/Projects/simbl/src/SIMBLPlugin.m".

. done
Reading symbols for shared libraries .... done
bt full
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000008
0x01f8d619 in QWidget::window ()
(gdb) bt full
#0  0x01f8d619 in QWidget::window ()
No symbol table info available.
#1  0x01f4c8bd in QApplication::notify ()
No symbol table info available.
#2  0x0343f9c2 in QCoreApplication::notifyInternal ()
No symbol table info available.
#3  0x01ed5fe5 in QWidgetPrivate::qt_mac_dnd_event ()
No symbol table info available.
#4  0x01eeb98c in QWidgetPrivate::qt_widget_event ()
No symbol table info available.
#5  0x979be0a9 in DispatchEventToHandlers ()
No symbol table info available.
#6  0x979bd370 in SendEventToEventTargetInternal ()
No symbol table info available.
#7  0x979bd1cf in SendEventToEventTargetWithOptions ()
No symbol table info available.
#8  0x97a9b568 in SendControlDefDragTrackEvent ()
No symbol table info available.
#9  0x97a8967e in HIView::DragEnterOne ()
No symbol table info available.
#10 0x97a89bfa in HIView::DragEnter ()
No symbol table info available.
#11 0x97a97fef in ControlDragTrackingHandler ()
No symbol table info available.
#12 0x97b6657f in CarbonTrackingMapper ()
No symbol table info available.
#13 0x923ac840 in DoTrackingMessage ()
No symbol table info available.
#14 0x923acc0e in SendTrackingMessage ()
No symbol table info available.
#15 0x923ae5c9 in DragInApplication ()
No symbol table info available.
#16 0x923af10c in CoreDragStartDragging ()
No symbol table info available.
#17 0x97b65f95 in TrackDrag ()
No symbol table info available.
#18 0x01ed4bff in QDragManager::drag ()
No symbol table info available.
#19 0x01f5a0c8 in QDrag::exec ()
No symbol table info available.
#20 0x01f5a168 in QDrag::exec ()
No symbol table info available.
#21 0x0004b938 in KviCustomToolBar::eventFilter (this=0x1262e130, o=0x1264ebb0, e=0xbfffe944) at /Users/Gigiopix/kvirc/src/kvirc/ui/kvi_customtoolbar.cpp:502
    pDrag = (QDrag *) 0x39f22d0
    pMime = (QMimeData *) 0x39e7c40
    act = (KviAction *) 0x12642150
    ev = {
  _vptr$QEvent = 0x3607988, 
  static staticMetaObject = {
    d = {
      superdata = 0x0, 
      stringdata = 0x35ccf14 "QEvent", 
      data = 0x35cc980, 
      extradata = 0x0
    }
  }, 
  d = 0x0, 
  t = 76, 
  posted = 0, 
  spont = 0, 
  m_accept = 1, 
  reserved = 112
}
    pEvent = (QMouseEvent *) 0xbfffe944
#22 0x0351e1c1 in QCoreApplicationPrivate::sendThroughObjectEventFilters ()
No symbol table info available.
#23 0x01f45a46 in QApplicationPrivate::notify_helper ()
No symbol table info available.
#24 0x01f4c2d9 in QApplication::notify ()
No symbol table info available.
#25 0x0343f9c2 in QCoreApplication::notifyInternal ()
No symbol table info available.
#26 0x01edd18d in QApplicationPrivate::globalEventProcessor ()
No symbol table info available.
#27 0x979be0a9 in DispatchEventToHandlers ()
No symbol table info available.
#28 0x979bd370 in SendEventToEventTargetInternal ()
No symbol table info available.
#29 0x979dfb55 in SendEventToEventTarget ()
No symbol table info available.
#30 0x01eed3a4 in QWidgetPrivate::qt_window_event ()
No symbol table info available.
#31 0x979be0a9 in DispatchEventToHandlers ()
No symbol table info available.
#32 0x979bd370 in SendEventToEventTargetInternal ()
No symbol table info available.
#33 0x979dfb55 in SendEventToEventTarget ()
No symbol table info available.
#34 0x979f163b in ToolboxEventDispatcherHandler ()
No symbol table info available.
#35 0x979be4fa in DispatchEventToHandlers ()
No symbol table info available.
#36 0x979bd370 in SendEventToEventTargetInternal ()
No symbol table info available.
#37 0x979dfb55 in SendEventToEventTarget ()
No symbol table info available.
#38 0x01ef3474 in QEventDispatcherMac::processEvents ()
No symbol table info available.
#39 0x0351d3a1 in QEventLoop::processEvents ()
No symbol table info available.
#40 0x0351d5cd in QEventLoop::exec ()
No symbol table info available.
#41 0x0351f92e in QCoreApplication::exec ()
No symbol table info available.
#42 0x00215638 in main (argc=2, argv=0xbffffa30) at /Users/Gigiopix/kvirc/src/kvirc/kernel/kvi_main.cpp:448
    a = {
  argc = 2, 
  argv = 0xbffffa30, 
  configFile = 0x0, 
  createFile = false, 
  bForceNewSession = true, 
  bShowPopup = false, 
  bShowSplashScreen = true, 
  bExecuteCommandAndClose = false, 
  szExecCommand = {
    <KviHeapObject> = {<No data fields>}, 
    members of KviStr: 
    m_ptr = 0x3809420 "", 
    m_len = 0
  }, 
  szExecRemoteCommand = {
    <KviHeapObject> = {<No data fields>}, 
    members of KviStr: 
    m_ptr = 0x3808ac0 "", 
    m_len = 0
  }
}
    iRetCode = 0
    pTheApp = (KviApp *) 0x380bfa0
    szRemoteCommand = {
  <KviHeapObject> = {<No data fields>}, 
  members of KviStr: 
  m_ptr = 0x38490f0 "", 
  m_len = 0
}
    iRetVal = 0
(gdb) 
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/803

**Comment by DarthGandalf** [comment]
**Modified by HelLViS69 on 27 Jun 2010 15:23:24**
Version: 4.0rc3 Insomnia → 4.0 Insomnia

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 12 Jul 2010 15:33:23**
fixed in r4655

---

Resolution: none → fixed
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by Pix on 23 Jul 2010 09:46:45**
is not fully fixed. <br/>

Now (on r4685, still on OSX) don't crash anymore, but if I try to move a button before or next another button, it duplicate the button. <br/>
The redundants buttons only shows at next kvirc restart. <br/>

This is the bar just modified:<br/>

http://img63.imageshack.us/img63/3337/schermata20100723a11242.png <br/>

and this is the same bar after kvirc restart:<br/>

http://img641.imageshack.us/img641/746/schermata20100723a11250.png

---

Priority: Crash → Normal
Resolution: fixed → none
Status: closed → reopened
Version: 4.0 Insomnia → 4.1 Equilibrium

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 25 Jul 2010 16:20:03**
re-fixed in r4687

---

Resolution: none → fixed
Status: reopened → closed
