### ISSUE TITLE
crash on encryption

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#821]
**Reported by mink on 21 Jun 2010 07:26:06 UTC**
Setup mirc(blowfish) encryption. As soon as someone else types. Boom.

```
Application: KVIrc (kvirc), signal: Aborted
[KCrash Handler]
#5  0x00007f7c020e3a75 in raise () from /lib/libc.so.6
#6  0x00007f7c020e75c0 in abort () from /lib/libc.so.6
#7  0x00007f7c01e688e5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/libstdc++.so.6
#8  0x00007f7c01e66d16 in ?? () from /usr/lib/libstdc++.so.6
#9  0x00007f7c01e66d43 in std::terminate() () from /usr/lib/libstdc++.so.6
#10 0x00007f7c01e66dc6 in __cxa_rethrow () from /usr/lib/libstdc++.so.6
#11 0x00007f7c0259eebd in QEventLoop::exec (this=<value optimized out>, flags=<value optimized out>) at kernel/qeventloop.cpp:214
#12 0x00007f7c025a2aab in QCoreApplication::exec () at kernel/qcoreapplication.cpp:981
#13 0x00000000006152f1 in main ()

```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/821

**Comment by DarthGandalf** [comment]
**Comment by aeriana on 26 Jun 2010 06:19:17**
That trace doesn't say much. Also, which revision?

I cannot reproduce it with r4529 on Ubuntu Lucid 10.04 32-bit. I had one client with mIRC encryption enabled and another client doing the typing. Had the other client try both plain text and mIRC encryption, works fine.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 30 Jun 2010 20:17:04**
Sounds more like a general crash that one related to mircryption.. any chance to get some more details on the problem? (the revision of kvirc you are using, an example message that always triggers the problem, ...)

---

Resolution: none → worksforme
Status: new → closed
