### ISSUE TITLE
Crash on CTCP #kvirc avatar

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#826]
**Reported by ambossarm on 01 Jul 2010 20:41:43 UTC**
I just had 2 crashes on ctcp #kvirc avatar. I did 3 times ctcp for 2 crashes…

Equilibrium 4.1.0, revision: 4576, sources date: 20100519, built on: 2010-07-01 20:26:36 UTC

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/826

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 05 Jul 2010 19:51:25**

```
(gdb) run
Starting program: /usr/local/bin/kvirc 
[Thread debugging using libthread_db enabled]
[New Thread 0x7fffe425f910 (LWP 5036)]
[New Thread 0x7fffe3a5e910 (LWP 5037)]
[New Thread 0x7fffe325d910 (LWP 5038)]
[Thread 0x7fffe325d910 (LWP 5038) exited]
[Thread 0x7fffe3a5e910 (LWP 5037) exited]
[Thread 0x7fffe425f910 (LWP 5036) exited]
[New Thread 0x7fffe425f910 (LWP 5039)]
[Thread 0x7fffe425f910 (LWP 5039) exited]
[New Thread 0x7fffe425f910 (LWP 5040)]
[Thread 0x7fffe425f910 (LWP 5040) exited]
[New Thread 0x7fffe425f910 (LWP 5041)]
[Thread 0x7fffe425f910 (LWP 5041) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff43eb8c0 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQtCore.so.4
(gdb) bt
#0  0x00007ffff43eb8c0 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQtCore.so.4
#1  0x000000000054ed40 in KviUserListEntry::detachAvatarData() ()
#2  0x000000000054ed96 in KviUserListEntry::updateAvatarData() ()
#3  0x000000000055544b in KviUserListView::avatarChanged(QString const&) ()
#4  0x00000000004c926f in KviConsole::avatarChangedUpdateWindows(QString const&, QString const&) ()
#5  0x00000000004ce55a in KviConsole::avatarChanged(KviAvatar*, QString const&, QString const&, QString const&, QString const&) ()
#6  0x0000000000567165 in KviServerParser::parseCtcpReplyAvatar(_KviCtcpMessage*) ()
#7  0x0000000000565a1c in KviServerParser::parseCtcpReply(_KviCtcpMessage*) ()
#8  0x000000000057accf in KviServerParser::parseLiteralNotice(KviIrcMessage*) ()
#9  0x000000000058d902 in KviServerParser::parseMessage(char const*, KviIrcConnection*) ()
#10 0x000000000068dd37 in KviIrcLink::processData(char*, int) ()
#11 0x00000000006920e0 in KviIrcSocket::readData(int) ()
#12 0x00000000006cb03b in KviIrcSocket::qt_metacall(QMetaObject::Call, int, void**) ()
#13 0x00007ffff43ebddc in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQtCore.so.4
#14 0x00007ffff4421e9e in QSocketNotifier::activated(int) () from /usr/lib/libQtCore.so.4
#15 0x00007ffff43f0773 in QSocketNotifier::event(QEvent*) () from /usr/lib/libQtCore.so.4
#16 0x00007ffff527aefc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#17 0x00007ffff52821ce in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#18 0x00007ffff43d6c2c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#19 0x00007ffff43ff42a in ?? () from /usr/lib/libQtCore.so.4
#20 0x00007ffff04b6bce in g_main_dispatch (context=0x9b5520) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:1960
#21 IA__g_main_context_dispatch (context=0x9b5520) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2513
#22 0x00007ffff04ba598 in g_main_context_iterate (context=0x9b5520, block=<value optimized out>, dispatch=<value optimized out>, self=<value optimized out>) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2591
#23 0x00007ffff04ba6c0 in IA__g_main_context_iteration (context=0x9b5520, may_block=1) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2654
#24 0x00007ffff43ff1a6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#25 0x00007ffff530f4be in ?? () from /usr/lib/libQtGui.so.4
#26 0x00007ffff43d5532 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#27 0x00007ffff43d5904 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#28 0x00007ffff43d7ab9 in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#29 0x0000000000697c73 in main ()
(gdb) bt full
#0  0x00007ffff43eb8c0 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#1  0x000000000054ed40 in KviUserListEntry::detachAvatarData() ()
No symbol table info available.
#2  0x000000000054ed96 in KviUserListEntry::updateAvatarData() ()
No symbol table info available.
#3  0x000000000055544b in KviUserListView::avatarChanged(QString const&) ()
No symbol table info available.
#4  0x00000000004c926f in KviConsole::avatarChangedUpdateWindows(QString const&, QString const&) ()
No symbol table info available.
#5  0x00000000004ce55a in KviConsole::avatarChanged(KviAvatar*, QString const&, QString const&, QString const&, QString const&) ()
No symbol table info available.
#6  0x0000000000567165 in KviServerParser::parseCtcpReplyAvatar(_KviCtcpMessage*) ()
No symbol table info available.
#7  0x0000000000565a1c in KviServerParser::parseCtcpReply(_KviCtcpMessage*) ()
No symbol table info available.
#8  0x000000000057accf in KviServerParser::parseLiteralNotice(KviIrcMessage*) ()
No symbol table info available.
#9  0x000000000058d902 in KviServerParser::parseMessage(char const*, KviIrcConnection*) ()
No symbol table info available.
#10 0x000000000068dd37 in KviIrcLink::processData(char*, int) ()
No symbol table info available.
#11 0x00000000006920e0 in KviIrcSocket::readData(int) ()
No symbol table info available.
#12 0x00000000006cb03b in KviIrcSocket::qt_metacall(QMetaObject::Call, int, void**) ()
No symbol table info available.
#13 0x00007ffff43ebddc in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#14 0x00007ffff4421e9e in QSocketNotifier::activated(int) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#15 0x00007ffff43f0773 in QSocketNotifier::event(QEvent*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#16 0x00007ffff527aefc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#17 0x00007ffff52821ce in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#18 0x00007ffff43d6c2c in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#19 0x00007ffff43ff42a in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#20 0x00007ffff04b6bce in g_main_dispatch (context=0x9b5520) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:1960
        dispatch = 0x7ffff43ff3c0
        user_data = 0x0
        callback = 0
        cb_funcs = 0x0
        cb_data = 0x0
        current_source_link = {data = 0x9b6750, next = 0x0}
        source = 0x9b6750
        current = 0x9b47c0
        i = 0
#21 IA__g_main_context_dispatch (context=0x9b5520) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2513
No locals.
#22 0x00007ffff04ba598 in g_main_context_iterate (context=0x9b5520, block=<value optimized out>, dispatch=<value optimized out>, self=<value optimized out>) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2591
---Type <return> to continue, or q <return> to quit---
        max_priority = 2147483647
        timeout = 393
        some_ready = 1
        nfds = 8
        allocated_nfds = -263425728
        fds = <value optimized out>
        __PRETTY_FUNCTION__ = "g_main_context_iterate"
#23 0x00007ffff04ba6c0 in IA__g_main_context_iteration (context=0x9b5520, may_block=1) at /build/buildd/glib2.0-2.22.3/glib/gmain.c:2654
        retval = <value optimized out>
#24 0x00007ffff43ff1a6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#25 0x00007ffff530f4be in ?? () from /usr/lib/libQtGui.so.4
No symbol table info available.
#26 0x00007ffff43d5532 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#27 0x00007ffff43d5904 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#28 0x00007ffff43d7ab9 in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#29 0x0000000000697c73 in main ()
No symbol table info available.
```

**Comment by DarthGandalf** [comment]
**Comment by ambossarm on 05 Jul 2010 19:55:02**
Bug is not reproduceable with kvirc -n /tmp/null, so it has to be a config thing

**Comment by DarthGandalf** [comment]
**Comment by aeriana on 09 Jul 2010 10:26:08**
This bug is only triggered if animation of avatars is disabled. I think the crash is triggered by an attempt to disconnect a signal-slot connection that doesn't exist. Therefore I propose a fix that involves checking if the signal actually has any receivers before attempting the disconnection.

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 09 Jul 2010 10:52:43**
patch applied in r4637, thank you!

---

Resolution: none → fixed
Status: new → closed
