### ISSUE TITLE
kvirc svn release 1165 crashes

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#83]
**Reported by mmodem on 25 Feb 2008 23:06:21 UTC**
I have build and installed kvirc svn release 1165 and it crashes, the backtrace:

[Thread debugging using libthread_db enabled]
[New Thread 47118695450816 (LWP 15657)](no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
(no debugging symbols found)
[KCrash handler]
#5  0x000000000051909e in KviIsOnNotifyListManager::handleUserhost ()
#6  0x00000000005ea08a in KviServerParser::parseNumericUserhost ()
#7  0x00000000005cd504 in KviServerParser::parseMessage ()
#8  0x00000000005064a9 in KviIrcLink::processData ()
#9  0x0000000000509634 in KviIrcSocket::readData ()
#10 0x000000000068727a in KviIrcSocket::qt_invoke ()
#11 0x00002adaa5aa44c2 in QObject::activate_signal ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#12 0x00002adaa5aa4e97 in QObject::activate_signal ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#13 0x00002adaa5dfca8c in QSocketNotifier::activated ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#14 0x00002adaa5ac53b8 in QSocketNotifier::event ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#15 0x00002adaa5a3d52a in QApplication::internalNotify ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#16 0x00002adaa5a3f2d4 in QApplication::notify ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#17 0x00002adaa32d804e in KApplication::notify ()

   from /usr/lib64/libkdecore.so.4
#18 0x00002adaa1e70c50 in QApplication::sendEvent ()

   from /usr/lib64/libkparts.so.2
#19 0x00002adaa5a2fc0f in QEventLoop::activateSocketNotifiers ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#20 0x00002adaa59e375a in QEventLoop::processEvents ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#21 0x00002adaa5a56a0b in QEventLoop::enterLoop ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#22 0x00002adaa5a566f7 in QEventLoop::exec ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#23 0x00002adaa5a3f00c in QApplication::exec ()

   from /usr/lib/qt3/lib64/libqt-mt.so.3
#24 0x000000000050db2a in main ()

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/83

**Comment by DarthGandalf** [comment]
**Comment by mren on 27 Feb 2008 00:04:45**
I can't reproduce this w/ r 1167.

**Comment by DarthGandalf** [comment]
**Comment by mmodem on 29 Feb 2008 05:29:10**
what release are you runing?
after installing kvirc svn release 1165 and after running kvirc it simply crashed.

**Comment by DarthGandalf** [comment]
**Comment by mmodem on 29 Feb 2008 07:45:15**
Using svn release 1172 and cant reproduce it anymore

---

Resolution: none → worksforme
Status: new → closed

**Comment by DarthGandalf** [comment]
**Comment by mmodem on 01 Mar 2008 22:25:37**
Well, using kvirc svn 1172 release and continues crashing, the output:

[KCrash handler]
#5  0x000000000051909e in KviIsOnNotifyListManager::handleUserhost ()
#6  0x00000000005ea08a in KviServerParser::parseNumericUserhost ()
#7  0x00000000005cd504 in KviServerParser::parseMessage ()
#8  0x00000000005064a9 in KviIrcLink::processData ()
#9  0x0000000000509634 in KviIrcSocket::readData ()
#10 0x000000000068726a in KviIrcSocket::qt_invoke ()
#11 0x00002aba75a0d4c2 in QObject::activate_signal ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#12 0x00002aba75a0de97 in QObject::activate_signal ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#13 0x00002aba75d65a8c in QSocketNotifier::activated ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#14 0x00002aba75a2e3b8 in QSocketNotifier::event ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#15 0x00002aba759a652a in QApplication::internalNotify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#16 0x00002aba759a82d4 in QApplication::notify ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#17 0x00002aba7324204e in KApplication::notify ()
   from /usr/lib64/libkdecore.so.4
#18 0x00002aba71dd9c50 in QApplication::sendEvent ()
   from /usr/lib64/libkparts.so.2
#19 0x00002aba75998c0f in QEventLoop::activateSocketNotifiers ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#20 0x00002aba7594c75a in QEventLoop::processEvents ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#21 0x00002aba759bfa0b in QEventLoop::enterLoop ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#22 0x00002aba759bf6f7 in QEventLoop::exec ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#23 0x00002aba759a800c in QApplication::exec ()
   from /usr/lib/qt3/lib64/libqt-mt.so.3
#24 0x000000000050db2a in main ()

---

Resolution: worksforme → none
Status: closed → reopened

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 02 Mar 2008 04:06:39**
Your version doesn't seem to have full debug output enabled.
Can you compile ith with --enable-debug ?

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 02 Mar 2008 18:04:09**
Committed several changes on svn that will probably fix this one as side effect. Could you please check again now ?

---

Resolution: none → fixed
Status: reopened → closed
