### ISSUE TITLE
Crash on close related to regchan

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#834]
**Reported by ctrlaltca on 05 Jul 2010 09:11:14 UTC**
While testing the "chanstats" scripts i've found a strange crash related to the registered channels handling (the script uses the registered channel properties to store its data).
Steps to reproduce:

Start kvirc with a clean regchan list, connect to a network and register a channel in that network. Then, open a new irc context and disconnect from the network in the first one. Then close kvirc.

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff710738f in KviPointerHashTable<char const*, KviStr>::clear (this=0x3874580) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerhashtable.h:634
634                                     delete pList;
(gdb) bt full
#0  0x00007ffff710738f in KviPointerHashTable<char const*, KviStr>::clear (this=0x3874580) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerhashtable.h:634
        pList = 0x38765e0
        i = <value optimized out>
#1  0x00007ffff7107709 in ~KviPointerHashTable (this=0x38765e0, __in_chrg=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerhashtable.h:900
No locals.
#2  0x00007ffff71059c2 in ~KviRegisteredChannel (this=0x3874640, __in_chrg=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/ext/kvi_regchan.cpp:40
No locals.
#3  0x00007ffff71077af in KviPointerList<KviRegisteredChannel>::removeFirst (this=0x3876470) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerlist.h:953
        pAuxData = 0x3874640
#4  0x00007ffff71077e8 in KviPointerList<KviRegisteredChannel>::clear (this=0x3876470) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerlist.h:1039
No locals.
#5  0x00007ffff7107813 in ~KviPointerList (this=0x38765e0, __in_chrg=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerlist.h:1197
No locals.
#6  0x00007ffff710729a in KviPointerHashTable<char const*, KviPointerList<KviRegisteredChannel> >::clear (this=0xa4c9e0)
    at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerhashtable.h:629
        e = 0x3876000
        pList = <value optimized out>
        i = <value optimized out>
#7  0x00007ffff71076d9 in ~KviPointerHashTable (this=0x38765e0, __in_chrg=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/core/kvi_pointerhashtable.h:900
No locals.
#8  0x00007ffff7105951 in ~KviRegisteredChannelDataBase (this=<value optimized out>, __in_chrg=<value optimized out>)
    at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvilib/ext/kvi_regchan.cpp:53
No locals.
#9  0x0000000000595786 in ~KviApp (this=0x8eed80, __in_chrg=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvirc/kernel/kvi_app.cpp:631
No locals.
#10 0x00000000005be2fb in main (argc=4, argv=<value optimized out>) at /mnt/hd/prj/kvirc/svn/trunk/kvirc/src/kvirc/kernel/kvi_main.cpp:459
        a = {argc = 4, argv = 0x7fffffffdea8, configFile = 0x7fffffffe21c "/root/.kvirc-test.rc", createFile = true, bForceNewSession = true, bShowPopup = false, 
          bShowSplashScreen = true, bExecuteCommandAndClose = false, szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x8b4640 "", m_len = 0}, 
          szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x8b4660 "", m_len = 0}}
        oAboutData = {d = 0x8e3ca0}
        iRetVal = 0
        iRetCode = <value optimized out>
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x9a04e0 "", m_len = 0}
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/834

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 14 Jul 2010 14:42:02**
fixed by pragma in r4669

---

Resolution: none → fixed
Status: new → closed
