### ISSUE TITLE
r1171 crashes w/o any trigger

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#89]
**Reported by mren on 29 Feb 2008 13:02:26 UTC**
KVIrc r1171 crashed unexpected w/o any known trigger. At the time it crashed I was not at my computer, but at least there is a back trace.

(no debugging symbols found)<br/>
Using host libthread_db library "/lib/libthread_db.so.1".<br/>
(no debugging symbols found)<br/>
(...)<br/>
[KCrash handler]<br/>
#6  0x0814a375 in KviIsOnNotifyListManager::handleUserhost ()<br/>
#7  0x08227fee in KviServerParser::parseNumericUserhost ()<br/>
#8  0x082088f2 in KviServerParser::parseMessage ()<br/>
#9  0x0812792a in KviIrcConnection::incomingMessage ()<br/>
#10 0x081367f9 in KviIrcLink::processData ()<br/>
#11 0x08139019 in KviIrcSocket::readData ()<br/>
#12 0x082d344d in KviIrcSocket::qt_invoke ()<br/>
#13 0xb6f416b9 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#14 0xb6f42212 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#15 0xb7275880 in QSocketNotifier::activated () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#16 0xb6f5f24f in QSocketNotifier::event () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#17 0xb6ee2747 in QApplication::internalNotify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#18 0xb6ee32c1 in QApplication::notify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#19 0xb76904fe in KApplication::notify () from /usr/kde/3.5/lib/libkdecore.so.4<br/>
#20 0xb6ed73a1 in QEventLoop::activateSocketNotifiers () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#21 0xb6e928d4 in QEventLoop::processEvents () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#22 0xb6ef8e30 in QEventLoop::enterLoop () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#23 0xb6ef8cb6 in QEventLoop::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#24 0xb6ee21df in QApplication::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#25 0x0813dd07 in main ()<br/>

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/89

**Comment by DarthGandalf** [comment]
**Comment by mren on 29 Feb 2008 13:10:51**
Next crash after only some minutes of KVIrc uptime:

[KCrash handler]<br/>
#6  0x0814a375 in KviIsOnNotifyListManager::handleUserhost ()<br/>
#7  0x08227fee in KviServerParser::parseNumericUserhost ()<br/>
#8  0x082088f2 in KviServerParser::parseMessage ()<br/>
#9  0x0812792a in KviIrcConnection::incomingMessage ()<br/>
#10 0x081367f9 in KviIrcLink::processData ()<br/>
#11 0x08139019 in KviIrcSocket::readData ()<br/>
#12 0x082d344d in KviIrcSocket::qt_invoke ()<br/>
#13 0xb6eaa6b9 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#14 0xb6eab212 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#15 0xb71de880 in QSocketNotifier::activated () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#16 0xb6ec824f in QSocketNotifier::event () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#17 0xb6e4b747 in QApplication::internalNotify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#18 0xb6e4c2c1 in QApplication::notify () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#19 0xb75f94fe in KApplication::notify () from /usr/kde/3.5/lib/libkdecore.so.4<br/>
#20 0xb6e403a1 in QEventLoop::activateSocketNotifiers () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#21 0xb6dfb8d4 in QEventLoop::processEvents () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#22 0xb6e61e30 in QEventLoop::enterLoop () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#23 0xb6e61cb6 in QEventLoop::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#24 0xb6e4b1df in QApplication::exec () from /usr/qt/3/lib/libqt-mt.so.3<br/>
#25 0x0813dd07 in main ()<br/>

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 01 Mar 2008 14:06:40**
Should be fixed on the current svn. Please try and report.

**Comment by DarthGandalf** [comment]
**Comment by pragmaware on 01 Mar 2008 14:07:13**
Probably solved on the current svn. Please test and report.

---

Resolution: none → fixed
Status: new → closed
