### ISSUE TITLE
Crash if logview is closed when its progressbar is visible

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#968]
**Reported by wRAR on 19 Sep 2010 13:29:45 UTC**
4.0.3 r4984

Open the log viewer and close it via the tab closing button,  while the "Processing" progress bar is visible. KVIrc crashes:

```
Program received signal SIGSEGV, Segmentation fault.
0x4ef9e919 in free () from /lib/libc.so.6
(gdb) bt
#0  0x4ef9e919 in free () from /lib/libc.so.6
#1  0x486250b1 in operator delete(void*) () from /usr/lib/libstdc++.so.6
#2  0x4738fdea in QProgressDialog::~QProgressDialog() () from /usr/lib/libQtGui.so.4
#3  0x45d76a2f in QObjectPrivate::deleteChildren() () from /usr/lib/libQtCore.so.4
#4  0x46efe2a7 in QWidget::~QWidget() () from /usr/lib/libQtGui.so.4
#5  0x0813ad1d in KviWindow::~KviWindow (this=0x886c138, __in_chrg=<value optimized out>)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_window.cpp:162
#6  0xb53b4819 in KviLogViewMDIWindow::~KviLogViewMDIWindow (this=0x886c138, __in_chrg=<value optimized out>)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/modules/logview/logviewmdiwindow.cpp:174
#7  0xb53b4873 in KviLogViewMDIWindow::~KviLogViewMDIWindow (this=0x886c138, __in_chrg=<value optimized out>)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/modules/logview/logviewmdiwindow.cpp:174
#8  0x0811134b in KviMdiChild::~KviMdiChild (this=0x887a1d8, __in_chrg=<value optimized out>)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_mdichild.cpp:77
#9  0x081113cb in KviMdiChild::~KviMdiChild (this=0x887a1d8, __in_chrg=<value optimized out>)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_mdichild.cpp:81
#10 0x0811232c in KviMdiManager::destroyChild (this=0x8435ee0, lpC=0x887a1d8) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_mdimanager.cpp:165
#11 0x080e39dd in KviFrame::closeWindow (this=0x8408ab0, wnd=0x886c138) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_frame.cpp:447
#12 0x080e42b8 in KviFrame::childWindowCloseRequest (this=0x8408ab0, wnd=0x886c138) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_frame.cpp:637
#13 0x0813d01c in KviWindow::closeEvent (this=0x886c138, e=0xbfffd8f8) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/ui/kvi_window.cpp:879
#14 0x46eff1ce in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#15 0x46eabd7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#16 0x46eb0f39 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#17 0x41296f83 in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#18 0x45d65728 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#19 0x46eb6fde in QCoreApplication::sendEvent(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#20 0x46efcb0e in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) () from /usr/lib/libQtGui.so.4
#21 0x46efcbc8 in QWidget::close() () from /usr/lib/libQtGui.so.4
#22 0x46efce33 in QWidget::qt_metacall(QMetaObject::Call, int, void**) () from /usr/lib/libQtGui.so.4
#23 0x08234c11 in KviWindow::qt_metacall (this=0x886c138, _c=InvokeMetaMethod, _id=22, _a=0xa81a550)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/BUILD-i686-alt-linux/src/kvirc/ui/moc_kvi_window.cxx:103
#24 0xb53b826c in KviLogViewMDIWindow::qt_metacall (this=0x886c138, _c=InvokeMetaMethod, _id=22, _a=0xa81a550)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/BUILD-i686-alt-linux/src/modules/logview/moc_logviewmdiwindow.cxx:144
#25 0x45d69dfa in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
#26 0x45d745a6 in QMetaCallEvent::placeMetaCall(QObject*) () from /usr/lib/libQtCore.so.4
#27 0x45d76882 in QObject::event(QEvent*) () from /usr/lib/libQtCore.so.4
#28 0x46efe6ec in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#29 0x46eabd7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#30 0x46eb0f39 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#31 0x41296f83 in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#32 0x45d65728 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#33 0x45d65d8a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQtCore.so.4
#34 0x45d65eed in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/libQtCore.so.4
#35 0x45d8c604 in ?? () from /usr/lib/libQtCore.so.4
#36 0x4dcb2605 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#37 0x4dcb6320 in ?? () from /lib/libglib-2.0.so.0
#38 0x4dcb6508 in g_main_context_iteration () from /lib/libglib-2.0.so.0
#39 0x45d8c0f5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#40 0x46f4ca25 in ?? () from /usr/lib/libQtGui.so.4
#41 0x45d66171 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#42 0xb53b4dc7 in KviLogViewMDIWindow::setupItemList (this=0x886c138) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/modules/logview/logviewmdiwindow.cpp:260
#43 0xb53b53a4 in KviLogViewMDIWindow::cacheFileList (this=0x886c138) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/modules/logview/logviewmdiwindow.cpp:332
#44 0xb53b8319 in KviLogViewMDIWindow::qt_metacall (this=0x886c138, _c=InvokeMetaMethod, _id=4, _a=0x88794c0)
    at /home/wrar/tmp/BUILD/kvirc-4.0.3/BUILD-i686-alt-linux/src/modules/logview/moc_logviewmdiwindow.cxx:153
#45 0x45d69dfa in QMetaObject::metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib/libQtCore.so.4
#46 0x45d745a6 in QMetaCallEvent::placeMetaCall(QObject*) () from /usr/lib/libQtCore.so.4
#47 0x45d76882 in QObject::event(QEvent*) () from /usr/lib/libQtCore.so.4
#48 0x46efe6ec in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
#49 0x46eabd7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#50 0x46eb0f39 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#51 0x41296f83 in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
#52 0x45d65728 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#53 0x45d65d8a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQtCore.so.4
#54 0x45d65eed in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/libQtCore.so.4
#55 0x45d8c604 in ?? () from /usr/lib/libQtCore.so.4
#56 0x4dcb2605 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#57 0x4dcb6320 in ?? () from /lib/libglib-2.0.so.0
#58 0x4dcb6508 in g_main_context_iteration () from /lib/libglib-2.0.so.0
#59 0x45d8c0f5 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#60 0x46f4ca25 in ?? () from /usr/lib/libQtGui.so.4
#61 0x45d64109 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#62 0x45d64312 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#63 0x45d65fa9 in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#64 0x46ea9e07 in QApplication::exec() () from /usr/lib/libQtGui.so.4
#65 0x08210a02 in main (argc=3, argv=0xbfffefb4) at /home/wrar/tmp/BUILD/kvirc-4.0.3/src/kvirc/kernel/kvi_main.cpp:456
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/968

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 19 Sep 2010 15:04:58**
fixed in r5021, thank you!

---

Resolution: none → fixed
Status: new → closed
