### ISSUE TITLE
Crash when quitting

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc#989]
**Reported by wodim on 13 Oct 2010 11:22:36 UTC**
I get this crash when I close KVIrc just after I start it (let's say, 1 second).

```

[ASSERT FAILED] (false) in KviConsole* KviFrame::firstConsole() at /home/neiko/kvirc/src/kvirc/ui/kvi_frame.cpp:618                                                                             

Program received signal SIGABRT, Aborted.                                                                                                                                                       
0x00007fffef046595 in raise () from /lib/libc.so.6                                                                                                                                              
(gdb) bt full                                                                                                                                                                                   
#0  0x00007fffef046595 in raise () from /lib/libc.so.6                                                                                                                                          
No symbol table info available.
#1  0x00007fffef047a16 in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x00007ffff278d45f in qt_message_output(QtMsgType, char const*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#3  0x00007ffff278d5ed in ?? () from /usr/lib/libQtCore.so.4
No symbol table info available.
#4  0x00007ffff278d785 in qFatal(char const*, ...) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#5  0x00000000004bef50 in KviFrame::firstConsole (this=0xcf8ad0) at /home/neiko/kvirc/src/kvirc/ui/kvi_frame.cpp:618
        __PRETTY_FUNCTION__ = "KviConsole* KviFrame::firstConsole()"
#6  0x000000000053393b in KviModuleManager::loadModule (this=<value optimized out>, modName=...) at /home/neiko/kvirc/src/kvirc/module/kvi_modulemanager.cpp:263
        tmp = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 16872}, alloc = 0, size = 0, data = 0x8ad1fa, clean = 0, simpletext = 0, righttoleft = 0, 
            asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 73}, alloc = 0, size = 0, data = 0x7ffff2bb0afa, clean = 0, simpletext = 0, 
            righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x14188c0, static codecForCStrings = 0x8d8750}
        szName = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 16872}, alloc = 0, size = 0, data = 0x8ad1fa, clean = 0, simpletext = 0, righttoleft = 0, 
            asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 73}, alloc = 0, size = 0, data = 0x7ffff2bb0afa, clean = 0, simpletext = 0, 
            righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x14077e0, static codecForCStrings = 0x8d8750}
        info = <value optimized out>
        module = 0x13e4ae0
        pLibrary = <value optimized out>
#7  0x0000000000533a55 in KviModuleManager::getModule (this=0xb033f0, modName=...) at /home/neiko/kvirc/src/kvirc/module/kvi_modulemanager.cpp:146
        m = 0x0
#8  0x00000000005843b6 in KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly (this=0xaf3190, c=0x7fffffffd3d0, pBuffer=0x7fffffffd330)
    at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_modulefunctioncall.cpp:63
        m = <value optimized out>
        proc = <value optimized out>
        l = {m_pList = 0x7fffef36ce80}
        call = {<KviKvsModuleRunTimeCall> = {<KviKvsRunTimeCall> = {_vptr.KviKvsRunTimeCall = 0x88, m_pContext = 0x9, m_pParams = 0xafb2d0}, m_pModule = 0xb083f0}, m_pResult = 0x20}
#9  0x000000000058664a in KviKvsTreeNodeOperationAssignment::execute (this=0x13d0590, c=0x7fffffffd3d0) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_operation.cpp:96
        v = {<KviHeapObject> = {<No data fields>}, m_pData = 0x0}
        target = <value optimized out>
#10 0x000000000058380b in KviKvsTreeNodeInstructionBlock::execute (this=<value optimized out>, c=0x7fffffffd3d0) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_instructionblock.cpp:81
        i = <value optimized out>
        it = {m_pList = 0xaf0ef0, m_pNode = 0xd1e790}
#11 0x00000000005775fd in KviKvsScript::executeInternal (this=0x7fffffffd470, pContext=0x7fffffffd3d0) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:291
        iRunStatus = 1
#12 0x000000000057783b in KviKvsScript::execute (this=0x7fffffffd470, pWnd=0x1281f00, pParams=0x7fffffffd480, pRetVal=0x13dd290, iRunFlags=<value optimized out>, 
    pExtData=<value optimized out>) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:342
        bDeleteParams = false
        bDeleteRetVal = false
        ctx = {m_pScript = 0x7fffffffd470, m_pLocalVariables = 0xd620a0, m_pParameterList = 0x7fffffffd480, m_pReturnValue = 0x13dd290, m_pWindow = 0x1281f00, m_uRunTimeFlags = 0, 
          m_pExtendedData = 0x0, m_bError = false, m_pDefaultReportLocation = 0x0}
        iRunStatus = <value optimized out>
#13 0x000000000057c862 in KviKvsTreeNodeAliasFunctionCall::evaluateReadOnly (this=0xe69660, c=0x7fffffffd580, pBuffer=0x13dd290)
---Type <return> to continue, or q <return> to quit---
    at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_aliasfunctioncall.cpp:70
        l = {m_pList = 0xd51ec0}
        s = <value optimized out>
        copy = {<KviHeapObject> = {<No data fields>}, m_pData = 0xb74110}
#14 0x000000000057f376 in KviKvsTreeNodeDataList::evaluate (this=<value optimized out>, c=0x7fffffffd580, pBuffer=0x7fffffffd520)
    at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_datalist.cpp:86
        t = 0xe69660
        v = 0x13dd290
        it = {m_pList = 0x9fb190, m_pNode = 0x13e7b10}
#15 0x0000000000589219 in KviKvsTreeNodeParameterReturn::execute (this=<value optimized out>, c=0x7fffffffd580) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_treenode_parameterreturn.cpp:60
        lBuffer = {m_pList = 0xcf8660}
        all = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 16872}, alloc = 0, size = 0, data = 0x8ad1fa, clean = 0, simpletext = 0, righttoleft = 0, 
            asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 73}, alloc = 0, size = 0, data = 0x7ffff2bb0afa, clean = 0, simpletext = 0, 
            righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x13db630, static codecForCStrings = 0x8d8750}
#16 0x00000000005775fd in KviKvsScript::executeInternal (this=0x7fffffffd620, pContext=0x7fffffffd580) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:291
        iRunStatus = 1
#17 0x000000000057783b in KviKvsScript::execute (this=0x7fffffffd620, pWnd=0x1281f00, pParams=0xa1fea0, pRetVal=0x7fffffffd690, iRunFlags=<value optimized out>, 
    pExtData=<value optimized out>) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:342
        bDeleteParams = false
        bDeleteRetVal = false
        ctx = {m_pScript = 0x7fffffffd620, m_pLocalVariables = 0x13db630, m_pParameterList = 0xa1fea0, m_pReturnValue = 0x7fffffffd690, m_pWindow = 0x1281f00, m_uRunTimeFlags = 0, 
          m_pExtendedData = 0x0, m_bError = false, m_pDefaultReportLocation = 0x0}
        iRunStatus = <value optimized out>
#18 0x0000000000577b35 in KviKvsScript::evaluate (szCode=..., pWindow=0x1281f00, pParams=0x0, pRetVal=0x7fffffffd690) at /home/neiko/kvirc/src/kvirc/kvs/kvi_kvs_script.cpp:156
        s = 11923568
#19 0x00000000005bf975 in KviIrcContext::terminateConnectionRequest (this=0x12823b0, bForce=true, szQuitMsg=<value optimized out>, bSimulateUnexpectedDisconnect=<value optimized out>)
    at /home/neiko/kvirc/src/kvirc/kernel/kvi_irccontext.cpp:878
        szQuit = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 16872}, alloc = 0, size = 0, data = 0x8ad1fa, clean = 0, simpletext = 0, righttoleft = 0, 
            asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 73}, alloc = 0, size = 0, data = 0x7ffff2bb0afa, clean = 0, simpletext = 0, 
            righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0xc2f450, static codecForCStrings = 0x8d8750}
        buffer = {static null = {<No data fields>}, static shared_null = {ref = {_q_value = 16872}, alloc = 0, size = 0, data = 0x8ad1fa, clean = 0, simpletext = 0, righttoleft = 0, 
            asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, static shared_empty = {ref = {_q_value = 73}, alloc = 0, size = 0, data = 0x7ffff2bb0afa, clean = 0, simpletext = 0, 
            righttoleft = 0, asciiCache = 0, capacity = 0, reserved = 0, array = {0}}, d = 0x8ad1e0, static codecForCStrings = 0x8d8750}
        ret = {<KviHeapObject> = {<No data fields>}, m_pData = 0x0}
        dat = {static shared_null = {ref = {_q_value = 721}, alloc = 0, size = 0, data = 0x8ad358 "", array = ""}, static shared_empty = {ref = {_q_value = 6}, alloc = 0, size = 0, 
            data = 0x7ffff2bb0998 "", array = ""}, d = 0xac0015}
        bWasSentQuit = true
        __PRETTY_FUNCTION__ = "void KviIrcContext::terminateConnectionRequest(bool, const QString&, bool)"
#20 0x00000000004b6163 in KviConsole::~KviConsole (this=0x1281f00, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_console.cpp:189
No locals.
#21 0x00000000004b6229 in KviConsole::~KviConsole (this=0x1281f00, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_console.cpp:199
No locals.
#22 0x00000000004e5482 in KviMdiChild::~KviMdiChild (this=0x12bd0a0, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_mdichild.cpp:77
No locals.
#23 0x00000000004e54c9 in KviMdiChild::~KviMdiChild (this=0x12bd0a0, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_mdichild.cpp:81
No locals.
---Type <return> to continue, or q <return> to quit---
#24 0x00000000004e6db7 in KviMdiManager::destroyChild (this=0xd396a0, lpC=0x12bd0a0) at /home/neiko/kvirc/src/kvirc/ui/kvi_mdimanager.cpp:165
No locals.
#25 0x00000000004c0e91 in KviFrame::closeWindow (this=0xcf8ad0, wnd=0x1281f00) at /home/neiko/kvirc/src/kvirc/ui/kvi_frame.cpp:447
No locals.
#26 0x00000000004c10e4 in KviFrame::~KviFrame (this=0xcf8ad0, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_frame.cpp:234
No locals.
#27 0x00000000004c1149 in KviFrame::~KviFrame (this=0xcf8ad0, __in_chrg=<value optimized out>) at /home/neiko/kvirc/src/kvirc/ui/kvi_frame.cpp:239
No locals.
#28 0x00007ffff2892188 in QObject::event(QEvent*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#29 0x00007ffff3e3256d in QWidget::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#30 0x00007ffff41f00ab in QMainWindow::event(QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#31 0x00007ffff3de1564 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#32 0x00007ffff3de5fda in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
No symbol table info available.
#33 0x00007ffff72561f6 in KApplication::notify(QObject*, QEvent*) () from /usr/lib/libkdeui.so.5
No symbol table info available.
#34 0x00007ffff287deac in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#35 0x00007ffff2881695 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQtCore.so.4
No symbol table info available.
#36 0x00007ffff288198e in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
No symbol table info available.
#37 0x00000000005c909a in main (argc=1, argv=0x7fffffffe588) at /home/neiko/kvirc/src/kvirc/kernel/kvi_main.cpp:456
        a = {argc = 1, argv = 0x7fffffffe588, configFile = 0x0, createFile = false, bForceNewSession = false, bShowPopup = false, bShowSplashScreen = true, bExecuteCommandAndClose = false, 
          szExecCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x8d7280 "", m_len = 0}, szExecRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x8d72a0 "", m_len = 0}}
        oAboutData = {d = 0x8d7650}
        iRetVal = <value optimized out>
        iRetCode = <value optimized out>
        pTheApp = 0x9112f0
        szRemoteCommand = {<KviHeapObject> = {<No data fields>}, m_ptr = 0x9e9c30 "", m_len = 0}
```

---

Migrated from: https://svn.kvirc.de/kvirc/ticket/989

**Comment by DarthGandalf** [comment]
**Comment by ctrlaltca on 31 Oct 2010 16:49:15**
a fix has been committed as r5123, please test

---

Resolution: none → fixed
Status: new → closed
